### ISSUE TITLE
kubeadm安装的单master集群升级为HA

### ISSUE THREAD

**Issue by godocean** [fanux/sealos#105]
如题，使用的kubernetes官方的kubeadm安装方式安装的cluster，现在想升级为多master HA，但是多个master位于不同网段，之前使用keepalived+harpoxy方式升级，vip和漂移到不同网段的master时，vip无法访问，使用keepalived单播方式也无法很好解决。

请问使用sealos可以解决么？或者如何使用sealos来升级kubeadm安装的单master集群，不考虑重装的前提下。

**Comment by fanux** [comment]
我们最早是haproxy keepalived架构的，现在已经被我们淘汰了，原因和你的差不多当然还有其它一些问题，如keepalived检测脚本失败，haproxy配置问题等。

我们全新架构采用内核ipvs负载，整个高可用轻量很多，稳定很多。 支持单master向多master扩展。如果你的集群不是用sealos安装的那不行。

README中有详细的升级教程，也有详细的原理介绍，建议仔细阅读
