### ISSUE TITLE
最新的sealos，kube1.15.0.tar  报错

### ISSUE THREAD

**Issue by xiaoyuzdy** [fanux/sealos#109]
启动命令：
sealos init --master 192.168.246.135 \
  --node 192.168.246.136 \
  --node 192.168.246.137 \
  --user root \
  --passwd xxxxx\
  --pkg-url https://sealyun.oss-cn-beijing.aliyuncs.com/free/kube1.15.0.tar.gz \
  --pk /root/.ssh/id_rsa # this is your ssh private key file \
  --version v1.15.0

KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.15.0" Control plane version: "1.14.1"

代码堆栈：
2019-09-21 17:08:17 [EROR] [github.com/fanux/sealos/install/utils.go:114] [192.168.246.135]Error exec command failed: Process exited with status 1
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fanux/sealos/install.decodeOutput(0x0, 0x0, 0x0)
	/go/src/github.com/fanux/sealos/install/sealos.go:81 +0x188
github.com/fanux/sealos/install.(*SealosInstaller).InstallMaster0(0xc00000f4a0)
	/go/src/github.com/fanux/sealos/install/init.go:61 +0x1c6
github.com/fanux/sealos/install.BuildInit()
	/go/src/github.com/fanux/sealos/install/init.go:21 +0x236
github.com/fanux/sealos/cmd.glob..func3(0xda22e0, 0xc0001060e0, 0x0, 0xe)
	/go/src/github.com/fanux/sealos/cmd/init.go:28 +0x20
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).execute(0xda22e0, 0xc000106000, 0xe, 0xe, 0xda22e0, 0xc000106000)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xda2a00, 0x970379, 0x17, 0x1)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:800
github.com/fanux/sealos/cmd.Execute()
	/go/src/github.com/fanux/sealos/cmd/root.go:46 +0x32
main.main()
	/go/src/github.com/fanux/sealos/main.go:20 +0x20

**Comment by cuisongliu** [comment]
@fanux  	slice1 := strings.Split(slice[1], "Please note")  是不是这里有问题？

**Comment by fanux** [comment]
我待会测试下，应该是控制面版本不对

**Comment by fanux** [comment]
我这边测试正常命令：
```
sealos init --master 172.31.12.83 --passwd Fanux#123 --pkg-url https://sealyun.oss-cn-beijing.aliyuncs.com/free/kube1.15.0.tar.gz --version v1.15.0
```
1. 密码不要同时与密钥使用
2. 你的集群应该有版本不一样，需要做好清理

**Comment by xiaoyuzdy** [comment]
@fanux 从你打印的错误信息里看   Kubelet version: "1.15.0" Control plane version: "1.14.1" 是这个原因，我后面换成1.14.1的版本，安装的时候告诉我docker版本过高，换了适当的docker版本后执行成功了，sealos clean 命令貌似卸载的不彻底，clean后重新init一直报端口被占用，服务器重置后才能安装成功

**Comment by fanux** [comment]
@xiaoyuzdy 嗯 应该是你机器上存在了1.14.1版本导致。  @cuisongliu 多人反馈clean命令清理不彻底了。
