### ISSUE TITLE
节点清理

### ISSUE THREAD

**Issue by Devin6Tam** [fanux/sealos#113]
sealos clean \
  --master 192.168.43.188 \
  --node 192.168.43.189 \
  --node 192.168.43.190 \
  --user root \
  --passwd XXXXXXXXXXXXX

只能清理到最后一个，后继续使用该命令，无任何变化；后面改单个清理，收效。

**Comment by cuisongliu** [comment]
可否贴一下堆栈信息？

**Comment by cuisongliu** [comment]
#115 已经修复
