### ISSUE TITLE
可以支持Kubernetes官方的下载包吗？

### ISSUE THREAD

**Issue by Icedroid** [fanux/sealos#117]
你给的kubernetes的下载包是定制过的吗？为什么不能使用官方的tar.gz包呢

**Comment by fanux** [comment]
也想过支持，官方下载包里缺少很多东西，如coreDNS, calico，etcd,和缺少很多配置，如systemd配置和一些yaml文件。 

本来是有支持的  现在被废弃了。  也想过把coreDNS calico剥离出去，但是会发现每个版本依赖的版本可能会不一样，所以非常的麻烦。
