### ISSUE TITLE
kubeadm join 无法加入node

### ISSUE THREAD

**Issue by wukaiying** [fanux/sealos#120]
无法加入node，一直处于这个状态，如何解决呢。
![image](https://user-images.githubusercontent.com/7676297/65829876-81ceb180-e2dc-11e9-8907-973eadadd887.png)

**Comment by cuisongliu** [comment]
vagrant安装的虚拟机？最好使用传统方式安装虚拟机再试。vagrant暂不列入测试范围。

**Comment by fanux** [comment]
vagrant网卡是什么情况，有多张网卡？

**Comment by cuisongliu** [comment]
对。一个hostonly + nat 的方式一般来说。多网卡lvscare好像有问题。 @wukaiying  截一下网络配置

**Comment by fanux** [comment]
不过他这个join是单master不会起lvscare

**Comment by Wandering** [comment]
我也碰到了相同的问题  你们能给个建议吗
![image](https://user-images.githubusercontent.com/11769582/67006470-cd27f300-f117-11e9-84a6-9d1f4efe5396.png)

**Comment by Wandering** [comment]
我也碰到了相同的问题  你们能给个建议吗
![image](https://user-images.githubusercontent.com/11769582/67006470-cd27f300-f117-11e9-84a6-9d1f4efe5396.png)
![image](https://user-images.githubusercontent.com/11769582/67006570-14ae7f00-f118-11e9-8685-a333d4c423f6.png)

**Comment by fanux** [comment]
得看kubelet日志  未必是一样的问题。  有另外一个问题也会导致无法join,解决版本是重启node节点即可。  

https://github.com/fanux/sealos/issues/127

**Comment by Wandering** [comment]
重启节点并未解决该问题

**Comment by fanux** [comment]
另一个网卡停掉试试？ 节点kubelet有什么日志，先看kubelet能不能正常，再用ipvsadm -Ln看ipvs规则正常不。   或者加群我给你远程看下
