### ISSUE TITLE
ETCD集群初始化节点个数分别是3，2，1

### ISSUE THREAD

**Issue by racooncry** [fanux/sealos#124]
我这边三台机器，初始化完之后：
$ cat /etc/kubernetes/manifests/etcd.yaml 

![微信图片_20191003205741](https://user-images.githubusercontent.com/25974372/66128495-7eab2c80-e620-11e9-9e8e-b516a52ccd62.png)
![微信图片_20191003205747](https://user-images.githubusercontent.com/25974372/66128496-7f43c300-e620-11e9-96c1-a8fad881ad00.png)
![微信图片_20191003205751](https://user-images.githubusercontent.com/25974372/66128497-7f43c300-e620-11e9-8275-1a8367aba272.png)

**Comment by fanux** [comment]
PS： 这是kubeadm join control-plan决定的。  etcd的集群启动方式为先起一个然后join其实etcd节点。 当然也可以在集群启动时就配置三个。 control-plan方式第一个master是不知道后面master的地址的
