### ISSUE TITLE
支持ingress nginx的方式吗

### ISSUE THREAD

**Issue by bnerDY** [fanux/sealos#125]
麻烦问一下 支持ingress nginx的方式吗

**Comment by fanux** [comment]
ingress 后续会单独提供，但不采用nginx controller,会使用envoy,contour.

**Comment by bnerDY** [comment]
那我想麻烦问下，假设按照sealos的脚本安装，如何从集群外部浏览器访问集群内部的dashboard呢？
虽然有nodeport 但是external ip这边是none

**Comment by fanux** [comment]
物理机IP即可
