### ISSUE TITLE
failed to update top level Burstable QOS cgroup

### ISSUE THREAD

**Issue by qqweasdqwsa** [fanux/sealos#126]
Failed to start ContainerManager failed to initialize top level QOS containers: failed to update top level Burstable QOS cgroup : failed to set supported cgroup subsystems for cgroup [kubepods burstable]: failed to find subsystem mount for required subsystem: pids

**Comment by fanux** [comment]
A reboot of the machine however seem to fix it.

https://github.com/kubernetes/kubernetes/issues/43856
