### ISSUE TITLE
kubectl join node节点时报错

### ISSUE THREAD

**Issue by qqweasdqwsa** [fanux/sealos#127]
![image](https://user-images.githubusercontent.com/56420056/66697061-c6a70f00-ed04-11e9-954b-005f260ec710.png)
 Unable to update cni config: no networks found in /etc/cni/net.d
节点显示notready
kube-proxy和calico-node显示Pending

**Comment by fanux** [comment]
重启机器可解决  同 https://github.com/kubernetes/kubernetes/issues/43856
