### ISSUE TITLE
Error image pull

### ISSUE THREAD

**Issue by chenfanlinux** [fanux/sealos#128]
我已经把 kube1.16.0.tar.gz下载到本地了，为啥要会去拉取这个镜像啊

[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by fanux** [comment]
磁盘不够造成
