### ISSUE TITLE
咱们命令的oss地址目前无法访问，无法下载1.16的离线安装包

### ISSUE THREAD

**Issue by msj905** [fanux/sealos#129]
https://sealyun.oss-cn-beijing.aliyuncs.com/37374d999dbadb788ef0461844a70151-1.16.0/kube1.16.0.tar.gz

**Comment by msj905** [comment]
还有一个问题 我这安装一直报错 [EROR] [github.com/fanux/sealos/install/utils.go:114] [192.168.11.11]Error exec command failed: Process exited with status 127 麻烦帮忙看下

**Comment by fanux** [comment]
我这边可以正常下载，请检查你的网络。   多发些日志，这个看不出啥。  并把你的执行命令也带上

**Comment by fanux** [comment]
安装包可能有更新  store.lameleg.com  上下载最新的安装包

**Comment by shaoyujiang** [comment]
你好执行这个 命令 报错sealos init --passwd 'xxxx' --master 42.192.150.241 --pkg-url /root/kube1.22.0.tar.gz --version v1.22.0
20:54:40 [EROR] [ssh.go:42] [ssh][42.192.150.241:22]Error exec command failed: Process exited with status 1
20:54:40 [EROR] [init.go:204] [42.192.150.241:22] install kubernetes failed. please clean and uninstall.
