### ISSUE TITLE
非22端口，初始化无法成功

### ISSUE THREAD

**Issue by Zziwen** [fanux/sealos#131]
CDM :  
./sealos init --master 10.10.30.51:5022 --node 10.10.31.110:5022 --node 10.10.30.46:5022 --user root  --pk /root/.ssh/id_rsa --version v1.14.1 --pkg-url /root/sealos/kube1.14.1.tar.gz

![KP0(P}79LTCXYI XU~%5E0C](https://user-images.githubusercontent.com/46589682/67181644-c4813680-f40f-11e9-9b03-551fca880711.png)

**Comment by cuisongliu** [comment]
是不是版本不对。这个问题早已修复了。

**Comment by Zziwen** [comment]
> 是不是版本不对。这个问题早已修复了。

是的，1.14.1的包
