### ISSUE TITLE
安装kube1.16.0 执行到kubeadm init错误

### ISSUE THREAD

**Issue by boystar1988** [fanux/sealos#132]
2019-10-22 15:29:33 [INFO] [github.com/fanux/sealos/install/utils.go:98] [x.x.x.x]exec cmd is : kubeadm init --config=/root/kubeadm-config.yaml --upload-certs
2019-10-22 15:34:42 [DEBG] [github.com/fanux/sealos/install/utils.go:111] [x.x.x.x]command result is: [init] Using Kubernetes version: v1.16.0
[preflight] Running pre-flight checks
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING FileExisting-socat]: socat not found in system path
	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 18.03.1-ce. Latest validated version: 18.09
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [izwz9eqeq1dzfztfj4m2nfz kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local apiserver.cluster.local apiserver.cluster.local] and IPs [10.96.0.1 172.18.79.82 127.0.0.1 x.x.x.x 10.103.97.2]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [izwz9eqeq1dzfztfj4m2nfz localhost] and IPs [172.18.79.82 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [izwz9eqeq1dzfztfj4m2nfz localhost] and IPs [172.18.79.82 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

2019-10-22 15:34:42 [EROR] [github.com/fanux/sealos/install/utils.go:114] [x.x.x.x]Error exec command failed: Process exited with status 1
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fanux/sealos/install.decodeOutput(0x0, 0x0, 0x0)
	/go/src/github.com/fanux/sealos/install/sealos.go:83 +0x188
github.com/fanux/sealos/install.(*SealosInstaller).InstallMaster0(0xc000093420)
	/go/src/github.com/fanux/sealos/install/init.go:62 +0x203
github.com/fanux/sealos/install.BuildInit()
	/go/src/github.com/fanux/sealos/install/init.go:21 +0x236
github.com/fanux/sealos/cmd.glob..func3(0xda32e0, 0xc000110180, 0x0, 0xc)
	/go/src/github.com/fanux/sealos/cmd/init.go:28 +0x20
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).execute(0xda32e0, 0xc0001100c0, 0xc, 0xc, 0xda32e0, 0xc0001100c0)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xda3a00, 0x9703c1, 0x17, 0x1)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:800
github.com/fanux/sealos/cmd.Execute()
	/go/src/github.com/fanux/sealos/cmd/root.go:46 +0x32
main.main()
	/go/src/github.com/fanux/sealos/main.go:20 +0x20

请问需要

**Comment by boystar1988** [comment]
请问还需要配置什么

**Comment by fanux** [comment]
[10.96.0.1 172.18.79.82 127.0.0.1 x.x.x.x 10.103.97.2]  哪来的 x.x.x.x 的IP地址  发一下你的init命令

**Comment by boystar1988** [comment]
感谢回复，我在提问时做了字符处理。原因找到了  是因为填写了公网的IP导致，修改为内网IP后完成安装

**Comment by fanux** [comment]
ok, 那issue先关了
