### ISSUE TITLE
我在virtualbox里，虚拟出两台linux- centos7+,安装在kubeadm join时就无反应状态了

### ISSUE THREAD

**Issue by aimin** [fanux/sealos#134]
我在virtualbox里，虚拟出两台linux- centos7+,安装在kubeadm join时就无反应状态了

如下：一至是如下这个界面，希望大侠排查为何

2019-10-28 21:02:00 [DEBG] [github.com/fanux/sealos/install/print.go:20] ==>SendPackage==>KubeadmConfigInstall==>InstallMaster0
2019-10-28 21:02:00 [INFO] [github.com/fanux/sealos/install/utils.go:98] [192.168.56.106]exec cmd is : echo 10.103.97.2 apiserver.cluster.local >> /etc/hosts
2019-10-28 21:02:00 [DEBG] [github.com/fanux/sealos/install/utils.go:111] [192.168.56.106]command result is: 
2019-10-28 21:02:00 [INFO] [github.com/fanux/sealos/install/utils.go:98] [192.168.56.106]exec cmd is : kubeadm join 10.103.97.2:6443 --token c8vh7h.e2oj2n9bktq59tnw --discovery-token-ca-cert-hash sha256:2c3a5a7e75b8d7bf86c9e77d3d7bfe0634cf0ce61e12e6f850a7e2b9ee7e5edc --master 192.168.56.105:6443

**Comment by aimin** [comment]
难道 是ipvs+virtualbox 的问题？

**Comment by aimin** [comment]
感觉像是ipvs+virtualbox 的问题？

**Comment by fanux** [comment]
这个问题反馈的人比较多，我来说下排查思路：

1. 重启下node节点重试，因为可能是社区的一个issue引起： https://github.com/fanux/sealos/issues/127

2. 检查node 借点上的kubelet能否正常启动  systemctl status kubelet   如果启动不了journalctl 看详细原因

3. 检查apiserver联通性
```
cat /etc/hosts
curl -k https://apiserver.cluster.local:6443
```
如果不通，检查lvscare进程是否存在
```
ps -aux|grep lvscare
```
使用ipvsadm命令检查ipvs规则是否正常
```
yum install -y ipvsadm
ipvsadm -Ln
```
注意有没有虚拟IP 10.103.97.2 这个的规则，后端是不是对应你的master

直接curl master
```
curl -k https://你的master地址:6443
```

**Comment by fanux** [comment]
通常join卡住原因有几个：
1. kubelet起不来 （系统兼容性导致）
2. kubelet能起来但是docker无法正常创建容器 (系统兼容性导致)
3. 不通apiserver (服务器网络导致)
4. sealos的ipvs代理异常，规则没创建或创建不生效  （系统网络不支持ipvs nat）

**Comment by fanux** [comment]
无法加载配置文件：
jourctl -u kubelet

```
Oct 10 15:21:43 ky001 kubelet[19129]: F1010 07:21:43.650488   19129 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config fil
Oct 10 15:21:43 ky001 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Oct 10 15:21:43 ky001 systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

**Comment by fanux** [comment]
/var/lib/kubelet/config.yaml 有这个文件不

**Comment by willzhang** [comment]
vagrant双网卡环境遇到同样问题：
## 版本信息
```
[root@master01 ~]# sealos version
v3.0.1
[root@master01 ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
[root@master01 ~]# uname -sr
Linux 3.10.0-1062.4.1.el7.x86_64
[root@master01 ~]# 
[root@master01 ~]# kubectl version --short
Client Version: v1.17.0
Server Version: v1.17.0
[root@master01 ~]# 

```


## 部署环境
1个master，2个node
```
sealos init --master 172.16.10.10 \
    --node 172.16.10.11 \
    --node 172.16.10.12 \
    --user root \
    --passwd 123456 \
    --version v1.17.0 \
    --pkg-url /root/kube1.17.0.tar.gz
```

## 部署完成后只运行一个master节点

·```
IP: 10.103.97.2, Port: 6443IP: 172.16.10.10, Port: 6443check svc ip: 10.103.97.2, port 6443
IP: 172.16.10.10, Port: 6443creat ipvs first time 10.103.97.2:6443 [172.16.10.10:6443]
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "node02" could not be reached
        [WARNING Hostname]: hostname "node02": lookup node02 on [::1]:53: read udp [::1]:38679->[::1]:53: read: connection refused
error execution phase preflight: couldn't validate the identity of the API Server: abort connecting to API servers after timeout of 5m0s
To see the stack trace of this error execute with --v=5 or higher

2019-12-11 06:02:43 [EROR] [github.com/fanux/sealos/install/utils.go:114] [172.16.10.12]Error exec command failed: Process exited with status 1
2019-12-11 06:02:44 [DEBG] [github.com/fanux/sealos/install/utils.go:111] [172.16.10.11]command result is: W1211 05:57:43.804406   10242 join.go:368] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
This is not a control plan
lvscare command is: [/usr/bin/lvscare care --vs 10.103.97.2:6443 --health-path /healthz --health-schem https --rs 172.16.10.10:6443]
IP: 10.103.97.2, Port: 6443IP: 172.16.10.10, Port: 6443check svc ip: 10.103.97.2, port 6443
IP: 172.16.10.10, Port: 6443creat ipvs first time 10.103.97.2:6443 [172.16.10.10:6443]
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "node01" could not be reached
        [WARNING Hostname]: hostname "node01": lookup node01 on 10.0.2.3:53: no such host
error execution phase preflight: couldn't validate the identity of the API Server: abort connecting to API servers after timeout of 5m0s
To see the stack trace of this error execute with --v=5 or higher

2019-12-11 06:02:44 [EROR] [github.com/fanux/sealos/install/utils.go:114] [172.16.10.11]Error exec command failed: Process exited with status 1
2019-12-11 06:02:44 [DEBG] [github.com/fanux/sealos/install/print.go:20] ==>SendPackage==>KubeadmConfigInstall==>InstallMaster0==>JoinMasters==>JoinNodes
2019-12-11 06:02:44 [INFO] [github.com/fanux/sealos/install/print.go:25] sealos install success.
[root@master01 ~]# 
[root@master01 ~]# 
[root@master01 ~]# kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
master01   Ready    master   14m   v1.17.0
[root@master01 ~]# 
```

## node节点kubelet日志
kubelet无法启动，提示无法加载证书，证书目录未创建

```
[root@node01 ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: inactive (dead) (Result: exit-code) since Wed 2019-12-11 04:01:48 UTC; 2h 12min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 9389 (code=exited, status=255)

Dec 11 04:01:47 node01 systemd[1]: Unit kubelet.service entered failed state.
Dec 11 04:01:47 node01 systemd[1]: kubelet.service failed.
Dec 11 04:01:48 node01 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
[root@node01 ~]# journalctl -fu kubelet
-- Logs begin at Wed 2019-12-11 02:50:36 UTC. --
Dec 11 04:01:47 node01 kubelet-pre-start.sh[9378]: net.bridge.bridge-nf-call-iptables = 1
Dec 11 04:01:47 node01 kubelet-pre-start.sh[9378]: * Applying /etc/sysctl.conf ...
Dec 11 04:01:47 node01 kubelet-pre-start.sh[9378]: net.ipv4.ip_forward = 1
Dec 11 04:01:47 node01 kubelet-pre-start.sh[9378]: setenforce: SELinux is disabled
Dec 11 04:01:47 node01 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 11 04:01:47 node01 kubelet[9389]: F1211 04:01:47.300264    9389 server.go:253] unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Dec 11 04:01:47 node01 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Dec 11 04:01:47 node01 systemd[1]: Unit kubelet.service entered failed state.
Dec 11 04:01:47 node01 systemd[1]: kubelet.service failed.
Dec 11 04:01:48 node01 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
```

## 查看ipvsadm规则

确认后端连通正常，但https://apiserver.cluster.local:6443无法连通，ipvs代理存在问题

```
[root@node01 ~]# ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.103.97.2:6443 rr
  -> 172.16.10.10:6443            Masq    1      0          0         
[root@node01 ~]# 
[root@node01 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.103.97.2 apiserver.cluster.local
10.103.97.2 apiserver.cluster.local

[root@master01 ~]# cat /etc/resolv.conf 
# Generated by NetworkManager
nameserver 10.0.2.3
[root@master01 ~]# 

[root@node01 ~]# 
[root@node01 ~]# 
[root@node01 ~]# curl -k https://172.16.10.10:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}[root@node01 ~]#
[root@node01 ~]# 
[root@node01 ~]# curl -k https://apiserver.cluster.local:6443
^C
[root@node01 ~]# 

```

## 网卡信息
eth0 nat网络，用户nat方式访问外网
eth1 hostonly网络，用于内部ssh登录

master节点
```
[root@master01 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:7c:1a:01 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
       valid_lft 78587sec preferred_lft 78587sec
    inet6 fe80::5054:ff:fe7c:1a01/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:5b:1a:4a brd ff:ff:ff:ff:ff:ff
    inet 172.16.10.10/24 brd 172.16.10.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe5b:1a4a/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:07:8b:15:df brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
5: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether d2:76:1c:97:d0:72 brd ff:ff:ff:ff:ff:ff
6: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether f6:0f:de:63:99:2b brd ff:ff:ff:ff:ff:ff
    inet 10.96.0.1/32 brd 10.96.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.0.10/32 brd 10.96.0.10 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
8: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 100.85.170.128/32 brd 100.85.170.128 scope global tunl0
       valid_lft forever preferred_lft forever
17: cali12c5fc66202@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
18: cali1f8965bedf6@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
19: cali84b2ec91d10@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
[root@master01 ~]# 
```

node01节点
```
[root@node01 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:7c:1a:01 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global noprefixroute dynamic eth0
       valid_lft 83160sec preferred_lft 83160sec
    inet6 fe80::5054:ff:fe7c:1a01/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:98:94:6e brd ff:ff:ff:ff:ff:ff
    inet 172.16.10.11/24 brd 172.16.10.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe98:946e/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:95:ea:8b:a5 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

```

**Comment by willzhang** [comment]
## 临时解决办法
在node节点执行
```
 curl -k https://apiserver.cluster.local:6443
```
新开窗口查看ipvs连接，看到source使用第一块网卡eth0的ip地址10.0.2.15:39852
```
[root@node01 ~]# ipvsadm -lnc
IPVS connection entries
pro expire state       source             virtual            destination
TCP 00:59  SYN_RECV    10.0.2.15:39852    10.103.97.2:6443   172.16.10.10:6443
```

查看路由信息,默认路由指向第一块网卡eth0
```
[root@node01 ~]# ip route
default via 10.0.2.2 dev eth0 proto dhcp metric 102 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 102 
172.16.10.0/24 dev eth1 proto kernel scope link src 172.16.10.11 metric 101 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
```
所有node节点添加默认路由指向第二块网卡网关ip
```
[root@node01 ~]# ip route add default via 172.16.10.1

[root@node01 ~]# ip route
default via 172.16.10.1 dev eth1 
default via 10.0.2.2 dev eth0 proto dhcp metric 102 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 102 
172.16.10.0/24 dev eth1 proto kernel scope link src 172.16.10.11 metric 101 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
```
再次执行能够成功负载
```
[root@node01 ~]# curl -k https://apiserver.cluster.local:6443         
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}[root@node01 ~]# 

[root@node01 ~]# ipvsadm -lnc
IPVS connection entries
pro expire state       source             virtual            destination
TCP 15:01  ESTABLISHED 172.16.10.11:58126 10.103.97.2:6443   172.16.10.10:6443
TCP 00:08  CLOSE       172.16.10.11:60028 10.103.97.2:6443   172.16.10.10:6443
TCP 14:59  ESTABLISHED 172.16.10.11:58118 10.103.97.2:6443   172.16.10.10:6443
```

删除集群重新部署成功
```
[root@master01 ~]# kubectl get nodes
NAME       STATUS   ROLES    AGE     VERSION
master01   Ready    master   4m50s   v1.17.0
node01     Ready    <none>   4m8s    v1.17.0
node02     Ready    <none>   4m8s    v1.17.0
[root@master01 ~]# kubectl -n kube-system get pods
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-564b6667d7-8c2sz   1/1     Running   0          4m40s
calico-node-c59dr                          0/1     Running   3          4m18s
calico-node-v849k                          0/1     Running   3          4m18s
calico-node-wmdkh                          1/1     Running   0          4m40s
coredns-6955765f44-6zl76                   1/1     Running   0          4m40s
coredns-6955765f44-ssbxm                   1/1     Running   0          4m40s
etcd-master01                              1/1     Running   0          4m36s
kube-apiserver-master01                    1/1     Running   0          4m36s
kube-controller-manager-master01           1/1     Running   0          4m36s
kube-proxy-fngmk                           1/1     Running   0          4m40s
kube-proxy-jf5mq                           1/1     Running   0          4m18s
kube-proxy-v578r                           1/1     Running   0          4m18s
kube-scheduler-master01                    1/1     Running   0          4m36s
kube-sealyun-lvscare-node01                1/1     Running   0          3m58s
kube-sealyun-lvscare-node02                1/1     Running   0          3m58s
```

**Comment by ysicing** [comment]
debian: 添加默认路由 `route add default gw <网卡地址>`

**Comment by fanux** [comment]
默认路由是必须需要的，或者指定advertise-address应该也行

**Comment by fanux** [comment]
内核版本太高可会导致该问题：
```
modprobe: FATAL: Module nf_conntrack_ipv4 not found.
```
高版本内核叫 nf_conntrack
自行加载ipvs即可

**Comment by ysicing** [comment]
@fanux 默认加载了，好像也是有这样的问题

**Comment by fanux** [comment]
@ysicing  只要ipvs能正常转发就好，很多情况下是多网卡没默认路由造成

 ip route add default via 172.16.10.1 很奏效

**Comment by ysicing** [comment]
vagrant启动时可以考虑新增一个public_network, 启用注册默认路由
![image](https://user-images.githubusercontent.com/8605565/71540247-e6a0b300-2982-11ea-9f32-7a4ec76f0dab.png)

这样默认路由不是nat网卡的呢
```
default via 192.168.199.1 dev eth1
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15
172.20.0.0/24 dev eth2 proto kernel scope link src 172.20.0.102
172.30.0.0/16 dev docker0 proto kernel scope link src 172.30.42.1 linkdown
```
