### ISSUE TITLE
dns一段时间后不起作用

### ISSUE THREAD

**Issue by stewart-yu** [fanux/sealos#143]
安装之后，dns域名解析成功
一段时间后，不起作用了。初步排查原因是pod网络不同。在节点A上ping节点B上一个pod  IP，不通
知道大概什么原因吗？

另外， ‘apiserver.cluster.local’要外网可以访问的、实实在在的域名吗？

**Comment by fanux** [comment]
1. pod网络不通通常与集群网络环境有关系，比如在openstack虚拟机或者AWS上需要关闭虚拟机的源地址检查。
2. MTU设置的不合理也可能会导致podIP不通
3. DNS可以外网访问，但是解析的clusterIP地址必需是外网可访问的地址，要不然没有意义，sealos提供的虚拟IP不负责外网访问。
