### ISSUE TITLE
cann't add master node after init kubernetes group

### ISSUE THREAD

**Issue by tristan-tsl** [fanux/sealos#144]
cann't add master node after init kubernetes group

**Comment by tristan-tsl** [comment]
and the same init operation will be failure,tips is:

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fanux/sealos/install.(*SealosInstaller).GeneratorToken(0xc000091360)
        /go/src/github.com/fanux/sealos/install/join.go:22 +0x89
github.com/fanux/sealos/install.BuildJoin()
        /go/src/github.com/fanux/sealos/install/join.go:15 +0xd0
github.com/fanux/sealos/cmd.glob..func5(0xda37a0, 0xc000112380, 0x0, 0x8)
        /go/src/github.com/fanux/sealos/cmd/join.go:29 +0x20
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).execute(0xda37a0, 0xc000112280, 0x8, 0x8, 0xda37a0, 0xc000112280)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xda3a00, 0x9703c1, 0x17, 0x1)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:800
github.com/fanux/sealos/cmd.Execute()
        /go/src/github.com/fanux/sealos/cmd/root.go:46 +0x32
main.main()
        /go/src/github.com/fanux/sealos/main.go:20 +0x20

**Comment by fanux** [comment]
master建议在集群初始化时规划好，不建议后来添加，后来添加master请[参考文档](https://github.com/fanux/sealos#master0-1010397100-%E4%B8%8A)  原有node上lvscare也都需要加上新的master地址，见lvscare static pod的命令参数，可直接修改static pod yaml 在 node /etc/kubernetes/manifests下面
