### ISSUE TITLE
sealos install  dashboard.tar not work

### ISSUE THREAD

**Issue by ykw2** [fanux/sealos#145]
sealos install --pkg-url https://github.com/sealstore/dashboard/releases/download/v2.0.0-bata5/dashboard.tar
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fanux/sealos/install.(*SealosInstaller).KubeApply(0xc00011dd20, 0x0, 0x0)
        /go/src/github.com/fanux/sealos/install/install.go:22 +0x131
github.com/fanux/sealos/install.BuildInstall(0x0, 0x0)
        /go/src/github.com/fanux/sealos/install/install.go:13 +0x182
github.com/fanux/sealos/cmd.glob..func4(0xda3540, 0xc00008f280, 0x0, 0x2)
        /go/src/github.com/fanux/sealos/cmd/install.go:28 +0x39
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).execute(0xda3540, 0xc00008f260, 0x2, 0x2, 0xda3540, 0xc00008f260)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xda3a00, 0x9703c1, 0x17, 0x1)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/fanux/sealos/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:800
github.com/fanux/sealos/cmd.Execute()
        /go/src/github.com/fanux/sealos/cmd/root.go:46 +0x32
main.main()
        /go/src/github.com/fanux/sealos/main.go:20 +0x20

**Comment by YikongW** [comment]
我也是

**Comment by fanux** [comment]
版本不对，请用最新版本sealos, 3.0.0以上。  release页面可以下载
