### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by yubang** [fanux/sealos#148]
1.官网购买的离线包都是可以用于生产环境的不（我买了1.16.3）
2.一键安装出来的k8s是否跟官方的k8s一模一样，因为看文章介绍好像有改动什么的，对稳定性有没有什么影响的
3.有没有用在生产环境，规模较大的成功案例
4.购买的离线包授权问题，我可以安装多少个集群
5.dashboard可否直接暴露到公网，有没有什么安全性问题（因为有token来登录）

**Comment by yubang** [comment]
另外安装能否使用免密码ssh

**Comment by fanux** [comment]
免密钥支持，请参考readme.

1. 可用于生产，已经有非常多用户用于生产了
2. 和官方一样，只是定制了kubeadm支持了时间更长的证书，和扩展了LB功能，对稳定性无影响，localLB性能稳定性更好
3. 我们跑了上千台
4. 集群数量不限制
5. 除非有安全漏洞
