### ISSUE TITLE
外部如何通过 vip 访问集群？

### ISSUE THREAD

**Issue by zexi** [fanux/sealos#154]
我把集群部署在阿里云上面，想通过 eip 访问虚拟机里面部署的 k8s 集群，是要单独创建一个 LB，后端设置为 3 个 ‘APIServer:6443' 的地址吗？
如果我在自己的私有云环境部署，想实现外部通过 vip 访问集群的话，是不是还是需要另外的机器组建 keepalived + haproxy 实现负载均衡？

**Comment by fanux** [comment]
是的，不过在阿里云上你得把eip加到证书里。  如果只是需要kubectl的话我感觉连其中一台master就行，挂了大不了换个IP

**Comment by zexi** [comment]
我的集群已经搭建好了，可以之后再把eip加到证书重新 init 生效吗？ 还是说只能在 init 之前就把所有外部访问的 ip 和域名加到证书配置中？

**Comment by fanux** [comment]
最好init之前，不然你需要轮换一遍证书，还没重装方便，建议加个域名到证书中防止IP变化

**Comment by zexi** [comment]
好的，多谢
