### ISSUE TITLE
join master功能

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#161]
join流程参考[文档](https://sealyun.com/docs/aatutorial.html#%E5%A2%9E%E5%8A%A0%E8%8A%82%E7%82%B9)：

使用：
```
sealos join --master 192.168.0.3
```
高版本init时会生成配置文件到/root/.sealos/config.yaml文件中，已经安装的master信息密码信息以及版本信息等都在其中

[config.go](https://github.com/fanux/sealos/blob/master/install/config.go#L79)  可以Load该配置文件

**Comment by ysicing** [comment]
@fanux  添加master节点是否考虑将admin.conf同步到当前master节点.kube目录下
```
		copyk8sConf := `mkdir -p /root/.kube && cp -i /etc/kubernetes/admin.conf /root/.kube/config`
		Cmd(master, copyk8sConf)
```

**Comment by fanux** [comment]
这个可以

**Comment by ysicing** [comment]
但是得考虑到不少同学不是root用户 🤔

**Comment by fanux** [comment]
不是root有点麻烦，因为资源包需要打开ipvs等 需要权限比较高

**Comment by fanux** [comment]
/pay 144

先join master [文档](https://sealyun.com/docs/aatutorial.html#%E5%A2%9E%E5%8A%A0master%E8%8A%82%E7%82%B9)

再使用sed命令给lvscare static pod加上新的master地址

```
sed '/- https/a\    - --10.1.0.2:6443' -i /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml
sed '/- https/a\    - --rs' -i /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml
```
