### ISSUE TITLE
支持源码编译 适应其他架构

### ISSUE THREAD

**Issue by chinausers** [fanux/sealos#178]
main.go:18:2: cannot find package "github.com/fanux/sealos/cmd" in any of:
	/usr/local/go/src/github.com/fanux/sealos/cmd (from $GOROOT)
	/root/go/src/github.com/fanux/sealos/cmd (from $GOPATH)）

在树莓派4b+ 上无法源码编译

**Comment by fanux** [comment]
编译过了目前也没有ARM的资源包可以用唉。   你的golang版本和编译命令是什么，推荐用golang1.13

go build -mod vendor -o sealos -ldflags "-X github.com/fanux/sealos/version.Version=latest" main.go
