### ISSUE TITLE
创建不成功

### ISSUE THREAD

**Issue by Userxue123** [fanux/sealos#179]
**那个命令或者组件**
eg. sealos init , sealos install , kubernetes cni, docker  and so on 
sealos init --passwd root --master 192.168.1.50 --node 192.168.1.51 --node 192.168.1.52 --pkg-url https://sealyun.oss-cn-beijing.aliyuncs.com/413bd3624b2fb9e466601594b4f72072-1.17.0/kube1.17.0.tar.gz --version v1.17.0
**描述你的问题**
详细描述出你的问题内容xxxx.
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

2019-12-18 21:21:01 [EROR] [github.com/fanux/sealos/install/utils.go:114] [192.168.1.50]Error exec command failed: Process exited with status 1
2019-12-18 21:21:01 [EROR] [github.com/fanux/sealos/install/init.go:65] [192.168.1.50]kubernetes install is error.please clean and uninstall.
**你看到的一些参考资料**
eg. 文档的引用xxxx

**Comment by Userxue123** [comment]
已经解决 可能是我机器不行 换了台机器

**Comment by fanux** [comment]
如果发现etcd中有写延迟可能会造成改问题，大部分情况是机器io性能差引起
