### ISSUE TITLE
缺陷: 保持离线包的一致性

### ISSUE THREAD

**Issue by PatHoo** [fanux/sealos#182]
**哪个命令或者组件**
sealos init

**描述这个缺陷**
修改sealos执行端的离线包文件(tar.gz)，如果远端文件(tar.gz)已存在，不会更新远端文件(tar.gz)。

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.17.0.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   eg 3master 3node

**Comment by fanux** [comment]
可以增加md5校验

**Comment by cuisongliu** [comment]
在提供包的同时提供md5的文件。

**Comment by fanux** [comment]
#211
