### ISSUE TITLE
需求: 支持主机名或者IP的通配符

### ISSUE THREAD

**Issue by PatHoo** [fanux/sealos#183]
**哪个命令或者组件**
sealos init; sealos clean

**详细描述你的需求/任务**
1. 希望--master跟--node能支持主机名或者IP的通配符，不用写那么多IP地址。或者支持默认IP段范围的主机列表。

**是否有解决方案，如果有请详述**
1. 已通过shell脚本实现，通过代码实现待解决。
关键脚本如下：
`
for IP in $(cat Slave.ini|grep -Ev "^#|^$"|awk -F"[ ]+" '{gsub(/^\s+|\s+$/, ""); print $1}'); do echo "  --node ${IP} \\" >> SealInit.sh; done
`

**运行环境**

- Docker版本:    19.03+
- Kubernetes版本 : 1.16+
- sealos版本: v3.1.0-alpha.2 （计划版本）

**Comment by fanux** [comment]
```
sealos init --masters 192.168.0.2~192.168.0.6 --nodes 192.168.0.7~192.168.0.170 
```
可以如上面设计。 增加masters nodes参数。

IP地址++可用以下SDK实现：

```
https://github.com/containernetworking/plugins/blob/master/pkg/ip/cidr.go#L23
```
