### ISSUE TITLE
ssh 支持指定端口号

### ISSUE THREAD

**Issue by geyaandy** [fanux/sealos#184]
**组件**
sealos init

**需求**
在初始化过程中发现sealos默认使用ssh 22端口，对于非22端口不支持

**是否有解决方案，如果有请详述**
可以考虑支持指定host文件，文件内容类似ansible的hosts文件？这样既可以支持不同端口又可以支持不同主机用户和密码
[master]
host1 ansible_ssh_port=65522 ansible_ssh_host=10.0.0.1 ansible_ssh_user=simon 
[node]
host2 ansible_ssh_port=65522 ansible_ssh_host=10.0.0.1 ansible_ssh_user=simon 

**运行环境**
- Docker版本:    19.03+
- Kubernetes版本 : 1.15+
- sealos版本: v3.1.0-alpha.1

**Comment by ysicing** [comment]
支持指定端口 #147

```
sealos init --master 192.168.0.2:2022
```
