### ISSUE TITLE
缺陷: apiserver硬编码

### ISSUE THREAD

**Issue by PatHoo** [fanux/sealos#185]
**哪个命令或者组件**
sealos init; sealos clean

**描述这个缺陷**
更改--apiserver的值，可以正常init，但clean的时候不会清理/etc/hosts的条目。

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   eg 3master 3node
- 附加说明: istio,dashboard ...

**Comment by ysicing** [comment]
```
sealos clean -h
sealos clean --apiserver <自定义的api地址>
```

**Comment by PatHoo** [comment]
谢谢
