### ISSUE TITLE
clean需要清理安装包

### ISSUE THREAD

**Issue by ysicing** [fanux/sealos#191]
**组件/命令**

`sealos clean`

**需求**
1. sealos clean 时可以清理安装包和安装包解压后的文件夹

**是否有解决方案，如果有请详述**
1. 通过`/root/.sealos/config.yaml`的pkgurl来判断安装包
2. 可以考虑安装成功后删除(扩容节点时如果使用本地则会有问题？)

**Comment by fanux** [comment]
清理目录可以，压缩包感觉还是保留一下好，占不了多少磁盘

**Comment by ysicing** [comment]
这个和 #182 有些类似，我可能更新了离线安装包，clean的时候需要清理掉或者安装的时候重新同步

**Comment by PatHoo** [comment]
还是看具体需求吧，最好是配置项可选。
