### ISSUE TITLE
需求: 安装hook功能

### ISSUE THREAD

**Issue by cgdg3** [fanux/sealos#193]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1. 我想在kubeadm init执行完成之后，额外加一些初始化动作，Sealos可选调用额外脚本在master上执行
- 如安装helm，或者安装一些初始化的业务必须组件

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
1. sealos init初始化后支持调用脚本kube/shell/master.sh

**运行环境**

- Docker版本:    19.03+
- Kubernetes版本 : 1.15+
- sealos版本: v3.1.0-alpha.2 （计划版本）

**Comment by fanux** [comment]
安装过程中可以有几个典型的过程让用户自定义hook脚本，调用hook时把配置文件放到环境变量中，以供用户自定义hook脚本使用。

**Comment by fanux** [comment]
先关闭了  在后续大版本升级中统一处理

**Comment by fanux** [comment]
sealos init
sealos install -f values.yaml -c config
