### ISSUE TITLE
pkg不要放在/root

### ISSUE THREAD

**Issue by PatHoo** [fanux/sealos#195]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
sealos init的时候，会判断kube1.17.1.tar.gz在不在远程主机的/root目录，然后将其解压到/root目录．生产环境的根目录一般不大，建议将pkg文件放在/root之外的其他目录(比如单独挂载的/tmp目录)，最好支持init的时候自定义放置的位置．

**是否有解决方案，如果有请详述**
修改SealOS/install/utils.go的SendPackage函数?

**运行环境**
- Docker版本:    19.03+
- Kubernetes版本 : 1.16+
- sealos版本: v3.0.2

**Comment by ysicing** [comment]
@PatHoo 
我觉得暂不考虑是否存放在/root。可以考虑安装完成后删除解压文件 

- 初始化完成或者添加节点后可以考虑删除解压文件
- clean时可以清理解压文件

#191

**Comment by ysicing** [comment]
压缩包其他不大。另外生产环境的根目录一般不大，这个需要考量一下，生产环境是否配置合理。<del>(PS：这个我确实遇到过，华为私有云镜像默认根目录就10-20G)</del>
