### ISSUE TITLE
优化sealos join

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#199]
node 与nodes参数合并，以免理解起来费解以及与sealos clean保持一致。

```
--node 192.168.0.2 --node 192.168.0.6-192.168.0.10
```
分析一下值的特点判断是单个节点还是一个连续的IP地址

https://github.com/fanux/sealos/blob/develop/cmd/join.go#L40

/pay 30

**Comment by cuisongliu** [comment]
192.168.0.[0,3]
192.168.0.[0-3]
192.168.1.2,192.168.2.3

这样规则就可以吧

**Comment by fanux** [comment]
192.168.0.6-192.168.0.10 join时已经实现了这种写法，把两个参数合并一下就行。 精力充沛扩展一下192.168.0.[0,3]
192.168.0.[0-3]这两种写法也行

**Comment by cuisongliu** [comment]
192.168.[0,3].1   我是想做这种通配符的。我先合并一下吧 合并比较简单

**Comment by fanux** [comment]
阔以
