### ISSUE TITLE
需求: 高可用高稳定 (stable)

### ISSUE THREAD

**Issue by 95zz** [fanux/sealos#207]
项目很棒也很看好~
详细描述你的需求和任务要求
1. redis3.4+mysql5.7+elasticsearch+mq+nginx 高可用高稳定 (stable)
2. 采用helm管理出一套方案：存储+高并发+自动运维
3. 然后简单列出各个端口及 java,go,c,php连接实例

**Comment by fanux** [comment]
redis等等我们准备使用app去管理 https://sealyun.com/docs/app.html , helm3还可以考虑已经放弃helm2.0了，个人更倾向于kustomize, 不过sealos install的设计是啥都可以支持的。只要按照格式进行打包即可。 

这个不属于sealos本身的功能，我先关闭这个issue了，https://github.com/sealstore sealstore 致力于打造上层生态。
