### ISSUE TITLE
sealos多master的apiserver高可用是如何体现的？需要如何配置？

### ISSUE THREAD

**Issue by sd797994** [fanux/sealos#208]
k8s官方的高可用方案一般是keepalived+haproxy暴露一个vip来实现的apiserver高可用，这样无论哪台master宕机，只要有一个master实例，整个apiserver就是可用的(这里不讨论etcd可用性的问题，先假定etcd可用)。但是在sealos中，通过命令部署多个master之后，每个master节点执行拷贝$HOME/.kube/config后可以kubectl get node来观测到集群状况。但是当主动关闭第一个master之后，其他master就无法执行kubectl命令了，将提示“The connection to the server apiserver.cluster.local:6443 was refused - did you specify the right host or port?”

问题补充：经过测试发现当我指定三台master并init成功后，随机关闭一台master则剩余master apiserver可用，当关闭任意两台master让集群只保留一台master时这台master的apiserver将变为不可用状态，使用kubectl get node 将提示“The connection to the server apiserver.cluster.local:6443 was refused - did you specify the right host or port?”
---测试环境----
阿里云 esc 硬件配置：2c4G * 4 操作系统：centos7.7  sealos集群版本：v1.17.0

**Comment by sd797994** [comment]
问题补充：经过测试发现当我指定三台master并init成功后，随机关闭一台master则剩余master apiserver可用，当关闭任意两台master让集群只保留一台master时这台master的apiserver将变为不可用状态，使用kubectl get node 将提示“The connection to the server apiserver.cluster.local:6443 was refused - did you specify the right host or port?”

**Comment by fanux** [comment]
1. raft协议3台允许挂一台，etcd决定，所以3master时最多能关闭一台。
2. sealos老版本使用的是haproxy keepalived,新版本有了创新采用ipvs实现负载均衡，每个node都会代理到master，这样master挂了一个不会影响node正常链接master
3. kubectl用不了不重要，到别的master上去用kubectl即可。

更多原理请参考官方文档： sealyun.com/docs
