### ISSUE TITLE
V3.1.0版本，K8S V1.17.3 安装时提示 unknown flag: --experimental-upload-certs

### ISSUE THREAD

**Issue by wanglishuai** [fanux/sealos#209]
2020-02-29 10:18:51 [DEBG] [github.com/fanux/sealos/install/utils.go:118] [172.16.28.56]command result is: unknown flag: --experimental-upload-certs
To see the stack trace of this error execute with --v=5 or higher

**Comment by wanglishuai** [comment]
经过测试，是由于在入参中没有 --user 参数导致的，请修改该问题。

**Comment by wanglishuai** [comment]
./sealos init --passwd ***  --master 172.16.28.56   --node 172.16.28.55  --node 172.16.219.215 --version v.1.17.3 --pkg-url /opt/kube1.17.3.tar.gz

**Comment by fanux** [comment]
@cuisongliu 不传user会导致这个问题？ 确认一下啥情况

**Comment by wanglishuai** [comment]
经过测试，不是这个参数导致的，在前一次安装失败后，再次安装可能会触发这个错误，暂时没有再模拟出来。

**Comment by wanglishuai** [comment]
可能是我缺少了 --version v.1.17.3这个参数，但是脚本并不提示缺少必要参数。

**Comment by fanux** [comment]
--version v.1.17.3  缺少这个确实会导致这个情况

**Comment by oldthreefeng** [comment]
无情, 忘记加 --version ... 会报相同的错.
