### ISSUE TITLE
离线包购买后显示404错误

### ISSUE THREAD

**Issue by zhengwei19003** [fanux/sealos#214]
https://excashier.alipay.com/standard/auth.htm?payOrderId=bc933550b8ae45d4ba3a10102a714f50.80
在这个地址购买1.17.0的版本，在支付宝页面付完0.01之后，显示网页404错误。

**Comment by fanux** [comment]
可清理下cookie再重试，如果只是用1.17.0版本这是下载链接：https://sealyun.oss-cn-beijing.aliyuncs.com/413bd3624b2fb9e466601594b4f72072-1.17.0/kube1.17.0.tar.gz  

更多问题可加群讨论：QQ群：98488045
