### ISSUE TITLE
增加/删除master时重新生成node节点的lvscare staticpod

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#218]
https://github.com/fanux/sealos/blob/develop/ipvs/lvscare.go#L14

调用LvsStaticPodYaml函数即可生成static pod的yaml字符串，写到所有node节点的/etc/kubernetes/manifests目录，写之前把老的lvscare static pod删除。

**Comment by cuisongliu** [comment]
删除的feature 已经修复。
