### ISSUE TITLE
sealos:v3.1.1版本搭建k8s1.17.2版本高可用集群，master节点notReady

### ISSUE THREAD

**Issue by Billyxxu** [fanux/sealos#229]
**哪个命令或者组件**
sealos init --passwd 123456 \
	--master 192.168.0.2  --master 192.168.0.3  --master 192.168.0.4  \
	--node 192.168.0.5 \
	--pkg-url /root/kube1.16.0.tar.gz \
	--version v1.16.0

**描述这个缺陷**
init命令执行未发生错误，但是执行该命令的节点处于notReady状态。查看coredns和kube-proxy未处于running状态；在kubelet中查看到“while getting aws credentials NoCredentialProviders:no valid providers in chain, Deprecated.”和"failed to start containerManager failed to initialize top level QOS container:fialed to update top level Burstable QOS cgroup..."

**重现步骤（如果有需要可以附加图片）**
1. 执行sealos init
...

**测试结果**
1. 执行init命令的master节点处于notReady状态
2. coredns和kube-proxy未running
3.推测证书存在问题

**期望结果**
1. 期望出现 所有节点处于ready状态
   前置条件: 主机名不重复；机器时间同步；关闭防火墙，selinux，swap等
   操作步骤:
   1. sealos init ...

**运行环境**

- Docker版本:   19.03.0
- Kubernetes版本 : 1.17.2
- sealos版本: v3.1.1
- 操作系统:  centos7.4
- 运行模式:  虚拟机 ( virbox, 内存 8gb, cpu 4核 ,存储 200gb )
- 集群规模:   3master1node

**Comment by zhangguanzhang** [comment]
7.4整docker问题非常多- -

**Comment by Billyxxu** [comment]
你觉得是linux7.4内核对docker/k8s不友好？

**Comment by Billyxxu** [comment]
> 7.4整docker问题非常多- -

你觉得是linux7.4内核对docker/k8s不友好？

**Comment by zhangguanzhang** [comment]
我只是建议，我这遇到不下于5起7.4出问题的，我都是把系统给他们整成7.6+后拷贝/var/lib/docker的
你这个问题得把kubelet的详细日志发出来，systemctl status -l kubelet

**Comment by fanux** [comment]
不是AWS的机器？ .aws/config有这个文件吗？

**Comment by fanux** [comment]
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/929

**Comment by fanux** [comment]
https://github.com/kubernetes/autoscaler/issues/1321

**Comment by fanux** [comment]
先关了
