### ISSUE TITLE
sealos 3.2.0 、k8s 1.17.0 ，sealos join --node 192.168.1.225 ,but failed

### ISSUE THREAD

**Issue by huangkaiyan10** [fanux/sealos#275]
![image](https://user-images.githubusercontent.com/5146180/78233025-b9c2e580-7507-11ea-96e6-f52ced548342.png)

![image](https://user-images.githubusercontent.com/5146180/78233067-c8a99800-7507-11ea-94a1-451d5b385ede.png)

**Comment by fanux** [comment]
用3.1.1+1.17.0  或 3.2.0+1.18.0

**Comment by zhangguanzhang** [comment]
怎么有执行个ipvs的子命令
