### ISSUE TITLE
执行安装命名出错:sealos init --master 192.168.3.187  --node 192.168.3.188  --user 'root'  --passwd  '123qwe!!!'  --version v1.17.0  pkg-url /opt/k8s/kube1.17.0.tar.gz

### ISSUE THREAD

**Issue by bell152** [fanux/sealos#277]
sealos init --master 192.168.3.187  --node 192.168.3.188  --user 'root'  --passwd  '123qwe!!!'  --version v1.17.0  pkg-url /opt/k8s/kube1.17.0.tar.gz

**描述你的问题**
Error exec command failed: Process exited with status 127
kubernetes install is error.please clean and uninstall.

![image](https://user-images.githubusercontent.com/11853380/78243084-af0f4d00-7515-11ea-9e7e-ba674ad23b7d.png)

**Comment by fanux** [comment]
1.17.0 请使用3.1.1版本sealos， 3.2.0版本对1.18.0以下版本有bug，我们正在修复
