### ISSUE TITLE
/etc/kubernetes/manifests/kube-sealyun-lvscare.yaml: 没有那个文件或目录

### ISSUE THREAD

**Issue by bingoku** [fanux/sealos#282]
版本：v3.2.0

部署1.18 的时候出错

```
" > /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml
2020-04-03 11:16:29 [DEBG] [github.com/fanux/sealos/vendor/github.com/cuisongliu/sshcmd/pkg/sshutil/ssh.go:23] [10.10.10.119]command result is: bash:行36: /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml: 没有那个文件或目录

2020-04-03 11:16:29 [EROR] [github.com/fanux/sealos/vendor/github.com/cuisongliu/sshcmd/pkg/sshutil/ssh.go:26] [10.10.10.119]Error exec command failed: Process exited with status 1
```

**Comment by jinnzy** [comment]
> 版本：v3.2.0
> 
> 部署1.18 的时候出错
> 
> ```
> " > /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml
> 2020-04-03 11:16:29 [DEBG] [github.com/fanux/sealos/vendor/github.com/cuisongliu/sshcmd/pkg/sshutil/ssh.go:23] [10.10.10.119]command result is: bash:行36: /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml: 没有那个文件或目录
> 
> 2020-04-03 11:16:29 [EROR] [github.com/fanux/sealos/vendor/github.com/cuisongliu/sshcmd/pkg/sshutil/ssh.go:26] [10.10.10.119]Error exec command failed: Process exited with status 1
> ```

可以提供当时执行的命令吗？

**Comment by fanux** [comment]
咦 这个锅应该是修了的吧。
执行下 sealos version 确认下版本，可能二进制被覆盖了

**Comment by zhangguanzhang** [comment]
是文件夹没创建

**Comment by fanux** [comment]
@zhangguanzhang @jinnzy 还特意修了这个问题呢

**Comment by bingoku** [comment]
初始化一个master 和一个node 的时候，稳定复现

**Comment by jinnzy** [comment]
> 初始化一个master 和一个node 的时候，稳定复现
执行如下命令看下版本，我刚才用这个版本测试没问题。
```
[root@vlnx107020 ~]# sealos version
sealos version v3.2.0, build  go1.13.5
```

**Comment by bingoku** [comment]
<img width="1937" alt="image" src="https://user-images.githubusercontent.com/4134788/78419858-573f2600-767c-11ea-922a-19fd9e737d99.png">

 执行命令

./sealos init  --passwd 1 --master 10.10.10.117 --node 10.10.10.119 --pkg-url /root/kube1.18.0.tar.gz --version v1.18.0

@cuisongliu @fanux

**Comment by bingoku** [comment]
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/4134788/78419922-198ecd00-767d-11ea-836e-dd2eb6d93a64.png">

**Comment by fanux** [comment]
版本不对  sealos version

**Comment by fanux** [comment]
输出来看下
