### ISSUE TITLE
node节点经常notReday

### ISSUE THREAD

**Issue by meidea** [fanux/sealos#299]
按照文档安装后，node节点经常notReady，使用 journalctl -f 查看日志后，发现是请求https://apiserver.cluster.local:6443 失败，请问这个怎么解决呢？

![error](https://user-images.githubusercontent.com/19621448/78633888-40dfd700-78d5-11ea-8f4e-b36b5dff02d7.jpg)

**Comment by fanux** [comment]
查看etcd日志，应该会有一些同步超时。 一般磁盘太差会出现不稳定的情况

**Comment by zhangguanzhang** [comment]
超时的时候
```bash
curl -sk https://xxx:6443/healthz
```
分别对master的ip访问看看，看看各个master情况正常不

**Comment by meidea** [comment]
> 超时的时候
> 
> ```shell
> curl -sk https://xxx:6443/healthz
> ```
> 
> 分别对master的ip访问看看，看看各个master情况正常不

使用ip是正常的，使用apiserver.cluster.local 不行

**Comment by fanux** [comment]
1. 你是什么版本 sealos 版本 离线包版本
2. notready时node磁盘满了没

**Comment by meidea** [comment]
> 1. 你是什么版本 sealos 版本 离线包版本
> 2. notready时node磁盘满了没

版本：v1.18.0
磁盘：没满

[root@kubernetes-slave1 ~]$ sealos version
sealos version latest, build 546eaa8 go1.13.5
[root@kubernetes-slave1 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
[root@kubernetes-slave1 ~]$ ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.168.0.165:32081 rr
TCP  10.96.0.1:443 rr
  -> 192.168.0.183:6443           Masq    1      2          0
TCP  10.96.0.10:53 rr
  -> 100.88.27.1:53               Masq    1      0          0
TCP  10.96.0.10:9153 rr
  -> 100.88.27.1:9153             Masq    1      0          0
TCP  10.103.97.2:6443 rr
  -> 192.168.0.183:6443           Masq    1      0          0
TCP  10.111.201.110:8081 rr
TCP  100.104.218.128:32081 rr
TCP  127.0.0.1:32081 rr
TCP  172.17.0.1:32081 rr
UDP  10.96.0.10:53 rr
  -> 100.88.27.1:53               Masq    1      0          0
[root@kubernetes-slave1 ~]$

**Comment by meidea** [comment]
具体表现：
curl -sk https://10.103.97.2:6443/healthz 返回ok
node运行一段时间后，curl -sk https://10.103.97.2:6443/healthz 请求无响应
systemctl restart docker 后，重新curl，正常返回ok

**Comment by fanux** [comment]
大概运行多长时间？ 我看看我这边能不能复现。  然后你可以更新一下fanux/lvscare这个镜像再杀一下lvscare pod再试试能不能修复。  还有就是1.18.0社区有一些bug，比如kube-proxy一直刷错误日志，我们1.18.1上线了可以试试

**Comment by meidea** [comment]
大概运行一天吧，我目前直接把hosts里的ip改成masterIP，暂时可以用了，回头用1.18.1试试

**Comment by fanux** [comment]
1.18.0 1.18.1最好都别用在生产，因为社区有bug.  你的这个问题我大概定位到了  再确认

**Comment by meidea** [comment]
好的👌

**Comment by Mavlarn** [comment]
@fanux 我安装1.18.0 和 1.18.1版本，也有这个问题，我在master节点获取部署在worker节点的pod的logs的时候，返回
```
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```
我也发现worker node的状态时不时的会变成“NotReady”。
因为在fanux/lvscare 的pod中看到过有关 `10.103.97.2:6443` 的错误，我就把worker节点的hosts文件中的apiserver.cluster.local对应的IP改成了真实的master的IP地址，就能够获取各节点的logs信息了。

目前准备现状1.17.x再看看。

**Comment by fanux** [comment]
Authorization error 问题已经定位到了，docker pull fanux/lvscare:tiny  用这个镜像替换node static pod 中的fanux/lvscare:latest即可。

**Comment by Mavlarn** [comment]
我刚才试了一下1.27.4的版本，还是同样的问题，之前玩的docker都是自己安装的，是18.x的版本，我试着删掉了docker，让sealos自动安装，装的是19.03的，目前看着是可以用了。lvscare的版本，我也是用的昨天pull的latest的，是修复了刷日志问题的那个。

**Comment by fanux** [comment]
@Mavlarn lvscare先不要用latest， latest中用了k8s的库，而k8s库有bug。 可以先用 fanux/lvscare:tiny 这个版本代替。 如我上面所说，就不会报错了。 社区也正在修复那个问题

**Comment by Mavlarn** [comment]
我load了tiny的版本，重新打tag成latest，然后删除pod，起来以后获取日志还是提示“Authorization error”，而且奇怪的是，过了一会又可以，又过一会又不可以。。。
我装的是1.17.4的版本，装完以后还是正常的，昨天发现又出现“Authorization error”的错误了。

**Comment by fanux** [comment]
https://github.com/fanux/sealos/issues/315
