### ISSUE TITLE
问题: Why not `sealos clean` remove docker that `sealos init` installed.

### ISSUE THREAD

**Issue by Jevi06** [fanux/sealos#300]
**那个命令或者组件**
sealos init,sealos clean

**描述你的问题**
sealos clean not work as expect.

**你看到的一些参考资料**
eg. nothing. But I think clean command should do reverse all that init command do to a master or node.

**Comment by fanux** [comment]
YES, I agree with you. We will consider your suggestion in a future version.   At present, the main consideration is just not to affect the reinstallation.

**Comment by Jevi06** [comment]
> YES, I agree with you. We will consider your suggestion in a future version. At present, the main consideration is just not to affect the reinstallation.

Thanks.And thanks for this great project.
