### ISSUE TITLE
无法查看node节点日志

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#306]
[root@iZ2zearpu5gbdedi9pm6qgZ ~]# kubectl  logs kube-sealyun-lvscare-iz2zearpu5gbdedi9pm6qhz -n kube-system
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)

**Comment by zhangguanzhang** [comment]
缺少一个rbac，我找下

**Comment by fanux** [comment]
```
Apr 10 15:34:35 localhost kubelet: E0410 15:34:35.476401   31230 server.go:269] Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)%!(EXTRA *url.Error=Post https://apiserver.cluster.local:6443/apis/authorization.k8s.io/v1/subjectaccessreviews: read tcp 172.16.9.237:42660->10.103.97.2:6443: use of closed network connection)
```

**Comment by fanux** [comment]
use of closed network connection  怀疑是lvscare在中间的时候清理了规则造成。  把lvscare停止之后再去获取node上的static pod日志就正常

**Comment by fanux** [comment]
1. lvscare启动时访问日志出错
2. 停止lvscare的static pod, 保留ipvs规则
3. 再起一个测试pod,访问测试pod日志，可正常访问

**Comment by fanux** [comment]
最新发现重启lvscare pod之后可以正常访问日志。

有群友提出：
![image](https://user-images.githubusercontent.com/8912557/79034235-09c83900-7be7-11ea-87fc-b8b7278a2727.png)

之后 可以访问日志

**Comment by fanux** [comment]
使用老版本lvscare无此问题。

到node上，修改lvscare static pod yaml, 把镜像改成 fanux/lvscare:tiny 可解决这个问题。

原因是引用了kube-proxy的库，而库中对ip解析有bug造成
