### ISSUE TITLE
sealog clean指定端口失效

### ISSUE THREAD

**Issue by svolence** [fanux/sealos#307]
**哪个命令或者组件**
sealos clean --master 192.168.10.3:2022

**描述这个缺陷**
# sealos clean --master 192.168.10.3:2022
clean command will clean masters [192.168.10.3:2022], continue clean (y/n)?y
13:37:36 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : kubeadm reset -f && modprobe -r ipip  && lsmod
13:37:37 [INFO] [ssh.go:60] [ssh][192.168.10.3:2022]: [reset] Reading configuration from the cluster...
13:37:37 [INFO] [ssh.go:60] [ssh][192.168.10.3:2022]: [preflight] Running pre-flight checks
13:37:37 [INFO] [ssh.go:60] [ssh][192.168.10.3:2022]: W0409 13:37:37.221227    8073 removeetcdmember.go:61] [reset] failed to remove etcd member: error syncing endpoints with etc: etcdclient: no available endpoints
13:37:37 [INFO] [ssh.go:60] [ssh][192.168.10.3:2022]: [reset] Unmounting mounted directories in "/var/lib/kubelet"
13:37:42 [INFO] [ssh.go:60] [ssh][192.168.10.3:2022]: [reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
13:37:42 [INFO] [ssh.go:60] [ssh][192.168.10.3:2022]:
13:37:42 [INFO] [ssh.go:60] [ssh][192.168.10.3:2022]: Module                  Size  Used by
13:37:42 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : rm -rf ~/.kube/ && rm -rf /etc/kubernetes/
13:37:42 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : rm -rf /etc/systemd/system/kubelet.service.d && rm -rf /etc/systemd/system/kubelet.service
13:37:42 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : rm -rf /usr/bin/kube* && rm -rf /usr/bin/crictl
13:37:42 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : rm -rf /etc/cni && rm -rf /opt/cni
13:37:43 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : rm -rf /var/lib/etcd && rm -rf /var/etcd
13:37:43 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : sed -i "/apiserver.cluster.local/d" /etc/hosts
13:37:43 [INFO] [ssh.go:36] [ssh][192.168.10.3:2022]exec cmd is : rm -rf ~/kube
13:37:44 [DEBG] [clean.go:123] clean node in master
13:37:44 [INFO] [ssh.go:11] [ssh][192.168.10.3:22]exec cmd is : kubectl get nodes | grep -v NAME  | awk '{print $1}'
13:37:44 [EROR] [ssh.go:15] [ssh][192.168.10.3:22]Error create ssh session failed,dial tcp 192.168.10.3:**22**: connect: connection refused

**运行环境**

- Docker版本:   18.09
- Kubernetes版本 : 1.15.3
- sealos版本: latest
- 操作系统:  centos7.6
- 集群规模:   3master 1node

**Comment by cuisongliu** [comment]
.root/sealos/config.yaml  麻烦看一下

**Comment by svolence** [comment]
重试成功！
