### ISSUE TITLE
部署一个服务在sealos里面，外部只能通过其中一个nodePort节点+端口访问到

### ISSUE THREAD

**Issue by kct12345** [fanux/sealos#314]
问题描述如下
部署了一个服务，本机通过浏览器+nodePort+服务端口访问，服务的防火墙是永久关闭的
http://192.168.10.15 k8s-master1(访问不到)
http://192.168.10. k8s-master2(访问不到)
http://192.168.10. k8s-master3(访问不到)
http://192.168.10..30 node1(访问不到)
http://192.168.10..31 node2(访问不到)
http://192.168.10..35 node3(访问到)
即服务pod运行在那个节点了上，只能通过那个节点ip+端口访问到服务，其他节点不行
看了群里面群友的建议
设置iptables
iptables -P FORWARD ACCEPT
设置之后问题还是没有解决，哪位遇到过向我这样的问题吗

**Comment by zhangguanzhang** [comment]
看看calico的pod状态，还有部署一个nginx的pod，垮节点curl podip 能不能看到nginx的默认index

**Comment by kct12345** [comment]
> 看看calico的pod状态，还有部署一个nginx的pod，垮节点curl podip 能不能看到nginx的默认index

采用张馆长的方法，查看calico的状态正常，部署了一个类似nginx的服务访问
curl http://192.168.10.15:30020 k8s-master1(访问不到) 
curl http://192.168.10.21:30020 k8s-master2(访问不到)
curl http://192.168.10.29:30020 k8s-master3(访问不到)
curl http://192.168.10.30:30020 node1(访问不到)
curl http://192.168.10.31:30020 node2(访问不到)
curl http://192.168.10.35:30020 node3(访问到) 
使用k8s内部网络：curl http://100.66.209.192:30020 还是只有在node3节点访问到index页面

**Comment by kct12345** [comment]
采用张馆长的方法，查看calico的状态正常，

部署了一个类似nginx的服务访问
curl&nbsp;k8s-master1(访问不到)
curl&nbsp;k8s-master2(访问不到)
curl&nbsp;&nbsp;k8s-master3(访问不到)
curl&nbsp;&nbsp;node1(访问不到)
curl&nbsp;&nbsp;node2(访问不到)
curl&nbsp;&nbsp;node3(访问到)
使用k8s内部网络：curl&nbsp;http://100.66.209.192:30020&nbsp;还是只有在node3节点访问到index页面




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangguanzhang"<notifications@github.com&gt;; 
发送时间: 2020年4月16日(星期四) 中午11:46
收件人: "fanux/sealos"<sealos@noreply.github.com&gt;; 
抄送: "1500906828"<1500906828@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fanux/sealos] 部署一个服务在sealos里面，外部只能通过其中一个nodePort节点+端口访问到 (#314)





 
看看calico的pod状态，还有部署一个nginx的pod，垮节点curl podip 能不能看到nginx的默认index

**Comment by fanux** [comment]
看下lvscare日志有没有报错，有的话按照 issue 315更新一下lvscare镜像

**Comment by zhangguanzhang** [comment]
如果你pod是在node3上，那就是垮节点不通，calico的协议没有正常工作，需要排下calico的错误

**Comment by kct12345** [comment]
> 看下lvscare日志有没有报错，有的话按照 issue 315更新一下lvscare镜像
更新了还是没有解决问题呀，

**Comment by kct12345** [comment]
> 如果你pod是在node3上，那就是垮节点不通，calico的协议没有正常工作，需要排下calico的错误

馆长大佬怎么排查呢。我看日志也没错，通过啥方法排calico的错误呀

**Comment by zhangguanzhang** [comment]
就是部署一个nginx的pod，然后假如pod落在x上，在非x的node上curl podIP看有没有nginx的index

**Comment by kct12345** [comment]
非x的是可以访问到podIp的index界面的.
现在想解决的是非x的节点ip+端口也能访问




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhangguanzhang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午5:39
收件人:&nbsp;"fanux/sealos"<sealos@noreply.github.com&gt;;
抄送:&nbsp;"1500906828"<1500906828@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fanux/sealos] 部署一个服务在sealos里面，外部只能通过其中一个nodePort节点+端口访问到 (#314)





 
就是部署一个nginx的pod，然后假如pod落在x上，在非x的node上curl podIP看有没有nginx的index
