### ISSUE TITLE
kubeadm init时在master节点卡主

### ISSUE THREAD

**Issue by kjl8401111** [fanux/sealos#344]
```
13:48:29 [INFO] [ssh.go:36] [ssh][192.168.56.88:22]exec cmd is : echo 192.168.56.88 apiserver.cluster.local >> /etc/hosts
13:48:29 [INFO] [ssh.go:11] [ssh][192.168.56.88:22]exec cmd is : kubeadm init --config=/root/kubeadm-config.yaml --upload-certs
13:57:26 [DEBG] [ssh.go:23] [ssh][192.168.56.88:22]command result is: W0507 13:48:29.616029   15195 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0507 13:48:29.618962   15195 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.2
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.18.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.18.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.18.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.18.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.4.3-0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.7: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

13:57:26 [EROR] [ssh.go:26] [ssh][192.168.56.88:22]Error exec command failed: Process exited with status 1
13:57:26 [EROR] [init.go:130] [192.168.56.88:22]kubernetes install is error.please clean and uninstall.
```

**Comment by fanux** [comment]
你的执行命令贴出来  应该是版本写错

**Comment by kjl8401111** [comment]
sealos init --user root --passwd 123123  --master 192.168.56.88  --node 192.168.56.77 --pkg-url /root/kube1.18.2.tar.gz --version v1.18.2 --interface enp0s3

**Comment by fanux** [comment]
那就是镜像导入失败，你到节点上解压压缩包 然后cd kube/shell && sh init.sh 之后再重新init试下

**Comment by zhangguanzhang** [comment]
应该加一个参数给kubeadm的-v的值，默认给kubeadm的所有命令加个-v=0，命令行提供一个参数或者环境变量来改变这个0来debug kubeadm的log level

**Comment by kjl8401111** [comment]
sh init.sh 初始化，报的错误如下：

14:50:15 [INFO] [ssh.go:36] [ssh][192.168.56.77:22]exec cmd is : echo 192.168.56.77 apiserver.cluster.local >> /etc/hosts
14:50:15 [INFO] [ssh.go:11] [ssh][192.168.56.77:22]exec cmd is : kubeadm init --config=/root/kubeadm-config.yaml --upload-certs
14:54:17 [DEBG] [ssh.go:23] [ssh][192.168.56.77:22]command result is: W0507 14:50:15.659755   23193 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0507 14:50:15.661715   23193 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.2
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
W0507 14:50:17.327756   23193 manifests.go:225] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
[control-plane] Creating static Pod manifest for "kube-scheduler"
W0507 14:50:17.329164   23193 manifests.go:225] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in docker:
                - 'docker ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'docker logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

14:54:17 [EROR] [ssh.go:26] [ssh][192.168.56.77:22]Error exec command failed: Process exited with status 1
14:54:17 [EROR] [init.go:104] [192.168.56.77:22]kubernetes install is error.please clean and uninstall.

**Comment by kjl8401111** [comment]
kubelet是正常运行的
![image](https://user-images.githubusercontent.com/25808688/81263965-33a03e80-9073-11ea-8b8c-57f4d506ccfa.png)

**Comment by fanux** [comment]
> 应该加一个参数给kubeadm的-v的值，默认给kubeadm的所有命令加个-v=0，命令行提供一个参数或者环境变量来改变这个0来debug kubeadm的log level

好主意

**Comment by fanux** [comment]
那是iptables的锅？

**Comment by zhangguanzhang** [comment]
昨晚我给他远程看了下，就是镜像不存在，我看了代码是kubeadm os.exec执行docker inspect判断镜像存在否，实际是判定不存在了拉取镜像，但是又拉不到镜像一直卡在那

**Comment by kjl8401111** [comment]
docker的镜像目录给删了，导致安装不能正常进行，sealos init不会清理已安装docker的相关部分，删掉节点中关于docker相关的，重新安装就可以了
