### ISSUE TITLE
k8s节点的INTERNAL-IP使用安装时指定的ip

### ISSUE THREAD

**Issue by ysicing** [fanux/sealos#346]
1. kubelet 指定--node-ip参数,而不是自动获取

**是否有解决方案，如果有请详述**
1. 安装时，将ip信息写到 EnvironmentFile 

如debian：

```
# kubelet配置
EnvironmentFile=-/etc/default/kubelet

cat /etc/default/kubelet 
KUBELET_EXTRA_ARGS="--node-ip=11.11.11.111"
```

**Comment by fanux** [comment]
你是需要sealos加这个环境变量？

**Comment by ysicing** [comment]
安装时给kubelet指定node-ip参数。

debian系统下默认是 EnvironmentFile=-/etc/default/kubelet
centos下好像是另外一个文件

**Comment by PatHoo** [comment]
多网卡导致的吗?

**Comment by PatHoo** [comment]
我也是多网卡，但没有这个问题。

**Comment by ysicing** [comment]
@PatHoo  多网卡时，不同网络下会有些问题，需要手动调整kubelet node ip

**Comment by ysicing** [comment]
感觉场景不多。
