### ISSUE TITLE
kube-proxy使用IPVS模式

### ISSUE THREAD

**Issue by BussanQ** [fanux/sealos#352]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1.是否支持配置kube-proxy使用IPVS模式，比iptables性能更高
2.
3.

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
1.
2.
3.

**Comment by cuisongliu** [comment]
现在就是ipvs的模式
