### ISSUE TITLE
sealos备份集群功能

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#353]
1. 落盘位置，支持远程服务器
2. 备份配置设计  是否支持定时？？？
3. 需要备份的文件？

**Comment by fanux** [comment]
1. 只需要备份到本地即可，至于要不要传oss啥的我们不关心，用户决定
2. 理论上定时肯定更友好，不过工具只考虑备份即可我觉得
3. 主要是etcd的数据备份

如：
```
sealos save etcd.db
sealos restore etcd.db
```
