### ISSUE TITLE
apiserver.cluster.local:6443 connection refused

### ISSUE THREAD

**Issue by zgzhly** [fanux/sealos#356]
centos75,kernel4.9  ,k8s1.18
calico-node的pod无法正常启动,节点显示Notready
![IMG_20200522_113429](https://user-images.githubusercontent.com/10286638/82629931-c28c8980-9c23-11ea-8c62-004995e710ea.jpg)
![IMG_20200522_115643](https://user-images.githubusercontent.com/10286638/82629935-c4eee380-9c23-11ea-89c3-06638ae26a16.jpg)
![IMG_20200522_115721](https://user-images.githubusercontent.com/10286638/82629938-c6201080-9c23-11ea-94ae-37c9625a5950.jpg)

**Comment by zhangguanzhang** [comment]
kubectl -s指向master的ip和apiserver的端口试试 get

**Comment by fanux** [comment]
建议升级到1.18.3  @cuisongliu 1.18.0是不是重新打包一下，因为目前1.18.0的lvscare还没优化

**Comment by PatHoo** [comment]
最近Q群里都在说节点NotReady的事情，最好还是重新打包一下吧，这问题挺烦的。

**Comment by cuisongliu** [comment]
已经重新打包
