### ISSUE TITLE
优化：当前的逻辑会重复使用机器上的cert及kubeconfig文件

### ISSUE THREAD

**Issue by dujiashu** [fanux/sealos#359]
**哪个命令或者组件**
sealos init等
**描述这个缺陷**
当使用sealos安装集群时， 如果执行sealos命令的机器上已经有了cert文件以及kubeconfig文件，那么sealos就会复用机器上已存在的文件进行load操作， 而不会重新创建，这样会在某些未清理完全的情况下引起问题。

**Comment by cuisongliu** [comment]
目前在clean集群的时候会把本地生成的文件全部删除，这个问题应该是fix了。
