### ISSUE TITLE
your pkg-url is empty,please check your command is ok?

### ISSUE THREAD

**Issue by w8589167** [fanux/sealos#365]
**那个命令或者组件**
sealos init --master 192.168.59.3 --node 192.168.59.4 --user root --passwd 7758521 --version v1.18.0 --pkg-url /root/kube1.18.0.tar.gz

**描述你的问题**
执行 sealos init --master 192.168.59.3 --node 192.168.59.4 --user root --passwd 7758521 --version v1.18.0 --pkg-url /root/kube1.18.0.tar.gz
报错 命令行提示：your pkg-url is empty,please check your command is ok?

![image](https://user-images.githubusercontent.com/29417610/83224835-f2ea9f80-a1b0-11ea-9b7d-03c35f6844a6.png)

**Comment by cuisongliu** [comment]
可以了 你在试试

**Comment by w8589167** [comment]
@cuisongliu 不行   还是一样的报错  ，我本地有离线包 它却提示pkg-url为空

**Comment by w8589167** [comment]
没有 还是不能用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cuisongliu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 中午1:35
收件人:&nbsp;"fanux/sealos"<sealos@noreply.github.com&gt;;
抄送:&nbsp;"妮可妮可妮"<445839655@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fanux/sealos] your pkg-url is empty,please check your command is ok? (#365)





 
可以了 你在试试

**Comment by cuisongliu** [comment]
重新下载sealos
