### ISSUE TITLE
your pkg-url is empty,please check your command is ok?

### ISSUE THREAD

**Issue by w8589167** [fanux/sealos#366]
那个命令或者组件
sealos init --master 192.168.59.3 --node 192.168.59.4 --user root --passwd 7758521 --version v1.18.0 --pkg-url /root/kube1.18.0.tar.gz

描述你的问题
执行 sealos init --master 192.168.59.3 --node 192.168.59.4 --user root --passwd 7758521 --version v1.18.0 --pkg-url /root/kube1.18.0.tar.gz
报错 命令行提示：your pkg-url is empty,please check your command is ok?

**Comment by fanux** [comment]
sealos version 看一下

@cuisongliu 貌似不止一个人提这个问题了哈

**Comment by cuisongliu** [comment]
这个已经修复了
