### ISSUE TITLE
缺陷: 删除第一个master

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#369]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/4150905/83827981-2a59ce80-a712-11ea-9ede-973fb931d268.png">

删除第一个master的问题

**Comment by cuisongliu** [comment]
`09:41:46 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] rm -rf ~/.kube/ && rm -rf /etc/kubernetes/
09:41:56 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] rm -rf /etc/systemd/system/kubelet.service.d && rm -rf /etc/systemd/system/kubelet.service
09:42:07 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] rm -rf /usr/bin/kube* && rm -rf /usr/bin/crictl
09:42:17 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] rm -rf /etc/cni && rm -rf /opt/cni
09:42:27 [INFO] [ssh.go:50] [172.27.139.67:22] /root/.bashrc: line 14: kubectl: command not found
09:42:27 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] rm -rf /var/lib/etcd && rm -rf /var/etcd
09:42:37 [INFO] [ssh.go:50] [172.27.139.67:22] /root/.bashrc: line 14: kubectl: command not found
09:42:37 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] sed -i "/apiserver.cluster.local/d" /etc/hosts
09:42:47 [INFO] [ssh.go:50] [172.27.139.67:22] /root/.bashrc: line 14: kubectl: command not found
09:42:47 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] rm -rf ~/kube
09:42:57 [INFO] [ssh.go:50] [172.27.139.67:22] /root/.bashrc: line 14: kubectl: command not found
09:42:57 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] rm -rf /etc/kubernetes/pki
09:43:08 [INFO] [ssh.go:50] [172.27.139.67:22] /root/.bashrc: line 14: kubectl: command not found
09:43:08 [DEBG] [clean.go:118] clean node in master
09:43:08 [INFO] [ssh.go:12] [ssh][172.27.139.67:22] kubectl get nodes | grep -v NAME  | awk '{print $1}'
09:43:18 [DEBG] [ssh.go:24] [ssh][172.27.139.67:22]command result is: /root/.bashrc: line 14: kubectl: command not found
bash: kubectl: command not found

09:43:18 [INFO] [ssh.go:12] [ssh][172.27.139.67:22] hostname
09:43:28 [DEBG] [ssh.go:24] [ssh][172.27.139.67:22]command result is: /root/.bashrc: line 14: kubectl: command not found
cjr-ylc-dev-4

09:43:28 [DEBG] [utils.go:157] hosts /root/.bashrc: line 14: kubectl: command not found,bash: kubectl: command not found,
09:43:28 [INFO] [ssh.go:57] [ssh][172.27.139.67:22] kubectl delete node
09:43:38 [INFO] [ssh.go:50] [172.27.139.67:22] /root/.bashrc: line 14: kubectl: command not found
09:43:38 [INFO] [ssh.go:50] [172.27.139.67:22] bash: kubectl: command not found`

**Comment by fanux** [comment]
所以不能取master0节点执行命令。。

**Comment by cuisongliu** [comment]
对。我修复一下、

**Comment by cuisongliu** [comment]
已经修复。是由于.bashrc里有kubect 自动提示导致。
