### ISSUE TITLE
ipvs模式

### ISSUE THREAD

**Issue by huangqun** [fanux/sealos#371]
**那个命令或者组件**
ipvs模式

**描述你的问题**
ipvs模式貌似会在网卡绑定虚拟ip，在内网很容易造成ip冲突，这个问题在新版k8s还有吗？

假如还有的话，能不能配置成使用iptables模式？

**你看到的一些参考资料**
参考https://github.com/kubernetes/kubernetes/issues/59156

**Comment by zhangguanzhang** [comment]
ipvs的vip都是svc的ip，你的svc的cidr设置成一个内网没使用的cidr即可

**Comment by huangqun** [comment]
但是如果需要，也能切换成iptables模式吗？

**Comment by zhangguanzhang** [comment]
能的，而且每次kube-proxy起来的时候会触发一次clean

**Comment by fanux** [comment]
修改kubeproxy的configmap即可，另外渣渣才用iptables模式，非常不稳定

**Comment by huangqun** [comment]
明白了，谢谢！
