### ISSUE TITLE
sealos创建k8s 1.18集群，在集群内解释不了内部命名空间等地址

### ISSUE THREAD

**Issue by FrelDX** [fanux/sealos#372]
1.18集群创建完成后dns解析不了，pod之间ip访问正常，在pod中ping svc解析不了。

**Comment by FrelDX** [comment]
dns服务正常

**Comment by FrelDX** [comment]
倒了血霉了，还是老实用kubeadm重新装算了

**Comment by zhangguanzhang** [comment]
请参考这个试下
https://github.com/fanux/sealos/issues/361#issuecomment-643099328
