### ISSUE TITLE
使用sealos 完成kubernetes集群的升级

### ISSUE THREAD

**Issue by oldthreefeng** [fanux/sealos#373]
**哪个命令或者组件**

 sealos upgrade  v1.18.4
eg.  sealos xxx, sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1. 使用sealos自动完成升级动作。 
2. 中途失败自动回滚至初始状态（dry-run）。 
3.

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
0.   升级kebelet，kubectl ， kubeadm
1.   kubeadm  upgrade  apply  -f --config  kubeadm-config-upgrade.yaml 
2.   
3.

**Comment by fanux** [comment]
此特性在roadmap中
