### ISSUE TITLE
openstack环境，初始化集群失败

### ISSUE THREAD

**Issue by 15770887034** [fanux/sealos#379]
**那个命令或者组件**
eg. sealos init , sealos install , kubernetes cni, docker  and so on 
```
sealos init 
```
**描述你的问题**
详细描述出你的问题内容xxxx.
使用三台虚拟机(使用VM虚拟化后远程连接)，按照步骤初始化集群，到sealos init 失败
**你看到的一些参考资料**
eg. 文档的引用xxxx
下面是错误日志
```
01:40:26 [WARN] [download.go:35] [10.8.76.179:22]SendPackage: file is exist
01:40:26 [INFO] [ssh.go:57] [ssh][10.8.76.179:22] echo 10.8.76.179 apiserver.cluster.local >> /etc/hosts
01:40:26 [INFO] [ssh.go:12] [ssh][10.8.76.179:22] kubeadm init --config=/root/kubeadm-config.yaml --experimental-upload-certs
01:40:26 [DEBG] [ssh.go:24] [ssh][10.8.76.179:22]command result is: bash: kubeadm: command not found

01:40:26 [EROR] [ssh.go:27] [ssh][10.8.76.179:22]Error exec command failed: Process exited with status 127
01:40:26 [EROR] [init.go:130] [10.8.76.179:22]kubernetes install is error.please clean and uninstall.
```
下面是输出的全部日志
[Uploading 全部日志.txt…]()

**Comment by oldthreefeng** [comment]
`kubeadm init --config=/root/kubeadm-config.yaml --experimental-upload-certs`

一般显示这个选项的, 要构建的集群版本是低于 1.15的.  默认不带` --version`  即走这个通道. 
我有一次init也是忘记带了 `--version`  . 

还有就是 `kubeadm: command not found`  有可能是压缩包有问题. 建议下载最新的.

**Comment by 15770887034** [comment]
终于安装成功了！猜测两个原因导致，一个是离线安装包不完整，一个是docker版本过低引起(之前是使用docker1.13.1)，现在是18.3.1

**Comment by fanux** [comment]
离线包不完整可以比对md5, 还有一个可能就是垃圾openstack的磁盘io很差导致。
