### ISSUE TITLE
sealos clean --master之后重新join，kublet启动失败

### ISSUE THREAD

**Issue by Pastel001** [fanux/sealos#380]
**哪个命令或者组件**
sealos clean --master x.x.x.x
sealos join --master x.x.x.x

**描述这个缺陷**
简短描述这个缺陷内容.
1、有一个master节点出现故障，所有的pod都被驱逐了，看了一下可能是因为磁盘满了照成的
/var/docker/lib/containers/中有一个容器的的.log目录沾满了空间。
2、然后我把此文件内容清空后
使用sealos clean --master x.x.x.x删了此master节点
然后sealos join --master x.x.x.x重新加入
3、kubelet启动失败
![图片](https://user-images.githubusercontent.com/10250772/85943062-219a9800-b960-11ea-8d85-15d0ce22eb3f.png)

4、join时输出如下，不知道是否跟etcd状态有关系
![图片](https://user-images.githubusercontent.com/10250772/85943059-1d6e7a80-b960-11ea-9276-591ce8616b56.png)

问题是我不知道是什么原因导致的
还有麻烦问下使用sealos安装集群，etcd是在集群里面创建的容器是吗？
这种情况怎么查看处理etcd的问题，谢谢

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: v3.3.7
- 操作系统:  eg. centos7
- 运行模式:  eg. 阿里云 ( 内存 4gb, cpu 2核 ,存储 40gb )
- 集群规模:   eg 3master 3node
- 附加说明: istio,dashboard ...

**Comment by zhangguanzhang** [comment]
看看etcd container的的log

**Comment by Pastel001** [comment]
![图片](https://user-images.githubusercontent.com/10250772/85943591-97543300-b963-11ea-9391-f5dff6ab4d83.png)
![图片](https://user-images.githubusercontent.com/10250772/85943594-a20ec800-b963-11ea-911d-684e7e3ab5fb.png)

**Comment by Pastel001** [comment]
192.168.7.3这个就是有问题的master，现在确实启动不了kubelet

**Comment by zhangguanzhang** [comment]
头一次看见etcd这种报错

**Comment by Pastel001** [comment]
clean master之后etcd没有被移除，使用etcdctl remove掉clean的master节点后，重新join，成功
