### ISSUE TITLE
sealos init之后重,无法找到kubeadm: command result is: bash: kubeadm: command not found

### ISSUE THREAD

**Issue by banna2019** [fanux/sealos#381]
服务器腾讯云:
系统: CentOS Linux release 7.6.1810 (Core)
内核版本: 4.4.228-2.el7.elrepo.x86_64
sealos版本: v3.3.7(github release分支拉取)
kubenetes版本: v1.16.10

**Comment by cuisongliu** [comment]
用latest的sealos
