### ISSUE TITLE
当pod重建后，pod的ip地址发生变化，而ipvs规则没有变化

### ISSUE THREAD

**Issue by hnr1017** [fanux/sealos#384]
删除pod，pod重新创建，前后pod的ip地址发生变化，而此时ipvs规则没有变化，导致无法访问pod
版本：latest

**Comment by hnr1017** [comment]
版本：latest

**Comment by oldthreefeng** [comment]
@hnr1017 kubernetes的版本号呢, 如果是 v1.18以上的, 系统内核不能是3.10的. 
建议升级内核或者低版本k8s即可.

**Comment by hnr1017** [comment]
目前latest版本，k8s是v1.18.0版本的

**Comment by oldthreefeng** [comment]
#361 参考这个
