### ISSUE TITLE
问题: 初始化master + node1，输出 “error execution phase preflight: couldn't validate the identity of the API Server”

### ISSUE THREAD

**Issue by CoolLinuxMan** [fanux/sealos#390]
**那个命令或者组件**

初始化命令如下：
```
[root@master ~]# sealos init --passwd w*** \
    --master 192.168.159.10 \
    --node 192.168.159.20 \
    --pkg-url /root/kube1.18.0.tar.gz  --version v1.18.0
```

输出结果：
```
01:10:26 [DEBG] [print.go:20] ==>SendPackage==>KubeadmConfigInstall==>InstallMaster0
01:10:26 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] echo 10.103.97.2 apiserver.cluster.local >> /etc/hosts
01:10:26 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] sealos ipvs --vs 10.103.97.2:6443  --rs 192.168.159.10:6443 --health-path /healthz --health-schem https --run-once
01:10:26 [INFO] [ssh.go:50] [192.168.159.20:22] 01:10:26 [WARN] [service.go:119] IsVirtualServerAvailable warn: virtual server is empty.
01:10:26 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] kubeadm join 10.103.97.2:6443 --token pu8u1o.0zqw1ojus80v9n4w --discovery-token-ca-cert-hash sha256:0cf9a82fd2c92915e27b71ea360af2633d1b7c498213f98b9134a9493ff0c0fb -v 0
01:10:27 [INFO] [ssh.go:50] [192.168.159.20:22] W0705 01:10:27.018169    2615 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
01:10:27 [INFO] [ssh.go:50] [192.168.159.20:22] 	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
01:10:27 [INFO] [ssh.go:50] [192.168.159.20:22] 	[WARNING FileExisting-socat]: socat not found in system path
01:15:27 [INFO] [ssh.go:50] [192.168.159.20:22] error execution phase preflight: couldn't validate the identity of the API Server: Get https://10.103.97.2:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
01:15:27 [INFO] [ssh.go:12] [ssh][192.168.159.20:22] mkdir -p /etc/kubernetes/manifests
01:15:27 [DEBG] [ssh.go:24] [ssh][192.168.159.20:22]command result is: 
01:15:27 [ALRT] [scp.go:156] [ssh][192.168.159.20:22]transfer total size is: 0MB
01:15:27 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] rm -rf /root/kube
01:15:28 [DEBG] [print.go:20] ==>SendPackage==>KubeadmConfigInstall==>InstallMaster0==>JoinMasters==>JoinNodes
01:15:28 [INFO] [print.go:25] sealos install success.

      ___           ___           ___           ___       ___           ___     
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \    
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \   
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \  
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \ 
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\  
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /  
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /   
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/  

                  官方文档：sealyun.com
                  项目地址：github.com/fanux/sealos
                  QQ群   ：98488045
                  常见问题：sealyun.com/faq

```

**描述你的问题**

背景：virtualbox +3台虚机 （node1 和 node2是由 master复制而来，所以就只改了 hostonly的ip地址，未修改nat的地址）
Centos7虚机（master，hostonly ：192.168.159.10，nat：10.0.3.15）
Centos7虚机（node1， hostonly：192.168.159.20， nat：10.0.3.15）
Centos7虚机（node2， hostonly：192.168.159.30， nat：10.0.3.15）

3台虚机直接可以互ping，且可以互相免密登陆； 3台虚机可以ping通外网；

**你看到的一些参考资料**

附件是完整的操作log 和 输出结果：
[install_k8s.txt](https://github.com/fanux/sealos/files/4874985/install_k8s.txt)

**Comment by CoolLinuxMan** [comment]
hi, 上述问题中的背景情况：

1，网络模式修改完后 为如下的情况；
Centos7虚机（master，hostonly ：192.168.159.10，nat：10.0.2.4）
Centos7虚机（node1， hostonly：192.168.159.20， nat：10.0.2.5）
Centos7虚机（node2， hostonly：192.168.159.30， nat：10.0.2.6）

2，三台虚机互相可以ping，也可以ping到外网； 已经做完NTP时间同步；

3，在master上执行sealos  clean --all 之后重新尝试初始化，仍然与之前报错相同；
00:02:07 [DEBG] [print.go:20] ==>SendPackage==>KubeadmConfigInstall==>InstallMaster0
00:02:07 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] echo 10.103.97.2 apiserver.cluster.local >> /etc/hosts
00:02:07 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] sealos ipvs --vs 10.103.97.2:6443  --rs 192.168.159.10:6443 --health-path /healthz --health-schem https --run-once
00:02:07 [INFO] [ssh.go:50] [192.168.159.20:22] 00:02:07 [WARN] [service.go:119] IsVirtualServerAvailable warn: virtual server is empty.
00:02:07 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] kubeadm join 10.103.97.2:6443 --token aw3bpt.0o5xtc546oasm8f5 --discovery-token-ca-cert-hash sha256:a63842da47069c3e45bb96035b07b8a6ef582e40b59cd1cadb0b745a0eedcd9a -v 0
00:02:08 [INFO] [ssh.go:50] [192.168.159.20:22] W0706 00:02:08.117836   15714 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
00:02:08 [INFO] [ssh.go:50] [192.168.159.20:22] 	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/doc
00:07:08 [INFO] [ssh.go:50] [192.168.159.20:22] error execution phase preflight: couldn't validate the identity of the API Server: Get https://10.103.97.2:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s:ne exceeded (Client.Timeout exceeded while awaiting headers)
00:07:08 [INFO] [ssh.go:12] [ssh][192.168.159.20:22] mkdir -p /etc/kubernetes/manifests
00:07:08 [DEBG] [ssh.go:24] [ssh][192.168.159.20:22]command result is: 
00:07:08 [ALRT] [scp.go:156] [ssh][192.168.159.20:22]transfer total size is: 0MB
00:07:08 [INFO] [ssh.go:57] [ssh][192.168.159.20:22] rm -rf /root/kube
00:07:09 [DEBG] [print.go:20] ==>SendPackage==>KubeadmConfigInstall==>InstallMaster0==>JoinMasters==>JoinNodes
00:07:09 [INFO] [print.go:25] sealos install success.


于是到node1上执行命令：
[root@slave1 ~]# kubeadm join 10.103.97.2:6443 --token aw3bpt.0o5xtc546oasm8f5 --discovery-token-ca-cert-hash sha256:a63842da47069c3e45bb96035b07b8a6ef582e40b59cd1cadb0b745a0eedcd9a -v 0
W0706 00:45:38.225994   19902 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING FileExisting-socat]: socat not found in system path
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR FileAvailable--etc-kubernetes-pki-ca.crt]: /etc/kubernetes/pki/ca.crt already exists
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
[root@slave1 ~]# 
[root@slave1 ~]# 
[root@slave1 ~]# kubeadm join 10.103.97.2:6443 --token aw3bpt.0o5xtc546oasm8f5 --discovery-token-ca-cert-hash sha256:a63842da47069c3e45bb96035b07b8a6ef582e40b59cd1cadb0b745a0eedcd9a --v=5
W0706 00:45:44.792210   19959 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
I0706 00:45:44.792256   19959 join.go:371] [preflight] found NodeName empty; using OS hostname as NodeName
I0706 00:45:44.792279   19959 initconfiguration.go:103] detected and using CRI socket: /var/run/dockershim.sock
[preflight] Running pre-flight checks
I0706 00:45:44.792316   19959 preflight.go:90] [preflight] Running general checks
I0706 00:45:44.792342   19959 checks.go:249] validating the existence and emptiness of directory /etc/kubernetes/manifests
I0706 00:45:44.792364   19959 checks.go:286] validating the existence of file /etc/kubernetes/kubelet.conf
I0706 00:45:44.792368   19959 checks.go:286] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0706 00:45:44.792375   19959 checks.go:102] validating the container runtime
I0706 00:45:44.814980   19959 checks.go:128] validating if the service is enabled and active
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
I0706 00:45:44.867683   19959 checks.go:335] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0706 00:45:44.867712   19959 checks.go:335] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0706 00:45:44.867728   19959 checks.go:649] validating whether swap is enabled or not
I0706 00:45:44.867750   19959 checks.go:376] validating the presence of executable conntrack
I0706 00:45:44.867767   19959 checks.go:376] validating the presence of executable ip
I0706 00:45:44.867778   19959 checks.go:376] validating the presence of executable iptables
I0706 00:45:44.867790   19959 checks.go:376] validating the presence of executable mount
I0706 00:45:44.868069   19959 checks.go:376] validating the presence of executable nsenter
I0706 00:45:44.868075   19959 checks.go:376] validating the presence of executable ebtables
I0706 00:45:44.868082   19959 checks.go:376] validating the presence of executable ethtool
I0706 00:45:44.868090   19959 checks.go:376] validating the presence of executable socat
	[WARNING FileExisting-socat]: socat not found in system path
I0706 00:45:44.868107   19959 checks.go:376] validating the presence of executable tc
I0706 00:45:44.868117   19959 checks.go:376] validating the presence of executable touch
I0706 00:45:44.868125   19959 checks.go:520] running all checks
I0706 00:45:44.916101   19959 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I0706 00:45:44.916211   19959 checks.go:618] validating kubelet version
I0706 00:45:44.960149   19959 checks.go:128] validating if the service is enabled and active
I0706 00:45:44.968334   19959 checks.go:201] validating availability of port 10250
I0706 00:45:44.968484   19959 checks.go:286] validating the existence of file /etc/kubernetes/pki/ca.crt
I0706 00:45:44.968508   19959 checks.go:432] validating if the connectivity type is via proxy or direct
[preflight] Some fatal errors occurred:
	[ERROR FileAvailable--etc-kubernetes-pki-ca.crt]: /etc/kubernetes/pki/ca.crt already exists
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:170
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
[root@slave1 ~]#

**Comment by zhangguanzhang** [comment]
sealos版本粘贴下
```
sealos version
```

**Comment by fanux** [comment]
/etc/kubernetes/pki/ca.crt already exists  删之
