### ISSUE TITLE
[WARNING FileExisting-socat]: socat not found in system path

### ISSUE THREAD

**Issue by guoh1988** [fanux/sealos#397]
**哪个命令或者组件**
sealos init --passwd qwe123 --master 192.168.109.131 --node 192.168.109.132 --pkg-url /mnt/kube1.16.0.tar.gz --version v1.16.0 

**描述这个缺陷**
简短描述这个缺陷内容.

[WARNING FileExisting-socat]: socat not found in system path

离线包中没有socat会影响pod通信，比如helm
E0522 22:22:15.492436   24409 portforward.go:331] an error occurred forwarding 38398 -> 44134: error forwarding port 44134 to pod dc6da4ab99ad9c497c0cef1776b9dd18e0a612d507e2746ed63d36ef40f30174, uid : unable to do port forwarding: socat not found.
Error: cannot connect to Tiller
**重现步骤（如果有需要可以附加图片）**
1. 
...

**测试结果**
1. 
2. 
3.

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   eg 3master 3node
- 附加说明: istio,dashboard ...

**Comment by zhangguanzhang** [comment]
这个`socat`是kubectl proxy用的，是在kubeadm的前置检查条件里。先和后安装都没问题
