### ISSUE TITLE
keepalived track_script not working

### ISSUE THREAD

**Issue by mxfj** [fanux/sealos#4]
`Sep  6 11:34:23 k8s-master02 kubelet: I0906 11:34:23.878890   14793 kuberuntime_manager.go:513] Container {Name:keepalived Image:fanux/keepalived:1.3.5 Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:haproxy-conf ReadOnly:false MountPath:/etc/keepalived SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Sep  6 11:34:23 k8s-master02 dockerd: time="2018-09-06T11:34:23.879331349+08:00" level=error msg="Handler for GET /v1.27/images/fanux/keepalived:1.3.5/json returned error: No such image: fanux/keepalived:1.3.5"
Sep  6 11:34:23 k8s-master02 kubelet: E0906 11:34:23.879521   14793 pod_workers.go:186] Error syncing pod 0174fc0a7364aec228b1552de90cb121 ("keepalived-k8s-master02_kube-system(0174fc0a7364aec228b1552de90cb121)"), skipping: failed to "StartContainer" for "keepalived" with ImagePullBackOff: "Back-off pulling image \"fanux/keepalived:1.3.5\""
Sep  6 11:34:29 k8s-master02 dhclient[18176]: DHCPDISCOVER on em2 to 255.255.255.255 port 67 interval 15 (xid=0x11149a73)`

no images fanux/keepalived:1.3.5

**Comment by fanux** [comment]
using Dockerfile build one
