### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by iamzxj** [fanux/sealos#405]
**哪个命令或者组件**
sealos init --user root --passwd jackzhou \
	--master 192.168.73.121  --master 192.168.73.122  \
	--node 192.168.73.123  --node 192.168.73.124 \
	--pkg-url /root/kube1.18.0.tar.gz \
	--version v1.18.0

**描述这个缺陷**
简短描述这个缺陷内容.

03:27:49 [EROR] [ssh.go:27] [ssh][192.168.73.121:22]Error exec command failed: Process exited with status 127
03:27:49 [EROR] [init.go:130] [192.168.73.121:22]kubernetes install is error.please clean and uninstall.

**运行环境**
- sealos版本: sealos version latest, build 6ad67eb go1.13.5
- 操作系统:  eg. centos8

**Comment by oldthreefeng** [comment]
错误日志有点少. 看不到是那一步错的.

**Comment by iamzxj** [comment]
05:27:31 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:31 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:31 [DEBG] [ssh.go:24] [ssh][192.168.73.122:22]command result is: 1

05:27:31 [WARN] [download.go:35] [192.168.73.122:22]SendPackage: file is exist
05:27:31 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:31 [INFO] [ssh.go:57] [ssh][192.168.73.122:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:32 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:32 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/etcd/ca.crt 2>/dev/null |wc -l
05:27:32 [DEBG] [download.go:29] [192.168.73.122:22]please wait for mkDstDir
05:27:32 [INFO] [ssh.go:12] [ssh][192.168.73.122:22] ls -l /etc/kubernetes/pki/etcd/ca.crt 2>/dev/null |wc -l
05:27:32 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:32 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:32 [DEBG] [ssh.go:24] [ssh][192.168.73.122:22]command result is: 1

05:27:32 [WARN] [download.go:35] [192.168.73.122:22]SendPackage: file is exist
05:27:32 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:32 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:32 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/apiserver.key 2>/dev/null |wc -l
05:27:33 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:33 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:33 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:33 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:33 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/apiserver.crt 2>/dev/null |wc -l
05:27:34 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:34 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:34 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:34 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:34 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/apiserver-kubelet-client.key 2>/dev/null |wc -l
05:27:35 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:35 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:35 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:35 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:35 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/apiserver-kubelet-client.crt 2>/dev/null |wc -l
05:27:35 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:35 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:35 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:36 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:36 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/front-proxy-client.key 2>/dev/null |wc -l
05:27:36 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:36 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:36 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:37 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:37 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/front-proxy-client.crt 2>/dev/null |wc -l
05:27:37 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:37 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:37 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:38 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:38 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/apiserver-etcd-client.key 2>/dev/null |wc -l
05:27:38 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:38 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:38 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki || true
05:27:39 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:39 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/apiserver-etcd-client.crt 2>/dev/null |wc -l
05:27:39 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:39 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:39 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:39 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:39 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/etcd/server.key 2>/dev/null |wc -l
05:27:40 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:40 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:40 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:40 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:40 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/etcd/server.crt 2>/dev/null |wc -l
05:27:41 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:41 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:41 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:41 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:41 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/etcd/peer.key 2>/dev/null |wc -l
05:27:42 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:42 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:42 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:42 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:42 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/etcd/peer.crt 2>/dev/null |wc -l
05:27:42 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:42 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:42 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:43 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:43 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/etcd/healthcheck-client.key 2>/dev/null |wc -l
05:27:43 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:43 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:43 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes/pki/etcd || true
05:27:44 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:44 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/pki/etcd/healthcheck-client.crt 2>/dev/null |wc -l
05:27:44 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:44 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:44 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] hostname
05:27:45 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: node1

[kubeconfig] Using existing kubeconfig file: "/root/.sealos/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/root/.sealos/controller-manager.conf"
[kubeconfig] Using existing kubeconfig file: "/root/.sealos/scheduler.conf"
[kubeconfig] Using existing kubeconfig file: "/root/.sealos/kubelet.conf"
05:27:47 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes || true
05:27:47 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:47 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/kubelet.conf 2>/dev/null |wc -l
05:27:48 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:48 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:48 [INFO] [ssh.go:57] [ssh][192.168.73.122:22] mkdir -p /etc/kubernetes || true
05:27:48 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes || true
05:27:48 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:48 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/admin.conf 2>/dev/null |wc -l
05:27:48 [DEBG] [download.go:29] [192.168.73.122:22]please wait for mkDstDir
05:27:48 [INFO] [ssh.go:12] [ssh][192.168.73.122:22] ls -l /etc/kubernetes/admin.conf 2>/dev/null |wc -l
05:27:48 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:48 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:49 [DEBG] [ssh.go:24] [ssh][192.168.73.122:22]command result is: 1

05:27:49 [WARN] [download.go:35] [192.168.73.122:22]SendPackage: file is exist
05:27:49 [INFO] [ssh.go:57] [ssh][192.168.73.122:22] mkdir -p /etc/kubernetes || true
05:27:49 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes || true
05:27:49 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:49 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/controller-manager.conf 2>/dev/null |wc -l
05:27:49 [DEBG] [download.go:29] [192.168.73.122:22]please wait for mkDstDir
05:27:49 [INFO] [ssh.go:12] [ssh][192.168.73.122:22] ls -l /etc/kubernetes/controller-manager.conf 2>/dev/null |wc -l
05:27:49 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:49 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:49 [DEBG] [ssh.go:24] [ssh][192.168.73.122:22]command result is: 1

05:27:49 [WARN] [download.go:35] [192.168.73.122:22]SendPackage: file is exist
05:27:49 [INFO] [ssh.go:57] [ssh][192.168.73.122:22] mkdir -p /etc/kubernetes || true
05:27:49 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] mkdir -p /etc/kubernetes || true
05:27:50 [DEBG] [download.go:29] [192.168.73.121:22]please wait for mkDstDir
05:27:50 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] ls -l /etc/kubernetes/scheduler.conf 2>/dev/null |wc -l
05:27:50 [DEBG] [download.go:29] [192.168.73.122:22]please wait for mkDstDir
05:27:50 [INFO] [ssh.go:12] [ssh][192.168.73.122:22] ls -l /etc/kubernetes/scheduler.conf 2>/dev/null |wc -l
05:27:50 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: 1

05:27:50 [WARN] [download.go:35] [192.168.73.121:22]SendPackage: file is exist
05:27:50 [DEBG] [ssh.go:24] [ssh][192.168.73.122:22]command result is: 1

05:27:50 [WARN] [download.go:35] [192.168.73.122:22]SendPackage: file is exist
05:27:50 [INFO] [ssh.go:57] [ssh][192.168.73.121:22] echo 192.168.73.121 apiserver.cluster.local >> /etc/hosts
05:27:51 [INFO] [ssh.go:12] [ssh][192.168.73.121:22] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
05:27:51 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: bash: kubeadm: command not found

05:27:51 [EROR] [ssh.go:27] [ssh][192.168.73.121:22]Error exec command failed: Process exited with status 127
05:27:51 [EROR] [init.go:130] [192.168.73.121:22]kubernetes install is error.please clean and uninstall.

**Comment by iamzxj** [comment]
第一次部署失败后，后面清理【sealos clean --all -f】再怎么部署都是报这个错误信息

**Comment by fanux** [comment]
: bash: kubeadm: command not found  tar包解压有问题，重新拷贝包试试，自己把离线包拷贝到目标机器/root

**Comment by iamzxj** [comment]
kube1.18.0.tar.gz 这个包分发到所有机器上去？

**Comment by iamzxj** [comment]
分发下去，还是存在这个问题

05:54:41 [DEBG] [ssh.go:24] [ssh][192.168.73.121:22]command result is: bash: kubeadm: command not found

05:54:41 [EROR] [ssh.go:27] [ssh][192.168.73.121:22]Error exec command failed: Process exited with status 127
05:54:41 [EROR] [init.go:130] [192.168.73.121:22]kubernetes install is error.please clean and uninstall.

**Comment by iamzxj** [comment]
是不是Centos8不支持？

**Comment by oldthreefeng** [comment]
亲测centos8 可用.  你看看你的压缩包是不是已经损坏了, MD5

**Comment by iamzxj** [comment]
我刚重新下载了个压缩包，报错变化了

[init] Using Kubernetes version: v1.18.0
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING FileExisting-socat]: socat not found in system path
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 4.18.0-147.el8.x86_64
CONFIG_NAMESPACES: enabled
CONFIG_NET_NS: enabled
CONFIG_PID_NS: enabled
CONFIG_IPC_NS: enabled
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled (as module)
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_AUFS_FS: not set - Required for aufs.
CONFIG_BLK_DEV_DM: enabled (as module)
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[ERROR CRI]: container runtime is not running: output: Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
, error: exit status 1
	[ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
	[ERROR IsDockerSystemdCheck]: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2
	[ERROR SystemVerification]: error verifying Docker info: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

06:03:41 [EROR] [ssh.go:27] [ssh][192.168.73.121:22]Error exec command failed: Process exited with status 1
06:03:41 [EROR] [init.go:130] [192.168.73.121:22]kubernetes install is error.please clean and uninstall.

**Comment by iamzxj** [comment]
docker 需要先安装好么？

**Comment by zhangguanzhang** [comment]
你没清理，清理了后再试试

**Comment by oldthreefeng** [comment]
不需要的.  你先clean --all. 然后再init.  

这种错误大概率是tar包损坏了.

**Comment by iamzxj** [comment]
sealos clean --all -f 执行后，重新执行init还是出现同上的错误

**Comment by iamzxj** [comment]
![2020-07-22_181433](https://user-images.githubusercontent.com/11895528/88164879-5cce7500-cc47-11ea-89b0-c7d04216eb99.png)

**Comment by iamzxj** [comment]
![2020-07-22_181433](https://user-images.githubusercontent.com/11895528/88164905-6821a080-cc47-11ea-8a14-89535ed3a2a8.png)

**Comment by iamzxj** [comment]
![2020-07-22_181433](https://user-images.githubusercontent.com/11895528/88164943-77a0e980-cc47-11ea-868a-2ac03c376aa3.png)

**Comment by zhangguanzhang** [comment]
docker你提前自己安装的吗

**Comment by iamzxj** [comment]
提前安装的都卸载了，还是端口被占用，不会要重启服务器吧。
[init] Using Kubernetes version: v1.18.0
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING FileExisting-socat]: socat not found in system path
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-6443]: Port 6443 is in use
	[ERROR Port-10259]: Port 10259 is in use
	[ERROR Port-10257]: Port 10257 is in use
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[ERROR Port-10250]: Port 10250 is in use
	[ERROR Port-2379]: Port 2379 is in use
	[ERROR Port-2380]: Port 2380 is in use
	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

07:22:50 [EROR] [ssh.go:27] [ssh][192.168.73.121:22]Error exec command failed: Process exited with status 1
07:22:50 [EROR] [init.go:130] [192.168.73.121:22]kubernetes install is error.please clean and uninstall.

**Comment by oldthreefeng** [comment]
这个是`kubernetes`集群没清理干净. 
`sealos clean --all`

**Comment by iamzxj** [comment]
清理，每次都是提示下面信息
[root@node1 ~]# sealos clean --all
Please enter the password to connect to the node:
clean command will clean all masters and nodes, continue clean (y/n)?y
08:16:02 [WARN] [clean.go:69] clean nodes and masters is empty,please check your args and config.yaml.

**Comment by zhangguanzhang** [comment]
手动编辑下`~/.sealos/config.yml`文件写入下node和master的ip，然后clean下再试

**Comment by oldthreefeng** [comment]
sealos clean 
--master 192.168.73.121 --master 192.168.73.122
--node 192.168.73.123 --node 192.168.73.124

**Comment by iamzxj** [comment]
指定ip清理确实起作用了，但是重新init还是报下面的错
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR CRI]: container runtime is not running: output: Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
, error: exit status 1
	[ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
	[ERROR IsDockerSystemdCheck]: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2
	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
	[ERROR SystemVerification]: error verifying Docker info: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

22:30:53 [EROR] [ssh.go:27] [ssh][192.168.73.121:22]Error exec command failed: Process exited with status 1
22:30:53 [EROR] [init.go:130] [192.168.73.121:22]kubernetes install is error.please clean and uninstall.

**Comment by iamzxj** [comment]
切换环境到Centos7.8，就init没问题。估计是那几台机器的操作系统(Centos8)环境有干扰。

10:35:58 [INFO] [print.go:25] sealos install success.

      ___           ___           ___           ___       ___           ___     
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \    
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \   
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \  
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \ 
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\  
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /  
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /   
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/  

                  官方文档：sealyun.com
                  项目地址：github.com/fanux/sealos
                  QQ群   ：98488045
                  常见问题：sealyun.com/faq

**Comment by zhangguanzhang** [comment]
docker没起来造成的，你清理后看看docker还在不在还是否有文件没清理干净

**Comment by iamzxj** [comment]
清理dockers的系统缓存文件，错误还在。还有个问题比较尴尬，在新的环境上成功了init操作，但是get node 竟然没有node结点信息？sealos clean -node 在join操作，node结点就出来了。

**Comment by iamzxj** [comment]
![2020-07-23_111438](https://user-images.githubusercontent.com/11895528/88249041-c2694280-ccd5-11ea-8775-6153695619dc.png)

**Comment by oldthreefeng** [comment]
centos8 安装的确是没有问题的. 我昨天在`CentOS-8.1.1911`部署了的, 还是那么丝滑 ~ 
可能是你node节点旧的环境导致的.  
你手动去node节点 启动docker试试?

**Comment by hubeixulu** [comment]
我知道是什么问题了，我也是centos8和你一样的问题，原来是centos8最小安装的时候没有tar命令，导致你下载下来的离线包不能解压，我装了tar命令以后就好了

**Comment by oldthreefeng** [comment]
>  [ERROR IsDockerSystemdCheck]: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2

@hubeixulu  这个问题是docker版本太低导致的. 和你的问题还不太一样.  tar命令centos8 minimal没有么? 这边minimal安装好像有的... 看来得加一个提示了.

**Comment by hubeixulu** [comment]
> > [ERROR IsDockerSystemdCheck]: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2
> 
> @hubeixulu 这个问题是docker版本太低导致的. 和你的问题还不太一样. tar命令centos8 minimal没有么? 这边minimal安装好像有的... 看来得加一个提示了.

@oldthreefeng 嗯，我也是找了半天问题，报Process exited with status 127这个错误，kubeadm命令没有，后面网上搜了一下说手动解压离线包试试，结果发现没有tar命令，tar命令装了以后报错就消失了，我的centos8镜像是官网哪个1.6G的镜像，然后安装的时候选择最小安装，以前都没遇到过，居然连tar命令都没有
