### ISSUE TITLE
3.4.10的etcd权限变化

### ISSUE THREAD

**Issue by zhangguanzhang** [fanux/sealos#408]
https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md#breaking-changes
etcd 3.4.10引入了一个不兼容以前的权限，Linux下etcd的数据目录权限必须为0700，我用kubeadm和二进制都测试了会导致etcd无法启动。这个问题需要解决

**Comment by cuisongliu** [comment]
哪个k8s版本出的问题 ？

**Comment by zhangguanzhang** [comment]
和版本无关，是etcd 3.4.10引入这个变动的特性，如果etcd是3.4.10+则要改目录权限

**Comment by fanux** [comment]
k8s主版本还没用到3.4吧
