### ISSUE TITLE
sealos delete命令

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#413]
用于执行config中的DELETE指令
```
LOAD xxx
APPLY 
DELETE # 对应LOAD的反向操作，在每个节点执行
REMOTE # 对应APPLY的反向操作，master节点执行
```
sealos delete --pkg-url mysql.tar

**Comment by oldthreefeng** [comment]
我来写写看. ~~

**Comment by oldthreefeng** [comment]
> 用于执行config中的DELETE指令
> 
> ```
> LOAD xxx
> APPLY 
> DELETE # 对应LOAD的反向操作，在每个节点执行
> REMOTE # 对应APPLY的反向操作，master节点执行
> ```
> 
> sealos delete --pkg-url mysql.tar

应该是REMOVE吧。 另外， 如果用户是自定义安装的话， 是不是应该也要支持这个命令呢～～ 
比如 `sealos install --pkg-url mysql.tar  -w /data/  -f values.yaml  -c confg` 
但是`sealos delete 得支持所有操作吧。。。`
或者 -w -f -c 相关信息都保存到`.sealos/config` 里面， delete直接从配置里面读。

**Comment by cuisongliu** [comment]
@fanux  这个是不是叫Uninstall好一点，叫remove会不会有点混淆？

**Comment by fanux** [comment]
@cuisongliu REMOVE 做了一些清理操作，比如删除之前的安装包
