### ISSUE TITLE
是否支持单点Master和多worker方式安装

### ISSUE THREAD

**Issue by TonyK-T** [fanux/sealos#417]
1、是否支持单点Master和多worker方式安装(比如只有两台机子)
2、高可用至少三台Master，对机子硬件有啥要求？ 比如 内存至少多少？
3、相关使用文档还是太少了，大佬们抽空整理下文档呗

**Comment by jun87lam** [comment]
自己实践呀， 我现在搭建的就是一master，多worker（一个master，一个worker）

**Comment by TonyK-T** [comment]
> 自己实践呀， 我现在搭建的就是一master，多worker（一个master，一个worker）

你是在 一台机子上同时部署 master和worker？或者说 master上也部署了一个worker吗？
