### ISSUE TITLE
sealos init 报错

### ISSUE THREAD

**Issue by TonyK-T** [fanux/sealos#418]
**哪个命令或者组件**
https://sealyun.oss-cn-beijing.aliyuncs.com/latest/sealos
sealos init 
kube1.18.0.tar.gz

**描述这个缺陷**
问题1-单机版 Master和worker安装在同一个机子上,报错 duplicate hostnames is not allowed(同一台机子检验了两遍hostname)

问题2-centos7Master200.200.200.9 + Ubuntu worker 16.04.2 LTS sealos init  报错如下：
18:30:27 [DEBG] [ssh.go:24] [ssh][200.200.200.9:22]command result is: W0731 18:30:27.153139   32205 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0731 18:30:27.155151   32205 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.0
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**重现步骤（如果有需要可以附加图片）**
问题1重现：sealos init --master 200.200.200.9 --node 200.200.200.9 --user root --passwd xxx --version v1.18.0 --pkg-url /home/kube1.18.0.tar.gz

问题2重现：sealos init --master 200.200.200.9 --node 200.200.200.10 --user root --passwd xxx --version v1.18.0 --pkg-url /home/kube1.18.0.tar.gz
...

- Docker版本:   Docker version 19.03.12, build 48a66213fe
- Kubernetes版本 : kube1.18.0.tar.gz
- sealos版本: latest
- 操作系统:  200.9 是centos7   200.10是Ubuntu 16.04.2 LTS
- 运行模式:  两台本地物理机 （内存 8g, ）
- 集群规模:   1master 1node

**Comment by tangyibo** [comment]
我也遇到了同样问题

**Comment by oldthreefeng** [comment]
> 我也遇到了同样问题

如果是 `/var/lib/etcd is not empty` , 先执行`sealos clean --all -f` 清理所有的集群. @tangyibo  另外, 如果错误不一样, 可以另外开issue.

**Comment by CoderWeiLee** [comment]
同样报错。执行了
```objc
# 下载并安装sealos, sealos是个golang的二进制工具，直接下载拷贝到bin目录即可, release页面也可下载
$ wget -c https://sealyun.oss-cn-beijing.aliyuncs.com/latest/sealos && \
    chmod +x sealos && mv sealos /usr/bin

# 下载离线资源包
$ wget -c https://sealyun.oss-cn-beijing.aliyuncs.com/05a3db657821277f5f3b92d834bbaf98-v1.22.0/kube1.22.0.tar.gz

# 安装一个三master的kubernetes集群
$ sealos init --passwd '123456' \
    --master 192.168.0.2  --master 192.168.0.3  --master 192.168.0.4  \
    --node 192.168.0.5 \
    --pkg-url /root/kube1.22.0.tar.gz \
    --version v1.22.0
```
将服务器地址和密码替换成自己的，执行完就报错。。。   三台master  一台node。请问下问题出在哪里呢

**Comment by CoderWeiLee** [comment]
> 我也遇到了同样问题

请问怎么解决的呀

**Comment by fanux** [comment]
sealos init --master 200.200.200.9 --node 200.200.200.9  master和node不能是相同IP, 如果装单机就不需要--node参数，master本质已经是node了

**Comment by fanux** [comment]
主机名不可重复

**Comment by CoderWeiLee** [comment]
> 主机名不可重复

嗯嗯谢谢 就是主机名重复的问题  hostnamectl status  查看主机名和系统配置  用这个看到了
