### ISSUE TITLE
安装prometheus报no matches for kind "ServiceMonitor" in version "monitoring

### ISSUE THREAD

**Issue by TonyK-T** [fanux/sealos#420]
**那个命令或者组件**
sealos install --pkg-url https://github.com/sealstore/prometheus/releases/download/v0.31.1/prometheus.tar

**描述你的问题**
安装prometheus报错如下：
cd /root/prometheus && kubectl apply -f manifests
unable to recognize "manifests/0prometheus-operator-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Comment by ysicing** [comment]
在执行  `cd /root/prometheus && kubectl apply -f manifests`

**Comment by TonyK-T** [comment]
> cd /root/prometheus && kubectl apply -f manifests
还是不行，我的是 v1.18.0版本
unable to recognize "manifests/0prometheus-operator-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/alertmanager-alertmanager.yaml": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/alertmanager-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/grafana-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/kube-state-metrics-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/node-exporter-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-prometheus.yaml": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-rules.yaml": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-serviceMonitorApiserver.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-serviceMonitorCoreDNS.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-serviceMonitorKubeControllerManager.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-serviceMonitorKubeScheduler.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
unable to recognize "manifests/prometheus-serviceMonitorKubelet.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Comment by TonyK-T** [comment]
cd /root/prometheus && kubectl apply -f manifests  改成了 cd /root/prometheus && kubectl create -f manifests
运行成功。。。。

**Comment by ysicing** [comment]
通常是crd资源创建完成，api还不可用。 `kgp -n monitoring` 看看

**Comment by zhangguanzhang** [comment]
看看Prometheus-operator ready了没，一般crd是让用户手动通过yaml创建的，Prometheus-operator没记错的话是controller调用接口创建crd的

**Comment by oldthreefeng** [comment]
官网上解释是 先创建 crd.  再创建operator.  
```
$ kubectl create -f manifests/setup
$ until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
$ kubectl create -f manifests/
```

**Comment by TonyK-T** [comment]
> 看看Prometheus-operator ready了没，一般crd是让用户手动通过yaml创建的，Prometheus-operator没记错的话是controller调用接口创建crd的

是正常的
NAMESPACE        NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
heptio-contour   contour                   2/2     2            2           5h24m
kube-system      calico-kube-controllers   1/1     1            1           6h19m
kube-system      coredns                   2/2     2            2           6h19m
kube-system      kuboard                   1/1     1            1           5h58m
kube-system      metrics-server            1/1     1            1           90m
monitoring       grafana                   1/1     1            1           67m
monitoring       kube-state-metrics        1/1     1            1           67m
monitoring       prometheus-adapter        1/1     1            1           67m
monitoring       prometheus-operator       1/1     1            1           67m

**Comment by TonyK-T** [comment]
> kubectl create -f manifests/

直接 kubectl create -f manifests/  貌似也可以，成功了
