### ISSUE TITLE
添加修改安装路径的功能

### ISSUE THREAD

**Issue by TonyK-T** [fanux/sealos#421]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1. sealos init  默认是安装在 /root/路径，希望添加修改安装路径参数化，比如 sealos init --path
2.
3.

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
1. 很多机子默认 /root/ 都不会给的很大，/root/目录很容易就 100% 了但是其他都安装不了
2.
3.

**Comment by oldthreefeng** [comment]
可以把安装包放在 比如`/tmp/kube1.18.0.tar.gz`.  
再使用  `--pkg-url /tmp/kube1.18.0.tar.gz` . 进行安装
默认的家目录`$HOME/.sealos`很小的.

**Comment by TonyK-T** [comment]
> 可以把安装包放在 比如`/tmp/kube1.18.0.tar.gz`.
> 再使用 `--pkg-url /tmp/kube1.18.0.tar.gz` . 进行安装
> 默认的家目录`$HOME/.sealos`很小的.
我所有的压缩包都是放在 /home/xxx目录下安装的，安装完成之后我发现，
所有的压缩包都会拷贝到 /root/目录下，并且解压后的目录文件(不清楚是解压文件还是安装文件) kube  contour(Ingress) kuboard prometheus 也都在 /root/ 目录下

**Comment by fanux** [comment]
此功能最新版本已支持  使用sealos install -w参数指定workdir https://github.com/fanux/sealos/releases/tag/v3.3.9-alpha.0
