### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhuchance** [fanux/sealos#422]
**那个命令或者组件**
sealos install 

**描述你的问题**
02:50:06 [EROR] [ssh.go:27] [ssh][172.xx.xx.xx:22]Error exec command failed: Process exited with status 127
02:50:06 [EROR] [init.go:130] [172.xx.xx.xx:22]kubernetes install is error.please clean and uninstall.

**你看到的一些参考资料**
https://github.com/fanux/sealos/blob/develop/README_zh.md

**Comment by cuisongliu** [comment]
错误贴全一些

**Comment by oldthreefeng** [comment]
是 `[ERROR NumCPU]: the number of available CPUs 1 is less than the required 2` . 这个错误.  ~~

**Comment by cuisongliu** [comment]
cpu 核数不能低于2个
