### ISSUE TITLE
sealos 在aarch64的架构的机器上无法执行

### ISSUE THREAD

**Issue by oreuuz** [fanux/sealos#424]
sealos init

在一台CentOS Linux release 7.6.1810 aarch64架构的机器上执行 sealos init，提示 -bash: /usr/bin/sealos: cannot execute binary file 错误

看到一些资料说可能是ARM架构导致的

**Comment by zhangguanzhang** [comment]
没交叉编译aarch64

**Comment by cuisongliu** [comment]
暂时还不支持arm 架构
