### ISSUE TITLE
pod无法连接外网

### ISSUE THREAD

**Issue by EverCurse** [fanux/sealos#425]
按照教程创建的1.18.0集群 1主3从(master也是从)

**那个命令或者组件**
curl

**描述你的问题**
dns内网解析没有问题 外网无法解析

![image](https://user-images.githubusercontent.com/12572050/89619546-b3cb7f80-d8c0-11ea-8d31-81e94046ecb7.png)

version: sealos version latest, build 6ad67eb go1.13.5

**Comment by zhangguanzhang** [comment]
去看看coredns所在node上的/etc/resolv.conf文件

**Comment by EverCurse** [comment]
> 去看看coredns所在node上的/etc/resolv.conf文件

nameserver 100.100.2.136
nameserver 100.100.2.138 @zhangguanzhang

**Comment by EverCurse** [comment]
node网络是正常的

**Comment by zhangguanzhang** [comment]
你在群里艾特下我

**Comment by zhangguanzhang** [comment]
coredns所在node上的/etc/resolv.conf文件里option影响，更改coredns的cm使用指定上游而非文件
