### ISSUE TITLE
问题: 10252和10251两个端口不能进行连接，导致监控出问题

### ISSUE THREAD

**Issue by liutao841204** [fanux/sealos#426]
**哪个命令或者组件**
sealos init

**描述这个缺陷**
在使用 kubectl get cs命令是，出现如下结果：
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused   
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused   
etcd-0               Healthy     {"health":"true"} 

**重现步骤（如果有需要可以附加图片）**
系统是centos7.6 x64，最小化安装，干净的没安装任何东西，在安装后，直接安装1.17.9或者1.18.6

**测试结果**
出现如上的问题

**期望结果**
10251和10252端口能够正常访问

**运行环境**

- Docker版本:   19.03
- Kubernetes版本 : kube1.17.9.tar.gz/kube1.18.6.tar.gz
- sealos版本: v3.3.9-alpha.0/ v3.3.8
- 操作系统:  centos7.6 x64
- 运行模式:  8c 16G 500Gi
- 集群规模:  1master 2node
- 附加说明: 无

**Comment by zhangguanzhang** [comment]
现在新版本的都是加密端口的，get cs是走非认证端口，而且get cs1.19版本后会删除

**Comment by liutao841204** [comment]
我在1.18.4上是可以的是在这个版本后就不行了吗？

**Comment by zhangguanzhang** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md
```
Kubeadm: add the deprecated flag --port=0 to kube-controller-manager and kube-scheduler manifests to disable insecure serving. Without this flag the components by default serve (e.g. /metrics) insecurely on the default node interface (controlled by --address). Users that wish to override this behavior and enable insecure serving can pass a custom --port=X via kubeadm's "extraArgs" mechanic for these components.
```

**Comment by liutao841204** [comment]
厉害，我明白了！
