### ISSUE TITLE
问题: 执行sealos join --master 192.168.1.103 增加成功，但是集群中看不到地址

### ISSUE THREAD

**Issue by scriptyang** [fanux/sealos#432]
[root@k8sm1 kubernetes]# kubectl get nodes
NAME    STATUS   ROLES    AGE     VERSION
k8sm1   Ready    master   5d22h   v1.16.0
k8sm2   Ready    master   5d22h   v1.16.0

在103中没有启动相关的docker容器

查看kubelet 启动失败

**Comment by zhangguanzhang** [comment]
ssh上去看看kubelet的log
