### ISSUE TITLE
问题: apiserver.cluster.local写入/etc/hosts失败

### ISSUE THREAD

**Issue by w0nwig** [fanux/sealos#439]
**哪个命令或者组件**
sealos init

**描述这个缺陷**
初始化集群时，报了这个错
02:37:33 [INFO] [ssh.go:57] [ssh][192.168.86.129:22] grep -qF '192.168.86.129 apiserver.cluster.local' /etc/hosts || echo %!s(MISSING) %!s(MISSING) >> /etc/hosts
02:37:33 [INFO] [ssh.go:50] [192.168.86.129:22] bash: -c: line 0: syntax error near unexpected token `('

**重现步骤（如果有需要可以附加图片）**
1. 
...

**测试结果**
1. 
2. 
3.

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   eg 3master 3node
- 附加说明: istio,dashboard ...

**Comment by oldthreefeng** [comment]
#438

**Comment by fanux** [comment]
@w0nwig 把你执行命令发出来

**Comment by oldthreefeng** [comment]
@fanux 修复了已经
