### ISSUE TITLE
缺陷:sealos init 过程中，报错Error: unknown flag: --service-cird

### ISSUE THREAD

**Issue by skyisfuck** [fanux/sealos#441]
**哪个命令或者组件**
sealos init

**描述这个缺陷**
Error: unknown flag: --service-cird

**重现步骤（如果有需要可以附加图片）**
1. 
15:43:31 [INFO] [ssh.go:50] [192.168.100.153:22] Error: unknown flag: --service-cird
15:43:31 [INFO] [ssh.go:57] [ssh][192.168.100.153:22] echo 192.168.100.151 apiserver.cluster.local >> /etc/hosts
15:43:31 [INFO] [ssh.go:50] [192.168.100.152:22] Error: unknown flag: --service-cird

![image](https://user-images.githubusercontent.com/35327374/91823624-14559e80-ec6c-11ea-8bc3-701449f01846.png)
![image](https://user-images.githubusercontent.com/35327374/91823649-21728d80-ec6c-11ea-97d2-4fece266c4e1.png)

**Comment by oldthreefeng** [comment]
`--service-cidr` , 已经更改过来了. 下载最新版本即可.
