### ISSUE TITLE
缺陷: 在拷贝文件时出现ssh: handshake failed

### ISSUE THREAD

**Issue by 46797536** [fanux/sealos#444]
sealos version v3.3.8, build  go1.13.5

执行命令：
sealos init \
    --master 172.20.80.230 \
    --master 172.20.80.231 \
    --master 172.20.80.232 \
    --vip 10.103.97.2 \
    --user root \
    --pk /root/.ssh/id_rsa \
    --pkg-url /root/kube1.17.11.tar.gz  \
    --podcidr 172.100.0.0/16 \
    --network flannel \
    --svccidr 10.100.0.0/16 \
    --version 1.17.11
结果：

18:02:03 [ALRT] [scp.go:98] [ssh][172.20.80.230:22]transfer total size is: 1.64KB ;speed is 1KB
18:02:03 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] md5sum /etc/kubernetes/pki/etcd/peer.key | cut -d" " -f1
18:02:03 [DEBG] [ssh.go:24] [ssh][172.20.80.230:22]command result is: 9c7234940298766c23c0c8a506bbe513

18:02:03 [DEBG] [scp.go:27] [ssh]host: 172.20.80.230:22 , remote md5: 9c7234940298766c23c0c8a506bbe513
18:02:03 [INFO] [scp.go:31] [ssh]md5 validate true
18:02:03 [INFO] [download.go:38] [172.20.80.230:22]copy file md5 validate success
18:02:03 [INFO] [ssh.go:57] [ssh][172.20.80.230:22] mkdir -p /etc/kubernetes/pki/etcd || true
18:02:04 [DEBG] [download.go:29] [172.20.80.230:22]please wait for mkDstDir
18:02:04 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] ls -l /etc/kubernetes/pki/etcd/peer.crt 2>/dev/null |wc -l
18:02:04 [DEBG] [ssh.go:24] [ssh][172.20.80.230:22]command result is: 0

18:02:04 [DEBG] [scp.go:24] [ssh]source file md5 value is 9b78b255486a6cfe6093bc025e428edb
18:02:04 [ALRT] [scp.go:98] [ssh][172.20.80.230:22]transfer total size is: 1.10KB ;speed is 1KB
18:02:04 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] md5sum /etc/kubernetes/pki/etcd/peer.crt | cut -d" " -f1
18:02:04 [DEBG] [ssh.go:24] [ssh][172.20.80.230:22]command result is: 9b78b255486a6cfe6093bc025e428edb

18:02:04 [DEBG] [scp.go:27] [ssh]host: 172.20.80.230:22 , remote md5: 9b78b255486a6cfe6093bc025e428edb
18:02:04 [INFO] [scp.go:31] [ssh]md5 validate true
18:02:04 [INFO] [download.go:38] [172.20.80.230:22]copy file md5 validate success
18:02:04 [INFO] [ssh.go:57] [ssh][172.20.80.230:22] mkdir -p /etc/kubernetes/pki/etcd || true
18:02:05 [DEBG] [download.go:29] [172.20.80.230:22]please wait for mkDstDir
18:02:05 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] ls -l /etc/kubernetes/pki/etcd/healthcheck-client.key 2>/dev/null |wc -l
18:02:05 [DEBG] [ssh.go:24] [ssh][172.20.80.230:22]command result is: 0

18:02:05 [DEBG] [scp.go:24] [ssh]source file md5 value is cf2502ee09d7ee954168de52a8087065
18:02:05 [ALRT] [scp.go:98] [ssh][172.20.80.230:22]transfer total size is: 1.64KB ;speed is 1KB
18:02:05 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] md5sum /etc/kubernetes/pki/etcd/healthcheck-client.key | cut -d" " -f1
18:02:05 [DEBG] [ssh.go:24] [ssh][172.20.80.230:22]command result is: cf2502ee09d7ee954168de52a8087065

18:02:05 [DEBG] [scp.go:27] [ssh]host: 172.20.80.230:22 , remote md5: cf2502ee09d7ee954168de52a8087065
18:02:05 [INFO] [scp.go:31] [ssh]md5 validate true
18:02:05 [INFO] [download.go:38] [172.20.80.230:22]copy file md5 validate success
18:02:05 [INFO] [ssh.go:57] [ssh][172.20.80.230:22] mkdir -p /etc/kubernetes/pki/etcd || true
18:02:05 [EROR] [ssh.go:60] [ssh][172.20.80.230:22]Error create ssh session failed,ssh: handshake failed: read tcp 172.20.80.144:36264->172.20.80.230:22: read: connection reset by peer
18:02:05 [DEBG] [download.go:29] [172.20.80.230:22]please wait for mkDstDir
18:02:05 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] ls -l /etc/kubernetes/pki/etcd/healthcheck-client.crt 2>/dev/null |wc -l
18:02:05 [EROR] [ssh.go:16] [ssh][172.20.80.230:22]Error create ssh session failed,ssh: handshake failed: EOF
18:02:05 [EROR] [watch.go:51] [ssh][172.20.80.230:22]RemoteFileExist:strconv.Atoi: parsing "": invalid syntax
18:02:05 [DEBG] [scp.go:24] [ssh]source file md5 value is 9d5c3345ea565db3762b37d554562348
18:02:05 [EROR] [scp.go:49] [ssh][172.20.80.230:22]scpCopy: ssh: handshake failed: EOF
18:02:05 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] md5sum /etc/kubernetes/pki/etcd/healthcheck-client.crt | cut -d" " -f1
18:02:05 [EROR] [ssh.go:16] [ssh][172.20.80.230:22]Error create ssh session failed,ssh: handshake failed: read tcp 172.20.80.144:36267->172.20.80.230:22: read: connection reset by peer
18:02:05 [DEBG] [scp.go:27] [ssh]host: 172.20.80.230:22 , remote md5: 
18:02:05 [EROR] [scp.go:34] [ssh]md5 validate false
18:02:05 [EROR] [download.go:40] [172.20.80.230:22]copy file md5 validate failed
18:02:05 [INFO] [ssh.go:12] [ssh][172.20.80.230:22] hostname
18:02:05 [EROR] [ssh.go:16] [ssh][172.20.80.230:22]Error create ssh session failed,ssh: handshake failed: EOF
18:02:05 [EROR] [init.go:112] generator kubeconfig failed nodeName can not be empty

**Comment by oldthreefeng** [comment]
直接  `ssh 172.20.80.230`  能连上么？

**Comment by 46797536** [comment]
> 直接 `ssh 172.20.80.230` 能连上么？

ssh都没问题，从上面日志也可以看出部分文件是拷贝成功的

**Comment by oldthreefeng** [comment]
这个问题的原因太多了。 
```
Error create ssh session failed,ssh: handshake failed: read tcp 172.20.80.144:36264->172.20.80.230:22: read: connection reset by peer
```

**Comment by 46797536** [comment]
> 这个问题的原因太多了。
> 
> ```
> Error create ssh session failed,ssh: handshake failed: read tcp 172.20.80.144:36264->172.20.80.230:22: read: connection reset by peer
> ```

会不会和sshd版本有关系？这些服务器之前sshd有进行升级过

**Comment by oldthreefeng** [comment]
@46797536  看看sshd的server端的日志`tail -f /var/log/auth.log` .  这个问题我没有碰到过...

参考 https://stackoverflow.com/questions/47805723/golang-ssh-handshake-failed-eof 。

**Comment by oldthreefeng** [comment]
https://github.com/fanux/sealos/blob/cec24edbe281c617d36dba814937344ecdc731da/pkg/sshcmd/sshutil/ssh.go#L16

**Comment by 46797536** [comment]
![image](https://user-images.githubusercontent.com/46241382/92076343-f8c5d180-edec-11ea-9cec-54379be910c6.png)
目前通过旧版的sealon安装可以通过，这个版本是在201909之前发布的

**Comment by oldthreefeng** [comment]
@46797536  用新版的`sealos` 每次安装都会报相同的错误么?? 还是就一次?

**Comment by oldthreefeng** [comment]
> 目前通过旧版的sealon安装可以通过，这个版本是在201909之前发布的
有具体的版本号么? 我看看这个版本的具体实现

**Comment by 46797536** [comment]
> > 目前通过旧版的sealon安装可以通过，这个版本是在201909之前发布的
> > 有具体的版本号么? 我看看这个版本的具体实现

查不到版本号，这个如果没猜错的话是在kubel1.15.4里面的sealon

**Comment by oldthreefeng** [comment]
@cuisongliu   `kubel1.15.4` 这个包的`sealos`版本号是多少....

**Comment by oldthreefeng** [comment]
@46797536  我看了一下. 大概在v2.0.5 左右 . 里面的逻辑和现在的逻辑是没区别的...

**Comment by oldthreefeng** [comment]
最大的可能是你server端的 `ssh session` 不支持`mutli session` ? 
因为17版本的sealos自己实现了ca证书的逻辑, 没有修改`kubeadm`源码, 所以要复制相关的文件到各个节点. 里面涉及的scp还是比较多的.

**Comment by 46797536** [comment]
> mutli session

这个有查看方式吗？或者指定版本？

**Comment by oldthreefeng** [comment]
在服务端 `/etc/ssh/sshd_config` 配置下, 修改这个默认值. 默认是10 .你调大试试看?  @46797536 
```
MaxSessions 10
```

**Comment by oldthreefeng** [comment]
在服务端上面 ,查看 `/var/log/secure` 这个日志, 看看有没有关于 `error: no more sessions` 这种错误的.

**Comment by 46797536** [comment]
> no more sessions

未发现error: no more sessions错误

**Comment by 46797536** [comment]
> 在服务端 `/etc/ssh/sshd_config` 配置下, 修改这个默认值. 默认是10 .你调大试试看? @46797536
> 
> ```
> MaxSessions 10
> ```

非常感谢oldthreefeng，这个参数有效果

**Comment by oldthreefeng** [comment]
@cuisongliu  感觉这个ssh的问题的得解决一下. session过多可能会导致这个问题的.
