### ISSUE TITLE
sealos 是否可以使用upx进行压缩二进制

### ISSUE THREAD

**Issue by oldthreefeng** [fanux/sealos#446]
**哪个命令或者组件**
sealos

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1. 目前依赖安装打包完成后 57M. 比较大. 

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
1. 使用 upx 打包 后只有22M 
2. 加上-ldflags="-s -w" , 也可以减少压缩包体积.  

```
$ ./sealos version
sealos version v3.3.9, build cec24ed go1.15, Build Time : 2020-09-03 09:33:17
```

| 序号 | 原装sealos | -ldflags "-s -w" | 使用 upx | 两者都使用 |
| ---- | ---------- | ---------------- | -------- | ---------- |
| 1    | 57M        | 41M              | 22M      | 11M        |

```
$ upx sealos 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  42283008 ->  11282748   26.68%   linux/amd64   sealos                        

```

**Comment by cuisongliu** [comment]
可以的，需要修改一下编译

**Comment by fanux** [comment]
好东西
