### ISSUE TITLE
现在支持安装后升级吗

### ISSUE THREAD

**Issue by LeoWenxiang** [fanux/sealos#450]
看描述，貌似不支持升级

**Comment by oldthreefeng** [comment]
https://kubernetes.io/zh/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
可以参考这个。来实现

**Comment by LeoWenxiang** [comment]
> https://kubernetes.io/zh/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
> 可以参考这个。来实现
