### ISSUE TITLE
部署kubernetes集群报错

### ISSUE THREAD

**Issue by super1603** [fanux/sealos#452]
参考https://github.com/fanux/sealos 快速开始，前两步已完成
执行如下命令时，
```
sealos init --passwd Aa123456 \
	--master 10.134.93.68  \
	--node 10.134.92.104 \
	--pkg-url /home/astlab/hanhongwei/kube1.18.0.tar.gz \
	--version v1.18.0
```
弹出
```
10:16:41 [INFO] [ssh.go:12] [ssh][10.134.93.68:22] hostname
```
紧接着过了两秒后报错
```
10:16:44 [EROR] [ssh.go:16] [ssh][10.134.93.68:22]Error create ssh session failed,ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
10:16:44 [EROR] [check.go:39] [10.134.93.68:22] ------------ check error
```

**Comment by oldthreefeng** [comment]
出现这个错误说明`ssh password/privateKey` 都验证失败了. 
直接`ssh root@10.134.93.68 ` 可以么?

**Comment by cuisongliu** [comment]
还有一种可能就是这个IP以前连过也可能连不上。需要删除known_hosts

**Comment by super1603** [comment]
感谢您
通过ssh root@10.134.93.68后，重新进行https://github.com/fanux/sealos 快速开始，执行
sealos init --passwd Aa123456 \
	--master 10.134.93.68  \
	--node 10.134.92.104 \
	--pkg-url /home/astlab/hanhongwei/kube1.18.0.tar.gz \
	--version v1.18.0
命令后，报了新的错误
root@astlab-RH2288H-V3:~/hanhongwei# sudo sealos init --passwd Aa123456 \
> kube1.18.0.tar.gz --master 10.134.93.68  \
> kube1.18.0.tar.gz --node 10.134.92.104 \
> kube1.18.0.tar.gz --pkg-url /home/astlab/hanhongwei/kube1.18.0.tar.gz \
> kube1.18.0.tar.gz --version v1.18.0
14:18:32 [INFO] [ssh.go:12] [ssh][10.134.93.68:22] hostname
14:18:33 [DEBG] [ssh.go:24] [ssh][10.134.93.68:22]command result is: astlab-RH2288H-V3

14:18:33 [INFO] [ssh.go:57] [ssh][10.134.93.68:22] cat /etc/hosts |grep astlab-RH2288H-V3 || echo '10.134.93.68 astlab-RH2288H-V3' >> /etc/hosts
14:18:33 [INFO] [ssh.go:50] [10.134.93.68:22] 127.0.1.1 astlab-RH2288H-V3
14:18:33 [INFO] [check.go:49] [10.134.93.68:22]  ------------ check ok
14:18:33 [INFO] [ssh.go:12] [ssh][10.134.92.104:22] hostname
14:18:35 [EROR] [ssh.go:16] [ssh][10.134.92.104:22]Error create ssh session failed,ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
14:18:35 [EROR] [check.go:39] [10.134.92.104:22] ------------ check error

> 
> 
> 还有一种可能就是这个IP以前连过也可能连不上。需要删除known_hosts


![1599200613(1)](https://user-images.githubusercontent.com/44093493/92206594-5aa03d00-eeba-11ea-98a9-684fd0f002e4.jpg)

**Comment by oldthreefeng** [comment]
`ssh root@10.134.92.104` .前面那个已经验证通过了.

**Comment by super1603** [comment]
请问是10.134.92.104这台机器也需要按照https://github.com/fanux/sealos 快速开始把前两部分下载下来吗？

> 
> 
> `ssh root@10.134.92.104` .前面那个已经验证通过了.

**Comment by super1603** [comment]
我的10.134.92.104这台机器无法执行ssh root@10.134.92.104，请问有其他方法吗?

**Comment by oldthreefeng** [comment]
sealos 的前提是 需要 ssh 验证通过的. 你先把ssh这关搞通@super1603

**Comment by super1603** [comment]
您好，我现在可以通过ssh root@10.134.92.104进入了，但是我还是会有ssh这个错误




> 
> 
> sealos 的前提是 需要 ssh 验证通过的. 你先把ssh这关搞通@super1603

![1599211105(1)](https://user-images.githubusercontent.com/44093493/92223319-e02fe700-eed2-11ea-94b6-03bb347da666.jpg)

**Comment by super1603** [comment]
thanks，已成功部署

> 
> 
> sealos 的前提是 需要 ssh 验证通过的. 你先把ssh这关搞通@super1603

![1 jpeg](https://user-images.githubusercontent.com/44093493/92339194-789eb500-f0e7-11ea-90cd-aa278b35a0a5.jpg)

**Comment by oldthreefeng** [comment]
@CAS-Xiong  是你init的时候， --master的地址。
