### ISSUE TITLE
成功部署后，三个pods处于not ready状态

### ISSUE THREAD

**Issue by super1603** [fanux/sealos#457]
sealos部署了单master单node集群后，查看kube-system下的pods状态，发现caliso、kube-sealyun均为imagepullbackoff的状态，metrics-server处于pending的状态。请问这会对集群造成什么影响呢？
![1](https://user-images.githubusercontent.com/44093493/92340328-7a1eac00-f0ec-11ea-94e3-cdea853a78be.png)
![1](https://user-images.githubusercontent.com/44093493/92340347-8571d780-f0ec-11ea-8db2-076ace589b33.png)

**Comment by oldthreefeng** [comment]
看一下执行安装的命令`sealos init xxx`.  
如果是使用安装包的 . 不应该会出现 `ImagePullBackOff`这种错误的.
另外`pending` 你得看看具体原因, 使用`kubectl describe` 查看.

**Comment by super1603** [comment]
我是采用的安装包安装
![未命名图片](https://user-images.githubusercontent.com/44093493/92343673-f0281080-f0f6-11ea-83e3-70a7bd0dfa91.png)

> 
> 
> 看一下执行安装的命令`sealos init xxx`.
> 如果是使用安装包的 . 不应该会出现 `ImagePullBackOff`这种错误的.
> 另外`pending` 你得看看具体原因, 使用`kubectl describe` 查看.

**Comment by super1603** [comment]
请问kubectl describe应该怎么查pending状态的pod呢？
我执行了 kubectl describe podname ，返回了
![未命名图片](https://user-images.githubusercontent.com/44093493/92344016-df2bcf00-f0f7-11ea-9155-b8c41bc9d4ef.png)
pod不存在的错误

**Comment by oldthreefeng** [comment]
> 请问kubectl describe应该怎么查pending状态的pod呢？

建议先学习`kubernetes`基础知识. 
`kubectl describe pod podname -n kube-system`

**Comment by super1603** [comment]
感谢，kubectl describe pod podname -n kube-system后如下
是没有可用的node吗？是我的两个服务器的问题吗？
另外请问我的两个imagepullbackoff是什么问题呢？

> 
> 
> > 请问kubectl describe应该怎么查pending状态的pod呢？
> 
> 建议先学习`kubernetes`基础知识.
> `kubectl describe pod podname -n kube-system`

![未命名图片](https://user-images.githubusercontent.com/44093493/92345116-ce308d00-f0fa-11ea-8dbb-6773e9411a7b.png)

**Comment by oldthreefeng** [comment]
你到 `node`对应节点, 查看一下docker的镜像. 可能是没有load成功 .  
```
docker images |grep calico
docker images |grep lvscare
```

**Comment by super1603** [comment]
感谢，
docker images |grep calico
docker images |grep lvscare
结果如下图
同时，用kubectl get nodes命令发现我的node处于notready状态，请问应该怎么解决呢？
![未命名图片](https://user-images.githubusercontent.com/44093493/92348907-181f7000-f107-11ea-95e8-24fe3b9c1e45.png)
![未命名图片](https://user-images.githubusercontent.com/44093493/92348929-28374f80-f107-11ea-8be7-a2de9e0247a2.png)

**Comment by oldthreefeng** [comment]
重启这两个pod即可.

**Comment by super1603** [comment]
你好，我重启了这个pod，但是这个pod依旧是无法征程运行
![未命名图片](https://user-images.githubusercontent.com/44093493/92356833-5a51ad00-f119-11ea-9d1e-18b382b5a156.png)


> 
> 
> 重启这两个pod即可.

**Comment by super1603** [comment]
您好，还有我在我的node工作节点上发现好像无法访问到集群，请问是安装出现了问题吗？
![未命名图片](https://user-images.githubusercontent.com/44093493/92358071-78201180-f11b-11ea-9a25-fa4bc299db69.png)



> 
> 
> 重启这两个pod即可.

**Comment by oldthreefeng** [comment]
请自行百度... 这已经不是sealos安装的问题了..

**Comment by super1603** [comment]
请问那三个not ready 的pod应该怎么处理呢？我已经重启过了，但是貌似还是不行
![未命名图片](https://user-images.githubusercontent.com/44093493/92366481-c9ce9900-f127-11ea-9791-1c0f3ccfd7b5.png)

**Comment by oldthreefeng** [comment]
在群里么? 远程帮你处理一下?

**Comment by super1603** [comment]
感谢，我在telegram群里的

> 
> 
> 在群里么? 远程帮你处理一下?
