### ISSUE TITLE
1.19.1ControlPlaneEndpoint改动. 

### ISSUE THREAD

**Issue by oldthreefeng** [fanux/sealos#462]
1.19.1版本
Kubeadm: make the kubeconfig files for the kube-controller-manager and kube-scheduler use the LocalAPIEndpoint instead of the ControlPlaneEndpoint. This makes kubeadm clusters more reseliant to version skew problems during immutable upgrades: 

https://github.com/kubernetes/kubernetes/pull/94398

**Comment by oldthreefeng** [comment]
<details><summary><code>install 1.19.1 logs  </code> Output</summary><br><pre>
11:30:54 [INFO] [ssh.go:12] [ssh][192.168.160.243:22] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 5
11:30:55 [DEBG] [ssh.go:24] [ssh][192.168.160.243:22]command result is: I0910 11:30:54.766717    5662 initconfiguration.go:200] loading configuration from "/root/kubeadm-config.yaml"
W0910 11:30:54.767080    5662 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
I0910 11:30:54.768544    5662 initconfiguration.go:103] detected and using CRI socket: /var/run/dockershim.sock
I0910 11:30:54.768652    5662 interface.go:400] Looking for default routes with IPv4 addresses
I0910 11:30:54.768659    5662 interface.go:405] Default route transits interface "ens33"
I0910 11:30:54.769098    5662 interface.go:208] Interface ens33 is up
I0910 11:30:54.769206    5662 interface.go:256] Interface "ens33" has 1 addresses :[192.168.160.243/23].
I0910 11:30:54.769258    5662 interface.go:223] Checking addr  192.168.160.243/23.
I0910 11:30:54.769308    5662 interface.go:230] IP found 192.168.160.243
I0910 11:30:54.769315    5662 interface.go:262] Found valid IPv4 address 192.168.160.243 for interface "ens33".
I0910 11:30:54.769320    5662 interface.go:411] Found active IP 192.168.160.243 
W0910 11:30:54.914959    5662 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.19.1
[preflight] Running pre-flight checks
I0910 11:30:54.915216    5662 checks.go:577] validating Kubernetes and kubeadm version
I0910 11:30:54.915229    5662 checks.go:166] validating if the firewall is enabled and active
I0910 11:30:55.002228    5662 checks.go:201] validating availability of port 6443
I0910 11:30:55.002321    5662 checks.go:201] validating availability of port 10259
I0910 11:30:55.002347    5662 checks.go:201] validating availability of port 10257
I0910 11:30:55.002361    5662 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0910 11:30:55.002381    5662 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0910 11:30:55.002397    5662 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0910 11:30:55.002410    5662 checks.go:286] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0910 11:30:55.002424    5662 checks.go:432] validating if the connectivity type is via proxy or direct
I0910 11:30:55.002449    5662 checks.go:471] validating http connectivity to first IP address in the CIDR
I0910 11:30:55.002473    5662 checks.go:471] validating http connectivity to first IP address in the CIDR
I0910 11:30:55.002481    5662 checks.go:102] validating the container runtime
I0910 11:30:55.065317    5662 checks.go:128] validating if the "docker" service is enabled and active
I0910 11:30:55.162266    5662 checks.go:335] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0910 11:30:55.162406    5662 checks.go:335] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0910 11:30:55.162472    5662 checks.go:649] validating whether swap is enabled or not
I0910 11:30:55.162518    5662 checks.go:376] validating the presence of executable conntrack
I0910 11:30:55.162558    5662 checks.go:376] validating the presence of executable ip
I0910 11:30:55.175687    5662 checks.go:376] validating the presence of executable iptables
I0910 11:30:55.175743    5662 checks.go:376] validating the presence of executable mount
I0910 11:30:55.188318    5662 checks.go:376] validating the presence of executable nsenter
I0910 11:30:55.194138    5662 checks.go:376] validating the presence of executable ebtables
I0910 11:30:55.194187    5662 checks.go:376] validating the presence of executable ethtool
I0910 11:30:55.194642    5662 checks.go:376] validating the presence of executable socat
	[WARNING FileExisting-socat]: socat not found in system path
I0910 11:30:55.194824    5662 checks.go:376] validating the presence of executable tc
I0910 11:30:55.195085    5662 checks.go:376] validating the presence of executable touch
I0910 11:30:55.204391    5662 checks.go:520] running all checks
I0910 11:30:55.301976    5662 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I0910 11:30:55.302137    5662 checks.go:618] validating kubelet version
I0910 11:30:55.396265    5662 checks.go:128] validating if the "kubelet" service is enabled and active
I0910 11:30:55.403923    5662 checks.go:201] validating availability of port 10250
I0910 11:30:55.404018    5662 checks.go:201] validating availability of port 2379
I0910 11:30:55.404036    5662 checks.go:201] validating availability of port 2380
I0910 11:30:55.404048    5662 checks.go:249] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0910 11:30:55.437917    5662 checks.go:839] image exists: k8s.gcr.io/kube-apiserver:v1.19.1
I0910 11:30:55.469758    5662 checks.go:839] image exists: k8s.gcr.io/kube-controller-manager:v1.19.1
I0910 11:30:55.508015    5662 checks.go:839] image exists: k8s.gcr.io/kube-scheduler:v1.19.1
I0910 11:30:55.543120    5662 checks.go:839] image exists: k8s.gcr.io/kube-proxy:v1.19.1
I0910 11:30:55.579704    5662 checks.go:839] image exists: k8s.gcr.io/pause:3.2
I0910 11:30:55.612593    5662 checks.go:839] image exists: k8s.gcr.io/etcd:3.4.13-0
I0910 11:30:55.645554    5662 checks.go:839] image exists: k8s.gcr.io/coredns:1.7.0
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
I0910 11:30:55.647425    5662 certs.go:69] creating new public/private key files for signing service account users
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
I0910 11:30:55.647499    5662 kubeconfig.go:84] creating kubeconfig file for admin.conf
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
I0910 11:30:55.694159    5662 kubeconfig.go:84] creating kubeconfig file for kubelet.conf
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
I0910 11:30:55.875922    5662 kubeconfig.go:84] creating kubeconfig file for controller-manager.conf
a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has got the wrong API Server URL
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.validateKubeConfig
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:226
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFileIfNotExists
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:239
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFiles
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:112
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.CreateKubeConfigFile
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:85
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runKubeConfigFile.func1
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/kubeconfig.go:144
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:149
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
error execution phase kubeconfig/controller-manager
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:149
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.19.1-rc.0.37+ccc0405f3c92f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

11:30:55 [EROR] [ssh.go:27] [ssh][192.168.160.243:22]Error exec command failed: Process exited with status 1
11:30:55 [EROR] [init.go:134] [192.168.160.243:22]kubernetes install is error.please clean and uninstall.

</pre></details>

**Comment by zhangguanzhang** [comment]
就是说如果多个master的话，每个master上的controller和scheduler都是连localhost的apiserver？

**Comment by oldthreefeng** [comment]
https://github.com/neolit123/kubernetes/blob/d9441906c4155173ce1a75421d8fcd1d2f79c471/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L226   @zhangguanzhang  这一步验证出错了.

**Comment by zhangguanzhang** [comment]
当前的server是多少，好像kubeconfig里多了个except字段？

**Comment by zhangguanzhang** [comment]
得编译一下kubeadm，然后这一步里加个打印看看字段的值

**Comment by oldthreefeng** [comment]
当前sealos使用的是go mod  0.18.0. 

逻辑是这样的.  获取验证的时候, 
scheduler.conf,controller-manager.conf 这里面的 cluster的 server获取的是 https://apiserver:6443

**Comment by zhangguanzhang** [comment]
apiserver这个host咋来的

**Comment by oldthreefeng** [comment]
是master ip

**Comment by oldthreefeng** [comment]
我这边正在重新编译 , 
测试的时候我1.19.1版本的kubeadm执行了` kubeadm init  --config=kubeadm-config.yaml` . 这个yaml文件是sealos生成的. 
得到的这个文件`scheduler.conf,controller-manager.conf` 这里面的 cluster的 server获取的是 https://masterip:6443.

**Comment by oldthreefeng** [comment]
```
I0910 13:14:53.017570   21006 kubeconfig.go:84] creating kubeconfig file for controller-manager.conf
currentConfig.Clusters https://apiserver.cluster.local:6443 
config.Clusters:  https://192.168.160.243:6443
error execution phase kubeconfig/controller-manager: a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has got the wrong API Server URL
```

**Comment by cuisongliu** [comment]
config.Clusters:  https://192.168.160.243:6443 这个改不掉？？？

**Comment by oldthreefeng** [comment]
```
func (s *SealosInstaller) CreateKubeconfig() {
	hostname := GetRemoteHostName(s.Masters[0])

	certConfig := cert.Config{
		Path:     CertPath,
		BaseName: "ca",
	}

	controlPlaneEndpoint := fmt.Sprintf("https://%s:6443", ApiServer)

	err := cert.CreateJoinControlPlaneKubeConfigFiles(cert.SealosConfigDir,
		certConfig, hostname, controlPlaneEndpoint, "kubernetes")
	if err != nil {
		logger.Error("generator kubeconfig failed %s", err)
		os.Exit(-1)
	}

}
```

**Comment by oldthreefeng** [comment]
@cuisongliu  这个是sealos的逻辑. 
kubeadm的逻辑是
```
// GetLocalAPIEndpoint parses an APIEndpoint and returns it as a string,
// or returns and error in case it cannot be parsed.
func GetLocalAPIEndpoint(localEndpoint *kubeadmapi.APIEndpoint) (string, error) {
	// get the URL of the local endpoint
	localEndpointIP, localEndpointPort, err := parseAPIEndpoint(localEndpoint)
	if err != nil {
		return "", err
	}
	url := formatURL(localEndpointIP.String(), localEndpointPort)
	return url.String(), nil
}
```

**Comment by cuisongliu** [comment]
localEndpoint 有入口传参么？改这个vip 改动还是挺大的

**Comment by oldthreefeng** [comment]
https://github.com/kubernetes/kubernetes/pull/94398/files  . 
方案一. 这个是源码级别改动. 如果要支持, 把这部分去掉, 然后重新编译 ? 

方案二:我们这边修改这个生成逻辑.
```
CreateJoinControlPlaneKubeConfigFiles(cert.SealosConfigDir,
		certConfig, hostname, controlPlaneEndpoint, "kubernetes") 
```
 然后每个master上的controller和scheduler都是连localhost的apiserver？

**Comment by oldthreefeng** [comment]
> localEndpoint 有入口传参么？改这个vip 改动还是挺大的

`localEndpoint *kubeadmapi.APIEndpoint`  是这个

**Comment by cuisongliu** [comment]
https://github.com/kubernetes/kubernetes/blob/88e3c95d7c46431e0842e0fdc2cb99279c038515/cmd/kubeadm/app/apis/kubeadm/types.go#L55

是不是设置一下initConfig 就可以

**Comment by oldthreefeng** [comment]
是的

**Comment by cuisongliu** [comment]
测试一下。那估计得加到sealos里了

**Comment by oldthreefeng** [comment]
InitConfiguration 这个里面的APIEndpoint.AdvertiseAddress 必须是ipv4或者ipv6... 
```
couldn't use "apiserver.cluster.local" as "apiserver-advertise-address", must be ipv4 or ipv6 address
```

**Comment by zhangguanzhang** [comment]
感觉那哥们给改毁了，没考虑controlPanel为域名的情况，advertiseAddr是用ip作为ep的ttl

**Comment by oldthreefeng** [comment]
@zhangguanzhang  这个问题你来搞吧， 哈哈哈

**Comment by cuisongliu** [comment]
那1.19.1 就下架了

**Comment by oldthreefeng** [comment]
@cuisongliu  可以重新编译 kubeadm.  不用下架吧..

**Comment by oldthreefeng** [comment]
后续安装过程ok的.  
```
currentConfig.Clusters[currentCluster].Server: https://apiserver.cluster.local:6443 
config.Clusters[expectedCluster].Server:  https://192.168.160.243:6443
I0911 16:01:53.024826   71493 kubeconfig.go:227] a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has got the wrong API Server URL
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/controller-manager.conf"
I0911 16:01:53.024837   71493 kubeconfig.go:84] creating kubeconfig file for scheduler.conf
currentConfig.Clusters[currentCluster].Server: https://apiserver.cluster.local:6443 
config.Clusters[expectedCluster].Server:  https://192.168.160.243:6443
I0911 16:01:53.127660   71493 kubeconfig.go:227] a kubeconfig file "/etc/kubernetes/scheduler.conf" exists already but has got the wrong API Server URL

```

**Comment by oldthreefeng** [comment]
当这个 https://github.com/kubernetes/kubernetes/pull/94816  合并后. 关闭issue
