### ISSUE TITLE
安装成功了，但是发布一个简单的demo 后，nodeport 没有external Ip  

### ISSUE THREAD

**Issue by ssuhvs** [fanux/sealos#463]
安装成功了，但是发布一个简单的demo 后，nodeport 没有external Ip  

也不能在master节点上通过内网IP访问。请问是什么原因。完全按操作步骤来的 。求解
`
[root@k8s-node1 app]# kubectl get svc
NAME          TYPE             CLUSTER-IP                  **EXTERNAL-IP**             PORT(S)          AGE
java-demo    NodePort    10.96.153.104               **none**                 **8080:30080/TCP**   45m
kubernetes   ClusterIP      10.96.0.1                        **none**                  443/TCP          103m

[root@k8s-node1 app]# curl http://192.168.1.151:30080

` 
我的问题是： 通过  curl http://192.168.1.151:30080
 没有任何返回。。。，以前用kubeadm安装过，是可以返回信息的

**Comment by oldthreefeng** [comment]
`EXTERNAL-IP` 请百度这个ip是什么,

**Comment by ssuhvs** [comment]
我用的宿主机的IP

**Comment by zhangguanzhang** [comment]
你如果使用ipvs模式的话现在是因为高版本kube-proxy的externalIPs这块处理变了
