### ISSUE TITLE
缺陷: 无法安装master和node节点

### ISSUE THREAD

**Issue by zenway33** [fanux/sealos#464]
sealos init --master 10.129.0.18  \
  --master 10.129.0.19 \
  --master 10.129.0.20 \
  --node 10.129.0.21 \
  --node 10.129.0.2 \
  --version v1.17.11 \
  --pkg-url /root/kube1.17.11.tar.gz
只可成功安装master1,  （master02,mater03,node01,node02)并没有安装。

再安装master2,master3
sealos join --master 10.129.0.19 --master 10.129.0.20

![image](https://user-images.githubusercontent.com/18653835/92697385-d815f280-f37d-11ea-87d9-e1588feb5160.png)
一直卡在这个状态不动。

**Comment by oldthreefeng** [comment]
感觉想sealos版本不对。  @zenway33

**Comment by zenway33** [comment]
应该安装哪个版本〈〉 ？

**Comment by oldthreefeng** [comment]
latest ， 或者 v3.3.8 .你首先得告诉我你用的什么版本吧？

**Comment by zenway33** [comment]
![image](https://user-images.githubusercontent.com/18653835/92702292-99833680-f383-11ea-9870-19400f5afcea.png)
[root@master01 ~]# sealos version
sealos version latest, build 55a39e6 go1.13.5, Build Time : 2020-09-01 14:15:36

[root@master01 ~]# kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
master01   Ready    master   12m   v1.17.11
[root@master01 ~]# kubectl get -A pod
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-688c5dc8c7-btt9r   1/1     Running   0          12m
kube-system   calico-node-qtkbl                          1/1     Running   0          12m
kube-system   coredns-6955765f44-nb7vf                   1/1     Running   0          12m
kube-system   coredns-6955765f44-xgfz8                   1/1     Running   0          12m
kube-system   etcd-master01                              1/1     Running   0          12m
kube-system   kube-apiserver-master01                    1/1     Running   0          12m
kube-system   kube-controller-manager-master01           1/1     Running   0          12m
kube-system   kube-proxy-v9jlg                           1/1     Running   0          12m
kube-system   kube-scheduler-master01                    1/1     Running   0          12m
[root@master01 ~]#

[root@master01 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
10.129.0.18  master01
10.129.0.19  master02
10.129.0.20  master03
10.129.0.21  node01
10.129.0.2  node02
127.0.0.1   master01
10.129.0.18 apiserver.cluster.local

sealos init --master 10.129.0.18  \
  --master 10.129.0.19 \
  --master 10.129.0.20 \
  --node 10.129.0.21 \
  --node 10.129.0.2 \
  --version v1.17.11 \
  --pkg-url /root/kube1.17.11.tar.gz  //执行只会成功安装master01

**Comment by oldthreefeng** [comment]
知道问题了所在了。  你下载v3.3.7 版本的sealos即可。 
修复后最新的没发到oss。 

@cuisongliu  
https://github.com/fanux/sealos/blob/3fd8aa11601cfa936b75afe0f75c0ea7973d24f2/install/join.go#L107
这里为什么要加`cp -i`  这个选项？

**Comment by cuisongliu** [comment]
> 知道问题了所在了。 你下载v3.3.7 版本的sealos即可。
> 修复后最新的没发到oss。
> 
> @cuisongliu
> 
> https://github.com/fanux/sealos/blob/3fd8aa11601cfa936b75afe0f75c0ea7973d24f2/install/join.go#L107
> 
> 
> 这里为什么要加`cp -i` 这个选项？

这个选项我也不清楚哎。现在sealos最新的没上oss么？

**Comment by oldthreefeng** [comment]
最新的是在修复 `cird`之前的commit.

**Comment by zenway33** [comment]
17:46:06 [INFO] [ssh.go:57] [ssh][10.129.0.21:22] rm -rf /root/kube
17:46:06 [INFO] [ssh.go:57] [ssh][10.129.0.2:22] rm -rf /root/kube
17:46:07 [DEBG] [print.go:20] ==>SendPackage==>KubeadmConfigInstall==>InstallMaster0==>JoinMasters==>JoinNodes
17:46:07 [INFO] [print.go:25] sealos install success.

      ___           ___           ___           ___       ___           ___
     /\  \         /\  \         /\  \         /\__\     /\  \         /\  \
    /::\  \       /::\  \       /::\  \       /:/  /    /::\  \       /::\  \
   /:/\ \  \     /:/\:\  \     /:/\:\  \     /:/  /    /:/\:\  \     /:/\ \  \
  _\:\~\ \  \   /::\~\:\  \   /::\~\:\  \   /:/  /    /:/  \:\  \   _\:\~\ \  \
 /\ \:\ \ \__\ /:/\:\ \:\__\ /:/\:\ \:\__\ /:/__/    /:/__/ \:\__\ /\ \:\ \ \__\
 \:\ \:\ \/__/ \:\~\:\ \/__/ \/__\:\/:/  / \:\  \    \:\  \ /:/  / \:\ \:\ \/__/
  \:\ \:\__\    \:\ \:\__\        \::/  /   \:\  \    \:\  /:/  /   \:\ \:\__\
   \:\/:/  /     \:\ \/__/        /:/  /     \:\  \    \:\/:/  /     \:\/:/  /
    \::/  /       \:\__\         /:/  /       \:\__\    \::/  /       \::/  /
     \/__/         \/__/         \/__/         \/__/     \/__/         \/__/

                  官方文档：sealyun.com
                  项目地址：github.com/fanux/sealos
                  QQ群   ：98488045
                  常见问题：sealyun.com/faq
[root@master01 ~]# sealos version
sealos version v3.3.7, build  go1.13.5

[root@master01 ~]# kubectl get nodes
NAME       STATUS   ROLES    AGE     VERSION
master01   Ready    master   5m52s   v1.17.11
[root@master01 ~]# kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-688c5dc8c7-l8wvc   1/1     Running   0          5m39s
kube-system   calico-node-mdctv                          1/1     Running   0          5m39s
kube-system   coredns-6955765f44-hdvz8                   1/1     Running   0          5m39s
kube-system   coredns-6955765f44-zsmhl                   1/1     Running   0          5m39s
kube-system   etcd-master01                              1/1     Running   0          5m34s
kube-system   kube-apiserver-master01                    1/1     Running   0          5m34s
kube-system   kube-controller-manager-master01           1/1     Running   0          5m34s
kube-system   kube-proxy-7ssnn                           1/1     Running   0          5m39s

还是只安装了master01 
![image](https://user-images.githubusercontent.com/18653835/92713754-f257cc80-f38d-11ea-9e51-84eb96c47ef8.png)

**Comment by zenway33** [comment]
![image](https://user-images.githubusercontent.com/18653835/92714274-993c6880-f38e-11ea-8cc6-04e01c5c21a1.png)
# sealos join --master 10.129.0.19 --master 10.129.0.20 重新join还是卡在这个地方，有证书相关的报错

**Comment by oldthreefeng** [comment]
@zenway33  先clean, 后join. 再试试.

**Comment by zenway33** [comment]
> @zenway33 先clean, 后join. 再试试.

已经clean很多次了，还是不行。

![image](https://user-images.githubusercontent.com/18653835/92724528-5afa7580-f39d-11ea-9b2c-24bde96eca69.png)

**Comment by oldthreefeng** [comment]
双网卡？

**Comment by zenway33** [comment]
![image](https://user-images.githubusercontent.com/18653835/92847324-a2bfe200-f41b-11ea-8ee9-1cf2c30818a5.png)
sealos init --master 10.129.0.18  \
--master 10.129.0.19 \
--master 10.129.0.20 \
--node 10.129.0.21 \
--node 10.129.0.2 \
--version v1.17.11 \
--pkg-url /root/kube1.17.11.tar.gz

**为什么执行安装后，生成的配置文件都是错的？** @oldthreefeng @fanux 
![image](https://user-images.githubusercontent.com/18653835/92847877-35f91780-f41c-11ea-9352-b0ed3b4e4a2e.png)


**我的问题还是没有解决，每次都只能安装成功master01**
master01
eth0: 10.128.9.151
eth1:  10.129.0.18

**主机名：**
[root@master01 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
10.129.0.18  master01
10.129.0.19  master02
10.129.0.20  master03
10.129.0.21  node01
10.129.0.2  node02
127.0.0.1   master01
10.129.0.18 apiserver.cluster.local

**Comment by oldthreefeng** [comment]
@zenway33  10.103.97.2/32 这个是内核高可用ip和你的masterip 无关.  另外双网卡问题@cuisongliu 来解释一下.

**Comment by zenway33** [comment]
sealos init --master 10.129.0.18
--master 10.129.0.19
--master 10.129.0.20
--node 10.129.0.21
--node 10.129.0.2
--version v1.17.11
--pkg-url /root/kube1.17.11.tar.gz

配置kubeadm-config.yaml 为什么不生成noe01,node02 相关的ip
还有在安装过程中确实发现在master02等机器上有安装镜像导入进程相关的操作，但是执行完以后，master02像什么都没有发生一样，没有任何配置，只有scp过来的包。

**Comment by oldthreefeng** [comment]
#134 #368  @zenway33

**Comment by zenway33** [comment]
[root@master01 ~]# cat .sealos/config.yaml
masters:
- 10.129.0.18:22
- 10.129.0.19:22
- 10.129.0.20:22
nodes:
- 10.129.0.21:22
- 10.129.0.2:22
dnsdomain: cluster.local
apiservercertsans:
- 127.0.0.1
- apiserver.cluster.local
- 10.129.0.18
- 10.129.0.19
- 10.129.0.20
- 10.103.97.2
user: root
passwd: ""
privatekey: /root/.ssh/id_rsa
apiserverdomian: apiserver.cluster.local
vip: 10.103.97.2
pkgurl: /root/kube1.17.11.tar.gz
version: v1.17.11
repo: k8s.gcr.io
podcidr: 100.64.0.0/10
svccidr: 10.96.0.0/12
certpath: /root/.sealos/pki
certetcdpath: /root/.sealos/pki/etcd
是对的，但是kubeadm-config.yaml 为什么不对？不过还是帮我指导一下，为什么只能安装master01，其他都无法安装成功，问题点可能存在哪？ 网络的配置？
@oldthreefeng @fanux  谢谢

**Comment by oldthreefeng** [comment]
@zenway33  参考 #134  .  双网卡的问题.

**Comment by zenway33** [comment]
@fanux 老大帮看一下

**Comment by oldthreefeng** [comment]
[sealos.tar.gz](https://github.com/fanux/sealos/files/5212272/sealos.tar.gz)
你试试这个版本的， 我改了一点东西 ， #409

**Comment by zenway33** [comment]
感谢 @oldthreefeng 改成单网卡安装成功了，但是网络这一块还是有问题。

![image](https://user-images.githubusercontent.com/18653835/93194801-13982e80-f77b-11ea-96f7-81cfd358210e.png)
![image](https://user-images.githubusercontent.com/18653835/93194863-23b00e00-f77b-11ea-9622-90ca9ce3200a.png)
@fanux @oldthreefeng  再帮指导一下。

**Comment by zenway33** [comment]
[root@master01 ~]# lsmod | grep -e ip_vs -e nf_conntrack_ipv4
ip_vs_sh               12688  0
ip_vs_wrr              12697  0
ip_vs_rr               12600  4
ip_vs                 145497  10 ip_vs_rr,ip_vs_sh,ip_vs_wrr
nf_conntrack_ipv4      15053  19
nf_defrag_ipv4         12729  1 nf_conntrack_ipv4
nf_conntrack          139264  7 ip_vs,nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4
libcrc32c              12644  4 xfs,ip_vs,nf_nat,nf_conntrack
[root@master01 ~]# ls -al /proc/sys/net/ipv4/vs/conn_reuse_mode
-rw-r--r-- 1 root root 0 9月  15 17:18 /proc/sys/net/ipv4/vs/conn_reuse_mode
[root@master01 ~]# cat  /proc/sys/net/ipv4/vs/conn_reuse_mode
这个文件是存在的。

另外一个报错：
startup.go 331: Hit error connecting to datastore - retry error=Get https://10.96.0.1:443/api/v1/nodes/foo: dial tcp 10.96.0.1:443: i/o timeout

**Comment by zenway33** [comment]
> [root@master01 ~]# lsmod | grep -e ip_vs -e nf_conntrack_ipv4
> ip_vs_sh 12688 0
> ip_vs_wrr 12697 0
> ip_vs_rr 12600 4
> ip_vs 145497 10 ip_vs_rr,ip_vs_sh,ip_vs_wrr
> nf_conntrack_ipv4 15053 19
> nf_defrag_ipv4 12729 1 nf_conntrack_ipv4
> nf_conntrack 139264 7 ip_vs,nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4
> libcrc32c 12644 4 xfs,ip_vs,nf_nat,nf_conntrack
> [root@master01 ~]# ls -al /proc/sys/net/ipv4/vs/conn_reuse_mode
> -rw-r--r-- 1 root root 0 9月 15 17:18 /proc/sys/net/ipv4/vs/conn_reuse_mode
> [root@master01 ~]# cat /proc/sys/net/ipv4/vs/conn_reuse_mode
> 这个文件是存在的。
> 
> 另外一个报错：
> startup.go 331: Hit error connecting to datastore - retry error=Get https://10.96.0.1:443/api/v1/nodes/foo: dial tcp 10.96.0.1:443: i/o timeout

上面的问题通过升级内核解决了。
[root@master02 ~]# modprobe br_netfilter   //注意升级内核
modprobe: FATAL: Module br_netfilter not found.
升级以后网络都正常了。

[root@master01 ~]# kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
etcd-0               Healthy     {"health":"true"}  @oldthreefeng   这个是什么问题，帮指导一下 谢谢。

目前遇到的坑：
1、双网卡问题
2、内核为升级无法加载br_netfilter 模块

**Comment by oldthreefeng** [comment]
>scheduler Unhealthy Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
>controller-manager Unhealthy Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused

正常现象。 无需关心 @zenway33

**Comment by zenway33** [comment]
后面安装都很顺利了，感谢 @oldthreefeng 
总结共计三个问题：
1、双网卡问题
2、内网之间（自己的环境传输文件受限）、传输文件这一块应该再优化一下
3、内核为升级无法加载br_netfilter 模块

目前一键安装app设计很爽
https://sealyun.com/docs/app.html#%E5%AE%89%E8%A3%85app%E5%A6%82dashboard-ingress
但是提供github下载地址太慢了，不知道有没有好的下载源，另外看镜像版本还停留在2019年。

**Comment by oldthreefeng** [comment]
> 1、双网卡问题

目前正在设计考虑这块内容. 后面会很好的支持.
> 2、内网之间（自己的环境传输文件受限）、传输文件这一块应该再优化一下

目前采用的是golang调用sftp client, 打开 file 句柄实现. 你有什么更好的方式么? 

>3、内核为升级无法加载br_netfilter 模块

这个问题在考虑中~~ 

> 不知道有没有好的下载源

已经有方案了, 稍安勿躁 @zenway33  . 没有其他问题我就关闭issue了.
