### ISSUE TITLE
centos7部署失败

### ISSUE THREAD

**Issue by wan19970127** [fanux/sealos#465]
用的是官方的最新的sealos命令去执行init单个master节点的命令
sealos init --master 192.168.1.137 --passwd 970127 --pkg-url /root/kube1.17.3.tar.gz --version v1.17.3
但是init失败，error说是coredns的镜像拉取失败
![bb7235103a7619736a837222e1dd97b](https://user-images.githubusercontent.com/62001602/92988006-5e574380-f4fa-11ea-8ab8-c0068ceee120.png)
然后使用sealos clean --all命令失败
![c76e3929845490eab36751ad5b1193c](https://user-images.githubusercontent.com/62001602/92988016-74fd9a80-f4fa-11ea-975c-5c15505f1384.png)
再次从官网拉取命令替换掉就可以执行clean了
![230b98bd37ceab09fa178df9f66770d](https://user-images.githubusercontent.com/62001602/92988031-95c5f000-f4fa-11ea-9319-45a2eaa6dbdb.png)
再次执行init，重复上述报错
请问这是什么情况，该怎么解决

**Comment by oldthreefeng** [comment]
https://github.com/fanux/sealos/blob/335454b1abdc807b4cecb0200db73489d7acf07b/install/send.go#L21

应该是这个问题， @cuisongliu 
当sealos 执行的主机和master0 是同一个的时候，这个SendPackage就跳过了。 这个时候使用的就是默认的`kube1.17.3.tar.gz`里面的sealos。  
这块逻辑你看看要改么？

**Comment by wan19970127** [comment]
> https://github.com/fanux/sealos/blob/335454b1abdc807b4cecb0200db73489d7acf07b/install/send.go#L21
> 
> 应该是这个问题， @cuisongliu
> 当sealos 执行的主机和master0 是同一个的时候，这个SendPackage就跳过了。 这个时候使用的就是默认的`kube1.17.3.tar.gz`里面的sealos。
> 这块逻辑你看看要改么？

kube压缩包里也有sealos命令么

**Comment by oldthreefeng** [comment]
恩， 有的。

**Comment by zhangguanzhang** [comment]
docker images看看coredns镜像

**Comment by wan19970127** [comment]
这个怎么解决啊，现在我重新换了一个集群，一样出现这个问题了

**Comment by wan19970127** [comment]
要是我回复不及时，请加我微信wan364725399

**Comment by cuisongliu** [comment]
是否已经解决 @wan19970127  长时间未回应会关闭这个issue

**Comment by oldthreefeng** [comment]
下载最新的`sealos`可以避免了 .
已经从根本上解决压缩包里面的`sealos`版本与执行`sealos`命令版本不兼容的问题了
