### ISSUE TITLE
问题: CentOS 7.6 安装时报permission denied问题

### ISSUE THREAD

**Issue by JamesLiAndroid** [fanux/sealos#474]
**那个命令或者组件**
安装命令如下：
```
sealos init --user root --passwd 123456 --master 192.168.192.22:14444  --master 192.168.192.23:14444  --master 192.168.192.24:14444 --node 192.168.192.25:14444 --pkg-url ./kube1.18.0.tar.gz --version v1.18.0

```
**描述你的问题**
![image](https://user-images.githubusercontent.com/6966410/93446886-520d2500-f904-11ea-9ddf-5bd33e766b20.png)

如图所示，根本就找不到**/root/.sealos**这个文件夹，而且在*/etc/kubernetes/*也找不到证书文件

求教

**Comment by oldthreefeng** [comment]
不建议使用非root用户安装.

**Comment by JamesLiAndroid** [comment]
@oldthreefeng 我用的root用户进行的安装，不过现在莫名奇妙安装上了。我更换了一台服务器，就是不使用k8s中的主节点服务器进行部署，目前部署成功了一次
