### ISSUE TITLE
pod内部无法解析域名

### ISSUE THREAD

**Issue by oldmanl** [fanux/sealos#477]
在阿里ecs搭建了集群，发现POD里解析域名出现问题。

**查看coredns日志如下**:
`[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:60114->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:59187->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:35935->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:53023->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:51849->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:57143->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:50647->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:56528->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:48702->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:42850->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:54379->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:53284->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:45336->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:38623->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:60507->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:49183->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:37259->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:33458->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. AAAA: read udp 100.112.151.135:46905->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 baidu.com. A: read udp 100.112.151.135:37314->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. AAAA: read udp 100.112.151.135:55776->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. A: read udp 100.112.151.135:34107->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. AAAA: read udp 100.112.151.135:51340->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. A: read udp 100.112.151.135:40719->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. AAAA: read udp 100.112.151.135:58093->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. A: read udp 100.112.151.135:47494->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. AAAA: read udp 100.112.151.135:50441->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. A: read udp 100.112.151.135:56550->100.100.2.136:53: i/o timeout
[ERROR] plugin/errors: 2 elasticsearch. AAAA: read udp 100.112.151.135:53596->100.100.2.136:53: i/o timeout`

**coredns所在节点/etc/resolv.conf**:
```
nameserver 100.100.2.136

nameserver 100.100.2.138

options timeout:2 attempts:3 rotate single-request-reopen
```

**查看kube-proxy日志正常，没出现错误**。

大佬看看怎么解决？

**Comment by oldthreefeng** [comment]
#150

**Comment by oldmanl** [comment]
通过上面说的，添加外网dns，重新部署coredns之后，能正常解析域名了。
经排查ecs里的默认dns是阿里的内网dns，需添加外网的dns例如223.5.5.5
```
nameserver 100.100.2.136

nameserver 100.100.2.138
```
现在还遗留的问题是，POD里外网的域名能正常解析访问，但是阿里内部的例如oss内网域名是访问不了的，使用dnsutils进行测试，访问oss-cn-shenzhen-internal.aliyuncs.com，能看到解析出了对应的ip，但是pod里是访问不了这个Ip的。

![image](https://user-images.githubusercontent.com/19261985/93836570-c570b700-fcb5-11ea-8bd6-cdb708f9b35d.png)

直接在主机上ping对应的ip是可以访问的

![image](https://user-images.githubusercontent.com/19261985/93836654-0963bc00-fcb6-11ea-9a1b-1d547de2f26a.png)

**Comment by oldthreefeng** [comment]
这种情况, 建议更换pod网段. 避免和阿里云的网段冲突. 比如`10.32.0.0/12`

```
sealos init --podcidr  10.32.0.0/12  
```

**Comment by oldmanl** [comment]
> 这种情况, 建议更换pod网段. 避免和阿里云的网段冲突. 比如`10.32.0.0/12`
> 
> ```
> sealos init --podcidr  10.32.0.0/12  
> ```

请问下这步操作会影响到正在运行着的pod吗

**Comment by oldthreefeng** [comment]
> 请问下这步操作会影响到正在运行着的pod吗.

相当于重装，肯定影响的。 如果你已经运行了服务， 建议自己查询一下如何优雅更改`kubernetes pod`网段。
