### ISSUE TITLE
join master error

### ISSUE THREAD

**Issue by 2690522020** [fanux/sealos#479]
**哪个命令或者组件**
sealos join --master 

**描述这个缺陷**
添加master报错

**测试结果**
net: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get https://dl.k8s.io/release/stable-1.txt: dial tcp: lookup dl.k8s.io on [::1]:53: read udp [::1]:55512->[::1]:53: read: connection refused
W0921 20:37:10.571978   30986 version.go:103] falling back to the local client version: v1.18.8
W0921 20:37:10.572275   30986 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[upload-certs] Storing the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
error execution phase upload-certs: error uploading certs: error creating token: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher

20:38:12 [EROR] [ssh.go:27] [ssh][15.26.3.125:22]Error exec command failed: Process exited with status 1
20:38:12 [DEBG] [join.go:64] [globals]decodeCertCmd:
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/fanux/sealos/install.(*SealosInstaller).GeneratorCerts(0xc0002b1130)
        /go/src/github.com/fanux/sealos/install/join.go:66 +0x393
github.com/fanux/sealos/install.joinMastersFunc(0xc0002e0c00, 0x1, 0x1)
        /go/src/github.com/fanux/sealos/install/join.go:34 +0x13f
github.com/fanux/sealos/install.BuildJoin(0xc0002e0c00, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/fanux/sealos/install/join.go:17 +0x77
github.com/fanux/sealos/cmd.glob..func11(0x286a600, 0xc000271880, 0x0, 0x2)
        /go/src/github.com/fanux/sealos/cmd/join.go:48 +0x167
github.com/spf13/cobra.(*Command).execute(0x286a600, 0xc000271860, 0x2, 0x2, 0x286a600, 0xc000271860)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:844 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x286a8a0, 0x43d4ba, 0x280dc60, 0xc000000180)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/fanux/sealos/vendor/github.com/spf13/cobra/command.go:885
github.com/fanux/sealos/cmd.Execute()
        /go/src/github.com/fanux/sealos/cmd/root.go:47 +0x31
main.main()
        /go/src/github.com/fanux/sealos/main.go:22 +0x20

**期望结果**
正常添加

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.18.tar.gz
- sealos版本: v3.1.0
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 125g, cpu 10核 ,存储 1t）
- 集群规模:   eg 3master 6node
- 附加说明: istio,dashboard ...

**Comment by oldthreefeng** [comment]
> v3.1.0

@2690522020 使用最新版sealos安装.
