### ISSUE TITLE
日志分批处理

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#482]
**哪个命令或者组件**
sealos 所有命令

**详细描述你的需求/任务**
详细描述你的需求和任务要求

由于存在并发问题，需要日志查找比较麻烦，针对多个机器的日志需要分批写入不同的文件中，方便查找问题。

**Comment by oldthreefeng** [comment]
@cuisongliu  
我的想法是这样的， 生成多个文件其实对用户很不友好。 在安装的时候， 其实出现error的日志很少， 一旦出现， 必定就是每个主机都存在。 所以， 我的解决方案是： 
1. 所有DEBG级别以上的日志打印在屏幕。
2. 所有ERROR级别以上的日志， 保存在“~/.sealos/error.log” . 用户只需要把`error.log` ，` os/kernel/sealos version `及`sealos  init`命令上传即可。

**Comment by cuisongliu** [comment]
这个先不需要实现了。
