### ISSUE TITLE
是不是可以考虑升级一下默认的calico版本

### ISSUE THREAD

**Issue by ysicing** [fanux/sealos#485]
**哪个命令或者组件**
eg.  sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1. 更新calico镜像版本
2. 支持指定calico镜像源，默认使用`https://index.docker.io/v1/`,  可以使用自定义的

**Comment by oldthreefeng** [comment]
@ysicing  这个是不是背离了 `all in one`的思想.  离线是sealos的一个大特色. 
感觉这种情况用户自定义安装 `calico` 会更好~

**Comment by WinterZhou** [comment]
用户可以自己更换网络组件吧，然后自行制作离线安装包

**Comment by ysicing** [comment]
@oldthreefeng 😁，目前内置的calico版本可以升级一下。简单描述一下我使用的方法，目前镜像都同步到内网镜像仓库的，如果init指定内网镜像源一条龙就很方便了，使用在线安装的。当然离线安装就不会有这个问题～

**Comment by oldthreefeng** [comment]
我明白你的意思了， 可能连 `sh init.sh` 你都不想操作？ @ysicing  
或者换一个说法。 
加一个参数 `--online` 或者 `--offline`  . 我估摸这要重构蛮多东西的。很多都是基于pkgUrl文件来操作的。 
`sealos`主要耗时都在`docker load `和 `tar xf kube1*.tar.gz`

**Comment by ysicing** [comment]
@oldthreefeng  主要是不想load镜像 😂

**Comment by oldthreefeng** [comment]
是的, 本地调试的时候, 这个 `docker load` 很费资源. 你想想有什么好的方案哇~ @ysicing

**Comment by ysicing** [comment]
@oldthreefeng  我本地测试的时候都是使用在线安装， 指定了repo，然后将安装包里的镜像去掉了，仅留下配置文件和二进制。
这个是我自己测试用的
https://github.com/ysicing/tools/tree/master/k7s

**Comment by oldthreefeng** [comment]
@ysicing  感觉可以打一个专门的 online 包, 只包含 二进制和配置文件.  `online`的话, 就跳过 load ..然后得指定`k8s repo`. 不然就直接卡死..  

> https://github.com/ysicing/tools/tree/master/k7s

这个项目借用了~

**Comment by willzhang** [comment]
> 我明白你的意思了， 可能连 `sh init.sh` 你都不想操作？ @ysicing
> 或者换一个说法。
> 加一个参数 `--online` 或者 `--offline` . 我估摸这要重构蛮多东西的。很多都是基于pkgUrl文件来操作的。
> `sealos`主要耗时都在`docker load `和 `tar xf kube1*.tar.gz`

online模式并没那么简单，因为部署k8s集群，docker镜像只是冰山一角，还有各种配置文件、脚本、二进制文件这些不好处理。

单个docker镜像打单个tar包是否好一些，反正也没有压缩，这样去做镜像校验，不存在就去load对应单个镜像。

**Comment by ysicing** [comment]
在线方式就不需要考虑镜像，本地不存在pull或者总是pull。至于其他配置等就需要通过sealos处理了，目前是使用通用的统一方式，后面可以考虑需要通过hook方式或者自定义配置文件方式来解决。

**Comment by fanux** [comment]
大版本升级准备解决这个问题
