### ISSUE TITLE
16:27:12 [INFO] [ssh.go:57] [ssh][172.16.90.51:22] cd /root/prometheus && kubectl apply -f manifests 16:27:13 [INFO] [ssh.go:50] [172.16.90.51:22] unable to recognize "manifests/0prometheus-operator-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

### ISSUE THREAD

**Issue by liushifa** [fanux/sealos#489]
16:27:12 [INFO] [ssh.go:57] [ssh][172.16.90.51:22] cd /root/prometheus && kubectl apply -f manifests
16:27:13 [INFO] [ssh.go:50] [172.16.90.51:22] unable to recognize "manifests/0prometheus-operator-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

**Comment by cuisongliu** [comment]
16:27:13 [INFO] [ssh.go:50] [172.16.90.51:22] unable to recognize "manifests/0prometheus-operator-serviceMonitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1" 

版本不对，查下配置吧

**Comment by fanux** [comment]
再apply一次即可
