### ISSUE TITLE
需求: 能否在安装时设置docker数据目录

### ISSUE THREAD

**Issue by liutao841204** [fanux/sealos#495]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
我先描述下我的场景：
1.sealos在全新的机器上安装docker，默认都安装到/var/lib/docker下
2.我们现在有许多客户的安装环境，var分区下都用的根分区空间，空间很小。
3.如果不能指定，我每次只能要求客户重新安装机器，十分不便。

**是否有解决方案，如果有请详述**
我想了一个方案，看看是否可行
1.sealos init 中指定一个参数，设置docker数据目录。在安装的时候，动态设置到程序中。

**Comment by oldthreefeng** [comment]
> 3.如果不能指定，我每次只能要求客户重新安装机器，十分不便。

使用软连接可以解决, 不必要重装吧. 

> 1.sealos init 中指定一个参数，设置docker数据目录。在安装的时候，动态设置到程序中。

可以考虑这样设置, 但是我感觉这个需求没必要.

**Comment by liutao841204** [comment]
我也在参考软连接，但是也希望在安装时，能够传进去。如果安装后调整，就出现两个存储目录了！

**Comment by oldthreefeng** [comment]
> 我也在参考软连接，但是也希望在安装时，能够传进去。如果安装后调整，就出现两个存储目录了！不是不行，就是觉得很别扭！

可以实现, 需要把安装docker那部分抽离出来就好.

**Comment by oldthreefeng** [comment]
想要自定义修改, 目前的方法是: 解压` kube1.x.y.tar.gz` , 修改 `kube/shell/docker.sh` . 修改相关的参数即可. 然后打包即可.  @liutao841204 

目前正在做的是把init.sh抽离出来, 
https://github.com/oldthreefeng/sealos/blob/77bdacb9f3ef4a90f1d469c6c587f659c38d3f77/install/constants.go#L34  
这个地方自定义数据卷的.

**Comment by liutao841204** [comment]
收到！
