### ISSUE TITLE
docker data-root 参数

### ISSUE THREAD

**Issue by zhangquan1129** [fanux/sealos#497]
一般来说ecs 系统盘40g
默认data-root 参数为 /var/lib/docker
建议自动匹配较大的目录空间 或自定义一些指标，如svc 网段  等

**Comment by zhangguanzhang** [comment]
可以软连接做

**Comment by oldthreefeng** [comment]
#495

**Comment by fanux** [comment]
svc 网段 目前是有的 存储目录参考上面issue
