### ISSUE TITLE
clean node need clean ipvs rule

### ISSUE THREAD

**Issue by dk-lockdown** [fanux/sealos#498]
**哪个命令或者组件**
sealos clean --node

**详细描述你的需求/任务**
移除一个工作节点，需要将其初始化的 ipvs 规则清除。否则再次将这个节点加入其他集群，ipvs 规则会有污染，10.103.97.2 可能会负载均衡到旧的 master 节点，如果旧的 master 节点挂了呢？

**Comment by zhangguanzhang** [comment]
ssh上去docker run --rm 下kube-proxy的镜像起个容器--clean有个选项清理下

**Comment by dk-lockdown** [comment]
> ssh上去docker run --rm 下kube-proxy的镜像起个容器--clean有个选项清理下

没明白你说的意思

**Comment by zhangguanzhang** [comment]
kube-proxy --help |& grep clean

**Comment by dk-lockdown** [comment]
> kube-proxy --help |& grep clean

node 都已经 clean 了，kube-proxy 都没了呀

**Comment by zhangguanzhang** [comment]
docker镜像还在就可以，其次我也是说给其他contributer这个issue的解决思路的

**Comment by dk-lockdown** [comment]
> docker镜像还在就可以，其次我也是说给其他contributer这个issue的解决思路的

sealos 里面有 ipvs 相关的代码，clean node 后，delete virtual server，delete real server 也可以

**Comment by oldthreefeng** [comment]
默认没有安装ipvsadm， 可以参考一下ipvs/iptables关sdk， 清理ipvs/iptables.

**Comment by zhangguanzhang** [comment]
> 默认没有安装ipvsadm， 可以参考一下ipvs/iptables关sdk， 清理ipvs/iptables.

```
docker run --rm --entrypoint /usr/local/bin/kube-proxy $kube-proxy-img --cleanup
```

**Comment by fanux** [comment]
@zhangguanzhang cleanup 会不会忽略掉
ipvs:
  excludeCIDRs: 
  - "{{.VIP}}/32"

**Comment by zhangguanzhang** [comment]
> @zhangguanzhang cleanup 会不会忽略掉
> ipvs:
> excludeCIDRs:
> 
> * "{{.VIP}}/32"

会的

**Comment by fanux** [comment]
那你的命令还是清理不掉 lvscare的

**Comment by zhangguanzhang** [comment]
lvscare启动前把vip的所有相关的规则干掉就行了，然后再添加

**Comment by oldthreefeng** [comment]
> lvscare启动前把vip的所有相关的规则干掉就行了，然后再添加 

这个再`sealos ipvs` 添加之前做就可以干掉吧.

**Comment by fanux** [comment]
> > lvscare启动前把vip的所有相关的规则干掉就行了，然后再添加
> 
> 这个再`sealos ipvs` 添加之前做就可以干掉吧.

我看行

**Comment by oldthreefeng** [comment]
晚点写写看.
