### ISSUE TITLE
清理集群的命令 少了 all

### ISSUE THREAD

**Issue by dongs365** [fanux/sealos#499]
sealos clean --all

**Comment by oldthreefeng** [comment]
> sealos clean --all

这个命令有问题么?

**Comment by dongs365** [comment]
文档里面错了

**Comment by oldthreefeng** [comment]
有具体的地址么.  我修改一下.

**Comment by dongs365** [comment]
https://github.com/fanux/sealos/blob/develop/README.md    里面的清理集群
