### ISSUE TITLE
问题: sealos安装k8s1.16想更换1.19版本怎么做？

### ISSUE THREAD

**Issue by wealthtears** [fanux/sealos#504]
**描述你的问题**
我在服务器已经使用sealos init命令一键安装安装了k8s v1.1.6版本。现在想通过sealos init命令中的pkg-url参数把k8s设置为v1.19高版本。请问我该怎么做？需要卸载k8s重新部署吗？还是直接继续sealos init就行？请给我说下步骤。

**Comment by wealthtears** [comment]
目前没有安装任何应用

**Comment by ysicing** [comment]
既然没有部署任何服务，clean掉重新安装新版本

```
# 清理集群
sealos clean --all
# 重新安装新版本
sealos init
```

**Comment by wealthtears** [comment]
> 既然没有部署任何服务，clean掉重新安装新版本
> 
> ```
> # 清理集群
> sealos clean --all
> # 重新安装新版本
> sealos init
> ```

你好，再次请教下。如果k8s安装了应用，例如mysql等。那么升级应该如何升级？

**Comment by oldthreefeng** [comment]
> 你好，再次请教下。如果k8s安装了应用，例如mysql等。那么升级应该如何升级？

sealos upgrade 命令.  @wealthtears 
文档 https://github.com/fanux/sealos/blob/develop/docs/upgrade.md
