### ISSUE TITLE
SealOS CLI 清除 Node 的优化建议

### ISSUE THREAD

**Issue by aiyijing** [fanux/sealos#510]
对于 sealos clean node 往往需要两步
* 输入 y/n  是否确认 clean Node
* 输入 Node password

这种做的意图是为了防止，用户的误操作。
但是这有点影响 sealos 在脚本中的自动化，
我认为可以参考 ceph 删除pool 的方式来进行优化
```bash
ceph osd pool delete ${pool} --yes-i-really-really-mean-it
````
建议：sealos clean node 可以加入flag:  --password, --yes-i-really-really-mean-it
这样既可以作为一个提示，提醒用户正在做的操作，也能够兼容一些脚本的自动化
```bash
sealos clean ${some node}  --password --yes-i-really-really-mean-it
```
不知道各位对此有何看法，如果觉得这个点子不错，我愿意贡献代码。

**Comment by oldthreefeng** [comment]
谢啦~~ 已经实现了.  password读取的是你的配置文件.  `.sealos/config.yaml ` 的`passwd` 字段. 
如果配置文件不存在, 则读取用户的输入. 
```
sealos clean --node $node   --force    
```

**Comment by aiyijing** [comment]
抱歉，我并没有发现这个 flag，谢谢提醒
