### ISSUE TITLE
当我先装sealos 的K8S集群，然后yum install iptables ，导致所有iptables规则都失效

### ISSUE THREAD

**Issue by xulei52074** [fanux/sealos#512]
因为内网安全是点对点白名单的，所以两者iptables service也需要安装上。所以安装上，只要restart 就会导致cni等其他规则都丢失了！

**Comment by zhangguanzhang** [comment]
你restart下kube-proxy

**Comment by xulei52074** [comment]
重新apply会写规则进去，很奇怪不知道为什么，proxy重启不会写cni规则



---原始邮件---
发件人: "zhangguanzhang"<notifications@github.com&gt;
发送时间: 2020年11月6日(周五) 下午5:04
收件人: "fanux/sealos"<sealos@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"xulei52074"<304374357@qq.com&gt;;
主题: Re: [fanux/sealos] 当我先装sealos 的K8S集群，然后yum install iptables ，导致所有iptables规则都失效 (#512)




 
你restart下kube-proxy

**Comment by zhangguanzhang** [comment]
安装iptables我记得会带一个iptables的daemon，一般是没必要安装这个的
