### ISSUE TITLE
需求: kubernetes相关镜像基于localRegistry管理

### ISSUE THREAD

**Issue by wisheen** [fanux/sealos#514]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1. sealos init 可指定localRegistry，并在目前init.sh中调用docker.sh时候传递过去（主机的docker可非https访问）,docker.sh目前有指定localRegistry的逻辑，但安装时候做了默认127.0.0.1
2. 如果sealos init 指定了localRegistry参数，则不在分发image.tar，在对应的localRegitry下载，例如
    k8s.gcr.io/kube-proxy/v1.15.12 镜像名称就被tag 为 $localRegistry/k8s.gcr.io/kube-proxy/v1.15.12
    同理 fanux/lvscare 就是 $localRegistry/fanux/lvscare

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
1. 镜像仓库可默认带一个，例如基于nexus，如果是权限要求的那可自己安装 harbor 等
2. 基于镜像仓库的好处是：
  a. 节点如果磁盘紧张时，镜像可能会被docker清空，这个时候除非手工 load image -i image.tar，否则节点无法恢复
  b. 安装时候可不显示分发，简化分发逻辑

**Comment by oldthreefeng** [comment]
有点像 #486 这个pr..

**Comment by wisheen** [comment]
> 有点像 #486 这个pr..

其实不一样，我可能没说清楚，上面说的  localRegistry 其实确切的是一个docker 镜像的仓库，例如在 192.168.11.1的80端口启动一个nexus服务配置作为docker仓库。
那所有的镜像都push到 192.168.11.1， 节点通过 192.168.11.1/k8s.gcr.io/kube-proxy/v1.15.12 下载，而由于80非https，所以dokcer的 /etc/docker/daemon.json里面需要对  "insecure-registries" 做什么（现在docker.sh脚本里面有逻辑）

**Comment by ysicing** [comment]
可以支持online & offline方式，online就不去load镜像了

**Comment by SwarmKit** [comment]
> 可以支持online & offline方式，online就不去load镜像了

怎么支持online 方式？初始化命令是这个，还是去拉取镜像，如果拿掉--pkg-url  命令就报错，缺少参数；

```
./sealos init --kubeadm-config kubeadm-config.yaml.tmpl \
--master 192.168.1.1 \
--master 192.168.1.2 \
--master 192.168.1.3 \
--node 192.168.1.5 \
--repo kube.io/google_containers \
--lvscare-image kube.io/google_containers/lvscare \
--lvscare-tag latest \
--without-cni \
--apiserver zzk-apiserver.cluster.local \
--podcidr 192.168.0.0/16 \
--user root \
--passwd 123456 \
--version v1.18.10 \
--pkg-url /root/kube1.18.10.tar.gz
```

**Comment by ysicing** [comment]
@SwarmKit  你可以手动调整一下，我们是默认修改了kube1.18.10.tar.gz里的脚本，移除了load镜像这步 这个是目前使用的https://github.com/ysicing/tools/blob/master/k7s/kube/shell/init.sh

**Comment by fanux** [comment]
@wisheen 这个需求暂时可能需要自己去hack了。    后续大版本升级准备用更颠覆的方式解决这些问题
