### ISSUE TITLE
缺陷: docker.sh 脚本的完善

### ISSUE THREAD

**Issue by wisheen** [fanux/sealos#521]
离线包里面的 kube/shell/docker.sh 不知道是维护那个仓库的，不能直接提交合并请求，建议如下修改：
```
if ! command_exists docker; then
...
  systemctl enable  docker.service
  systemctl restart docker.service
  cat > /etc/docker/daemon.json  << eof
  ...
  eof
fi
systemctl restart docker.service
docker version
```
修改为：
```
if ! command_exists docker; then
...
  systemctl enable  docker.service
fi # 安装放到条件里面
#  systemctl restart docker.service 删除，否则安装时候会restart两次
# /etc/docker/daemon.json 只要执行docker.sh就新生成，新安装参数可能会有变化
[ -f /etc/docker/daemon.json ] && mv /etc/docker/daemon.json /etc/docker/daemon.json-$(date +'%Y%m%d%H%M%S') # 新增，备份一下以备不测
mkdir -p  /etc/docker # 这个必须，否则ubuntu server18.04 安装node节点一定不会生成文件，原因就是没目录
  cat > /etc/docker/daemon.json  << eof 
  ...
  eof
#  fi 移到上面
systemctl restart docker.service
docker version
```

**Comment by oldthreefeng** [comment]
其实只需要改最后两行就好.

```
systemctl restart docker.service
docker version 
```
to 
```
docker info || systemctl restart docker.service
```

**Comment by wisheen** [comment]
> 其实只需要改最后两行就好.
> 
> ```
> systemctl restart docker.service
> docker version 
> ```
> 
> to
> 
> ```
> docker info || systemctl restart docker.service
> ```

mkdir -p  /etc/docker
这个必须，否则没上级目录文件会失败，放到if外面与否只是逻辑优化，调整与否不关键，但mkdir 这个必须，是逻辑错误

**Comment by oldthreefeng** [comment]
#471  有点重复, 我这边会统一修改然后pr.

**Comment by oldthreefeng** [comment]
@wisheen 看看这个

**Comment by oldthreefeng** [comment]
> [ -f /etc/docker/daemon.json ] && mv /etc/docker/daemon.json /etc/docker/daemon.json-$(date +'%Y%m%d%H%M%S') # 新增，备份一下以备不测

如果docker command 不存在, 备份这个没有意义. 所以直接覆盖即可, 
如果docker command 存在,  直接跳过逻辑.  判断是否运行了docker. 没有运行重启.

**Comment by wisheen** [comment]
> > [ -f /etc/docker/daemon.json ] && mv /etc/docker/daemon.json /etc/docker/daemon.json-$(date +'%Y%m%d%H%M%S') # 新增，备份一下以备不测
> 
> 如果docker command 不存在, 备份这个没有意义. 所以直接覆盖即可,
> 如果docker command 存在, 直接跳过逻辑. 判断是否运行了docker. 没有运行重启.

docker存在，但可能是之前同版本安装，也可能是老版本安装，或者是其他厂商安装，也可能是自己apt/yum 安装，覆盖的话，保证节点的配置都一致
其实我这边有个场景是把docker.sh 的参数$harbor_ip 用起来了（修改过init.sh逻辑适配），如果不覆盖，基本上就出错了，harbor_ip没指定导致镜像仓库由于非https pull失败。
而且本身还有日志规则定义等，或许后面还有更优化的其他选项配置，所以我建议是覆盖，备份这个可优化，文件md5同就不备份和覆盖了

**Comment by wisheen** [comment]
等于sealos安装就是一个大原则，安装就是强制覆盖安装，会涉及修改docker参数，系统参数（swap，iptable，file limit等）等，这些都强制以sealos的推荐为准，所有节点保持一致，被安装系统有的就暴力覆盖，但为了怕手抖误操作，老的备份下

**Comment by oldthreefeng** [comment]
这到不是， docker存在并运行， 则不会操作(前面几个版本是会重启docker)， 请仔细看看脚本..

**Comment by oldthreefeng** [comment]
> 系统参数（swap，iptable，file limit等）等，这些都强制以sealos的推荐为准，所有节点保持一致，被安装系统有的就暴力覆盖，但为了怕手抖误操作，老的备份下

这些的确是覆盖， 避免小白用户因参数设置导致安装失败， 有能力用户可以自行修改.
