### ISSUE TITLE
sealos init 执行无响应

### ISSUE THREAD

**Issue by htfhxx** [fanux/sealos#525]
sealos init 执行无响应，
![image](https://user-images.githubusercontent.com/34822492/99214941-7efa8d00-280c-11eb-9f84-f051ea695bae.png)
![image](https://user-images.githubusercontent.com/34822492/99215034-c254fb80-280c-11eb-951a-a39ddb398975.png)

还需要做别的什么吗
感谢回复~

**Comment by oldthreefeng** [comment]
按照issue模板回复..

**Comment by htfhxx** [comment]
> 按照issue模板回复..

抱歉没懂您什么意思，issue模板里的内容包括命令、问题和参考资料三方面，其中1和3暂时没有涉及呢...

**Comment by airship-shrimp** [comment]
一样的问题，确认过usr/bin 里面sealos也存在了。但是任何sealos命令都没有响应。如sealos verison

**Comment by airship-shrimp** [comment]
重新安装
wget -c https://github.com/fanux/sealos/releases/download/v3.3.9-alpha.2/sealos && chmod +x sealos && mv sealos /usr/bin
这个版本，解决了问题

**Comment by oldthreefeng** [comment]
```
wget https://sealyun.oss-cn-beijing.aliyuncs.com/v3.3.9-alpha.2/sealos  && chmod +x sealos && mv sealos /usr/bin
```
阿里云的oss应该也没有问题.

**Comment by airship-shrimp** [comment]
> ```
> wget https://sealyun.oss-cn-beijing.aliyuncs.com/v3.3.9-alpha.2/sealos  && chmod +x sealos && mv sealos /usr/bin
> ```
> 
> 阿里云的oss应该也没有问题.

之前我是安装wget https://sealyun.oss-cn-beijing.aliyuncs.com/lastest/sealos  && chmod +x sealos && mv sealos /usr/bin 出现这个问题

**Comment by oldthreefeng** [comment]
我这边正常的, 奇怪了.

**Comment by htfhxx** [comment]
感谢大家。我这边换了3.38的版本，也可以了。latest安装包大小只有10M+，3.38的版本50M+，可能工具包残缺吧。

**Comment by oldthreefeng** [comment]
lastet包是没有问题的， 经过upx压缩的 ，方便用户快速下载
