### ISSUE TITLE
[ERROR SystemVerification]: unsupported graph driver: vfs

### ISSUE THREAD

**Issue by htfhxx** [fanux/sealos#527]
**那个命令或者组件**
eg. sealos init , sealos install , kubernetes cni, docker  and so on 

sealos init命令

**描述你的问题**
详细描述出你的问题内容xxxx.
部署过程如下：
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled (as module)
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_AUFS_FS: not set - Required for aufs.
CONFIG_BLK_DEV_DM: enabled (as module)
DOCKER_VERSION: 19.03.0
DOCKER_GRAPH_DRIVER: vfs
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR SystemVerification]: unsupported graph driver: vfs
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

15:00:35 [EROR] [ssh.go:27] [ssh][10.60.1.97:22]Error exec command failed: Process exited with status 1
15:00:35 [EROR] [init.go:130] [10.60.1.97:22]kubernetes install is error.please clean and uninstall.
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled (as module)
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_AUFS_FS: not set - Required for aufs.
CONFIG_BLK_DEV_DM: enabled (as module)
DOCKER_VERSION: 19.03.0
DOCKER_GRAPH_DRIVER: vfs
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR SystemVerification]: unsupported graph driver: vfs
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

15:00:35 [EROR] [ssh.go:27] [ssh][10.60.1.97:22]Error exec command failed: Process exited with status 1
15:00:35 [EROR] [init.go:130] [10.60.1.97:22]kubernetes install is error.please clean and uninstall.

**你看到的一些参考资料**
eg. 文档的引用xxxx

我的sealos版本为3.38.
CentOS Linux release 7.2.1511 (Core)
Linux version 3.10.0-327.el7.x86_64 

https://github.com/fanux/sealos/issues/394#issuecomment-656291614 这里说到修改文件系统为ext4，但是我这里是生产环境，无法轻易格式化，请问还有别的办法吗？

**Comment by fanux** [comment]
docker存储驱动改成overlay2

**Comment by htfhxx** [comment]
> docker存储驱动改成overlay2

修改之后docker就启动不起来了，报错日志：

[root@k8snode2 ~]# systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

[root@k8snode2 ~]# systemctl status docker.service -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2020-11-16 15:53:46 CST; 6s ago
     Docs: https://docs.docker.com
  Process: 383459 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 383459 (code=exited, status=1/FAILURE)

Nov 16 15:53:45 k8snode2 dockerd[383459]: time="2020-11-16T15:53:45.448655817+08:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
Nov 16 15:53:45 k8snode2 dockerd[383459]: time="2020-11-16T15:53:45.448700503+08:00" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
Nov 16 15:53:45 k8snode2 dockerd[383459]: time="2020-11-16T15:53:45.448717608+08:00" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Nov 16 15:53:45 k8snode2 dockerd[383459]: time="2020-11-16T15:53:45.448731982+08:00" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
Nov 16 15:53:45 k8snode2 dockerd[383459]: time="2020-11-16T15:53:45.448748492+08:00" level=warning msg="could not use snapshotter overlayfs in metadata plugin" error="/var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.overlayfs does not support d_type. If the backing filesystem is xfs, please reformat with ftype=1 to enable d_type support"
Nov 16 15:53:46 k8snode2 dockerd[383459]: failed to start daemon: error initializing graphdriver: overlay2: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior. Reformat the filesystem with ftype=1 to enable d_type support. Backing filesystems without d_type support are not supported.
Nov 16 15:53:46 k8snode2 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Nov 16 15:53:46 k8snode2 systemd[1]: Failed to start Docker Application Container Engine.
Nov 16 15:53:46 k8snode2 systemd[1]: Unit docker.service entered failed state.
Nov 16 15:53:46 k8snode2 systemd[1]: docker.service failed.



做了一些尝试都没有生效：
1. 在daemon.json中加入  "storage-opts": [  "overlay2.override_kernel_check=true"  ]
2. https://www.jianshu.com/p/93518610eea1
3. https://www.cnblogs.com/ayanmw/p/10258171.html

感谢回复~

**Comment by fanux** [comment]
-s overlay2

**Comment by htfhxx** [comment]
> -s overlay2

抱歉，没明白您的意思，，，您是说我更改为overlay2的方式（我是在/etc/docker/daemon中添加了"storage-driver": "overlay2"）有问题还是？我没找到关于-s的命令，希望能够详说一下，多谢了！~

**Comment by htfhxx** [comment]
> 我的sealos版本为3.38.
> CentOS Linux release 7.2.1511 (Core)
> Linux version 3.10.0-327.el7.x86_64
> 
> [#394 (comment)](https://github.com/fanux/sealos/issues/394#issuecomment-656291614) 这里说到修改文件系统为ext4，但是我这里是生产环境，无法轻易格式化，请问还有别的办法吗？

或者是说我的linux内核版本太低了，并不支持？求解答Orz...

**Comment by fanux** [comment]
那其它的存储驱动呢  device-mapper overlay这些都试一下   不行的话只能修改文件系统或者升级内核了

**Comment by htfhxx** [comment]
> 那其它的存储驱动呢 device-mapper overlay这些都试一下 不行的话只能修改文件系统或者升级内核了

非常感谢，我试一下

**Comment by ysicing** [comment]
我记得centos 7.2版本上docker 存储好像有坑，升级内核或者使用centos 7.6+ 🤔️
