### ISSUE TITLE
sealos安装过程对hosts的修改建议

### ISSUE THREAD

**Issue by wisheen** [fanux/sealos#533]
**哪个命令或者组件**
sealos

**描述这个缺陷**
例如ip 192.168.11.21 hostname node1
cat  cat /etc/hosts |grep node1 || echo '192.168.11.21 node1' >> /etc/hosts

如果修改了节点名称，会导致同一个ip在hosts里面出现多份

**重现步骤（如果有需要可以附加图片）**

**测试结果**

**期望结果**

**运行环境**

**修改建议**
 基于begin sealos end sealos 标记， 删除后新加，此思路来源于ansible的安装，它会维护所有节点，不会带来ip修改或者node修改维护出问题
```
sed "/^# begin sealos/,/# end sealos$/d" -i /etc/hosts

	cat >>/etc/hosts <<EOF
# begin sealos
$hostIp	$hostname
# end sealos
EOF
```

**Comment by oldthreefeng** [comment]
安装完成后， 不建议修改主机名

**Comment by wisheen** [comment]
能程序解决并代价有限的就不要对客户做要求

**Comment by wisheen** [comment]
不是安装完后修改，而是安装完毕后，clean之后修改了安装
安装后修改，这个没必要下支持也无法支持。

**Comment by oldthreefeng** [comment]
> 不是安装完后修改，而是安装完毕后，clean之后修改了安装

我记得有个删除的动作。 clean 节点， 有删除 host解析的。
