### ISSUE TITLE
centos 7.4下 sealos clean后再次join失败

### ISSUE THREAD

**Issue by kingslary** [fanux/sealos#534]
**哪个命令或者组件**
sealos join --master

**描述这个缺陷**
目的是为了添加一个master2节点，但是只有在刚装完系统的时候第一次join才会成功，之后如果clean再join就报错“error execution phase control-plane-prepare/kubeconfig: error generating kubeconfig files: a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has got the wrong API Server URL”

**重现步骤（如果有需要可以附加图片）**
1. kubectl get nodes 确定已经有1个master节点和2个node节点
·
NAME         STATUS     ROLES    AGE     VERSION
k8s-master   Ready      master   3d18h   v1.19.1
k8s-node1    Ready      <none>   3d18h   v1.19.1
k8s-node2    Ready      <none>   3d18h   v1.19.1
·
2.  sealos join --master 192.168.220.136   添加第2个master节点，且该节点是新装机器，仅设置过ip和hostname（k8s-master2）
这次添加能够成功，是没问题的，但是下面开始就不行了。

3. sealos clean --master 192.168.220.136 清理
4. sealos join --master 192.168.220.136  尝试再次添加，就报错了。

13:58:30 [INFO] [ssh.go:51] [192.168.220.136:22] [kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
13:58:30 [INFO] [ssh.go:51] [192.168.220.136:22] error execution phase control-plane-prepare/kubeconfig: error generating kubeconfig files: a kubeconfig file "/etc/kubernetes/controller-manager.conf" exists already but has got the wrong API Server URL
13:58:30 [INFO] [ssh.go:51] [192.168.220.136:22] To see the stack trace of this error execute with --v=5 or higher

**运行环境**

[root@k8s-master ~]# sealos version
sealos version latest, build  go1.15.2, Build Time : 
sealos current latest version is v3.3.9-goreleaser

[root@k8s-master ~]# uname -r
3.10.0-862.el7.x86_64

系统 CentOS  7.4 64位
使用的是sealyun官网的v1.19.1安装包

**Comment by oldthreefeng** [comment]
#462  还是这个问题。 我看看有什么疏漏没有

**Comment by kingslary** [comment]
> 
> 
> #462 还是这个问题。 我看看有什么疏漏没有

刚刚我在本地搭建了centos7.5环境，这次直接第一次sealos join 就失败了。没等到我先clean后join。

**Comment by oldthreefeng** [comment]
> 刚刚我在本地搭建了centos7.5环境，这次直接第一次sealos join 就失败了。没等到我先clean后join。

建议先使用 1.19.3 或者1.19.4 。 

1.19.1/1.19.2 join的确有点问题 ， 我这边看看为什么。
