### ISSUE TITLE
问题: 官网改版后，我的会员不能登录了

### ISSUE THREAD

**Issue by liutao841204** [fanux/sealos#536]
hi，我的账号（liutao841204）不能登录了
![截屏2020-11-19 下午12 16 31](https://user-images.githubusercontent.com/24605302/100056838-505e6100-2e61-11eb-8696-afa8816ad97b.png)
![截屏2020-11-19 下午12 17 28](https://user-images.githubusercontent.com/24605302/100056867-57856f00-2e61-11eb-9213-2ee508c4e964.png)

**Comment by oldthreefeng** [comment]
这个是github被强了？？？ 感觉是网络问题

**Comment by liutao841204** [comment]
> 这个是github被强了？？？ 感觉是网络问题
这个已经是在github登录了，并且返回到sealos官网了。另外我用我的阿里云主机登录，也是一样的结果，看起来不像是被墙。

**Comment by oldthreefeng** [comment]
@cuisongliu  看一看吧。  
@liutao841204  可以试试翻墙是否能访问？

**Comment by liutao841204** [comment]
> @cuisongliu 看一看吧。
> @liutao841204 可以试试翻墙是否能访问？

好，我去我同事那看看，他有翻墙

**Comment by liutao841204** [comment]
> > @cuisongliu 看一看吧。
> > @liutao841204 可以试试翻墙是否能访问？
> 
> 好，我去我同事那看看，他有翻墙

翻墙也是不行的，同样的问题

**Comment by oldthreefeng** [comment]
> 翻墙也是不行的，同样的问题

已经在看了， 稍等~

**Comment by liutao841204** [comment]
> > 翻墙也是不行的，同样的问题
> 
> 已经在看了， 稍等~

好的

**Comment by oldthreefeng** [comment]
@liutao841204  已经修复了~~

**Comment by liutao841204** [comment]
> @liutao841204 已经修复了~~

能登录，但会员的期限不对，还是不能下载
![企业微信截图_301f8e92-39c3-4a07-8188-9928a3b0f68f](https://user-images.githubusercontent.com/24605302/100065677-0e3c1c00-2e6f-11eb-8472-899bc7a51eb5.png)

**Comment by oldthreefeng** [comment]
上面显示是 10.17号会员过期。

**Comment by liutao841204** [comment]
好的，我看到我的缴费记录了，是去年交的。我续个费用

**Comment by dlscodes** [comment]
@liutao841204 请问还有vip可以购买么
