### ISSUE TITLE
问题: sealos安装时需要主机的密码规则

### ISSUE THREAD

**Issue by liutao841204** [fanux/sealos#552]
我在使用sealos安装时，使用密码OnlineService@Chzu&*!，进行安装时，报错。能问下sealos
的密码规则有什么特殊需求吗？

**Comment by liutao841204** [comment]
错误内容，就是不能连接到服务器！

**Comment by oldthreefeng** [comment]
带上引号引起来

**Comment by liutao841204** [comment]
> 带上引号引起来

是这个样子，是吧？--passwd '123456'

**Comment by liutao841204** [comment]
> > 带上引号引起来
> 
> 是这个样子，是吧？--passwd '123456'

对sealos的版本有要求吗？

**Comment by oldthreefeng** [comment]
没有， 建议下载latest版本进行安装部署

**Comment by liutao841204** [comment]
> 没有， 建议下载latest版本进行安装部署

好的，谢谢啊！
