### ISSUE TITLE
我确定我使用的是root 权限，却爆出了 Permission denied错误

### ISSUE THREAD

**Issue by Suaron-Biliu** [fanux/sealos#553]
22:27:52 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] hostname
22:27:54 [EROR] [ssh.go:17] [ssh][192.168.51.181:22]Error create ssh session failed,ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
22:27:54 [EROR] [check.go:40] [192.168.51.181:22] ------------ check error
root@master-01:~$ sealos join  --node 192.168.51.181
22:28:46 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] hostname
22:28:46 [DEBG] [ssh.go:25] [ssh][192.168.51.181:22]command result is: node-01

22:28:46 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] cat /etc/hosts |grep node-01 || echo '192.168.51.181 node-01' >> /etc/hosts
22:28:47 [INFO] [ssh.go:51] [192.168.51.181:22] 192.168.51.181 node-01
22:28:47 [INFO] [check.go:50] [192.168.51.181:22]  ------------ check ok
22:28:47 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] mkdir -p /usr/bin || true
22:28:48 [DEBG] [download.go:30] [192.168.51.181:22]please wait for mkDstDir
22:28:48 [DEBG] [download.go:32] [192.168.51.181:22]please wait for before hook
22:28:48 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] ps -ef |grep -v 'grep'|grep sealos >/dev/null || rm -rf /usr/bin/sealos
22:28:48 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] ls -l /usr/bin/sealos 2>/dev/null |wc -l
22:28:49 [DEBG] [ssh.go:25] [ssh][192.168.51.181:22]command result is: 0

22:28:49 [DEBG] [scp.go:27] [ssh]source file md5 value is 7546574c469ef7c2e80eaf56e11edae3
22:28:54 [INFO] [scp.go:101] [ssh][192.168.51.181:22]transfer total size is: 47.48MB ;speed is 47MB
22:28:54 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] md5sum /usr/bin/sealos | cut -d" " -f1
22:28:55 [DEBG] [ssh.go:25] [ssh][192.168.51.181:22]command result is: /root/.bashrc: line 15: /usr/bin/sealos: Permission denied
7546574c469ef7c2e80eaf56e11edae3

22:28:55 [DEBG] [scp.go:30] [ssh]host: 192.168.51.181:22 , remote md5: /root/.bashrc: line 15: /usr/bin/sealos: Permission denied7546574c469ef7c2e80eaf56e11edae3
22:28:55 [EROR] [scp.go:37] [ssh]md5 validate false
22:28:55 [EROR] [download.go:52] [192.168.51.181:22]copy file md5 validate failed
22:28:55 [DEBG] [download.go:56] [192.168.51.181:22]please wait for after hook
22:28:55 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] chmod a+x /usr/bin/sealos
22:28:56 [INFO] [ssh.go:51] [192.168.51.181:22] /root/.bashrc: line 15: /usr/bin/sealos: Permission denied
22:28:57 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] mkdir -p /root || true
22:28:57 [DEBG] [download.go:30] [192.168.51.181:22]please wait for mkDstDir
22:28:57 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] ls -l /root/kube1.19.5.tar.gz 2>/dev/null |wc -l
22:28:58 [DEBG] [ssh.go:25] [ssh][192.168.51.181:22]command result is: 1

22:28:59 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] md5sum /root/kube1.19.5.tar.gz | cut -d" " -f1
22:29:02 [DEBG] [ssh.go:25] [ssh][192.168.51.181:22]command result is: ca41f7b7132bf2ffe5085416ad4b9efd

22:29:02 [INFO] [download.go:37] [192.168.51.181:22]SendPackage:  /root/kube1.19.5.tar.gz file is exist and ValidateMd5 success
22:29:02 [DEBG] [download.go:56] [192.168.51.181:22]please wait for after hook
22:29:02 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] cd /root && rm -rf kube && tar zxvf kube1.19.5.tar.gz  && cd /root/kube/shell && rm -f ../bin/sealos && sh init.sh && sed -i '/kubectl/d;/sealos/d' /root/.bashrc  && echo 'command -v kubectl &>/dev/null && source <(kubectl completion bash)' >> /root/.bashrc && echo 'command -v sealos &>/dev/null && source <(sealos completion bash)' >> /root/.bashrc && source /root/.bashrc
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/shell/
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/shell/init.sh
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/shell/master.sh
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/shell/docker.sh
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/README.md
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/bin/
22:29:02 [INFO] [ssh.go:51] [192.168.51.181:22] kube/bin/kubelet
22:29:06 [INFO] [ssh.go:51] [192.168.51.181:22] kube/bin/kubectl
22:29:07 [INFO] [ssh.go:51] [192.168.51.181:22] kube/bin/crictl
22:29:08 [INFO] [ssh.go:51] [192.168.51.181:22] kube/bin/conntrack
22:29:08 [INFO] [ssh.go:51] [192.168.51.181:22] kube/bin/kubeadm
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/bin/kubelet-pre-start.sh
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/docker.service
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/kubeadm.yaml
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/kubelet.service
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/calico.yaml
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/10-kubeadm.conf
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/net/
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/conf/net/calico.yaml
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/docker/
22:29:09 [INFO] [ssh.go:51] [192.168.51.181:22] kube/docker/docker.tgz
22:29:11 [INFO] [ssh.go:51] [192.168.51.181:22] kube/docker/README.md
22:29:11 [INFO] [ssh.go:51] [192.168.51.181:22] kube/images/
22:29:11 [INFO] [ssh.go:51] [192.168.51.181:22] kube/images/images.tar
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] kube/images/README.md
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] + storage=/var/lib/docker
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] + harbor_ip=127.0.0.1
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] + mkdir -p /var/lib/docker
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] + command_exists docker
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] + command -v docker
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] + docker info
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] Client:
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22]  Debug Mode: false
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] 
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] Server:
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] errors pretty printing info
22:29:48 [INFO] [ssh.go:51] [192.168.51.181:22] + systemctl restart docker.service
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] * Applying /usr/lib/sysctl.d/00-system.conf ...
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.bridge.bridge-nf-call-ip6tables = 0
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.bridge.bridge-nf-call-iptables = 0
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.bridge.bridge-nf-call-arptables = 0
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] * Applying /usr/lib/sysctl.d/50-default.conf ...
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] kernel.sysrq = 16
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] kernel.core_uses_pid = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] kernel.kptr_restrict = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.ipv4.conf.default.rp_filter = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.ipv4.conf.all.rp_filter = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.ipv4.conf.default.accept_source_route = 0
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.ipv4.conf.all.accept_source_route = 0
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.ipv4.conf.default.promote_secondaries = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.ipv4.conf.all.promote_secondaries = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] fs.protected_hardlinks = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] fs.protected_symlinks = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] * Applying /etc/sysctl.d/99-sysctl.conf ...
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] * Applying /etc/sysctl.d/k8s.conf ...
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.bridge.bridge-nf-call-ip6tables = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.bridge.bridge-nf-call-iptables = 1
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] * Applying /etc/sysctl.conf ...
22:30:04 [INFO] [ssh.go:51] [192.168.51.181:22] net.ipv4.ip_forward = 1
22:30:05 [INFO] [ssh.go:51] [192.168.51.181:22] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
22:31:33 [INFO] [ssh.go:51] [192.168.51.181:22] errors pretty printing info
22:31:33 [INFO] [ssh.go:51] [192.168.51.181:22] driver is 
22:31:33 [INFO] [ssh.go:13] [ssh][192.168.51.178:22] kubeadm token create --print-join-command -v 0
22:31:39 [DEBG] [ssh.go:25] [ssh][192.168.51.178:22]command result is: W1217 22:31:39.377367    7280 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
kubeadm join apiserver.cluster.local:6443 --token ww1mu9.r1wiuptwk8pfu3h9     --discovery-token-ca-cert-hash sha256:bd706588835162452c7a800767d5280a17acae14ae2ffca5078aff2f4639a969 

22:31:39 [DEBG] [sealos.go:84] [globals]decodeOutput: W1217 22:31:39.377367    7280 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
kubeadm join apiserver.cluster.local:6443 --token ww1mu9.r1wiuptwk8pfu3h9     --discovery-token-ca-cert-hash sha256:bd706588835162452c7a800767d5280a17acae14ae2ffca5078aff2f4639a969 

22:31:39 [INFO] [sealos.go:87] [globals]join command is:  apiserver.cluster.local:6443 --token ww1mu9.r1wiuptwk8pfu3h9     --discovery-token-ca-cert-hash sha256:bd706588835162452c7a800767d5280a17acae14ae2ffca5078aff2f4639a969 

22:31:39 [DEBG] [sealos.go:93] [globals]decodeJoinCmd:  apiserver.cluster.local:6443 --token ww1mu9.r1wiuptwk8pfu3h9     --discovery-token-ca-cert-hash sha256:bd706588835162452c7a800767d5280a17acae14ae2ffca5078aff2f4639a969 

22:31:39 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] echo 10.103.97.2 apiserver.cluster.local >> /etc/hosts
22:31:46 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] sealos route --host 192.168.51.181
22:31:47 [DEBG] [ssh.go:25] [ssh][192.168.51.181:22]command result is: ok

22:31:47 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] sealos ipvs --vs 10.103.97.2:6443  --rs 192.168.51.178:6443 --rs 192.168.51.179:6443 --health-path /healthz --health-schem https --run-once
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [WARN] [service.go:119] IsVirtualServerAvailable warn: virtual server is empty.
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 10.103.97.2, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 10.103.97.2, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [WARN] [service.go:55] CreateVirtualServer error:  file exists
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 192.168.51.178, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 192.168.51.178, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 10.103.97.2, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [EROR] [service.go:94] CreateRealServer error:  file exists
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 192.168.51.179, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 192.168.51.179, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [DEBG] [utils.go:21] SplitServer debug: IP: 10.103.97.2, Port: 6443
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [EROR] [service.go:94] CreateRealServer error:  file exists
22:31:48 [INFO] [ssh.go:51] [192.168.51.181:22] 22:31:47 [WARN] [create.go:31] createVsAndRs error: [new virtual server failed: file exists new real server failed: file exists new real server failed: file exists]
22:31:48 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] kubeadm join 10.103.97.2:6443 --token ww1mu9.r1wiuptwk8pfu3h9 --discovery-token-ca-cert-hash sha256:bd706588835162452c7a800767d5280a17acae14ae2ffca5078aff2f4639a969 -v 0
22:31:49 [INFO] [ssh.go:51] [192.168.51.181:22] [preflight] Running pre-flight checks
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22]         [WARNING FileExisting-socat]: socat not found in system path
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] [preflight] The system verification failed. Printing the output from the verification:
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] KERNEL_VERSION: 5.10.1-1.el7.elrepo.x86_64
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_NAMESPACES: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_NET_NS: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_PID_NS: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_IPC_NS: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_UTS_NS: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_CGROUPS: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_CGROUP_CPUACCT: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_CGROUP_DEVICE: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_CGROUP_FREEZER: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_CGROUP_SCHED: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_CPUSETS: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_MEMCG: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_INET: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_EXT4_FS: enabled (as module)
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_PROC_FS: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_OVERLAY_FS: enabled (as module)
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_AUFS_FS: not set - Required for aufs.
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CONFIG_BLK_DEV_DM: enabled (as module)
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] OS: Linux
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_CPU: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_CPUACCT: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_CPUSET: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_DEVICES: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_FREEZER: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_MEMORY: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_HUGETLB: enabled
22:31:50 [INFO] [ssh.go:51] [192.168.51.181:22] CGROUPS_PIDS: enabled
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] error execution phase preflight: [preflight] Some fatal errors occurred:
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22]         [ERROR DirAvailable--etc-kubernetes-manifests]: /etc/kubernetes/manifests is not empty
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22]         [ERROR CRI]: container runtime is not running: output: Client:
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22]  Debug Mode: false
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] 
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] Server:
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] errors pretty printing info
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] , error: exit status 1
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22]         [ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22]         [ERROR IsDockerSystemdCheck]: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22]         [ERROR SystemVerification]: error verifying Docker info: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
22:31:52 [INFO] [ssh.go:51] [192.168.51.181:22] To see the stack trace of this error execute with --v=5 or higher
22:31:52 [INFO] [ssh.go:13] [ssh][192.168.51.181:22] mkdir -p /etc/kubernetes/manifests
22:31:53 [DEBG] [ssh.go:25] [ssh][192.168.51.181:22]command result is: 
22:31:54 [INFO] [scp.go:159] [ssh][192.168.51.181:22]transfer total size is: 0MB
22:31:54 [INFO] [ssh.go:58] [ssh][192.168.51.181:22] rm -rf /root/kube
root@master-01:~$ kubectl get node

**Comment by oldthreefeng** [comment]
请按issue格式， 至少能让我复现这个问题

**Comment by G-Akiraka** [comment]
系统问题，重新装就好了😁
