### ISSUE TITLE
新部署集群1.18.13, 节点notready, lvscare输出大量日志，parseIP Error ip=[10 201 2 161 0 0 0 0 0 0 0 0 0 0 0 0]

### ISSUE THREAD

**Issue by ziyouguodu** [fanux/sealos#563]
环境：华为云
系统： Centos 7.9； k8s版本 1.18.13 ； calico 网络

问题：

集群kubelet 不知道什么问题导致集群网络有问题，服务无法正常暴露； kubelet的报错信息：

![image](https://user-images.githubusercontent.com/11712435/102857170-e7b7d380-4462-11eb-95dd-41ec5bc4812f.png)

排查：

1、 集群网络通信是正常的，安全组全部开放的

2、master 和node 分别kubectl  都能正常获取信息

3、防火墙和selinux关闭状态

**Comment by zhangguanzhang** [comment]
看下默认路由网卡的mtu和calico的tunl0的mtu

**Comment by ziyouguodu** [comment]
eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000


tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000

**Comment by zhangguanzhang** [comment]
看看lvscare的日志

**Comment by ziyouguodu** [comment]
现在kubectl  exec  到pods会报这个错：

![image](https://user-images.githubusercontent.com/11712435/102865541-dc6ba480-4470-11eb-8c9d-d9580b254ab6.png)

lvscare 节点日志：GG，这中奕的锅

![image](https://user-images.githubusercontent.com/11712435/102865653-0f159d00-4471-11eb-90b6-a5ecc1b69d9e.png)

**Comment by oldthreefeng** [comment]
怎么感觉是低内核的锅 ....

**Comment by ziyouguodu** [comment]
CentOS Linux 7.9 (Core)   3.10.0-1160.6.1.el7.x86_64   docker://19.3.12

**Comment by ziyouguodu** [comment]
可以确定是lvscare ipvs转发问题：所有节点都是这样


17:20:34 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.162;  6443; parseIP Error ip=[10 201 2 161 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:39 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.160;  6443; parseIP Error ip=[10 201 2 162 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:39 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.161;  6443; parseIP Error ip=[10 201 2 160 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:39 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.162;  6443; parseIP Error ip=[10 201 2 161 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:44 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.160;  6443; parseIP Error ip=[10 201 2 162 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:44 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.161;  6443; parseIP Error ip=[10 201 2 160 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:44 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.162;  6443; parseIP Error ip=[10 201 2 161 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:49 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.160;  6443; parseIP Error ip=[10 201 2 162 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:49 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.161;  6443; parseIP Error ip=[10 201 2 160 0 0 0 0 0 0 0 0 0 0 0 0] ^C
17:20:49 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.162;  6443; parseIP Error ip=[10 201 2 161 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:54 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.160;  6443; parseIP Error ip=[10 201 2 162 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:54 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.161;  6443; parseIP Error ip=[10 201 2 160 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:54 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.162;  6443; parseIP Error ip=[10 201 2 161 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:59 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.160;  6443; parseIP Error ip=[10 201 2 162 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:59 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.161;  6443; parseIP Error ip=[10 201 2 160 0 0 0 0 0 0 0 0 0 0 0 0]
17:20:59 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.162;  6443; parseIP Error ip=[10 201 2 161 0 0 0 0 0 0 0 0 0 0 0 0]
17:21:04 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.160;  6443; parseIP Error ip=[10 201 2 162 0 0 0 0 0 0 0 0 0 0 0 0]
17:21:04 [EROR] [service.go:175] GetRealServer error[get real server failed]: 10.201.2.161;  6443; parseIP Error ip=[10 201 2 160 0 0 0 0 0 0 0 0 0 0 0 0]

**Comment by oldthreefeng** [comment]
受影响的版本: 
1.17.16/1.17.15/1.18.13/1.18.14/1.19.5/1.19.6/1.20.0/1.20.1
解决方案1:
手动在node节点执行
docker版本
```
mv /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml  . 
docker rmi $(docker images | grep "none" | awk '{print $3}')
docker pull fanux/lvscare  
mv kube-sealyun-lvscare.yaml /etc/kubernetes/manifests/
```
containerd版本 
```
mv /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml  . 
ctr -n=k8s.io image pull docker.io/fanux/lvscare:latest
mv kube-sealyun-lvscare.yaml /etc/kubernetes/manifests/
```
解决方案2:
重新下载我们的tar包, 重新安装即可解决.

**Comment by ziyouguodu** [comment]
官网是否已经替换最新包？

**Comment by ziyouguodu** [comment]
我已升级内核版本5.10解决

**Comment by oldthreefeng** [comment]
@ziyouguodu  稍等, 打包完成会进行一波测试,  发布完成后, 我这边会关闭issue

**Comment by oldthreefeng** [comment]
这个bug 是 与低版本的内核不兼容, 建议使用docker pull 更新镜像更稳妥.

**Comment by ziyouguodu** [comment]
那我在init 初始化节点的包替换掉就行了？

**Comment by oldthreefeng** [comment]
替换后 , 重新部署了.

**Comment by ziyouguodu** [comment]
也就说要重新初始化才行是吧

**Comment by oldthreefeng** [comment]
是的, 主要是要替换 fanux/lvscare的latest 镜像即可.

**Comment by ziyouguodu** [comment]
那也就是说必须重置整个集群，重新做一次初始化是吧  ^^…………

**Comment by oldthreefeng** [comment]
fix

**Comment by zhangguanzhang** [comment]
可以直接去改/etc/kubernetes/manifests/里的lvscare.yml里的文件镜像的，不需要重装

**Comment by ziyouguodu** [comment]
> 可以直接去改/etc/kubernetes/manifests/里的lvscare.yml里的文件镜像的，不需要重装

我是初始化过了哦，直接替换新包就行了吗？再join节点不会有问题吗

**Comment by oldthreefeng** [comment]
> 我是初始化过了哦，直接替换新包就行了吗？再join节点不会有问题吗

替换包不是解决方案. 如果已经部署了, 替换镜像即可.  @ziyouguodu 
```
## 停止lvscare
mv /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml  . 
docker rmi $(docker images | grep "none" | awk '{print $3}')

## 这个是tar包里面的新镜像.
docker load -i image.tar
## 或者执行
docker pull fanux/lvscare 

##  最后还原
mv kube-sealyun-lvscare.yaml /etc/kubernetes/manifests/
```

**Comment by ziyouguodu** [comment]
我是说做初始的那台机器，是不是替换包就行，后面join进来新节点

**Comment by oldthreefeng** [comment]
后面join 用新包即可.
