### ISSUE TITLE
缺陷: 删除master后需要对kube-sealyun-lvscare.yaml维护

### ISSUE THREAD

**Issue by wisheen** [fanux/sealos#566]
**哪个命令或者组件**
sealos clean

**描述这个缺陷**
删除master后，节点上的 /etc/kubernetes/manifests/kube-sealyun-lvscare.yaml 没有移除对应的master，导致有大量的6443访问的异常日志

**运行环境**

- Docker版本:   19.03
- Kubernetes版本 : kube1.18.12.tar.gz
- sealos版本: v3.3.9-alpha.2
- 操作系统:  ubuntu 18.0.4
- 运行模式:  虚拟机
- 集群规模:   3master 3node

**Comment by oldthreefeng** [comment]
这个好像已经写了. .. 
https://github.com/fanux/sealos/blob/a2d6a06e9f981f1c359d557d4ce124f1193b37a5/install/clean.go#L140-L149

**Comment by oldthreefeng** [comment]
已经实现

**Comment by oldthreefeng** [comment]
这个需求应该是: 

使用 `sealos clean  --node  ` 不小心写了` masterip`.  
或者` sealos clean  --master `不小心写了 `nodeip`. 

sealos 给出提示或者直接退出 .

**Comment by hmrg-grmh** [comment]
> 这个需求应该是:
> 
> 使用 `sealos clean --node ` 不小心写了` masterip`.
> 或者`sealos clean --master`不小心写了 `nodeip`.
> 
> sealos 给出提示或者直接退出 .

猜对了！果然是用来限制的。

（话说我个人这里其实不急这个。只要小心点就能主动避免，甚至还可以把它当成一种特性让一个节点不能被删除（实际应该不会这么用就是了....））
