### ISSUE TITLE
虚拟机安装，出现错误

### ISSUE THREAD

**Issue by z5614036** [fanux/sealos#573]
我从 192.168.10.155 ping  192.168.10.166， 192.168.10.166是node节点，每次安装都这样 1.17.9版本的k8s
我是虚拟机

From 192.168.10.155 icmp_seq=1 Destination Host Unreachable
From 192.168.10.155 icmp_seq=2 Destination Host Unreachable
From 192.168.10.155 icmp_seq=3 Destination Host Unreachable
From 192.168.10.155 icmp_seq=4 Destination Host Unreachable
From 192.168.10.155 icmp_seq=5 Destination Host Unreachable

**Comment by oldthreefeng** [comment]
安装k8s要求网络通。

**Comment by z5614036** [comment]
安装之前网络没问题的是可以ping通的

**Comment by z5614036** [comment]
用的是桥接模式

**Comment by oldthreefeng** [comment]
使用NAT试试。 我这边用NAT跑了无数次。

**Comment by zhangguanzhang** [comment]
能远程吗

**Comment by z5614036** [comment]
可以远程

**Comment by zhangguanzhang** [comment]
你在哪个微信群里

**Comment by z5614036** [comment]
云原生与sealyun

**Comment by zhangguanzhang** [comment]
具体哪个群，有好几个群，或者你艾特下我吧
