### ISSUE TITLE
calico的 CustomResourceDefinition 需要同步升级至 apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by oldthreefeng** [fanux/sealos#576]
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition

**哪个命令或者组件**
网络组件

**详细描述你的需求/任务**

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
1.16+ 使用`apiextensions.k8s.io/v1`的配置文件即可.

**Comment by fanux** [comment]
是不是可以考虑直接升级calico

**Comment by oldthreefeng** [comment]
我以前写过一版. 直接把yaml 写到最新.  .

**Comment by oldthreefeng** [comment]
这个放在 1.21+ 全部换吧, 不然也不好控制版本.

**Comment by fanux** [comment]
我们tar是啥镜像不是根据yaml来的嘛。 打包是先起了一个集群然后在集群上save镜像的啊

**Comment by oldthreefeng** [comment]
是的， 但是你save镜像的版本号是在文件写好的， 所以和sealos还得匹配上， 这就很难办....

**Comment by oldthreefeng** [comment]
fixed by #657
