### ISSUE TITLE
networkManger导致calico网卡一直无法生成, 结果pod之间无法访问.

### ISSUE THREAD

**Issue by zzlingyun** [fanux/sealos#579]
**那个命令或者组件**
eg. sealos init , sealos install , kubernetes cni, docker  and so on 
Centos7.9  内核4.4  
环境是内网环境，根据我的此时这几台机器之间tcp和udp端口都是互通的，防火墙已关闭
[root@master1 user1]# kubectl get nodes
NAME        STATUS   ROLES    AGE     VERSION
bigdata01   Ready    <none>   2d12h   v1.18.13
bigdata02   Ready    <none>   2d12h   v1.18.13
bigdata03   Ready    <none>   2d12h   v1.18.13
master1     Ready    master   2d15h   v1.18.13
node1       Ready    <none>   2d15h   v1.18.13
node2       Ready    <none>   2d15h   v1.18.13

**描述你的问题**
安装命令
sealos init  --mtu 1350 --master 10.165.10.XXX:6122  --master 10.165.10.XXX:6122  --master 10.165.10.xxx:6122 --node 10.165.10.XXX:6122 --node 10.165.10.xxx:6122 --node 10.165.10.XXX:6122 --pkg-url /root/kube1.18.13.tar.gz --version v1.18.13
安装完成后 发现集群问题就把master2 master3 踢出了集群，使用命令sealos clean --master

dns的pod ip 在每个节点都ping不通

**你看到的一些参考资料**
eg. 文档的引用xxxx

**Comment by zzlingyun** [comment]
我发现有的node节点有
![image](https://user-images.githubusercontent.com/46774973/104145850-95cff100-5403-11eb-8c94-725e3df20cbc.png)
网卡，有的node节点没有
![image](https://user-images.githubusercontent.com/46774973/104145891-b0a26580-5403-11eb-8506-81bc9089ea41.png)
就是说有的节点没有calif3006077e93@if4相关的几个网卡

**Comment by oldthreefeng** [comment]
@zhangguanzhang    有空看看么?  很奇怪的是calico网卡都没有生成.

**Comment by oldthreefeng** [comment]
主要是 networkManger导致的. 
如果需要使用 networkManger, 需要修改这个文件 ` /etc/NetworkManager/conf.d/calico.conf`

> Configure NetworkManager before attempting to use Calico networking.
>NetworkManager manipulates the routing table for interfaces in the default network namespace where Calico veth pairs are  anchored for connections to containers. This can interfere with the Calico agent’s ability to route correctly.
> Create the following configuration file at /etc/NetworkManager/conf.d/calico.conf to prevent NetworkManager from interfering with the interfaces:

```
[keyfile]
unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico
```

另外, 一版在本地或者在云上, 这个服务都没有.  建议禁止掉. 
```
$ systemctl stop networkManger && systemctl disable networkManger
```
