### ISSUE TITLE
Please don’t spam

### ISSUE THREAD

**Issue by fpg1503** [fanux/sealos#58]
Hi! I just got spammed in the email on my profile! That’s not nice, please don’t spam people (specially those who specifically opted-out from spam).

**Comment by fanux** [comment]
Sorry, my fault...

**Comment by tonious** [comment]
Seriously.  Not nice.

**Comment by fanux** [comment]
@tonious I am really sorry about this, our program bug caused this problem, I promise that it  will not happen again...

**Comment by dehli** [comment]
This "bug" still exists because I was just spammed.
