### ISSUE TITLE
安装1.19.5版本 部分节点有些pods 加载镜像失败 ImagePullBackOff

### ISSUE THREAD

**Issue by JDshi** [fanux/sealos#590]
最新版的sealos sealos init  安装1.19.5版本，部分节点有些pods加载镜像失败

calico-node-n4l65                          0/1     Init:ImagePullBackOff
kube-proxy-6f8zt                           0/1     ImagePullBackOff

执行docker images
发现机器上没有这两个镜像

为什么会出现镜像加载失败呢

**Comment by oldthreefeng** [comment]
**哪个命令或者组件**
eg. sealos init,install ...

**描述这个缺陷**
简短描述这个缺陷内容.

**重现步骤（如果有需要可以附加图片）**
1. 
...


**测试结果**
1. 
2. 
3.

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   eg 3master 3node
- 附加说明: istio,dashboard ...

**Comment by zhangguanzhang** [comment]
看下node节点的根分区容量

**Comment by JDshi** [comment]
> 看下node节点的根分区容量

还有70多G的空间可以用

**Comment by oldthreefeng** [comment]
修改 `/var/lib/kubelet/config.yaml` 添加以下参数。 自定义修改即可。 
```
evictionHard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
```
