### ISSUE TITLE
安装k8s时docker启动失败

### ISSUE THREAD

**Issue by zhoachenIt** [fanux/sealos#597]
**执行如下命令进行安装**
sealos init --master 192.168.28.160 \
    --node 192.168.28.161 \
	--node 192.168.28.162 \
    --user root \
    --passwd root \
    --version v1.18.15 \
    --pkg-url kube1.18.15.tar.gz

**错误日志**
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] error execution phase preflight: [preflight] Some fatal errors occurred:
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] 	[ERROR CRI]: container runtime is not running: output: Client:
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22]  Debug Mode: false
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] 
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] Server:
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] errors pretty printing info
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] , error: exit status 1
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] 	[ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] 	[ERROR IsDockerSystemdCheck]: cannot execute 'docker info -f {{.CgroupDriver}}': exit status 2
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] 	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] 	[ERROR SystemVerification]: error verifying Docker info: "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
17:30:23 [INFO] [ssh.go:51] [192.168.28.141:22] [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

**Comment by zhangguanzhang** [comment]
journalctl -xe -u docker

**Comment by zhoachenIt** [comment]
@zhangguanzhang ***journalctl -xe -u docker   日志如下***
Unit docker.service has begun starting up.
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.250419919+08:00" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.308718351+08:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.311494325+08:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.312166766+08:00" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.312175647+08:00" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.312180501+08:00" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
2月 18 12:21:41 master systemd[1]: Started Docker Application Container Engine.
-- Subject: Unit docker.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished starting up.
-- 
-- The start-up result is done.

**Comment by zhoachenIt** [comment]
@zhangguanzhang  journalctl -xe -u docker 日志如下

-- Logs begin at 四 2021-02-18 12:16:27 CST, end at 四 2021-02-18 12:23:40 CST. --
2月 18 12:21:24 master systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.250419919+08:00" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.308718351+08:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.311494325+08:00" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.312166766+08:00" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.312175647+08:00" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
2月 18 12:21:28 master dockerd[19210]: time="2021-02-18T12:21:28.312180501+08:00" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found.\n": exit status 1"
2月 18 12:21:41 master systemd[1]: Started Docker Application Container Engine.
-- Subject: Unit docker.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has finished starting up.
-- 
-- The start-up result is done.
~

**Comment by zhangguanzhang** [comment]
看下docker的配置文件
```
cat /etc/docker/daemon.json
```

**Comment by zhoachenIt** [comment]
@zhangguanzhang  cat /etc/docker/daemon.json
 [root@localhost home]# cat /etc/docker/daemon.json 
{
  "registry-mirrors": [
     "https://bxsfpjcb.mirror.aliyuncs.com"
  ],
  "max-concurrent-downloads": 10,
  "log-driver": "json-file",
  "log-level": "warn",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
    },
  "insecure-registries":
        ["127.0.0.1"],
  "data-root":"/var/lib/docker"
}

**Comment by zhangguanzhang** [comment]
设置下用overlay2存储
