### ISSUE TITLE
No routes specified in CNI configuration

### ISSUE THREAD

**Issue by mxfj** [fanux/sealos#6]
Sep  6 15:15:44 k8s-master01 kubelet: 2018-09-06 15:15:44.205 [DEBUG][36642] k8s.go 146: No routes specified in CNI configuration, using defaults. ContainerID="e328bffaba8ccb55081da90ce73f0f0d5844c1e1f1ba2748dabf23c331965d6e" Namespace="kube-system" Pod="heapster-55884f49b6-d86xx" WorkloadEndpoint="k8s--master01\n-k8s-heapster--55884f49b6--d86xx-eth0"

**Comment by fanux** [comment]
add default route may solve this
