### ISSUE TITLE
k8s1.14.1重启节点，导致该节点无法自动加入集群

### ISSUE THREAD

**Issue by liudd99** [fanux/sealos#60]
系统：centos7.5 
内核版本:5.0
docker版本：18.06.1-ce
利用sealos init搭建好k8s集群后，手动重启其中一个节点，该节点无法自动加入集群。
systemctl status其中kubelet、docker、显示是running状态。
但lsmod ip_vs，则没有运行，输出为空。
即便手动modprobe ip_vs，同时重启docker、kubelet等，任然无法使该节点加入原有集群。

**Comment by fanux** [comment]
1. 初始化，最好设置成开机启动：
```
modprobe -- ip_vs
modprobe -- ip_vs_rr
modprobe -- ip_vs_wrr
modprobe -- ip_vs_sh
modprobe -- nf_conntrack_ipv4

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system
sysctl -w net.ipv4.ip_forward=1
systemctl stop firewalld && systemctl disable firewalld
swapoff -a
setenforce 0
```

2. 重启kubelet，确保lvscare容器正常拉起，查看ipvs规则正常
```
ipvsadm -Ln
```

**Comment by fanux** [comment]
1.14.2版本修复此问题，把相关初始化命令加入kubelet启动依赖
