### ISSUE TITLE
zteos 使用sealos部署v1.18.15报错

### ISSUE THREAD

**Issue by lamboyo** [fanux/sealos#602]
**哪个命令或者组件**
sealos init --passwd '****' --master 10.10.10.10 --pkg-url /local/kube1.18.15.tar.gz --version v1.18.15

**描述这个缺陷**
15:19:47 [INFO] [ssh.go:58] [ssh][10.54.148.52:22] grep -qF '10.54.148.52 apiserver.cluster.local' /etc/hosts || echo 10.54.148.52 apiserver.cluster.local >> /etc/hosts
15:19:47 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
15:19:48 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: W0302 15:19:48.228689   13836 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0302 15:19:48.231484   13836 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0302 15:19:48.232782   13836 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.15
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
        [WARNING FileExisting-socat]: socat not found in system path
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

15:19:48 [EROR] [ssh.go:28] [ssh][10.54.148.52:22]Error exec command failed: Process exited with status 1
15:19:48 [EROR] [init.go:138] [10.54.148.52:22]kubernetes install is error.please clean and uninstall.

**重现步骤（如果有需要可以附加图片）**
1. 执行sealos init...
...

**测试结果**
1. 我的环境必现

**期望结果**
1. 期望出现 sealos部署成功

**运行环境**

- Docker版本:  本机无
- Kubernetes版本 : kube1.18.15.tar.gz
- sealos版本: sealos version v0.0.0-next, build 5d754f9 go1.14.12, Build Time : 2020-12-08T02:39:41Z
- 操作系统:  基于centos7
- 运行模式:  虚拟机 ( tecs, 内存 16gb, cpu 8核 ,存储 200gb )
- 集群规模:   1master
- 附加说明:

**Comment by lamboyo** [comment]
15:35:02 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] hostname
15:35:03 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: cgslv5.04-148.52.novalocal

15:35:03 [DEBG] [ssh.go:58] [10.54.148.52:22] cat /etc/hosts |grep cgslv5.04-148.52.novalocal || echo '10.54.148.52 cgslv5.04-148.52.novalocal' >> /etc/hosts
15:35:03 [INFO] [ssh.go:51] [10.54.148.52:22] 10.54.148.52 cgslv5.04-148.52.novalocal
15:35:03 [INFO] [check.go:50] [10.54.148.52:22]  ------------ check ok
15:35:03 [INFO] [print.go:14] 
[globals]sealos config is:  {"Hosts":["10.54.148.52:22"],"Masters":["10.54.148.52:22"],"Nodes":null}
15:35:03 [DEBG] [ssh.go:58] [10.54.148.52:22] mkdir -p /usr/bin || true
15:35:03 [DEBG] [download.go:30] [10.54.148.52:22]please wait for mkDstDir
15:35:03 [DEBG] [download.go:32] [10.54.148.52:22]please wait for before hook
15:35:03 [DEBG] [ssh.go:58] [10.54.148.52:22] ps -ef |grep -v 'grep'|grep sealos >/dev/null || rm -rf /usr/bin/sealos
15:35:04 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] ls -l /usr/bin/sealos 2>/dev/null |wc -l
15:35:04 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: 1

15:35:04 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] md5sum /usr/bin/sealos | cut -d" " -f1
15:35:05 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: ec67af2e20fc81cc7964c57d2c9c59e7

15:35:05 [INFO] [download.go:37] [10.54.148.52:22]SendPackage:  /usr/bin/sealos file is exist and ValidateMd5 success
15:35:05 [DEBG] [download.go:56] [10.54.148.52:22]please wait for after hook
15:35:05 [DEBG] [ssh.go:58] [10.54.148.52:22] chmod a+x /usr/bin/sealos
15:35:06 [DEBG] [ssh.go:58] [10.54.148.52:22] mkdir -p /root || true
15:35:06 [DEBG] [download.go:30] [10.54.148.52:22]please wait for mkDstDir
15:35:06 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] ls -l /root/kube1.18.15.tar.gz 2>/dev/null |wc -l
15:35:07 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: 1

15:35:08 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] md5sum /root/kube1.18.15.tar.gz | cut -d" " -f1
15:35:09 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: 7c99d609558739833f892ec385914933

15:35:09 [INFO] [download.go:37] [10.54.148.52:22]SendPackage:  /root/kube1.18.15.tar.gz file is exist and ValidateMd5 success
15:35:09 [DEBG] [download.go:56] [10.54.148.52:22]please wait for after hook
15:35:09 [DEBG] [ssh.go:58] [10.54.148.52:22] cd /root && rm -rf kube && tar zxvf kube1.18.15.tar.gz  && cd /root/kube/shell && rm -f ../bin/sealos && bash init.sh && sed -i '/kubectl/d;/sealos/d' /root/.bashrc  && echo 'command -v kubectl &>/dev/null && source <(kubectl completion bash)' >> /root/.bashrc && echo '[ -x /usr/bin/sealos ] && source <(sealos completion bash)' >> /root/.bashrc && source /root/.bashrc
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/shell/
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/shell/init.sh
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/shell/master.sh
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/shell/docker.sh
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/README.md
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/bin/
15:35:09 [INFO] [ssh.go:51] [10.54.148.52:22] kube/bin/kubelet
15:35:10 [INFO] [ssh.go:51] [10.54.148.52:22] kube/bin/kubectl
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/bin/crictl
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/bin/conntrack
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/bin/kubeadm
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/bin/kubelet-pre-start.sh
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/docker.service
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/kubeadm.yaml
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/kubelet.service
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/calico.yaml
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/10-kubeadm.conf
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/net/
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/conf/net/calico.yaml
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/docker/
15:35:11 [INFO] [ssh.go:51] [10.54.148.52:22] kube/docker/docker.tgz
15:35:12 [INFO] [ssh.go:51] [10.54.148.52:22] kube/docker/README.md
15:35:12 [INFO] [ssh.go:51] [10.54.148.52:22] kube/images/
15:35:12 [INFO] [ssh.go:51] [10.54.148.52:22] kube/images/images.tar
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] kube/images/README.md
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + storage=/var/lib/docker
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + harbor_ip=127.0.0.1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + mkdir -p /var/lib/docker
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + command_exists docker
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + command -v docker
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++ get_distribution
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++ lsb_dist=
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++ '[' -r /etc/os-release ']'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] +++ . /etc/os-release
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ NAME='NewStart CGS Linux'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ VERSION=5.04
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ ID=ZTEOS
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ ID_LIKE='centos rhel fedora'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ VERSION_ID=5.04
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ PRETTY_NAME='NewStart Carrier Grade Server Linux 5.04'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ ANSI_COLOR='0;31'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ CPE_NAME=cpe:/o:centos:centos:7
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ HOME_URL=http://www.gd-linux.com/
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++++ BUG_REPORT_URL=http://www.gd-linux.com/
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] +++ echo ZTEOS
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++ lsb_dist=ZTEOS
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++ echo ZTEOS
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + lsb_dist=ZTEOS
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++ echo ZTEOS
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] ++ tr '[:upper:]' '[:lower:]'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + lsb_dist=zteos
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + echo 'current system is zteos'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] current system is zteos
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + case "$lsb_dist" in
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + echo 'current system not support'
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] current system not support
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] + exit 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] * Applying /usr/lib/sysctl.d/00-system.conf ...
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] kernel.yama.ptrace_scope = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] * Applying /usr/lib/sysctl.d/50-default.conf ...
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] kernel.sysrq = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] kernel.core_uses_pid = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.rp_filter = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.rp_filter = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.accept_source_route = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.accept_source_route = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.promote_secondaries = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.promote_secondaries = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] fs.protected_hardlinks = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] fs.protected_symlinks = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] * Applying /usr/lib/sysctl.d/90-cgsl.conf ...
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] kernel.sysrq = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] kernel.printk = 4 4 1 7
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] * Applying /etc/sysctl.d/99-sysctl.conf ...
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.ip_forward = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.send_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.send_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.accept_source_route = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.accept_source_route = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.secure_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.secure_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.log_martians = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.log_martians = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.icmp_echo_ignore_broadcasts = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.icmp_ignore_bogus_error_responses = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.rp_filter = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.rp_filter = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.tcp_syncookies = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.all.accept_ra = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.default.accept_ra = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.route.flush = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.all.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.default.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] * Applying /etc/sysctl.d/k8s.conf ...
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.rp_filter = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] * Applying /etc/sysctl.conf ...
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.ip_forward = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.send_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.send_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.accept_source_route = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.accept_source_route = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.secure_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.secure_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.log_martians = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.log_martians = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.icmp_echo_ignore_broadcasts = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.icmp_ignore_bogus_error_responses = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.all.rp_filter = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.conf.default.rp_filter = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.tcp_syncookies = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.all.accept_ra = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.default.accept_ra = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.route.flush = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.all.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv6.conf.default.accept_redirects = 0
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] net.ipv4.ip_forward = 1
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] current system not support
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] init.sh: line 71: docker: command not found
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] init.sh: line 79: docker: command not found
15:35:21 [INFO] [ssh.go:51] [10.54.148.52:22] driver is 
15:35:21 [DEBG] [print.go:21] ==>SendPackage
15:35:21 [DEBG] [ssh.go:58] [10.54.148.52:22] echo "apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.54.148.52
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.18.15
controlPlaneEndpoint: "apiserver.cluster.local:6443"
imageRepository: k8s.gcr.io
networking:
  # dnsDomain: cluster.local
  podSubnet: 100.64.0.0/10
  serviceSubnet: 10.96.0.0/12
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 10.54.148.52
  - 10.103.97.2
  extraArgs:
    feature-gates: TTLAfterFinished=true
  extraVolumes:
  - name: localtime
    hostPath: /etc/localtime
    mountPath: /etc/localtime
    readOnly: true
    pathType: File
controllerManager:
  extraArgs:
    feature-gates: TTLAfterFinished=true
    experimental-cluster-signing-duration: 876000h
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
scheduler:
  extraArgs:
    feature-gates: TTLAfterFinished=true
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  excludeCIDRs:
  - "10.103.97.2/32"" > /root/kubeadm-config.yaml
15:35:22 [DEBG] [print.go:21] ==>SendPackage==>KubeadmConfigInstall
15:35:22 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] hostname
15:35:22 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: cgslv5.04-148.52.novalocal

15:35:22 [INFO] [kube_certs.go:223] apiserver altNames : {map[apiserver.cluster.local:apiserver.cluster.local cgslv5.04-148.52.novalocal:cgslv5.04-148.52.novalocal kubernetes:kubernetes kubernetes.default:kubernetes.default kubernetes.default.svc:kubernetes.default.svc kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local localhost:localhost] map[10.103.97.2:10.103.97.2 10.54.148.52:10.54.148.52 10.96.0.1:10.96.0.1 127.0.0.1:127.0.0.1]}
15:35:22 [INFO] [kube_certs.go:243] Etcd altnames : {map[cgslv5.04-148.52.novalocal:cgslv5.04-148.52.novalocal localhost:localhost] map[10.54.148.52:10.54.148.52 127.0.0.1:127.0.0.1 ::1:::1]}, commonName : cgslv5.04-148.52.novalocal
15:35:25 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] hostname
15:35:25 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: cgslv5.04-148.52.novalocal

15:35:27 [DEBG] [ssh.go:58] [10.54.148.52:22] mkdir -p /etc/kubernetes || true
15:35:27 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/kubelet.conf] to Dst [/etc/kubernetes/kubelet.conf] total size is: 5.46KB ;speed is 5KB
15:35:28 [DEBG] [ssh.go:58] [10.54.148.52:22] mkdir -p /etc/kubernetes || true
15:35:29 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/admin.conf] to Dst [/etc/kubernetes/admin.conf] total size is: 5.34KB ;speed is 5KB
15:35:30 [DEBG] [ssh.go:58] [10.54.148.52:22] mkdir -p /etc/kubernetes || true
15:35:30 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/controller-manager.conf] to Dst [/etc/kubernetes/controller-manager.conf] total size is: 5.38KB ;speed is 5KB
15:35:31 [DEBG] [ssh.go:58] [10.54.148.52:22] mkdir -p /etc/kubernetes || true
15:35:31 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/scheduler.conf] to Dst [/etc/kubernetes/scheduler.conf] total size is: 5.32KB ;speed is 5KB
15:35:32 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/apiserver-etcd-client.crt] to Dst [/etc/kubernetes/pki/apiserver-etcd-client.crt] total size is: 1.07KB ;speed is 1KB
15:35:33 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/apiserver-etcd-client.key] to Dst [/etc/kubernetes/pki/apiserver-etcd-client.key] total size is: 1.64KB ;speed is 1KB
15:35:33 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/apiserver-kubelet-client.crt] to Dst [/etc/kubernetes/pki/apiserver-kubelet-client.crt] total size is: 1.08KB ;speed is 1KB
15:35:33 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/apiserver-kubelet-client.key] to Dst [/etc/kubernetes/pki/apiserver-kubelet-client.key] total size is: 1.64KB ;speed is 1KB
15:35:33 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/apiserver.crt] to Dst [/etc/kubernetes/pki/apiserver.crt] total size is: 1.29KB ;speed is 1KB
15:35:34 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/apiserver.key] to Dst [/etc/kubernetes/pki/apiserver.key] total size is: 1.64KB ;speed is 1KB
15:35:34 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/ca.crt] to Dst [/etc/kubernetes/pki/ca.crt] total size is: 1.00KB ;speed is 1KB
15:35:34 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/ca.key] to Dst [/etc/kubernetes/pki/ca.key] total size is: 1.64KB ;speed is 1KB
15:35:34 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/ca.crt] to Dst [/etc/kubernetes/pki/etcd/ca.crt] total size is: 1.00KB ;speed is 0KB
15:35:35 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/ca.key] to Dst [/etc/kubernetes/pki/etcd/ca.key] total size is: 1.64KB ;speed is 1KB
15:35:35 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/healthcheck-client.crt] to Dst [/etc/kubernetes/pki/etcd/healthcheck-client.crt] total size is: 1.07KB ;speed is 1KB
15:35:35 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/healthcheck-client.key] to Dst [/etc/kubernetes/pki/etcd/healthcheck-client.key] total size is: 1.64KB ;speed is 1KB
15:35:35 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/peer.crt] to Dst [/etc/kubernetes/pki/etcd/peer.crt] total size is: 1.16KB ;speed is 1KB
15:35:36 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/peer.key] to Dst [/etc/kubernetes/pki/etcd/peer.key] total size is: 1.64KB ;speed is 1KB
15:35:36 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/server.crt] to Dst [/etc/kubernetes/pki/etcd/server.crt] total size is: 1.16KB ;speed is 1KB
15:35:36 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/etcd/server.key] to Dst [/etc/kubernetes/pki/etcd/server.key] total size is: 1.64KB ;speed is 1KB
15:35:37 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/front-proxy-ca.crt] to Dst [/etc/kubernetes/pki/front-proxy-ca.crt] total size is: 1.01KB ;speed is 1KB
15:35:37 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/front-proxy-ca.key] to Dst [/etc/kubernetes/pki/front-proxy-ca.key] total size is: 1.64KB ;speed is 1KB
15:35:37 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/front-proxy-client.crt] to Dst [/etc/kubernetes/pki/front-proxy-client.crt] total size is: 1.03KB ;speed is 1KB
15:35:37 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/front-proxy-client.key] to Dst [/etc/kubernetes/pki/front-proxy-client.key] total size is: 1.64KB ;speed is 1KB
15:35:38 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/sa.key] to Dst [/etc/kubernetes/pki/sa.key] total size is: 1.64KB ;speed is 1KB
15:35:38 [DEBG] [scp.go:337] [ssh][10.54.148.52:22]transfer local [/root/.sealos/pki/sa.pub] to Dst [/etc/kubernetes/pki/sa.pub] total size is: 0.44KB ;speed is 0KB
15:35:38 [DEBG] [ssh.go:58] [10.54.148.52:22] grep -qF '10.54.148.52 apiserver.cluster.local' /etc/hosts || echo 10.54.148.52 apiserver.cluster.local >> /etc/hosts
15:35:39 [INFO] [ssh.go:13] [ssh][10.54.148.52:22] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
15:35:39 [DEBG] [ssh.go:25] [ssh][10.54.148.52:22]command result is: W0302 15:35:39.614318   30081 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0302 15:35:39.616194   30081 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0302 15:35:39.618115   30081 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.15
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
        [WARNING FileExisting-socat]: socat not found in system path
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

15:35:39 [EROR] [ssh.go:28] [ssh][10.54.148.52:22]Error exec command failed: Process exited with status 1
15:35:39 [EROR] [init.go:171] [10.54.148.52:22] install kubernetes failed. please clean and uninstall.

**Comment by imdingtalk** [comment]
噢~ 糟糕的issue~

**Comment by oldthreefeng** [comment]
这个看起来是初始化没成功.  zteos 目前没写入到脚本. 看起来还是得改的更兼容一点.

**Comment by imdingtalk** [comment]
```
[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist

[preflight] If you know what you are doing, you can make a check non-fatal with --ignore-preflight-errors=...

To see the stack trace of this error execute with --v=5 or higher


15:35:39 [EROR] [ssh.go:28] [ssh][10.54.148.52:22]Error exec command failed: Process exited with status 1

15:35:39 [EROR] [init.go:171] [10.54.148.52:22] install kubernetes failed. please clean and uninstall.
```

就检查下这里吧，，ssh 失败了，手动能连上么

**Comment by oldthreefeng** [comment]
解压下载的 kube1.18.15.tar.gz.    @lamboyo 
```
$ tar xf kube1.18.15.tar.gz
$ cd kube/shell

## 修改 docker.sh 第27行. 
centos|rhel|ol|sles)   ==> centos|rhel|ol|sles|zteos)
## 修改 init.sh 第45 行
 centos|rhel) ==> centos|rhel|zteos)

# 重新打包.
$ tar zcvf  kube1.18.15.tar.gz kube 

# 重新部署. 即可解决
$ sealos init --passwd '****' --master 10.10.10.10 --pkg-url /local/new/kube1.18.15.tar.gz --version v1.18.15
```

**Comment by lamboyo** [comment]
下载最新版sealos和kube1.20.4，部署成功。

**Comment by lamboyo** [comment]
照着指导也可以解决。
