### ISSUE TITLE
sealos 后续是否支持自定义组件的数据目录

### ISSUE THREAD

**Issue by balainit** [fanux/sealos#605]
**哪个命令或者组件**

sealos init 

**详细描述你的需求/任务**

要部署的主机根分区一般很小，或者系统盘只做了riad0，数据盘做了raid5。想通过一些参数，自定义组件的数据目录存储。

比如 kubelet、etcd、docker 存储到 /xxxx/kubelet、/xxxx/etcd    /xxx/docker

sealos init --kubelet root-dir=/xxxx/kubelet   --docker root-dir=/xxx/docker  ..............

**Comment by fanux** [comment]
特殊配置如果全支持参数会非常重，建议使用sealos自定义kubeadm配置文件的能力。   后续大版本升级会以更牛逼更优雅的方式解决这个问题。
