### ISSUE TITLE
使用sealos安装了k8s后，重启docker后集群内网络不通

### ISSUE THREAD

**Issue by always-waiting** [fanux/sealos#607]
使用sealos安装后，使用busybox镜像ping一个外网域名是可以的。重启docker后（使用systemctl restart docker重启），在busybox中ping相同外网域名，就不能解析了。

希望有大神能够提供一下技术指导

**Comment by always-waiting** [comment]
@fanux 能否指导一下？

**Comment by zhangguanzhang** [comment]
在群里的话艾特我，我看下，docker info信息先复制上来

**Comment by always-waiting** [comment]
@fanux 请问是那个群？我加进去

**Comment by yangchuansheng** [comment]
> @fanux 请问是那个群？我加进去

加我微信拉你进群：cloud-native-yang
