### ISSUE TITLE
目前Sealos join master为并发，在etcd底层盘比较慢的情况下，有可能join失败，建议改成串行模式

### ISSUE THREAD

**Issue by VinceCui** [fanux/sealos#608]
**哪个命令或者组件**
eg. sealos init,install ...

sealos init/join

**描述这个缺陷**
简短描述这个缺陷内容.
目前Sealos join master为并发，在etcd底层盘比较慢的情况下，有可能join失败，建议改成串行模式

该现象发生概率较高，发生后，会发现部分master加入成功，但role为worker。

**重现步骤（如果有需要可以附加图片）**
1. 多试几次
2. 搞个慢盘
...

**测试结果**
1. 
2. 
3.

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   eg 3master 3node
- 附加说明: istio,dashboard ...

**Comment by fanux** [comment]
一些垃圾机器上确实经常丢master 丢node什么的， join master可以设置成同步

**Comment by cuisongliu** [comment]
4.0 代码 join-master设置为同步
