### ISSUE TITLE
拷贝kubeconfig时不能cp -i,已有文件可能会卡死

### ISSUE THREAD

**Issue by fanux** [fanux/sealos#613]
copyk8sConf := `mkdir -p /root/.kube && cp -i /etc/kubernetes/admin.conf /root/.kube/config && chmod 600 /root/.kube/config`

改成：
rm -rf .kube/config && mkdir -p /root/.kube && cp  /etc/kubernetes/admin.conf /root/.kube/config

**Comment by oldthreefeng** [comment]
ok, 我晚一点pr.

**Comment by zhangguanzhang** [comment]
```
\cp  /etc/kubernetes/admin.conf /root/.kube/config
