### ISSUE TITLE
master ip变化之后恢复

### ISSUE THREAD

**Issue by BussanQ** [fanux/sealos#615]
单master集群部署之后，master服务器的ip发生变化（外部原因导致，其他资源无变化），能否支持命令一键恢复集群状态；
不通过reset之后重新init的方式，因为可能已经有一些应用pod或者对象部署过了。

**Comment by zhangguanzhang** [comment]
hosts文件没动的话，你master上的网卡ip整回去就行了，其余的等集群自愈

**Comment by BussanQ** [comment]
> hosts文件没动的话，你master上的网卡ip整回去就行了，其余的等集群自愈

就是需要用新ip，不使用安装时配置的旧ip。

**Comment by oldthreefeng** [comment]
可以添加另外添加2个master， 然后一步一步迁移呗， 
单master无损切换ip基本很难实现。

**Comment by zhangguanzhang** [comment]
新ip不在证书certSan里，你得重新整证书

**Comment by fanux** [comment]
delete再join即可

**Comment by fanux** [comment]
不能
