### ISSUE TITLE
如何自行构建离线包？

### ISSUE THREAD

**Issue by ganttee** [fanux/sealos#627]
#97 在这个issue中看到可以自行构建离线包，但是最新版本没有找到相关的命令。也没有找到sealbuild相关仓库。

是否可以简单说明如何自行构建离线包？

**Comment by oldthreefeng** [comment]
https://github.com/fanux/sealos/issues/620 这个。

**Comment by ganttee** [comment]
> #620 这个。

这个是应用的构建方式吧。kubernetes离线资源包也是这么构建吗？

**Comment by hhstu** [comment]
把 1.20.0的下载下来，，改吧改吧替换替换 然后重现 tar 一下

**Comment by oldthreefeng** [comment]
@ganttee @hhstu 
可以看 一下我们很早之前写的打包方式。 
amd64: https://github.com/fanux/cloud-kernel
arm64: https://github.com/oldthreefeng/arm64-test

也有最新的打包方式(支持arm64 和 amd64)： 
https://github.com/sealyun/cloud-kernel

底层都是去云服务上开启一个k8s集群， 然后把需要的资源全部打成tar包。 

当然， 如果你需要自己打包的话， 建议使用阿里巴巴最新开源产品： sealer  https://github.com/alibaba/sealer
