### ISSUE TITLE
问题: Node节点无法使用kubectl命令获取信息

### ISSUE THREAD

**Issue by gdtdpt** [fanux/sealos#628]
使用Sealos安装的集群在master节点可以正常使用`kubectl`命令，比如`kubectl get svc -n kube-system`，但是在Node节点上会提示`The connection to the server localhost:8080 was refused - did you specify the right host or port?`。

另一个集群使用原生`kubeadm`部署，所有节点都可以正常使用`kubectl`命令查看集群及组件信息。

想问一下这是因为Sealos的负载模式导致的吗？还是说可能有某些地方配置错误或者操作错误？

如果是Sealos集群模式导致，还希望能在文档中说明一二。

版本信息：
- Sealos: v3.3.8
- kube 1.19.11
- rhel 7.9
- kernel 3.10.0

**Comment by oldthreefeng** [comment]
这方面是涉及了 rbac 授权。  @gdtdpt 

如果需要在node节点使用kubectl（cluster-admin）。 你可以直接复制master的 `/etc/kubernetes/admin.conf` 到 node节点。

如果是其他权限， 可以阅读一下官方文档。 比如 https://kubernetes.io/zh/docs/reference/access-authn-authz/rbac/
```
$ mkdir ~/.kube
$ scp master01:/etc/kubernetes/admin.conf ~/.kube/config
```

**Comment by zhangguanzhang** [comment]
kubectl 只是一个 http 请求工具，鉴权信息则是 `kubeconfig`，如果没提供 kubeconfig文件(里面也有server的地址)，则认为 kube-apiserver 的地址是 `http://localhost:8080`

**Comment by gdtdpt** [comment]
@oldthreefeng @zhangguanzhang 感谢两位的回复，是我没了解鉴权方面的知识，草率提问了，不好意思。
