### ISSUE TITLE
问题: 只用etcd备份(sealos etcd save），没有etcd恢复吗？

### ISSUE THREAD

**Issue by Cinzq4615** [fanux/sealos#629]
**那个命令或者组件**
sealos etcd save

**描述你的问题**
没有对应的集群恢复吗?

**Comment by oldthreefeng** [comment]
sealos etcd restore . 条件也比较苛刻， 需要重建新集群， 然后导入备份数据。 @Cinzq4615

**Comment by Cinzq4615** [comment]
K8S集群灾备 有什么好的方案@oldthreefeng

**Comment by zhangguanzhang** [comment]
最重要的是etcd备份还有证书备份，如果有ci/cd，比如说创建啥deploy和svc，一般是gitops，yaml来源于仓库啥的。
业务数据就db那些，无论用没有pv啥的，都得备份
