### ISSUE TITLE
unable to load kernel module: "configs"

### ISSUE THREAD

**Issue by JingChengSoft** [fanux/sealos#632]
系统:CentOS Linux release 7.8.2003 (Core)
安装:1.18.16
# uname -r
3.10.0-1127.19.1.el7.x86_64
# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 3.10.0-1127.19.1.el7.x86_64
DOCKER_VERSION: 19.03.9
DOCKER_GRAPH_DRIVER: overlay2
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found.\n", err: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

13:50:43 [EROR] [ssh.go:28] [ssh][192.168.111.60:22]Error exec command failed: Process exited with status 1
13:50:43 [EROR] [init.go:173] [192.168.111.60:22] install kubernetes failed. please clean and uninstall.

**Comment by oldthreefeng** [comment]
补全一下相关的系统信息.
