### ISSUE TITLE
缺陷:sealos clean --all  命令清理不干净问题

### ISSUE THREAD

**Issue by jingslunt** [fanux/sealos#633]
**哪个命令或者组件**
sealos clean --all 

**描述这个缺陷**
命令清理不干净问题

**处理步骤（如果有需要可以附加图片）**
yum remove docker-scan-plugin
ifconfig docker0 down
ifconfig cni0 down
find / -name "kubernetes" -exec rm -rf {} \;
find / -name "containerd" -exec rm -rf {} \;
mount #显示大量overlay挂载,需要重启

**Comment by cuisongliu** [comment]
ip link del docker0
