### ISSUE TITLE
缺陷: master 节点 kubelet 的 apiserver的地址应该是 vip 而不是本机

### ISSUE THREAD

**Issue by hhstu** [fanux/sealos#637]
下边是一个 master 节点的 kubelet 配置文件的实例，如果这个节点的 apiserver 故障，那么这个节点的 kubelet 就无法工作，节点后续就该 not reasdy，然后驱逐等等。 这是不科学的

```shell 

[root@master ~]# cat /etc/kubernetes/kubelet.conf
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJeE1EWXdPREE0TkRreU1Wb1lEekl4TWpFd05URTFNRGcwT1RJeFdqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCjJTZVlPdlF6ZVVIMUkyYnJJYm4rNURiSjE2NnZDbjV4R1JWZ05xUGtOa1pITllWTVJwWFQwSWh2cjI3OTBiYy8KbXBzZ0xuRDFJNVNOYWhlYktSNmRTa3JzTVFlZDFabEhxaWk1dzFvSGlPZk5EZWhqVWxPQjZCYVl5QmM1SUlLZQppMm9UaU92Tkd6SlFjT252Sk03WEN1dlFuN1NEUE9nWmtQaHNjVGRKanJ6eC83MW1GbjlOUER6ZUhNMS9WWW1mCkhPZVdTdDN4R21aTXdEcUl5VG9JMjFydURMclIxbVlBazFVaFRWcjZ4Z2dIOHV6cHRpSm4vUEd2NXpHYVhwMkgKcTMzZHdmL0c0SmJoMFloSTZWaTdLSVpsVnJ4M04zU21OYkpkTVBHQUNVeGt1NWN1ekJXOGFGTVl6R0pwMkFrKwpmdmUrYm9qMGs2WnRHei91T0thaUxRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVEK3pGSVlpRHhBZW9uaksvZkdwL0I2dVgyZ2N3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFJcTJsbnRWTWFzNklsNnA5WDhvSE1EVHA0MWFRaG1xdHJsWHFiVllNUTQ2VGNtUQpkV0czWndhT3l0b2JFS0haSGJxeitzRjFHM0VHU25UcXJuRmVWNHpGNWtGOGdoTkk2YUprMld3a0dOT3c3eWtFClJxQ1hlWklURnZxYnRZMk5JU1JvbjNVY2FQcDV6YzJNYWRpKzFYZTFER3cwM1Z2eHRrei90aU1MTUdoTWNjMTEKK3JtK2YwVlBYalZpQ05uWHllS3lGRXd1NkhIMEJQL0tXeWNCVlhPMlBLTWp0aXIrZTZtNk5NSUpvUndTTUprZwp0VnY3VjFWWkt4K0U2a3FVR1NHMVNXb054VEpWT3pybURkclpneFVUN1l3VUdZUjYzc3ZBaWhnbXgyQjIzeVJJCjJRSlU0eFVFY3hvMDRIOXVqaTFnRGVYanhVSGlhN2dlcjVPVXZRcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://apiserver.cluster.local:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:master
  name: system:node:master@kubernetes
current-context: system:node:master@kubernetes
kind: Config
preferences: {}
users:
- name: system:node:master
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem
[root@master ~]#
[root@master ~]# cat  /etc/hosts
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1 localhost6 localhost6.localdomain6 localhost6.localdomain

172.20.72.72 master RJYF-T-202.ctfo.local RJYF-T-202
172.20.72.39 node1
172.20.72.72 apiserver.cluster.local[

```

**Comment by hhstu** [comment]
同样 controller-manager 和 scheduler 也有类似的问题，不能因为自己节点的 apiserver down 了就要来一波主备切换

**Comment by oldthreefeng** [comment]
你有什么好的方法解决么？  

我们认为 节点的kube-apiserver done了， 认为节点有问题， 所以下线改节点的所以服务。

**Comment by hhstu** [comment]
@oldthreefeng  我看了下，只有第一个 master 的 kubelet的 apiserver的 地址指向 自己的 apiserever，而其它master 上的kubelet 都用的vip。     很多时候一个边缘集群肯可能只有 3个 节点全是master，没有node，业务直接跑在 master 上，某个 master 上的 apiserver 退出了，或者就想down掉节约资源，这时它的 kubelet 原则上还是可以连 vip 继续工作的，而不是判定下线。

**Comment by fanux** [comment]
解决很简单，在master上面也跑lvscare即可。  我觉得没有必要，什么情况会出现apiserver挂掉而kubelet没挂。  apiserver是static pod 凉了kubelet也会尝试再次拉起。  另外就是节点宕机的情况，那kubelet也不可用了 配置vip也没意义。   所以还是看需要有多高的可用性以及 只有apiserver挂掉还拉不起来的可能性有多大

**Comment by hhstu** [comment]
1、k8s 的三 master 实现高可用的本质是 3 个 etcd的高可用，而不是 3 个 apiserver。 即使 只有 2个 apiserver 在 run，这个集群高可用也没有被破坏。
2、apiserver 和 kubelet 本身不应该在某个节点上偶合。
3、我们现在的场景是，业务一开始没有多少服务，一开始就部署 3 个 master。为了能部署更多的服务我们会把其中一个master上的 /etc/kubernetes/manifest下的 yaml move出来节约资源，如果 kubelet 配置的是本机 apiserver，那么这个节点就 notready了，没法跑服务了。
4、当前 sealos 的只有 master 0 的kubelet 是配的本机 apiservedr，其它master配的是 vip，也没有统一 ！！！！！！！

**Comment by oldthreefeng** [comment]
> 4、当前 sealos 的只有 master 0 的kubelet 是配的本机 apiservedr，其它master配的是 vip，也没有统一 ！！！！！！！

master节点全都是都是监听的 本机apiserver, 只有 worker节点才配置的 vip。 

你这个情况。 在master上也跑一个lvscare就好了。 @hhstu

**Comment by hhstu** [comment]
> 4、当前 sealos 的只有 master 0 的kubelet 是配的本机 apiservedr，其它master配的是 vip，也没有统一 ！！！！！！！

这是我的错误，没有清理干净环境，虚拟机上测试 master 之前 测试过 部署node类型。

**Comment by oldthreefeng** [comment]
这种独特的情况是否需要在sealos里面实现？ 

 @fanux  @cuisongliu  @yangchuansheng @hhstu @zhangguanzhang

**Comment by hhstu** [comment]
1、lvscare 改成以 daemonset 容忍所有污点的方式跑到所有机器上  2、 改 /etc/kubernetes/kubelet.conf apiserver地址为 vip。  这样无论 master 还是 node 一视同仁，部署脚本也会变得更简单。

**Comment by oldthreefeng** [comment]
1. daemonset不可以， 你要保证k8s起来才能起ds， 然而k8s起来依赖lvscare。 所以死循环了
2. 这个已经是vip的地址了， 可以手动更改解析即可。 你看看node节点的实现.

**Comment by hhstu** [comment]
> daemonset不可以， 你要保证k8s起来才能起ds， 然而k8s起来依赖lvscare。 所以死循环了

好吧，我以为是 selos init 时会先 写一次 ipvs，后续才由 lvscare增量维护

**Comment by oldthreefeng** [comment]
> sealos init 时会先 写一次 ipvs，后续才由 lvscare增量维护 ， 由kubelet的 static_pod进行守护
的确是这样。

**Comment by cuisongliu** [comment]
其实我一开始想把lvscare做成类似nginx的东西
