### ISSUE TITLE
问题: sealer和sealos的关系

### ISSUE THREAD

**Issue by ZhengJuCn** [fanux/sealos#641]
**那个命令或者组件**
sealer 和 sealos的关系

**描述你的问题**
sealer是否可以看做sealos的升级版？有了sealer后是否sealos就不再需要了

**你看到的一些参考资料**

**Comment by fanux** [comment]
sealos只能帮助你安装k8s，sealer支持用户Build一个自定义的k8s，比如你想要一个包含dashboard的k8s 那sealer更合适。 sealer定位是实现分布式软件的build share run. 更多 详情：https://mp.weixin.qq.com/s/0SBslzaMWtqn9H8Q57urNA
