### ISSUE TITLE
问题: 应用包中config文件中command的执行时机和数量问题

### ISSUE THREAD

**Issue by ZhengJuCn** [fanux/sealos#642]
**那个命令或者组件**
构建应用包

**描述你的问题**

1、command执行时机

构建应用包，如dashboard时的config文件，例子只描述了command执行发生的node节点

但未描述command执行的时机，如config 文件中apply和delete是依次执行，还是apply在install中的某一时机执行，delete在install不执行，load在install中执行？

2、command数量

如：单个config中apply命令只能有一条还是多条？对其他命令同样有这方面的疑问

之所以有这个问题，是由于例子中允许在sealos install时覆盖command，如--cmd "APPLY kubectl apply -k manifests"

**你看到的一些参考资料**
应用安装.doc

**Comment by oldthreefeng** [comment]
> 1、command执行时机

sealos install  只执行 START. LOAD. APPLY。
sealos delete 只执行 REMOVE ，STOP， DELETE。
> 2. command数量

没有限制， 另外， sealos install 没有 --cmd命令。 
如果需要自定义, 你可以写 values.yaml 可以写 config。覆盖 tar包里面的 config和mainifest。  
	sealos install --pkg-url /root/dashboard.tar -f values.yaml -c config

**Comment by ZhengJuCn** [comment]
> > 1、command执行时机
> 
> sealos install 只执行 START. LOAD. APPLY。
> sealos delete 只执行 REMOVE ，STOP， DELETE。
> 
> > 1. command数量
> 
> 没有限制， 另外， sealos install 没有 --cmd命令。
> 如果需要自定义, 你可以写 values.yaml 可以写 config。覆盖 tar包里面的 config和mainifest。
> sealos install --pkg-url /root/dashboard.tar -f values.yaml -c config

感谢回复~，不过文档中有这样的示例，如果没有--cmd命令是否需要文档修改下 @oldthreefeng 

**sealos install --pkg-url dashboard.tar --label role=master --cmd "APPLY kubectl apply -k manifests" --cmd "LOAD docker load -i images.tar"**

另外再跟您确认下cmd的执行顺序：
1、按cmd类型决定执行顺序？如 START -> LOAD -> APPLY

2、基于1中的问题再进一步，同一中命令多条如果在config中的书写顺序为：start1, load1, start2, load2
      则最终的执行顺序是按照书写顺序，还是按照start1 , start2, load1, load2

**Comment by oldthreefeng** [comment]
> 如果没有--cmd命令是否需要文档修改下

文档已经修改了
> cmd的执行顺序

2, 按config里面的顺序执行 ， install 和delete 一样。

**Comment by ZhengJuCn** [comment]
@oldthreefeng 了解了，感谢~
