### ISSUE TITLE
需求: 目前程序日志未能完整显示代码路径

### ISSUE THREAD

**Issue by workman-Lu** [fanux/sealos#645]
eg.  sealos check.go, sealos install

1.支持程序日志等级配置，或现式显示代码路径。在安装时报告错误位置，便于追寻源码。

1.wonderivan/logger引入日志配置文件,或现式打印执行日志代码定位完整信息

**Comment by fanux** [comment]
我们故意去掉了完整路径，因为过长。可以考虑加个参数，要不你来贡献一下？😄

**Comment by workman-Lu** [comment]
这想法比我原来想的加配置文件好，那我看看review一遍看看把日志部分抽出来怎么样。😀

发自 iPhone 版 Yahoo 邮箱


星期一, 七月 12, 2021, 11:01 上午 于 中弈 ***@***.***>写道：




我们故意去掉了完整路径，因为过长。可以考虑加个参数，要不你来贡献一下？ 😄
