### ISSUE TITLE
question: what about my machine's sshd port is not 22

### ISSUE THREAD

**Issue by donngchao** [fanux/sealos#647]
~]# sealos init --passwd '123456' --master xxx.xx.xx.xx --pkg-url /root/kube1.20.0.tar.gz --version v1.20.0
16:02:19 [INFO] [ssh.go:13] [ssh][xxx.xx.xx.xx:22] hostname
16:02:19 [EROR] [ssh.go:17] [ssh][xxx.xx.xx.xx:22]Error create ssh session failed,dial tcp xxx.xx.xx.xx:22: connect: connection refused
16:02:19 [EROR] [check.go:41] [xxx.xx.xx.xx:22] ------------ check error

**Comment by oldthreefeng** [comment]
--master xxx.xx.xx.xx:port

**Comment by donngchao** [comment]
[root@centos ~]# sealos init --passwd '123456' --master x.x.x.x:77  --pkg-url /root/kube1.20.0.tar.gz --version v1.20.0
17:29:40 [INFO] [ssh.go:13] [ssh][x.x.x.x:77] hostname
17:29:40 [EROR] [ssh.go:17] [ssh][x.x.x.x:77]Error create ssh session failed,ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
17:29:40 [EROR] [check.go:41] [x.x.x.x:77] ------------ check error

**Comment by oldthreefeng** [comment]
maybe your password is wrong or sshkey is error. @donngchao

**Comment by donngchao** [comment]
Thank you for your patient guidance. I tried to configured my /etc/ssh/sshd_config file and set the ```PasswordAuthentication  yes```, and then restart the service sshd. Then install with ```sealos init --passwd '123456' --master x.x.x.x:77 --pkg-url /root/kube1.20.0.tar.gz --version v1.20.0```, and finally install successfully. Thank you again.
