### ISSUE TITLE
问题: 简短说明你的问题

### ISSUE THREAD

**Issue by bizy01** [fanux/sealos#648]
**描述你的问题**
阿里云ecs单节点执行报错
22:17:07 [EROR] [ssh.go:28] [ssh][139.224.132.247:22]Error exec command failed: Process exited with status 1
22:17:07 [EROR] [init.go:173] [139.224.132.247:22] install kubernetes failed. please clean and uninstall.

**Comment by oldthreefeng** [comment]
信息太少 , 不足以判断. 提供整个 `/root/.sealos/sealos.log`
