### ISSUE TITLE
1.20.0或1.20.4安装好后，crictl pull nginx 或其他镜像，过一会镜像会被自动删除。

### ISSUE THREAD

**Issue by sundong1982** [fanux/sealos#649]
安装好后存在的docker.io/fanux/lvscare:latest 也会被自动删除

**Comment by oldthreefeng** [comment]
大概率是你磁盘不够用了

**Comment by sundong1982** [comment]
@oldthreefeng 还有70多个G呢

**Comment by zhangguanzhang** [comment]
看看百分比到了85%没，还有inode

**Comment by sundong1982** [comment]
我又开了个纯净的虚拟机，没问题。确定是我机器问题，那台机器有点久了，具体原因明天去排查下。

**Comment by sundong1982** [comment]
发现问题，是我机器上vda1磁盘有问题，能否在安装时用一个参数改变containerd的root目录为/var/lib/containerd->/data/containerd

**Comment by zhangguanzhang** [comment]
安装之前创建一个链接。同一个分区就软连接，跨分区就硬连接，路径不用修改
