### ISSUE TITLE
建议1.20+主节点加入buildkit和nerdctl

### ISSUE THREAD

**Issue by sundong1982** [fanux/sealos#651]
反正也得用，自己再去装一遍挺麻烦的。

**Comment by cuisongliu** [comment]
nerdctl 这个好像是存在的吧，buildkit的确是不存在

**Comment by sundong1982** [comment]
之前没注意nerdctl确实存在。再整合一个buildkit呗，nerdctl build用到的时候再去装挺麻烦。

**Comment by cuisongliu** [comment]
暂时可以先用 sshcmd 这个工具拷贝进去 https://github.com/cuisongliu/sshcmd

**Comment by sundong1982** [comment]
这个工具怎么实现镜像构建

**Comment by cuisongliu** [comment]
sshcmd直接下载release使用就可以 ，传到你每个节点就好了 。要不还得换包。

**Comment by sundong1982** [comment]
我是想build自定义镜像，不是同步到其他节点啊

**Comment by oldthreefeng** [comment]
> 我是想build自定义镜像，不是同步到其他节点啊

可以看看 sealer. 它更符合你的预期

**Comment by sundong1982** [comment]
@oldthreefeng 感谢推荐，我去捣鼓一下
