### ISSUE TITLE
nacos2.0.3源码编译失败

### ISSUE THREAD

**Issue by cccssppp** [fanux/sealos#660]
[ERROR] PROTOC FAILED: E:\项目\java\nacos-2.0.3\consistency\src\main\proto: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\target\protoc-dependencies\76d8e9011cba2eb89844f9a8d499c251: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\target\protoc-dependencies\a5c569378010620c404fe9c75094aed4: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\src\main\proto\consistency.proto: No such file or directory

[ERROR] E:\项目\java\nacos-2.0.3\consistency\src\main\proto\consistency.proto [0:0]: E:\项目\java\nacos-2.0.3\consistency\src\main\proto: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\target\protoc-dependencies\76d8e9011cba2eb89844f9a8d499c251: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\target\protoc-dependencies\a5c569378010620c404fe9c75094aed4: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\src\main\proto\consistency.proto: No such file or directory

[ERROR] E:\项目\java\nacos-2.0.3\consistency\src\main\proto\Data.proto [0:0]: E:\项目\java\nacos-2.0.3\consistency\src\main\proto: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\target\protoc-dependencies\76d8e9011cba2eb89844f9a8d499c251: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\target\protoc-dependencies\a5c569378010620c404fe9c75094aed4: warning: directory does not exist.
E:\项目\java\nacos-2.0.3\consistency\src\main\proto\consistency.proto: No such file or directory

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Alibaba NACOS 2.0.3 2.0.3:
[INFO]
[INFO] Alibaba NACOS 2.0.3 ................................ SUCCESS [  4.128 s]
[INFO] nacos-api 2.0.3 .................................... SUCCESS [  9.359 s]
[INFO] nacos-common 2.0.3 ................................. SUCCESS [  5.546 s]
[INFO] nacos-consistency 2.0.3 ............................ FAILURE [  2.333 s]
[INFO] nacos-sys 2.0.3 .................................... SKIPPED
[INFO] nacos-auth 2.0.3 ................................... SKIPPED
[INFO] nacos-core 2.0.3 ................................... SKIPPED
[INFO] nacos-config 2.0.3 ................................. SKIPPED
[INFO] nacos-cmdb 2.0.3 ................................... SKIPPED
[INFO] nacos-naming 2.0.3 ................................. SKIPPED
[INFO] nacos-address 2.0.3 ................................ SKIPPED
[INFO] nacos-client 2.0.3 ................................. SKIPPED
[INFO] nacos-istio 2.0.3 .................................. SKIPPED
[INFO] nacos-console 2.0.3 ................................ SKIPPED
[INFO] nacos-test 2.0.3 ................................... SKIPPED
[INFO] nacos-config-test 2.0.3 ............................ SKIPPED
[INFO] nacos-naming-test 2.0.3 ............................ SKIPPED
[INFO] nacos-core-test 2.0.3 .............................. SKIPPED
[INFO] nacos-example 2.0.3 ................................ SKIPPED
[INFO] nacos-distribution 2.0.3 ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.095 s
[INFO] Finished at: 2021-08-10T20:33:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project nacos-consistency: protoc did not exit cleanly. Review output for more information. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nacos-consistency

环境windows10，jdk1.8.0_271，maven3.6.1
根目录下执行：mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U 
很奇怪你们没有这样的问题吗？还是我有什么没配置

**Comment by liweiy** [comment]
你这个是怎么解决的，也是本地安装proto吗

**Comment by liweiy** [comment]
yes，but i do not want to install it locally



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 下午3:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [labring/sealos] nacos2.0.3源码编译失败 (#660)




  
Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
  
 
How did you solve this problem? Did you also install proto locally?
