### ISSUE TITLE
1.20.0 集群安装失败

### ISSUE THREAD

**Issue by gogeof** [fanux/sealos#661]
**哪个命令或者组件**
sealos install

**描述这个缺陷**
安装 1.20.0，master 成功， worker 节点报错：unknown flag: --master To see the stack trace of this error execute with --v=5 or higher

**重现步骤（如果有需要可以附加图片）**
1. 执行命令：sealos init --master 100.76.118.18 --node 100.76.118.19 --node 100.76.118.20 --pkg-url /data/kube1.20.0.tar.gz --version v1.20.0
2. 错误：
![image](https://user-images.githubusercontent.com/13129099/129648544-45d69e55-b685-403f-ba01-5dcbe52ef3a4.png)
...

**运行环境**

- Docker版本:   eg. 1.13.1
- Kubernetes版本 : eg.kube1.20.tar.gz
- sealos版本: v3.0.1
- 操作系统:  eg. centos7
- 运行模式:  eg. 虚拟机 ( openstack 虚拟机, 内存 16gb, cpu 4核 ,存储 200gb )
- 集群规模:   eg 1master 2node

**Comment by oldthreefeng** [comment]
sealos版本太老.

**Comment by gogeof** [comment]
谢谢答复。是的，sealos 版本确实不是最新的，我是按照 README.md 命令行下载，没注意到它的版本居然不是最新的。

文档路径：https://github.com/fanux/sealos#readme
下载路径：

```bash
# 下载并安装sealos, sealos是个golang的二进制工具，直接下载拷贝到bin目录即可, release页面也可下载
$ wget -c https://sealyun.oss-cn-beijing.aliyuncs.com/latest/sealos && \
    chmod +x sealos && mv sealos /usr/bin 
```

![image](https://user-images.githubusercontent.com/13129099/130355376-25882675-8175-48fb-a423-dbe9abecf9b2.png)

**Comment by gogeof** [comment]
是的，本地版本太老了，请忽略。
