### ISSUE TITLE
/root/.sealos/config.yaml 能否用命令生成

### ISSUE THREAD

**Issue by cichuliubai** [fanux/sealos#664]
不小心把~/.sealos/config.yaml  这个文件删除了，有什么方法生成嘛？

**Comment by oldthreefeng** [comment]
sealos init gen 这个是生成模板的 . 替换你自己的即可. 

但是想要完全靠命令恢复可能是不可能的.  因为所以的记录都存在这个文件了...

**Comment by cuisongliu** [comment]
https://github.com/fanux/sealos/wiki/sealos-recovery--.sealos
