### ISSUE TITLE
缺陷: network选择flannel安装失败

### ISSUE THREAD

**Issue by wisheen** [fanux/sealos#666]
**哪个命令或者组件**
sealos init

**描述这个缺陷**
使用flannel安装缺少镜像和文件

**重现步骤（如果有需要可以附加图片）**
加参数 --network flannel
...

**测试结果**
1.  缺镜像 quay.io.azk8s.cn/coreos/flannel:v0.11.0-amd64
2.  /opt/cni/bin 缺文件

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : kube1.19.11.tar.gz
- sealos版本: v3.3.9-rc5
- 操作系统:  ubutnu 18.94
- 运行模式:  
- 集群规模:  
- 附加说明: 

解决方式：
1. 加载镜像
2. 从calico:cni 镜像复制 容器同路径的到 本机 /opt/cni/bin

**Comment by oldthreefeng** [comment]
默认的组件是 calico. 其他的 network 组件需要自己下载镜像了, 这个地方的确不完善..
