### ISSUE TITLE
关于etcd故障的问题

### ISSUE THREAD

**Issue by cichuliubai** [fanux/sealos#667]
环境：3 master，3node的高可用K8S集群。master、node全是跑的虚拟机。
故障描述：
       几天前将master2虚拟机从A物理机迁移到B物理机，但是没删除A上面的master2，只是停了它。运行几天后，机房停电，物理机都重启，原来A上的master2也运行起来了。导致etcd的数据不一致，然后过了半天才发现。现在我删除旧的master2， 但是B上的master2，etcd容器也启动不了了。 请问这应该怎么做，我将master2 上etcd挂载的数据目录清空，etcd删除它再重新添加，也不行。

报错：
![image](https://user-images.githubusercontent.com/39149203/130225530-71c9766e-71d1-40d3-aec5-0da6b1ba0c2c.png)

**Comment by zhangguanzhang** [comment]
用备份恢复

**Comment by oldthreefeng** [comment]
两个问题:
- 集群现在是否稳定运行?
- 直接删除master2应该问题也不大?

至于怎么删除master， 请看一下wiki， 里面有怎么删除断电后的master
