### ISSUE TITLE
init初始化containerd时，没有将cgroup变量写入到containerd.conf

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [fanux/sealos#672]
**哪个命令或者组件**
离线包中的 shell/init.sh

**描述这个缺陷**
![`T36GXMU$71D(O2 G(KBYNE](https://user-images.githubusercontent.com/19485237/131625765-43d41a10-308e-44c9-8f8e-3af759a15232.png)
这里的变量获取不到，所以导致生成的containerd.conf是这样的
![HT%FLSHE7CQC@L4YA AWJWV](https://user-images.githubusercontent.com/19485237/131625861-520d77fa-106b-45d6-986b-5a93f0044cbb.png)

**重现步骤（如果有需要可以附加图片）**
sealos init即可

**运行环境**

- Containerd版本:  v1.5.5
- Kubernetes版本 : kube.1.21.4.tag.gz
- sealos版本: v3.3.9-rc.5
- 操作系统:  centos7
- 运行模式:  虚拟机
- 集群规模:   3master 3node

**Comment by oldthreefeng** [comment]
@cuisongliu  大佬麻烦测一下.

**Comment by oldthreefeng** [comment]
这个应该是我们拆分脚本的时候, 测试不够充分导致的... 紧急修复中.

**Comment by oldthreefeng** [comment]
我测试过了， 目前应该不影响使用， 会尽快修复的~  会以另外的方式来处理。

**Comment by cuisongliu** [comment]
```
https://sealyun.oss-cn-beijing.aliyuncs.com/tools/kubelet-cgroup.tar
https://sealyun.oss-cn-beijing.aliyuncs.com/tools/kubelet-systemd.tar
```

下载对应cgroup的app包 执行：

```
sealos install  --pkg-url /root/kubelet-cgroup.tar
```

即可。临时修复，后面打包是正常的。
