### ISSUE TITLE
如果CNI网络插件, 我想使用canal怎么办

### ISSUE THREAD

**Issue by JACKCHEN99** [fanux/sealos#675]
刚了解到sealos, 试了一遍, 有一些疑问:

- 网络插件是否可以自由选择, 比如flunnel或者canal, 我知道可以delete掉现有的calico, 重新部署其它的, 但总有点麻烦
- kubectl top相关的东西好像默认没有部署, 这个还是用的挺多的

**Comment by fanux** [comment]
sealos init --without-cni即可
metric server可以考虑支持
