### ISSUE TITLE
关于sealyun.com的交互优化

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#680]
关于目前[官网](https://www.sealyun.com) sealyun的优化想法

在这里可以提出一些网站的bug，以及使用上的问题为了让我们可以更好的优化。欢迎大家提出自己的想法，谢谢。

有什么关于sealyun.com相关问题可以加微信cuisongliu联系我。

**Comment by chenshengshi** [comment]
要是有方便控制pod数量就好了sealos

**Comment by oldthreefeng** [comment]
@chenshengshi  具体是 node 节点的最大可以运行的 pod 数量?
