### ISSUE TITLE
新加入master节点，证书一年，有什么好办法修改成99年

### ISSUE THREAD

**Issue by SQGE** [fanux/sealos#681]
![image](https://user-images.githubusercontent.com/30278569/133041699-2b1b9a2d-292b-41c6-bac2-38c032a3d455.png)

**Comment by oldthreefeng** [comment]
sealos 证书 99 年. 从来没有 1 年的.

**Comment by SQGE** [comment]
这个是我手动加进来的master 现在是1年，其他俩个节点上99年。

**Comment by SQGE** [comment]
![image](https://user-images.githubusercontent.com/30278569/133044117-9b3e04ad-e8e1-4545-b485-99c3f3040c24.png)

**Comment by oldthreefeng** [comment]
自己百度, 或者 使用 sealos 的方式添加 master.
