### ISSUE TITLE
sealos recovery `~/.sealos/` 目录

### ISSUE THREAD

**Issue by oldthreefeng** [fanux/sealos#682]
使用 sealos recovery 或者其他命令. 来 restore 这个目录. 因为这个目录是可以从集群master 拷贝的.

原理: 
https://github.com/fanux/sealos/wiki/sealos-recovery--.sealos

实现可以反向操作即可. 

https://github.com/fanux/sealos/blob/b6144f310e55596644eafcc0707a4cb630d86b2e/install/init.go#L243-L261

**Comment by soulmz** [comment]
<img width="423" alt="图片" src="https://user-images.githubusercontent.com/10662992/167233252-b2ae74c3-ac99-4700-9551-849817906586.png">

无法访问。有具体的文档地址吗？

**Comment by oldthreefeng** [comment]
@cuisongliu  看看，我们的wiki好像都没有了。

**Comment by oldthreefeng** [comment]
@soulmz  https://github.com/labring/sealos/blob/main/docs/3.0/plan/recovery_sealos.md 看看这个。
