### ISSUE TITLE
1台mast 2 node 安装错位提示

### ISSUE THREAD

**Issue by spectrumzhang** [fanux/sealos#684]
1台mast 2 node都是centos8, 已经清除防火墙,swap,iptable,
安装错位提示如下, 请问如何解决?

sealos init --passwd 'xxxx123!' \
    --master 192.168.3.88 \
    --node 192.168.3.89 \
    --node 192.168.3.90 \
    --pkg-url /root/kube1.22.0.tar.gz \
    --version v1.22.0

安装错误提示如下, 请问如何解决? 输出最后几行如下:

17:37:03 [DEBG] [ssh.go:58] [192.168.3.88:22] grep -qF '192.168.3.88 apiserver.cluster.local' /etc/hosts || echo 192.168.3.88 apiserver.cluster.local >> /etc/hosts
17:37:03 [INFO] [ssh.go:13] [ssh][192.168.3.88:22] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
17:37:04 [DEBG] [ssh.go:25] [ssh][192.168.3.88:22]command result is: bash: kubeadm: command not found

17:37:04 [EROR] [ssh.go:28] [ssh][192.168.3.88:22]Error exec command failed: Process exited with status 127
17:37:04 [EROR] [init.go:190] [192.168.3.88:22] install kubernetes failed. please clean and uninstall.

**Comment by zhangguanzhang** [comment]
包有问题。kubeadm 没找到二进制文件

**Comment by spectrumzhang** [comment]
> 包有问题。kubeadm 没找到二进制文件

https://www.sealyun.com/instructions 按照官网操作的, 难道包没下完整?

是否要把包放到/bin目录? 如果按照提示"下载并安装sealos, sealos是个golang的二进制工具，直接下载拷贝到bin目录即可"

**Comment by fanux** [comment]
没拷贝全？清理干净重试一下。

**Comment by spectrumzhang** [comment]
> 没拷贝全？清理干净重试一下。

都试过重新清理干净下载好几遍了, 也把centos8 内核升级了, 仍然不可以, 彻底没辙等待指导.

VBOX 是基于WIN10安装, win10启用Hyper-v 但没虚拟机, win10装了WSL debian, 这2个会有影响吗?

**Comment by cuisongliu** [comment]
我看包是没问题的啊。

**Comment by oldthreefeng** [comment]
暂不支持 wsl.
