### ISSUE TITLE
无法拉取图像 k8s.gcr.io/kube-apiserver:v1.18.5

### ISSUE THREAD

**Issue by 448486810** [fanux/sealos#685]
**哪个命令或者组件**
在使用sealos init时出现[ERROR ImagePull]错误

**描述这个缺陷**
17:26:07 [INFO] [ssh.go:13] [ssh][10.111.210.228:2222] kubeadm init --config=/root/kubeadm-config.yaml --upload-certs -v 0
17:26:11 [DEBG] [ssh.go:25] [ssh][10.111.210.228:2222]command result is: W0924 17:26:08.088605    1576 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0924 17:26:08.090134    1576 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0924 17:26:08.096475    1576 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.5
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.18.5: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.18.5: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.18.5: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.18.5: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.4.3-0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.7: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

17:26:11 [EROR] [ssh.go:28] [ssh][10.111.210.228:2222]Error exec command failed: Process exited with status 1
17:26:11 [EROR] [init.go:190] [10.111.210.228:2222] install kubernetes failed. please clean and uninstall.

简短描述这个缺陷内容.
纯内网环境，离线安装，先是报没有kubeadm、kubectl，手动安装后，接着报错无法拉去镜像。
使用镜像为1.18.5和最新版sealos
**重现步骤（如果有需要可以附加图片）**
1. 
...

**测试结果**
1. 
2. 
3.

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Docker版本:   19.03
- Kubernetes版本 : kube1.18.5.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:  2master 8node
- 附加说明: istio,dashboard ...

**Comment by fanux** [comment]
你执行的命令是啥 ，觉得你包版本和参数版本不一致

**Comment by 448486810** [comment]
--pkg-url /root/kubel 1.18.5.tar   --version 1.18.5
参数为这两个

**Comment by fanux** [comment]
--version v1.18.5

**Comment by 448486810** [comment]
[root@qklcspt-1 ~]# kubeadm config images pull
W0924 17:44:31.618487    9295 version.go:102] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get https://dl.k8s.io/release/stable-1.txt: dial tcp: lookup dl.k8s.io on 172.16.25.3:53: server misbehaving
W0924 17:44:31.618632    9295 version.go:103] falling back to the local client version: v1.18.13
W0924 17:44:31.618969    9295 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
failed to pull image "k8s.gcr.io/kube-apiserver:v1.18.13": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 172.16.25.3:53: server misbehaving
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
还是报同样的错误，执行kubeadm config images pull后依然无法拉去镜像
