### ISSUE TITLE
缺陷: 简短说明缺陷内容

### ISSUE THREAD

**Issue by 448486810** [fanux/sealos#689]
**哪个命令或者组件**
sealos init   --pkg-url kube1.18.5.tar.gz和kube1.18.20.tar.gz     --version v1.18.5和v1.18.20
**描述这个缺陷**
简短描述这个缺陷内容.
wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in docker:
		- 'docker ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'docker logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

13:34:16 [EROR] [ssh.go:28] [ssh][124.71.77.205:22]Error exec command failed: Process exited with status 1
13:34:16 [EROR] [init.go:173] [124.71.77.205:22] install kubernetes failed. please clean and uninstall.
**重现步骤（如果有需要可以附加图片）**
1. 使用sealos init命令都会报这样的错误
...

**Comment by zhangguanzhang** [comment]
```
systemctl status kubelet
docker ps -a
docker images
```

**Comment by 448486810** [comment]
kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 日 2021-09-26 17:21:33 CST; 9min ago
     Docs: http://kubernetes.io/docs/
  Process: 10252 ExecStartPre=/usr/bin/kubelet-pre-start.sh (code=exited, status=0/SUCCESS)
 Main PID: 10271 (kubelet)
    Tasks: 14
   Memory: 37.9M
   CGroup: /system.slice/kubelet.service
           └─10271 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bo...

9月 26 17:31:15 ecloudos kubelet[10271]: I0926 17:31:15.379460   10271 kube...c
9月 26 17:31:15 ecloudos kubelet[10271]: I0926 17:31:15.417948   10271 kube...c
9月 26 17:31:15 ecloudos kubelet[10271]: I0926 17:31:15.779517   10271 kube...c
9月 26 17:31:15 ecloudos kubelet[10271]: I0926 17:31:15.819766   10271 kube...c
9月 26 17:31:15 ecloudos kubelet[10271]: I0926 17:31:15.913122   10271 kube...s
9月 26 17:31:15 ecloudos kubelet[10271]: E0926 17:31:15.916968   10271 kube...d
9月 26 17:31:16 ecloudos kubelet[10271]: E0926 17:31:16.023199   10271 cont...d
9月 26 17:31:16 ecloudos kubelet[10271]: I0926 17:31:16.367758   10271 kube...c
9月 26 17:31:16 ecloudos kubelet[10271]: I0926 17:31:16.379472   10271 kube...c
9月 26 17:31:16 ecloudos kubelet[10271]: I0926 17:31:16.417933   10271 kube...c
Hint: Some lines were ellipsized, use -l to show in full.
[root@ecloudos ~]# docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS               NAMES
047f81bde271        0369cf4303ff           "etcd --advertise-cl…"   2 minutes ago       Exited (1) 2 minutes ago                       k8s_etcd_etcd-ecloudos_kube-system_1ab746b01f9681708d5871bcc4fdff4f_6
485cd6f6538a        5b9e3415461d           "kube-apiserver --ad…"   2 minutes ago       Exited (1) 2 minutes ago                       k8s_kube-apiserver_kube-apiserver-ecloudos_kube-system_7be71305d8ea6b9bdd0ace04ed0d7598_5
933cdff26db8        k8s.gcr.io/pause:3.2   "/pause"                 8 minutes ago       Up 8 minutes                                   k8s_POD_kube-apiserver-ecloudos_kube-system_7be71305d8ea6b9bdd0ace04ed0d7598_0
0684fbbc4169        k8s.gcr.io/pause:3.2   "/pause"                 8 minutes ago       Up 8 minutes                                   k8s_POD_etcd-ecloudos_kube-system_1ab746b01f9681708d5871bcc4fdff4f_0
3fb1ce7c6ac5        98659ccbefae           "kube-scheduler --au…"   8 minutes ago       Up 8 minutes                                   k8s_kube-scheduler_kube-scheduler-ecloudos_kube-system_19bdb32d52a8f415e5019f6e824b2494_0
5bdfbdf5961a        k8s.gcr.io/pause:3.2   "/pause"                 8 minutes ago       Up 8 minutes                                   k8s_POD_kube-scheduler-ecloudos_kube-system_19bdb32d52a8f415e5019f6e824b2494_0
d9ee305a5a6b        3e3b73af318b           "kube-controller-man…"   8 minutes ago       Up 8 minutes                                   k8s_kube-controller-manager_kube-controller-manager-ecloudos_kube-system_a04c555c8a67ba058a5174f82d580272_0
21fb2e6341c5        k8s.gcr.io/pause:3.2   "/pause"                 8 minutes ago       Up 8 minutes                                   k8s_POD_kube-controller-manager-ecloudos_kube-system_a04c555c8a67ba058a5174f82d580272_0
[root@ecloudos ~]# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy                v1.19.10            ecc0e51b4836        5 months ago        118MB
k8s.gcr.io/kube-apiserver            v1.19.10            5b9e3415461d        5 months ago        119MB
k8s.gcr.io/kube-scheduler            v1.19.10            98659ccbefae        5 months ago        46.5MB
k8s.gcr.io/kube-controller-manager   v1.19.10            3e3b73af318b        5 months ago        111MB
fanux/lvscare                        latest              38af5ed07c1b        9 months ago        14.9MB
k8s.gcr.io/etcd                      3.4.13-0            0369cf4303ff        13 months ago       253MB
k8s.gcr.io/coredns                   1.7.0               bfe3a36ebd25        15 months ago       45.2MB
k8s.gcr.io/pause                     3.2                 80d28bedfe5d        19 months ago       683kB
calico/node                          v3.8.2              11cd78b9e13d        2 years ago         189MB
calico/cni                           v3.8.2              c71c24a0b1a2        2 years ago         157MB
calico/kube-controllers              v3.8.2              de959d4e3638        2 years ago         46.8MB
calico/pod2daemon-flexvol            v3.8.2              96047edc008f        2 years ago         9.37MB

**Comment by 448486810** [comment]
kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 日 2021-09-26 17:21:33 CST; 20min ago
     Docs: http://kubernetes.io/docs/
  Process: 10252 ExecStartPre=/usr/bin/kubelet-pre-start.sh (code=exited, status=0/SUCCESS)
 Main PID: 10271 (kubelet)
    Tasks: 14
   Memory: 37.0M
   CGroup: /system.slice/kubelet.service
           └─10271 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --network-plugin=cni --...

9月 26 17:42:26 ecloudos kubelet[10271]: I0926 17:42:26.145470   10271 kubelet.go:449] kubelet nodes not sync
9月 26 17:42:26 ecloudos kubelet[10271]: I0926 17:42:26.610971   10271 kubelet.go:449] kubelet nodes not sync
9月 26 17:42:26 ecloudos kubelet[10271]: I0926 17:42:26.611005   10271 kubelet.go:449] kubelet nodes not sync
9月 26 17:42:26 ecloudos kubelet[10271]: W0926 17:42:26.615526   10271 status_manager.go:550] Failed to get status for pod "kube-apiserver-ecloudos_kube-system(7be71305d8ea6b9bdd0ace04ed...dshake timeout
9月 26 17:42:26 ecloudos kubelet[10271]: E0926 17:42:26.616206   10271 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing reque...
9月 26 17:42:26 ecloudos kubelet[10271]: E0926 17:42:26.616405   10271 kubelet_node_status.go:93] Unable to register node "ecloudos" with API server: Post "https://apiserver.cluster.loca... reset by peer
9月 26 17:42:26 ecloudos kubelet[10271]: I0926 17:42:26.627296   10271 kubelet.go:449] kubelet nodes not sync
9月 26 17:42:26 ecloudos kubelet[10271]: I0926 17:42:26.778187   10271 kubelet.go:449] kubelet nodes not sync
9月 26 17:42:26 ecloudos kubelet[10271]: I0926 17:42:26.779265   10271 kubelet.go:449] kubelet nodes not sync
9月 26 17:42:27 ecloudos kubelet[10271]: I0926 17:42:27.145643   10271 kubelet.go:449] kubelet nodes not sync
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by zhangguanzhang** [comment]
看etcd那个容器的日志

**Comment by 448486810** [comment]
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2021-09-26 14:08:53.671738 I | etcdmain: etcd Version: 3.4.13
2021-09-26 14:08:53.671770 I | etcdmain: Git SHA: ae9734ed2
2021-09-26 14:08:53.671773 I | etcdmain: Go Version: go1.12.17
2021-09-26 14:08:53.671776 I | etcdmain: Go OS/Arch: linux/amd64
2021-09-26 14:08:53.671779 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2021-09-26 14:08:53.671848 I | embed: peerTLS: cert = /etc/kubernetes/pki/etcd/peer.crt, key = /etc/kubernetes/pki/etcd/peer.key, trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true, crl-file =
2021-09-26 14:08:53.671958 C | etcdmain: listen tcp 124.71.77.205:2380: bind: cannot assign requested address

**Comment by 448486810** [comment]
解决方法:
1.修改/etc/kubernetes/manifests/etcd.yaml,将–listen-client-urls、–listen-peer-urls后面的ip都设置为0.0.0.0
etcd.yaml内容如下
`apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://182.42.61.199:2379
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://182.42.61.199:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://182.42.61.199:2380
    - --initial-cluster=d0tihpxwtqddgpwm.novalocal=https://182.42.61.199:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://0.0.0.0:2379,https://0.0.0.0:2379（修改的位置）
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://0.0.0.0:2380（修改的位置）
    - --name=d0tihpxwtqddgpwm.novalocal
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: registry.aliyuncs.com/google_containers/etcd:3.4.3-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}


`
2.重置节点kubeadm reset（重置节点之前将etcd.yaml文件移出来）
3.重新初始化集群,当/etc/kubernetes/manifests/etcd.yaml被创建出来时，迅速将etcd.yaml文件删除，然后将重置节点之前保存的etcd.yaml文件移动到/etc/kubernetes/manifests/目录

虽然有点傻，但是解决了
原文链接：https://blog.csdn.net/haishan88996/article/details/109599057

**Comment by 448486810** [comment]
apiserver、etcd容器都是exited状态，etcd容器日志报了一个错误，绑定不了ip端口，通过查看网卡ip可以看到，公网ip是没有绑定在网卡上的，
解决方法:
1.修改/etc/kubernetes/manifests/etcd.yaml,将–listen-client-urls、–listen-peer-urls后面的ip都设置为0.0.0.0

23--listen-client-urls=https://0.0.0.0:2379,https://0.0.0.0:2379
26--listen-peer-urls=https://0.0.0.0:2380

2.重置节点kubeadm reset（重置节点之前将etcd.yaml文件移出来）
3.重新初始化集群,当/etc/kubernetes/manifests/etcd.yaml被创建出来时，迅速将etcd.yaml文件删除，然后将重置节点之前保存的etcd.yaml文件移动到/etc/kubernetes/manifests/目录
原文链接：https://blog.csdn.net/haishan88996/article/details/109599057
