### ISSUE TITLE
根据cri 决定使用docker还是containerd

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#698]
> 有些用户在1.20上使用docker，可以根据cni判断使用哪个cri  默认1.20使用containerd

**Comment by fanux** [comment]
cni?

**Comment by cuisongliu** [comment]
cri 就是判断一下本地的cri是docker还是containerd 不是通过1.20判断的，因为有可能用户已经安装了docker，这样可以在已经安装了docker的机器上使用1.20+的包。
