### ISSUE TITLE
kubeadm init 时 一直报kubelet 没有运行，log 显示host not found

### ISSUE THREAD

**Issue by ldh761** [fanux/sealos#699]
**那个命令或者组件**
sealos  init  --master 10.3.138.175  --node 10.3.138.167 --pkg-url /root/kube1.22.0.tar.gz  --version v1.22.0

**描述你的问题**
之前用sealos安装过 k8s群集，后来重启master 节点后 群集就挂了，在关闭swap 后问题还存在，log 日志报
Oct 15 11:18:59 host-10-3-138-175 kubelet: E1015 11:18:59.506798   25554 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"host-10-3-138-175.16ae147dca297dc7", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"host-10-3-138-175", UID:"host-10-3-138-175", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node host-10-3-138-175 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"host-10-3-138-175"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc052590150868bc7, ext:6548214272, loc:(*time.Location)(0x55b99ddc7660)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc0525901639137a1, ext:6867680730, loc:(*time.Location)(0x55b99ddc7660)}}, Count:5, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Patch "https://apiserver.cluster.local:6443/api/v1/namespaces/default/events/host-10-3-138-175.16ae147dca297dc7": dial tcp 10.3.138.175:6443: connect: connection refused'(may retry after sleeping)
Oct 15 11:18:59 host-10-3-138-175 kubelet: E1015 11:18:59.542752   25554 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 11:18:59 host-10-3-138-175 kubelet: E1015 11:18:59.643806   25554 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"

**你看到的一些参考资料**
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

        Unfortunately, an error has occurred:
                timed out waiting for the condition

        This error is likely caused by:
                - The kubelet is not running
                - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

        If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                - 'systemctl status kubelet'
                - 'journalctl -xeu kubelet'

        Additionally, a control plane component may have crashed or exited when started by the container runtime.
        To troubleshoot, list all containers using your preferred container runtimes CLI.

        Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
                - 'crictl --runtime-endpoint /run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
                Once you have found the failing container, you can inspect its logs with:
                - 'crictl --runtime-endpoint /run/containerd/containerd.sock logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
[root@host-10-3-138-175 ~]# tail -f /var/log/messages
Oct 15 10:08:01 host-10-3-138-175 kubelet: E1015 10:08:01.721363   18724 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"host-10-3-138-175.16ae12192bd7df61", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"host-10-3-138-175", UID:"host-10-3-138-175", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"host-10-3-138-175"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc052566f8606f361, ext:5194550566, loc:(*time.Location)(0x55edb2499660)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc052566f8606f361, ext:5194550566, loc:(*time.Location)(0x55edb2499660)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Post "https://apiserver.cluster.local:6443/api/v1/namespaces/default/events": dial tcp 10.3.138.175:6443: connect: connection refused'(may retry after sleeping)
Oct 15 10:08:01 host-10-3-138-175 kubelet: E1015 10:08:01.785303   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:01 host-10-3-138-175 kubelet: E1015 10:08:01.886237   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:01 host-10-3-138-175 kubelet: E1015 10:08:01.987312   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.088026   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.188175   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.288420   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.388967   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.489771   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.589925   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.690835   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.742830   18724 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://apiserver.cluster.local:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/host-10-3-138-175?timeout=10s": dial tcp 10.3.138.175:6443: connect: connection refused
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.792017   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.892218   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:02 host-10-3-138-175 kubelet: I1015 10:08:02.918412   18724 kubelet_node_status.go:71] "Attempting to register node" node="host-10-3-138-175"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.919023   18724 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://apiserver.cluster.local:6443/api/v1/nodes\": dial tcp 10.3.138.175:6443: connect: connection refused" node="host-10-3-138-175"
Oct 15 10:08:02 host-10-3-138-175 kubelet: E1015 10:08:02.992815   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.093095   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.194291   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.294604   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.395231   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.496135   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.596669   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.697719   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.797904   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.898385   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:03 host-10-3-138-175 kubelet: E1015 10:08:03.998899   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:04 host-10-3-138-175 kubelet: E1015 10:08:04.099730   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:04 host-10-3-138-175 kubelet: E1015 10:08:04.200819   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:04 host-10-3-138-175 kubelet: E1015 10:08:04.301861   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:04 host-10-3-138-175 kubelet: E1015 10:08:04.402020   18724 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-175\" not found"
Oct 15 10:08:04 host-10-3-138-175 kubelet: E1015 10:08:04.426620   18724 eviction_manager.go:255] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"host-10-3-138-175\" not found"
Oct 15 10:08:04 host-10-3-138-175 containerd: time="2021-10-15T10:08:04.442842718+08:00" level=error msg="Failed to load cni configuration" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
Oct 15 10:08:04 host-10-3-138-175 kubelet: E1015 10:08:04.443170   18724 kubelet.go:2332] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"

eg. 文档的引用xxxx

**Comment by zhangguanzhang** [comment]
hostname 修改过了重启就会这样

**Comment by ldh761** [comment]
[messages.log](https://github.com/fanux/sealos/files/7351287/messages.log)

**Comment by ldh761** [comment]
> ```
> systemctl cat kubelet
> ```

[root@host-10-3-138-175 ~]# systemctl cat kubelet       
# /etc/systemd/system/kubelet.service
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/

[Service]
ExecStart=/usr/bin/kubelet
ExecStartPre=/usr/bin/kubelet-pre-start.sh
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generates at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/sysconfig/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
# /etc/systemd/system/kubelet.service.d/containerd.conf
[Service]
Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --cgroup-driver= --runtime-request-timeout=15m --container-runtime-endpoint=u

**Comment by zhangguanzhang** [comment]
```
systemctl cat kubelet 
```
截全，有部分丢失的，自己找找有没有`--hostname-override`的参数，还有你粘贴输出的时候用单个反引号` 包起来

**Comment by zhangguanzhang** [comment]
cat /var/lib/kubelet/kubeadm-flags.env

**Comment by ldh761** [comment]
你好，配置信息如下：
`  [root@host-10-3-138-175 ~]# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --pod-infra-container-image=k8s.gcr.io/pause:3.5"
[root@host-10-3-138-175 ~]# `

**Comment by zhangguanzhang** [comment]
kubelet的--hostname-override试下吧

**Comment by ldh761** [comment]
[root@host-10-3-138-175 ~]# kubelet  --hostname-override host-10-3-138-175
I1018 14:06:59.284545   29509 server.go:440] "Kubelet version" kubeletVersion="v1.22.0"
I1018 14:06:59.285650   29509 server.go:600] "Standalone mode, no API client"
I1018 14:06:59.286329   29509 container_manager_linux.go:979] "CPUAccounting not enabled for process" pid=29509
I1018 14:06:59.286362   29509 container_manager_linux.go:982] "MemoryAccounting not enabled for process" pid=29509
I1018 14:07:04.340690   29509 server.go:488] "No api server defined - no events will be sent to API server"
I1018 14:07:04.340766   29509 server.go:687] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
I1018 14:07:04.341599   29509 container_manager_linux.go:280] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
I1018 14:07:04.341866   29509 container_manager_linux.go:285] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerPolicyOptions:map[] ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
I1018 14:07:04.341958   29509 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
I1018 14:07:04.342024   29509 container_manager_linux.go:320] "Creating device plugin manager" devicePluginEnabled=true
I1018 14:07:04.342649   29509 state_mem.go:36] "Initialized new in-memory state store"
I1018 14:07:04.342827   29509 kubelet.go:314] "Using dockershim is deprecated, please consider using a full-fledged CRI implementation"
I1018 14:07:04.342913   29509 client.go:78] "Connecting to docker on the dockerEndpoint" endpoint="unix:///var/run/docker.sock"
I1018 14:07:04.342950   29509 client.go:97] "Start docker client with request timeout" timeout="2m0s"
E1018 14:07:04.344044   29509 server.go:294] "Failed to run kubelet" err="failed to run Kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

**Comment by Ainsigang** [comment]
请问这个问题有解决掉么？我也出现了这个问题，节点重启后notready，node的kubelet报错：
k8s-2 kubelet[11462]: E1110 21:02:19.922767   11462 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https:/...ode="k8s-2"
k8s-2 kubelet[11462]: E1110 21:02:19.934814   11462 kubelet.go:2407] "Error getting node" err="node \"k8s-2\" not found"
k8s-2 kubelet[11462]: E1110 21:02:20.035506   11462 kubelet.go:2407] "Error getting node" err="node \"k8s-2\" not found"

**Comment by Ainsigang** [comment]
记一下，是node节点记录apiserver的IP地址不对，发现集群（单master单节点）安装完了后node节点的hosts文里面apiserver的IP地址不是真实的apiserver的IP地址，和master节点hosts文件记录不一致，记录的这个地址没有找到是属于哪里的。
[root@k8s-2 ~]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.20.11 k8s-2
**10.103.97.2 apiserver.cluster.local**

**Comment by ldh761** [comment]
我的hosts 是对的，现在出新问题，节点连不上master ，telnet master  6443 不通， firewalld  是关闭状态，其他节点测试该端口可以通。
请大佬指教 感谢
master [root@host-10-3-138-175 ~]# hostname
host-10-3-138-175

[root@host-10-3-138-175 ~]#  kubectl get node
NAME                STATUS   ROLES                  AGE   VERSION
host-10-3-138-175   Ready    control-plane,master   30d   v1.22.0

[root@host-10-3-138-175 ~]#  kubectl get pods -A
NAMESPACE     NAME                                        READY   STATUS    RESTARTS     AGE
kube-system   calico-kube-controllers-78d6f96c7b-xztrl    1/1     Running   0            18h
kube-system   calico-node-lfhjb                           1/1     Running   0            18h
kube-system   coredns-78fcd69978-2rz5l                    1/1     Running   3 (3d ago)   30d
kube-system   coredns-78fcd69978-8fff5                    1/1     Running   3 (3d ago)   30d
kube-system   etcd-host-10-3-138-175                      1/1     Running   3 (3d ago)   30d
kube-system   kube-apiserver-host-10-3-138-175            1/1     Running   3 (3d ago)   30d
kube-system   kube-controller-manager-host-10-3-138-175   1/1     Running   3 (3d ago)   30d
kube-system   kube-proxy-chgb4                            1/1     Running   3 (3d ago)   30d
kube-system   kube-scheduler-host-10-3-138-175            1/1     Running   3 (3d ago)   30d

[root@host-10-3-138-175 ~]# netstat -tunlp |grep 6443
tcp6       0      0 :::6443                 :::*                    LISTEN      1680/kube-apiserver 
[root@host-10-3-138-175 ~]# lsof -p 1680
COMMAND    PID USER   FD      TYPE             DEVICE  SIZE/OFF      NODE NAME
kube-apis 1680 root  cwd       DIR               0,80        17 135372680 /
kube-apis 1680 root  rtd       DIR               0,80        17 135372680 /
kube-apis 1680 root  txt       REG               0,80 124919808 135372682 /usr/local/bin/kube-apiserver
**kube-apis 1680 root  mem       REG              253,1           135372682 /usr/local/bin/kube-apiserver (stat: No such file or directory)**


[root@host-10-3-138-175 ~]# lsof -p 15649
COMMAND     PID USER   FD      TYPE             DEVICE SIZE/OFF       NODE NAME
calico-no 15649 root  cwd       DIR              0,198       34  135379606 /etc/service/enabled/felix
calico-no 15649 root  rtd       DIR              0,198       39     598699 /
calico-no 15649 root  txt       REG              0,198 85542856   68659580 /usr/bin/calico-node
**calico-no 15649 root  mem       REG              253,1            68659580 /usr/bin/calico-node (stat: No such file or directory)
calico-no 15649 root  mem       REG              253,1              788781 /usr/lib64/libc-2.28.so (stat: No such file or directory)
calico-no 15649 root  mem       REG              253,1             1523948 /usr/lib64/libpthread-2.28.so (stat: No such file or directory)
calico-no 15649 root  mem       REG              253,1              788775 /usr/lib64/ld-2.28.so (stat: No such file or directory)**
**这个报找不到是什么情况**


node
[root@host-10-3-138-167 ~]# hostname
host-10-3-138-167

[root@host-10-3-138-167 ~]# ping -c 3 apiserver.cluster.local
PING apiserver.cluster.local (10.3.138.175) 56(84) bytes of data.
64 bytes from host-10-3-138-175 (10.3.138.175): icmp_seq=1 ttl=64 time=0.766 ms
64 bytes from host-10-3-138-175 (10.3.138.175): icmp_seq=2 ttl=64 time=0.578 ms
64 bytes from host-10-3-138-175 (10.3.138.175): icmp_seq=3 ttl=64 time=0.677 ms

--- apiserver.cluster.local ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.578/0.673/0.766/0.082 ms

[root@host-10-3-138-167 ~]# telnet apiserver.cluster.local 6443
Trying 10.3.138.175...
telnet: connect to address 10.3.138.175: Connection refused

其他节点
[root@host-10-3-138-165 ~]# telnet  10.3.138.175 6443
Trying 10.3.138.175...
Connected to 10.3.138.175.
Escape character is '^]'.

[root@host-10-3-138-165 ~]# telnet  apiserver.cluster.local 6443
Trying 10.3.138.175...
Connected to apiserver.cluster.local.
Escape character is '^]'.

Nov 18 11:56:45 host-10-3-138-167 kubelet: E1118 11:56:45.514852   13157 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://apiserver.cluster.local:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.3.138.175:6443: connect: connection refused
Nov 18 11:56:45 host-10-3-138-167 kubelet: E1118 11:56:45.551676   13157 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-167\" not found"
Nov 18 11:56:45 host-10-3-138-167 kubelet: E1118 11:56:45.554862   13157 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https://apiserver.cluster.local:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 10.3.138.175:6443: connect: connection refused
Nov 18 11:56:45 host-10-3-138-167 kubelet: E1118 11:56:45.586966   13157 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://apiserver.cluster.local:6443/api/v1/nodes?fieldSelector=metadata.name%3Dhost-10-3-138-167&limit=500&resourceVersion=0": dial tcp 10.3.138.175:6443: connect: connection refused
Nov 18 11:56:45 host-10-3-138-167 kubelet: E1118 11:56:45.651885   13157 kubelet.go:2407] "Error getting node" err="node \"host-10-3-138-167\" not found"



master 节点log


Nov 18 12:50:15 host-10-3-138-175 containerd: time="2021-11-18T12:50:15.031577753+08:00" level=info msg="ExecSync for \"06b93cc97004679aa87c79bf48b343e14bda7365d36c14a963e7900c1f6f1026\" with command [/bin/calico-node -felix-live -bird-live] and timeout 1 (s)"
Nov 18 12:50:15 host-10-3-138-175 containerd: time="2021-11-18T12:50:15.232807810+08:00" level=info msg="Finish piping \"stdout\" of container exec \"acab5057b9d91bec7e127fecbfd53d80649ef520eea078ef58939b6b1d100947\""
Nov 18 12:50:15 host-10-3-138-175 containerd: time="2021-11-18T12:50:15.232946991+08:00" level=info msg="Finish piping \"stderr\" of container exec \"acab5057b9d91bec7e127fecbfd53d80649ef520eea078ef58939b6b1d100947\""
Nov 18 12:50:15 host-10-3-138-175 containerd: time="2021-11-18T12:50:15.233547674+08:00" level=info msg="Exec process \"acab5057b9d91bec7e127fecbfd53d80649ef520eea078ef58939b6b1d100947\" exits with exit code 0 and error <nil>"
Nov 18 12:50:15 host-10-3-138-175 containerd: time="2021-11-18T12:50:15.236699369+08:00" level=info msg="ExecSync for \"06b93cc97004679aa87c79bf48b343e14bda7365d36c14a963e7900c1f6f1026\" returns with exit code 0"

**Comment by jdxia** [comment]
root@box1:~ # kubectl get cs -o wide
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                       ERROR
scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Healthy     ok
etcd-0               Healthy     {"health":"true","reason":""}

我这边出现这个问题

**Comment by jdxia** [comment]
我加了这个就好了
![image](https://user-images.githubusercontent.com/23069626/147436207-ea997f65-0625-4cf0-9b02-c392b3e1a3c1.png)

**Comment by cuisongliu** [comment]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/4150905/147484884-efb3430b-ce1a-4792-845c-90cd1d09d6bb.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/4150905/147484923-1ed9f295-672a-463c-91be-292350e6c955.png">

并没有你说的port=0的配置啊

**Comment by jdxia** [comment]
我这边1.19出现了
![image](https://user-images.githubusercontent.com/23069626/147492845-eb49bfb1-553a-44e7-bb34-cf5acb32aacc.png)

**Comment by cuisongliu** [comment]
@jdxia  rancher ???

**Comment by jdxia** [comment]
@cuisongliu sealos 1.19,不是rancher

**Comment by ldh761** [comment]
我这个问题解决了，安装版本1.22.0   对系统内核有要求，我的是 3.10.0-1160.6.1.el7.x86_64  ，升级高版本内核后解决

**Comment by ldh761** [comment]
感谢大家的关注 ，谢谢
