### ISSUE TITLE
在完全离线的环境下，会报拉取文件失败的问题，无法顺利安装

### ISSUE THREAD

**Issue by ignorantcaomao** [fanux/sealos#701]
在完全断网的环境下，使用sealos离线包提示文件拉取失败，无法完成安装。

![捕获](https://user-images.githubusercontent.com/31404343/137864923-522d8cf5-43bd-4f9d-91d4-5a66c06c3703.PNG)

**Comment by ignorantcaomao** [comment]
> 这个大概率是你机器磁盘不够了. kubelet 自动清理了镜像. 检查一下. @ignorantcaomao

这就是单纯的拉取镜像失败，我理解的就是它拉取的是它在阿里云的资源文件，而不是它宣传的那样完全离线安装。

**Comment by oldthreefeng** [comment]
@ignorantcaomao  没有拉取动作， 镜像已经load再本地了， 除非你磁盘不够了， 然后kubelet把你的镜像删除才会有这个动作。 
所以让你检查磁盘。

**Comment by ignorantcaomao** [comment]
> 
肯定不会是磁盘空间的问题，我500多G的空间，就算上传上传百遍，也不见得把磁盘占用满。而且我手动安装k8s集群是没有问题。我这个问题取相关镜像文件失败，肯定是这个离线安装的工具没有做到完全离线安装的要求。
