### ISSUE TITLE
sealos NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

### ISSUE THREAD

**Issue by we868618** [fanux/sealos#704]
**哪个命令或者组件**
sealos init --passwd  XXXXX \
    --user root \
    --master 192.168.0.8  \
    --node 192.168.0.9 \
    --podcidr 10.100.0.1/16 \
    --svccidr 10.96.0.0/16 \
    --pkg-url /together/tools/k8s/kube1.22.2.tar.gz \
    --version v1.22.2

**描述这个缺陷**
简短描述这个缺陷内容.

**重现步骤（如果有需要可以附加图片）**
1.  安装显示正常
![image](https://user-images.githubusercontent.com/19547977/138584100-be0c99f1-84ab-44bc-94aa-a1396ed30e8a.png)

2、kubectl get nodes 发现都是not ready 状态
![image](https://user-images.githubusercontent.com/19547977/138584104-0962693b-e93c-4bc0-9ddf-72e7e45fe729.png)
3、查看节点详情发现网络异常
![image](https://user-images.githubusercontent.com/19547977/138584130-c526dc74-2855-45ce-b674-e2f4516a54bd.png)
4、服务器没有重名
![image](https://user-images.githubusercontent.com/19547977/138584157-084af33f-03db-4a93-87f8-dafe55ff0dfc.png)
![image](https://user-images.githubusercontent.com/19547977/138584166-920d2f49-36e8-4e9c-b337-5e97ace190d2.png)
5、网络状态
![image](https://user-images.githubusercontent.com/19547977/138584187-f697b836-8b46-44d3-b0b8-9cc73cc5e7ec.png)
![image](https://user-images.githubusercontent.com/19547977/138584178-26824ccc-e756-4a08-8ae3-3a0ff01e2a24.png)
6、系统环境 centos7.6
![image](https://user-images.githubusercontent.com/19547977/138584269-2b7f22b3-ec7e-435a-9be8-9bcf8c0ab58f.png)

**Comment by oldthreefeng** [comment]
重启一下cotnainerd试试。

**Comment by cyl-007** [comment]
参考：https://github.com/fanux/sealos/issues/748
