### ISSUE TITLE
我搭建的是3个master，现在只有master1的kubelet，起来了。

### ISSUE THREAD

**Issue by junzikai** [fanux/sealos#711]
master2 和3的 kubelet  没有起来
其中master2 和3：
![$VLAG7`H9W_`KAU9G 5`T`P](https://user-images.githubusercontent.com/17429579/139460711-594b8772-b889-48c7-92f6-24fc09b46324.png)

-------------------------------------------------

[root@master2 ~]# systemctl status kubelet 
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, containerd.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2021-10-29 23:09:35 CST; 1s ago
     Docs: http://kubernetes.io/docs/
  Process: 13157 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
  Process: 13135 ExecStartPre=/usr/bin/kubelet-pre-start.sh (code=exited, status=0/SUCCESS)
 Main PID: 13157 (code=exited, status=1/FAILURE)

=======================================================
在log中找到了：
![LK5P{WI87KXYK7~AB42A$V1](https://user-images.githubusercontent.com/17429579/139460844-a9e83dfa-3342-446a-b857-f6123b72e0e9.png)
=======================================================================
 E1029 22:55:35.431294   10205 server.go:294] "Failed to run kubelet" err="failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory"
Oct 29 22:55:35 master2 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Oct 29 22:55:35 master2 systemd[1]: kubelet.service: Failed with result 'exit-code'.

====================================================
服务器信息：
服务器版本centos8 ，安装的是kube1.22.1。[root@master2 ~]# cat /etc/redhat-release
CentOS Linux release 8.0.1905 (Core)

[root@master2 ~]# uname -a
Linux master2 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

感谢大佬帮忙！！！

**Comment by oldthreefeng** [comment]
centos 8.x 不支持。。
最好是centos7.9 或者ubuntu。
