### ISSUE TITLE
calico-node flexvol image should upgrade

### ISSUE THREAD

**Issue by berlinsaint** [fanux/sealos#713]
**哪个命令或者组件**
eg. sealos init,install ...

**描述这个缺陷**
k8s控制大量爆出 
```bash
E0727 12:37:49.351357       1 driver-call.go:267] Failed to unmarshal output for command: init, output: "2019/07/27 12:37:49 Unix syslog delivery error\n", error: invalid character '/' after top-level value
W0727 12:37:49.351372       1 driver-call.go:150] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: exit status 1, output: "2019/07/27 12:37:49 Unix syslog delivery error\n"
E0727 12:37:49.351384       1 plugins.go:746] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: invalid character '/' after top-level value
```

问题和https://github.com/projectcalico/pod2daemon/issues/20 一致

并在 https://github.com/projectcalico/pod2daemon/pull/23 得到解决
但是我这边会不定期出现pod 创建失败，训练tfjob的时候回出现 name service not found 不定期出现。怀疑这个问题导致
官方pod2daemon已经修复， sealos这里使用3.8.2 貌似有点老

我看了下 pod2daemon 3.8.9 已经修复改问题

请大佬们分析calico组件是否需要 小版本更新下
**重现步骤（如果有需要可以附加图片）**
和 https://github.com/projectcalico/pod2daemon/issues/20  一致操作

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.19.11.tar.gz 
- sealos版本: Version: 3.3.9-rc.3- 操作系统:  eg. centos7

**Comment by oldthreefeng** [comment]
fix to use calico new version v1.19.1 with new k8s version. v1.22.0+ ,v1.21.4+,v1.20.10+, v1.19.14.
