### ISSUE TITLE
ingress中的ADDRESS为空

### ISSUE THREAD

**Issue by wtsnwei** [fanux/sealos#717]
**kubectl get ingress -n kube-system**

很奇怪，查看ingress时发现ADDRESS为空，但是访问又是正常的

![img2](https://s3.bmp.ovh/imgs/2021/11/7428b823f12f0a14.png)
![img2](https://s3.bmp.ovh/imgs/2021/11/8d3897b083f21f27.png)

sealos版本：3.3.9-rc.6
kubernetes版本：1.22.0
ingess-controller：nginx-ingress

请问这种情况该如何处理呢？

**Comment by zhangguanzhang** [comment]
这个地址是ingress-nginx的那个参数可以配置的，显示多少无所谓，不影响使用

**Comment by wtsnwei** [comment]
因为ingress-controller 的pod里面日志有如下报错:
```
Failed to update lock: configmaps "ingress-controller-leader" is forbidden: User "system:serviceaccount:basic-service:ic-nginx-ingress-controller" cannot update resource "configmaps" in API group "" in the namespace "basic-service"
```

这个好像是没有权限导致的, 赋予集群管理员权限就解决了:
```
kubectl create clusterrolebinding \
test:serviceaccount:basic-service:ic-nginx-ingress-controller \
--clusterrole=cluster-admin \
--user=system:serviceaccount:basic-service:ic-nginx-ingress-controller
```
