### ISSUE TITLE
DNS问题: pod DNS无法正常工作

### ISSUE THREAD

**Issue by kurimi1** [fanux/sealos#720]
**运行环境**

- Docker版本:   containerd
- Kubernetes版本 : eg.kube1.20.tar.gz
- sealos版本: atest
- 操作系统:  ubuntu18
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   1master 4node

pod 无法解析任何域名包括svc。安装成功未做任何操作。看到很多关于dns的issue
![image](https://user-images.githubusercontent.com/33993460/141775459-96dcde08-eb13-4ad4-b31f-42bbcb511058.png)

**Comment by kurimi1** [comment]
```bash
#!/bin/bash

# 关闭 防火墙
sudo systemctl stop firewalld
sudo systemctl disable firewalld

# 关闭 swap
sudo swapoff -a
sudo yes | sudo cp /etc/fstab /etc/fstab_bak
sudo cat /etc/fstab_bak | grep -v swap > /etc/fstab

# 允许 iptables 检查桥接流量
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF

cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sudo sysctl --system
```
配置一下重启coredns就好了。
我按照教程一键安装操作的，但出现了这个问题，请考虑一下这个bug

**Comment by cuisongliu** [comment]
已经设置了应该是被其他数据覆盖了
