### ISSUE TITLE
问题: 怎么在init 部署的时候指定 etcd 安装的位置

### ISSUE THREAD

**Issue by Waitfish** [fanux/sealos#721]
**那个命令或者组件**
sealos init ,

**描述你的问题**
怎么在init 部署的时候指定 etcd 安装的位置？
没有在文档里看到这个配置。

想在安装的时候 将etcd单独挂到ssd盘

**Comment by cuisongliu** [comment]
这个得查看一下kubeadm是否支持，我了解的是可以支持外部etcd。你可以单独安装etcd然后再指定一下其实也是可以的。
