### ISSUE TITLE
cannot allocated memory  

### ISSUE THREAD

**Issue by scriptyang** [fanux/sealos#722]
sealos 

k8s 版本  16.0

一直存在内存泄漏
查看 /sys/fs/cgroup/memory/kubepods/burstable/pod*/*/memory.kmem.slabinfo 一直有数据。通过
cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto rhgb quiet cgroup.memory=nokmem"
GRUB_DISABLE_RECOVERY="true"
重启后问题依旧

![Uploading image.png…]()

**Comment by zhangguanzhang** [comment]
https://zhangguanzhang.github.io/2021/04/08/kubelet-runc-disable-kmem/
