### ISSUE TITLE
执行sealos clean --node尝试移除节点时,造成master自己被删除!

### ISSUE THREAD

**Issue by danielxxka** [fanux/sealos#724]
**相关命令 sealos clean --node **

**描述这个缺陷**
在master节点上执行了 clean 移除工作节点 node的命令后, 则这台master的kubelet整个也被删掉. master死掉, 并且无法通过其他master clean --master 进行移除和重新加入集群.

**重现步骤（如果有需要可以附加图片）**
1. 成功安装好 3mastar ,4 worker 集群
2. 此时发现其中一个 worker 无法正常pull到应用image,似乎有点问题,最后决定简单clean移出集群.
3. master1上执行 sealos clean --node 127.16.0.109 准备移除节点 
4. 执行到最后,没有完全提示成功,命令退出.此时发现 master节点已经no work, kubelet service已经停止,并且通过systemctl restart及reboot无法重启.
5. 此时master2 及 master3 还在运行, 执行但是在2,3上指向  clean --master 和 join --master 也无法重新加master1进来.
6. 由于master2,3没有.sealos/confing.yaml 文件执行清除及重新加入master时也报错.

**运行环境**

- Kubernetes版本 : kube1.21.7.tar
- sealos版本: 最新v3.3.9-rc.6
- 操作系统:  centos7.9
- 运行模式:  阿里云ECS （2cpu ,4GB, 40GB  ) x 7 
- 集群规模:   3master 4node
- 附加说明: 安装步骤:及删除步骤:

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/6206411/142411619-1a767f5f-6806-4ec4-a5d0-0ea84a4fabdf.png">

sealos init --passwd '88889999' \
    --master 172.16.0.96  --master 172.16.0.95  --master 172.16.0.93  \
    --node 172.16.0.97 --node 172.16.0.98 --node 172.16.0.108 --node 172.16.0.109  \
    --podcidr 172.88.0.0/24 \
    --pkg-url kube1.21.7.tar.gz \
    --version v1.21.7

删除节点操作: (执行后结果master自己死掉,并且 节点依然在集群中,get nodes还没被删掉)
sealos clean --node 172.16.0.109
执行命令后 master自己崩溃.

**Comment by oldthreefeng** [comment]
肯定不是这个原因。 master宕机肯定是另外的原因。
 查看一下master节点的kubelet日志和etcd日志。 通过日志定位问题， 而不是通过现象判定问题。

**Comment by danielxxka** [comment]
@oldthreefeng  1.整個過程我已經寫下來,確實是這個過程造成問題,你是否有復現測試過? 2.如果通過kubelet日誌和etcd日誌定位問題?有具體方案和指引嗎?
