### ISSUE TITLE
sealos join 失败

### ISSUE THREAD

**Issue by HaozhengAN** [fanux/sealos#727]
**那个命令或者组件**
sealos join node --xxx 

**描述你的问题**
13:25:03 [INFO] [ssh.go:12] [ssh][10.103.238.15:22] sealos route --host 10.103.238.15
13:25:04 [DEBG] [ssh.go:24] [ssh][10.103.238.15:22]command result is: failed

13:25:04 [INFO] [ssh.go:12] [ssh][10.103.238.15:22] sealos route add --host 10.103.97.2 --gateway 10.103.238.15
13:25:04 [DEBG] [ssh.go:24] [ssh][10.103.238.15:22]command result is:
13:25:04 [INFO] [ssh.go:57] [ssh][10.103.238.15:22] sealos ipvs --vs 10.103.97.2:6443  --rs 10.138.42.17:6443 --health-path /healthz --health-schem https --run-once
13:25:05 [INFO] [ssh.go:50] [10.103.238.15:22] 13:25:05 [WARN] [service.go:119] IsVirtualServerAvailable warn: virtual server is empty.
13:25:05 [INFO] [ssh.go:57] [ssh][10.103.238.15:22] kubeadm join 10.103.97.2:6443 --token 8l9lf6.7gcjbeps0okh2ecr --discovery-token-ca-cert-hash sha256:f291d6ac36c8487d469dadcf5810a6967f0d9eda7d0dd6166c90cdeed0824abb -v 0
13:25:05 [INFO] [ssh.go:50] [10.103.238.15:22] [preflight] Running pre-flight checks
13:25:05 [INFO] [ssh.go:50] [10.103.238.15:22] 	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
13:25:05 [INFO] [ssh.go:50] [10.103.238.15:22] 	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.11. Latest validated version: 19.03
13:25:05 [INFO] [ssh.go:50] [10.103.238.15:22] [preflight] Reading configuration from the cluster...
13:25:05 [INFO] [ssh.go:50] [10.103.238.15:22] error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: unable to select an IP from default routes.

**Comment by fanux** [comment]
主机是否有默认路由

**Comment by cuisongliu** [comment]
error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: unable to select an IP from default routes.
