### ISSUE TITLE
无法使用自定义kubeadm-config

### ISSUE THREAD

**Issue by marcfang** [fanux/sealos#730]
1、使用sealos config -t kubeadm >>  kubeadm-config.yaml.tmpl创建了模版config；
2、在kubeadm-config.yaml.tmpl添加了“clusterName: sh-kubernetes”；
3、使用sealos init --kubeadm-config /home/kubeadm-config.yaml.tmpl --master  ***（后面省略）创建k8s集群；
4、在$HOME/.kube/config中发现clusterName未修改成功；
5、已确认由sealos生成的kubeadm-config.yaml有clusterName: sh-kubernetes字段；
6、sealos版本3.3.9 rc.6，通过sealos init --help查看支持本地自定义kubeadm-config，k8s版本1.18.9，docker版本19.03，操作系统centos 7.9 64位；
7、使用kubeadm 1.18.9版本用自定义的kubeadm-config安装，是修改成功的；
![image](https://user-images.githubusercontent.com/64076196/144227161-c3fee19d-8320-4de9-9b5c-fcbcad3f2a3a.png)
![image](https://user-images.githubusercontent.com/64076196/144227237-3a6a2a19-fe62-4bbd-90b3-b025e8fa54c3.png)
![image](https://user-images.githubusercontent.com/64076196/144227287-4a929e1c-dc1d-40ce-883b-81939980eb28.png)

**Comment by cuisongliu** [comment]
sealos的执行命令是什么

**Comment by marcfang** [comment]
> sealos的执行命令是什么

./sealos init --kubeadm-config /home/kubeadm-config.yaml.tmpl --master 192.168.11.51 --user ${用户名} --passwd ${密码} --pkg-url /home/kube1.18.9.tar.gz --version v1.18.9；
步骤3中已指出。

**Comment by oldthreefeng** [comment]
@marcfang   你配置文件config 的 name随便改。 和集群的clusterName不是一个概念。

**Comment by zishen** [comment]
> > sealos的执行命令是什么
> 
> ./sealos init --kubeadm-config /home/kubeadm-config.yaml.tmpl --master 192.168.11.51 --user ${用户名} --passwd ${密码} --pkg-url /home/kube1.18.9.tar.gz --version v1.18.9； 步骤3中已指出。

Is clusterName set ok, after this issue?
