### ISSUE TITLE
优化token功能

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#731]
//  192.168.0.200:6443 --token 9vr73a.a8uxyaju799qwdjv --discovery-token-ca-cert-hash sha256:7c2e69131a36ae2a042a339b33381c6d0d43887e2de83720eff5359e26aec866 --experimental-control-plane --certificate-key f8902e114ef118304e561c3ecd4d0b543adc226b7a07f675f56564185ffe0c07

1. join-token (secrets中获取)
2. discovery-token-ca-cert-hash  
   ```
   publicKeyPins := make([]string, 0, len(caCerts))
	for _, caCert := range caCerts {
		publicKeyPins = append(publicKeyPins, pubkeypin.Hash(caCert))
	}
   ```
3. certificate-key
 
   kubeadm 数据 kubeadm-certs 
  ```
   //CreateCertificateKey returns a cryptographically secure random key
   func CreateCertificateKey() (string, error) {
	randBytes, err := cryptoutil.CreateRandBytes(kubeadmconstants.CertificateKeySize)
	if err != nil {
		return "", err
	}
	return hex.EncodeToString(randBytes), nil
  }
  ```

**Comment by cuisongliu** [comment]
1. 使用之前必须执行 “kubeadm init phase upload-certs --upload-certs”，k8s会把admin相关证书全部存到kube-system 的kubeadm-certs 的secrets中，并使用随机生成的certificate-key进行加密，并对bootstrap-token进行rbac认证
2. 当join拿到随机生成的certificate-key可以对数据解密，拿join-token的token进行获取数据
3. discovery-token-ca-cert-hash 只是个ca的hash可以直接hash即可

我们优化
1. discovery-token-ca-cert-hash 直接拿到ca的hash
2. certificate-key 我们手动去做upload 即可
3. join-token直接存储secret即可

**Comment by fanux** [comment]
我觉得OK

**Comment by cuisongliu** [comment]
sealctl 完成这个feature
