### ISSUE TITLE
添加master节点，新节点kubelet无法启动

### ISSUE THREAD

**Issue by 46797536** [fanux/sealos#744]
原先3个master节点，宕机一台；已成功移除故障的etcd节点
![image](https://user-images.githubusercontent.com/46241382/145372510-18fdedd2-4116-49e6-bbf5-5d9c7da11a73.png)

通过clean清理节点并重启
重新加入节点
![image](https://user-images.githubusercontent.com/46241382/145372834-21c85f2c-6396-48d8-9a6e-4860788a6081.png)
新节点kubelet无法启动
![image](https://user-images.githubusercontent.com/46241382/145372892-2e8cd30f-ec47-4b2c-a4c0-7c8c3618136c.png)

**Comment by cuisongliu** [comment]
是把整个集群清空后重装的么？
<img width="768" alt="image" src="https://user-images.githubusercontent.com/4150905/145600915-40cd3180-7e54-4943-aaea-ee4d41076904.png">
安装的时候报错了我看到。
