### ISSUE TITLE
kubernetes 1.20+的问题

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#746]
对于目前1.20强制使用containerd的需求引发的问题

1. 本身安装docker无法使用
2. app依赖docker 模块无法使用

可以提出你的修改建议，在这里讨论一下这个需求

**Comment by freemankevin** [comment]
会吗？我的都正常使用docker呢？现在用1.20.4/1.20.6

**Comment by cuisongliu** [comment]
> 会吗？我的都正常使用docker呢？现在用1.20.4/1.20.6

`/usr/local/bin/ctr` 目前只是判断这个文件是否存在，并不优雅。
