### ISSUE TITLE
ReadMe中的拷贝按钮内容错误

### ISSUE THREAD

**Issue by liruishan** [fanux/sealos#802]
**哪个命令或者组件**
ReadMe

**描述这个缺陷**
ReadMe中的拷贝按钮内容错误
当我直接使用下图中的按钮复制内容时，复制的内容为下图中txt所示：
![image](https://user-images.githubusercontent.com/41253645/147718179-3e59f473-ae74-495d-9ebb-eaefd2738e78.png)
![image](https://user-images.githubusercontent.com/41253645/147718191-f918a660-b57a-4409-9cd0-5cd34f8dd3ef.png)
当我直接拷贝到linux系统时，会出现报错：
![image](https://user-images.githubusercontent.com/41253645/147718241-1c7b3b33-220f-4b52-97c6-21fda25cbc38.png)

**重现步骤（如果有需要可以附加图片）**
1. 
...

**测试结果**
1. 
2. 
3.

**期望结果**
1. 期望出现 xxx
   前置条件: xxx
   操作步骤:
   1. xxx
   2. xxx
   预期结果:
   1. xxx
   2. xxx

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.16.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
- 集群规模:   eg 3master 3node
- 附加说明: istio,dashboard ...

**Comment by cuisongliu** [comment]
这个是得自己改一下的，因为服务器密码每个都不一样，需要修改密码才能执行。
