### ISSUE TITLE
这个是必须付费才能使用的是吗

### ISSUE THREAD

**Issue by zhuxindong** [fanux/sealos#811]
这个是必须付费才能使用的是吗

**Comment by cuisongliu** [comment]
sealos是开源的，离线包付费，提供试用版1.22.0

**Comment by wordpeaceyes** [comment]
> sealos是开源的，离线包付费，提供试用版1.22.0

离线包内大概是什么内容

**Comment by oldthreefeng** [comment]
> 离线包内大概是什么内容

安装k8s需要的所有内容。
