### ISSUE TITLE
免费和收费什么区别

### ISSUE THREAD

**Issue by cubita-io** [fanux/sealos#813]
**那个命令或者组件**
eg. sealos init , sealos install , kubernetes cni, docker  and so on 

**描述你的问题**
详细描述出你的问题内容xxxx.

**你看到的一些参考资料**
eg. 文档的引用xxxx

**Comment by cyl-007** [comment]
免费仅提供v1.22.0版本试用版，该版本不建议上生产环境；付费版可以下载x86或者arm架构的全量的k8s版本。
