### ISSUE TITLE
按1 master 3node 安装部署后应用只能在单节点上运行

### ISSUE THREAD

**Issue by ge2009** [fanux/sealos#816]
sealos 版本：Version: 3.3.9-rc.10
部署命令：sealos init --passwd '****' \
	--master 192.168.0.160  \
	--node 192.168.0.161 --node 192.168.0.162 --node 192.168.0.163 \
	--user root \
	--pkg-url /root/kube1.23.1.tar.gz \
	--version v1.23.1

部署sealos版本：v1.23.1
部署yml脚本：kubectl apply -f https://kuboard.cn/install-script/kuboard.yaml
kubectl apply -f https://addons.kuboard.cn/metrics-server/0.3.7/metrics-server.yaml

问题现象：
无论是kuboard还是bashboard都只能在其中的某一个节点访问（如192.168.0.161）访问，master节点192.168.0.160均不能访问，只能是单节点访问。

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/13895712/148007268-de5523ba-8a99-4566-87f5-b10163f62ddb.png">

<img width="877" alt="image" src="https://user-images.githubusercontent.com/13895712/148007295-4b72faab-ba49-4274-9d98-402ecd703ad1.png">

master上的ipvsadm的结果如下图
<img width="586" alt="image" src="https://user-images.githubusercontent.com/13895712/148007381-43af5acb-fe61-4b01-93de-27c59d28522e.png">

**Comment by ge2009** [comment]
后面把CNI更换为Flannel后就正常了。

**Comment by zhangguanzhang** [comment]
如果你的机器是在openstack上的话，可能需要看下我这个文章 https://zhangguanzhang.github.io/2018/07/18/ecs-vip/
