### ISSUE TITLE
1master和1node在一个局域网内，无法建立k8s集群

### ISSUE THREAD

**Issue by njxz** [fanux/sealos#818]
**哪个命令或者组件**
运行sealos init 后，

**描述这个缺陷**

sealos显示成功，但是实际node 无法连接到服务器

**测试结果**

![1](https://user-images.githubusercontent.com/16254670/148039344-9aea166f-f02a-48cd-b8ae-aa6238500ade.jpg)

![2](https://user-images.githubusercontent.com/16254670/148039364-5996e0a8-085f-4f4f-abd3-38b825ccab4b.png)

**运行环境**

- Docker版本:   20.10
- Kubernetes版本 : kube1.16.12.tar.gz
- sealos版本: v3.3.9-rc9
- 操作系统:  ecentos7
- 集群规模:    1master 1node

**Comment by njxz** [comment]
[sealos.log](https://github.com/fanux/sealos/files/7806690/sealos.log)

**Comment by cuisongliu** [comment]
node 无法连接到服务器  什么意思

**Comment by njxz** [comment]
![图片](https://user-images.githubusercontent.com/16254670/148173356-49a9f504-1ab2-4390-87f6-36814324fc56.png)
![图片](https://user-images.githubusercontent.com/16254670/148173381-153e637b-2cce-4363-8c3d-4914d567ea02.png)

**Comment by oldthreefeng** [comment]
了解一下 k8s的 rbac授权就明白了。 

集群的权限 需要单独授权。

**Comment by ls-2018** [comment]
你将config文件里的地址改成master的地址
