### ISSUE TITLE
k8s 使用flannel网络插件，coredns安装一直pending

### ISSUE THREAD

**Issue by houjibofa2050** [fanux/sealos#829]
sealos init --passwd 123456 --master 192.168.81.160  --node 192.168.81.161 --pkg-url /opt/sealos/kube1.19.16.tar.gz --version v1.19.16 --without-cni true  --podcidr 10.244.0.0/16

k8s 使用flannel网络插件，coredns安装一直pending

flannel.yaml 使用的是官方的yaml文件

报错信息
![lQLPDhsLnqOepnfNAkfNBjOwUMJuWYwZwq8B47X8hcAMAA_1587_583](https://user-images.githubusercontent.com/19608744/148916516-dc8daa95-72b9-4667-84eb-35bea326fe4d.png)

**Comment by oldthreefeng** [comment]
@zhangguanzhang  麻烦看一下这个问题， flannel的报错

**Comment by houjibofa2050** [comment]
解决方案:1.下载cni的二进制安装包 https://github.com/containernetworking/plugins/releases/download/v0.8.3/cni-plugins-linux-amd64-v0.8.3.tgz
2.每个机器创建文件夹  opt/cni/bin /etc/cni/net.d -p
3.copy文件夹 scp -r /opt/cni/bin/*  root@x.x.x.x:/opt/cni/bin/
4.部署flannel.yaml文件  kubectl apply -f flannel.yaml文件

**Comment by oldthreefeng** [comment]
@houjibofa2050  新版的flannel不给装cni的二进制了么？ 我记得老版本是flannel给装的

**Comment by zhangguanzhang** [comment]
最新版本的cni plugins里没flannel的二进制了

**Comment by 1447443432** [comment]
我看sealos中没有 flannel网络 配置信息，是有哪个参数控制启用哪种网络插件吗
