### ISSUE TITLE
node notready

### ISSUE THREAD

**Issue by cc20110101** [fanux/sealos#831]
**哪个命令或者组件**
  sealos init --passwd 'as12bc-sds1djhk23' --master 192.168.104.16 --node 192.168.104.19 --pkg-url /root/kube1.22.0.tar.gz --version v1.22.0

**描述这个缺陷**
简短描述这个缺陷内容.
随意安装了下，就发现体验不咋样，感觉生产不靠谱，确定有人敢用？？
1、
主机node设置了taint 导致calico插件起不来，导致node notready
  Warning  FailedScheduling  81s   default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.

2、主机名得提前设置，体验差；
3、ssh端口不同咋设置；
4、主机用户名不同咋设置；
5、镜像安装，为何不二进制安装；
6、etcd单机版吗；

- 操作系统:  eg. centos7

**Comment by cc20110101** [comment]
要重启containerd才行

**Comment by imdingtalk** [comment]
1. 你描述的只是现象，不是根本原因
234应该文档已经说明了
5 这是开源产品，不是商业产品，就算是有商业部分。。又为何要二进制安装。？。其次，这个有二进制安装的，也有镜像安装的。  你问为何不是二进制安装，，这怎么问出来的
6   建议再熟悉下架构

**Comment by fanux** [comment]
1. sealer不会设置taint 其它原因导致你的node not ready的
2. 直接篡改用户的主机名很自作主张，check 检查到重复 fail fast让用户自行修改才正常，或者像sealer的插件方式修改，而且主机名的管理并非sealos范畴
3. 端口直接 --master 192.168.104.16:2222
4. 只支持root，因为要调整内核参数
5. 为何不二进制 上个世纪的人才会这样问，太低级不回答
6. 多master就是高可用

最后 sealos已经服务数千家企业客户在生产环境中使用，包含互联网头部客户阿里 百度 华为等。 他们是敢用了  你敢不敢随你
