### ISSUE TITLE
NVIDIA GPU使用nvidia-docker

### ISSUE THREAD

**Issue by cc20110101** [fanux/sealos#833]
NVIDIA GPU使用nvidia-docker，k8s 20+高版本去掉docker后，怎么使用GPU呢？

**Comment by cc20110101** [comment]
解决

**Comment by pokitpeng** [comment]
> 解决

老哥怎么解决的，求教

**Comment by cc20110101** [comment]
> > 解决
> 
> 老哥怎么解决的，求教

一、驱动安装

GPU主机执行：
./NVIDIA-Linux-x86_64-440.33.01.run --uninstall
./NVIDIA-Linux-x86_64-440.33.01.run -no-x-check -no-nouveau-check -no-opengl-files //只有禁用opengl这样安装才不会出现循环登陆的问题

-no-x-check：安装驱动时关闭X服务
-no-nouveau-check：安装驱动时禁用nouveau
-no-opengl-files：只安装驱动文件，不安装OpenGL文件


二、k8s使用GPU--docker运行时
解压nvidia_docker.tar.gz包，里面有nvidia_docker的rpm包，安装即可
/etc/docker/daemon.json中加入"default-runtime": "nvidia":
[root@k8s-node3 docker_packages]# cat /etc/docker/daemon.json 
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "insecure-registries": ["192.168.202.61"]
}

重启docker服务： systemctl restart docker

二、k8s使用GPU--containerd运行时
Kubernetes官方发布公告，宣布自v1.20起放弃对Docker的支持，届时用户将收到Docker弃用警告，并需要改用其他容器运行时；预计1.24版本删除dockershim。
Kubernetes是通过CRI来对接容器运行时的，而Docker本身是没有实现CRI的，所以Kubernetes内置了一个“为Docker提供CRI支持” 的dockershim组件。现在Kubernetes宣布不再维护这个组件了，大概的意思就是：Docker虽然好用，但那是对人来说的，Kubernetes又不是人，不需要那些花里胡哨的东西！
Kubernetes这是话里有话，说白了就是：我以前为了兼容你，我集成在我自己这里，现在我就想自己单纯一点，要么你自己写CRI的接口要么就再见。

#根据https://nvidia.github.io/nvidia-container-runtime/官网配置yum源，我们下载rpm到本地centos7并压缩成nvidia-container-runtime.tar.gz离线包，后续离线安装：
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.repo | tee /etc/yum.repos.d/nvidia-container-runtime.repo
yum install --downloadonly --downloaddir=./nvidia-container-runtime   nvidia-container-runtime
tar -zcvf nvidia-container-runtime.tar.gz nvidia-container-runtime

若是ubuntu20.04则：
curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list |  tee /etc/apt/sources.list.d/nvidia-container-runtime.list
apt-get update
apt-get -d install nvidia-container-runtime
mkdir nvidia-container
mv  /var/cache/apt/archives/*.deb  ./nvidia-container
tar -zcvf nvidia-container-runtime-ubuntu20.04.tar.gz  nvidia-container

解压nvidia-container-runtime.tar.gz包，安装rpm包即可
配置Containerd使用Nvidia container runtime
如果 /etc/containerd 目录不存在，就先创建它：
$ mkdir /etc/containerd
生成默认配置：
$ containerd config default > /etc/containerd/config.toml
Kubernetes 使用设备插件（Device Plugins）[3] 来允许 Pod 访问类似 GPU 这类特殊的硬件功能特性，但前提是默认的 OCI runtime 必须改成 nvidia-container-runtime，需要修改/etc/containerd/config.toml的内容如下：

...
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runtime.v1.linux" # 将此处 runtime_type 的值io.containerd.runc.v2改成 io.containerd.runtime.v1.linux
...
  [plugins."io.containerd.runtime.v1.linux"]
    shim = "containerd-shim"
    runtime = "nvidia-container-runtime" # 将此处 runtime 的值runc改成 nvidia-container-runtime
...

修改运行时：
sed -i 's/runtime_type = "io.containerd.runc.v2"/runtime_type = "io.containerd.runtime.v1.linux"/g' /etc/containerd/config.toml
sed -i 's/runtime = "runc"/runtime = "nvidia-container-runtime"/g' /etc/containerd/config.toml

#修改仓库：
 # sed -i 's/registry.mirrors."docker.io"/registry.mirrors."192.168.202.61"/g' /etc/containerd/config.toml
# sed -i 's/"https:\/\/registry-1.docker.io"/"http:\/\/192.168.202.61"/g' /etc/containerd/config.toml

重启 containerd 服务:  systemctl restart containerd

#参考https://blog.csdn.net/alex_yangchuansheng/article/details/110675615

三、k8s安装GPU插件
tar -zxvf k8s-device-plugin-0.10.0.tar.gz
kubectl apply -f k8s-device-plugin-0.10.0/deployments/static/nvidia-device-plugin.yml    #文件镜像改成自己仓库地址


参考：https://github1s.com/NVIDIA/k8s-device-plugin/releases
下载：https://github.com/NVIDIA/k8s-device-plugin/releases

**Comment by pokitpeng** [comment]
> > > 解决
> > 
> > 
> > 老哥怎么解决的，求教
> 
> 一、驱动安装
> 
> GPU主机执行： ./NVIDIA-Linux-x86_64-440.33.01.run --uninstall ./NVIDIA-Linux-x86_64-440.33.01.run -no-x-check -no-nouveau-check -no-opengl-files //只有禁用opengl这样安装才不会出现循环登陆的问题
> 
> -no-x-check：安装驱动时关闭X服务 -no-nouveau-check：安装驱动时禁用nouveau -no-opengl-files：只安装驱动文件，不安装OpenGL文件
> 
> 二、k8s使用GPU--docker运行时 解压nvidia_docker.tar.gz包，里面有nvidia_docker的rpm包，安装即可 /etc/docker/daemon.json中加入"default-runtime": "nvidia": [root@k8s-node3 docker_packages]# cat /etc/docker/daemon.json { "default-runtime": "nvidia", "runtimes": { "nvidia": { "path": "nvidia-container-runtime", "runtimeArgs": [] } }, "insecure-registries": ["192.168.202.61"] }
> 
> 重启docker服务： systemctl restart docker
> 
> 二、k8s使用GPU--containerd运行时 Kubernetes官方发布公告，宣布自v1.20起放弃对Docker的支持，届时用户将收到Docker弃用警告，并需要改用其他容器运行时；预计1.24版本删除dockershim。 Kubernetes是通过CRI来对接容器运行时的，而Docker本身是没有实现CRI的，所以Kubernetes内置了一个“为Docker提供CRI支持” 的dockershim组件。现在Kubernetes宣布不再维护这个组件了，大概的意思就是：Docker虽然好用，但那是对人来说的，Kubernetes又不是人，不需要那些花里胡哨的东西！ Kubernetes这是话里有话，说白了就是：我以前为了兼容你，我集成在我自己这里，现在我就想自己单纯一点，要么你自己写CRI的接口要么就再见。
> 
> #根据[https://nvidia.github.io/nvidia-container-runtime/官网配置yum源，我们下载rpm到本地centos7并压缩成nvidia-container-runtime.tar.gz离线包，后续离线安装：](https://nvidia.github.io/nvidia-container-runtime/%E5%AE%98%E7%BD%91%E9%85%8D%E7%BD%AEyum%E6%BA%90%EF%BC%8C%E6%88%91%E4%BB%AC%E4%B8%8B%E8%BD%BDrpm%E5%88%B0%E6%9C%AC%E5%9C%B0centos7%E5%B9%B6%E5%8E%8B%E7%BC%A9%E6%88%90nvidia-container-runtime.tar.gz%E7%A6%BB%E7%BA%BF%E5%8C%85%EF%BC%8C%E5%90%8E%E7%BB%AD%E7%A6%BB%E7%BA%BF%E5%AE%89%E8%A3%85%EF%BC%9A) distribution=$(. /etc/os-release;echo $ID$VERSION_ID) curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.repo | tee /etc/yum.repos.d/nvidia-container-runtime.repo yum install --downloadonly --downloaddir=./nvidia-container-runtime nvidia-container-runtime tar -zcvf nvidia-container-runtime.tar.gz nvidia-container-runtime
> 
> 若是ubuntu20.04则： curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | sudo apt-key add - distribution=$(. /etc/os-release;echo $ID$VERSION_ID) curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | tee /etc/apt/sources.list.d/nvidia-container-runtime.list apt-get update apt-get -d install nvidia-container-runtime mkdir nvidia-container mv /var/cache/apt/archives/*.deb ./nvidia-container tar -zcvf nvidia-container-runtime-ubuntu20.04.tar.gz nvidia-container
> 
> 解压nvidia-container-runtime.tar.gz包，安装rpm包即可 配置Containerd使用Nvidia container runtime 如果 /etc/containerd 目录不存在，就先创建它： $ mkdir /etc/containerd 生成默认配置： $ containerd config default > /etc/containerd/config.toml Kubernetes 使用设备插件（Device Plugins）[3] 来允许 Pod 访问类似 GPU 这类特殊的硬件功能特性，但前提是默认的 OCI runtime 必须改成 nvidia-container-runtime，需要修改/etc/containerd/config.toml的内容如下：
> 
> ... [plugins."io.containerd.grpc.v1.cri".containerd.runtimes] [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc] runtime_type = "io.containerd.runtime.v1.linux" # 将此处 runtime_type 的值io.containerd.runc.v2改成 io.containerd.runtime.v1.linux ... [plugins."io.containerd.runtime.v1.linux"] shim = "containerd-shim" runtime = "nvidia-container-runtime" # 将此处 runtime 的值runc改成 nvidia-container-runtime ...
> 
> 修改运行时： sed -i 's/runtime_type = "io.containerd.runc.v2"/runtime_type = "io.containerd.runtime.v1.linux"/g' /etc/containerd/config.toml sed -i 's/runtime = "runc"/runtime = "nvidia-container-runtime"/g' /etc/containerd/config.toml
> 
> #修改仓库：
> 
> # sed -i 's/registry.mirrors."docker.io"/registry.mirrors."192.168.202.61"/g' /etc/containerd/config.toml
> # sed -i 's/"https://registry-1.docker.io"/"http://192.168.202.61"/g' /etc/containerd/config.toml
> 重启 containerd 服务: systemctl restart containerd
> 
> #参考https://blog.csdn.net/alex_yangchuansheng/article/details/110675615
> 
> 三、k8s安装GPU插件 tar -zxvf k8s-device-plugin-0.10.0.tar.gz kubectl apply -f k8s-device-plugin-0.10.0/deployments/static/nvidia-device-plugin.yml #文件镜像改成自己仓库地址
> 
> 参考：https://github1s.com/NVIDIA/k8s-device-plugin/releases 下载：https://github.com/NVIDIA/k8s-device-plugin/releases

多谢，看来还是要替换重启，不能在第一次部署就做到把nvidia-runtime写进去😭
