### ISSUE TITLE
安装之后一直coredns pending 

### ISSUE THREAD

**Issue by QuentinLee** [fanux/sealos#834]
**哪个命令或者组件**
![image](https://user-images.githubusercontent.com/4740360/149308121-643c48a6-0302-4051-b33a-269dee39310e.png)

- Kubernetes版本 : kube1.23.1.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  eg. centos7
- 运行模式:  eg. 物理机 （内存 100g, cpu 10核 ,存储 10t）， 虚拟机 ( virbox, 内存 10gb, cpu 2核 ,存储 100gb ) , 云 ( aws,内存 10gb, cpu 2核 ,存储 100gb )
[sealos.log](https://github.com/fanux/sealos/files/7861908/sealos.log)

**Comment by zhangguanzhang** [comment]
```
kubectl -n kube-system describe pod xxx
```

**Comment by cyl-007** [comment]
重启containerd后，问题解决，关闭该单

**Comment by zhucan** [comment]
> 重启containerd后，问题解决，关闭该单

@cyl-007 这个原因有定位吗？

**Comment by zhucan** [comment]
https://github.com/containerd/containerd/blob/f18880a0edecf616a3552e34394b3619ca8e5647/pkg/cri/server/cni_conf_syncer.go#L86 sealos clean的时候不会卸载containerd，但是会删除/etc/cni这个目录，重新部署的的时候会创建这个目录，但是containerd现在忽略了这个event，所以要重启containerd重新加载cni plugin.

**Comment by 258532431** [comment]
重启containerd不起作用

**Comment by 258532431** [comment]
【node：k8s-master01】
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Sat, 03 Aug 2024 14:50:00 +0800   Sat, 03 Aug 2024 11:42:36 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Sat, 03 Aug 2024 14:50:00 +0800   Sat, 03 Aug 2024 11:42:36 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Sat, 03 Aug 2024 14:50:00 +0800   Sat, 03 Aug 2024 11:42:36 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Sat, 03 Aug 2024 14:50:00 +0800   Sat, 03 Aug 2024 11:42:36 +0800   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

【pod：registry.k8s.io/coredns/coredns:v1.10.1】
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  74s (x39 over 3h11m)  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
