### ISSUE TITLE
ctr events看时间不是北京时间

### ISSUE THREAD

**Issue by jdxia** [fanux/sealos#836]
![image](https://user-images.githubusercontent.com/23069626/149924033-6ab16edc-17d7-49ac-99f5-9f65d59f6e61.png)
![image](https://user-images.githubusercontent.com/23069626/149924081-482fddc0-eb3c-4604-9d8c-1d72acc37a6e.png)

这几个命令
`root@box1:~ # ctr events`
`ctr -n k8s.io c ls`

**Comment by jdxia** [comment]
本机时间是北京时间, 但是容器事件里面显示不是

**Comment by cuisongliu** [comment]
这个需要看一下containerd的配置了。目前只是默认配置，需要调整
