### ISSUE TITLE
银河麒麟V4 arm平台启动报错

### ISSUE THREAD

**Issue by helloxizhao** [fanux/sealos#838]
架构为1master+1slave，mater节点启动之后，kubelet报错如下

![image](https://user-images.githubusercontent.com/19920436/150090614-7042a707-76d2-4a7f-bd6b-202e8bc41919.png)

**Comment by oldthreefeng** [comment]
apiserver 没起来。

**Comment by helloxizhao** [comment]
是的，APIserver没启动成功，apiserver需要etcd,etcd是容器部署的，也是启动失败

**Comment by oldthreefeng** [comment]
0. etcd日志有么？
1.安装过程日志有么？

**Comment by helloxizhao** [comment]
0、
![image](https://user-images.githubusercontent.com/19920436/150092479-b8675d29-9d24-42c3-a17c-b65e1975300e.png)
1、安装过程没问题，是安装完成之后，我重启服务器发生的错误

**Comment by oldthreefeng** [comment]
重启服务器报错 不是很正常么？ 
你期望单master节点故障自愈么？ 那还要高可用干嘛

**Comment by helloxizhao** [comment]
单节点，master重启失败，我启动之后，那集群就挂了，我们自己的无论单节点，多节点服务器启动成功，集群还是可以恢复，这个重启就失败了，那么弱鸡吗，那还怎么用

**Comment by oldthreefeng** [comment]
嗯 ， 单节点就是这么弱鸡。

**Comment by helloxizhao** [comment]
那如果高可用呢，我三个master 都重启呢，会故障吗

**Comment by helloxizhao** [comment]
arm只有两个服务器，高可用没测试 不知道是不是有问题

**Comment by oldthreefeng** [comment]
同时重启， 肯定故障。  这种基础建设的东西， 重启都是保证集群可用之后才去做的。 

比如 es， 集群扩容缩容， green 后 操作， 你全部宕机， es肯定也会有问题， 那你说es也弱鸡了？ 
比如etcd 
太多了。

**Comment by helloxizhao** [comment]
我指的弱鸡，是你的这个单节点master，master重启到导致整个集群crash，难道这个不弱鸡吗，那资源不充足的情况就直接不能用了吗，那就只能放弃你这个工具了

**Comment by oldthreefeng** [comment]
和工具无关， 你用 rancher / kubesphere / kubeadm / kubekey 等 工具。 都是一样的结果。 
 你放弃使用k8s吧。

**Comment by helloxizhao** [comment]
我放弃使用的这个垃圾工具了，我们自己X86的完全没问题，支持的真是无语了。你的工具和k8s无关谢谢，自己垃圾不要关联k8s哦谢谢，你这个收费，就这种技术支持我只能呵呵一笑，自己支持的差还能这样子理直气壮，祝你越来越好，加油

**Comment by oldthreefeng** [comment]
谢谢你的使用。

**Comment by cuisongliu** [comment]
@helloxizhao  实在抱歉，需要更详细了解为什么重启后导致集群clash了。这个工具只是帮你更快速启动集群，具体clash的原因需要进一步检查。如果我们的服务没有让您满意，可以联系QQ群稳定负责人可以退款之类的，多谢支持。

**Comment by helloxizhao** [comment]
日志就是上面的输出的，单节点master重启没有拉起etcd,导致整个失败，原来发现过单点重启会有问题，所以这次重启了，以为高版本处理这个问题了，结果还是有报错
master hosts
![image](https://user-images.githubusercontent.com/19920436/150103373-6ddc6a8d-84c0-47b5-9a58-697b35287696.png)
slave hosts
![image](https://user-images.githubusercontent.com/19920436/150103487-22db81c8-62f8-46e0-afbb-c35ecc154c7d.png)

**Comment by cuisongliu** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/4150905/150105784-10cca21b-fb1e-4093-bf96-5c9753f6e903.png">
这个etc的配置有点问题啊。

**Comment by fanux** [comment]
> <img alt="image" width="762" src="https://user-images.githubusercontent.com/4150905/150105784-10cca21b-fb1e-4093-bf96-5c9753f6e903.png">
> 
> 这个etc的配置有点问题啊。

像是没清理干净或者代码bug导致

**Comment by cuisongliu** [comment]
ubuntu resolv.conf丢失导致

**Comment by cuisongliu** [comment]
```
if [ "18.04" = "$osVersion" ];then
        if  systemctl status systemd-resolved.service >/dev/null 2>&1
        then
            systemctl stop systemd-resolved.service
            systemctl disable systemd-resolved.service
            rm /etc/resolv.conf
            cp /run/systemd/resolve/resolv.conf /etc/resolv.conf
        fi
    fi
```

**Comment by helloxizhao** [comment]
我这个的系统是16.04，也需要适配下
![image](https://user-images.githubusercontent.com/19920436/150254288-7977d27a-976c-4750-8247-4681a5cd8416.png)

**Comment by helloxizhao** [comment]
银河麒麟V4对应的link 位置为 /var/run/NetworkManager/resolv.conf
![image](https://user-images.githubusercontent.com/19920436/150255162-454c83bf-52e5-4d54-ae0a-9ebe4602a0ca.png)

**Comment by cuisongliu** [comment]
OK，先暂时这么解决 后面看要不要适配一下。 这个issue就先关了哈
