### ISSUE TITLE
虚拟机关机后无法重启kubelet

### ISSUE THREAD

**Issue by KitherRunner** [fanux/sealos#841]
**哪个命令或者组件**
systemcrl start kubelet 失败

**描述这个缺陷**
![1643116666421_A6ACFF0C-FA8B-495d-936F-31563C933E24](https://user-images.githubusercontent.com/46001931/150987041-7ac64527-4282-4e18-bcee-c50f99ffc76e.png)

![image](https://user-images.githubusercontent.com/46001931/150988002-12425a84-17ab-4ded-bb54-5076b5607209.png)

selinux swap 已经关闭，containerd状态正常，还是无法启动

**运行环境**

- Kubernetes版本 : kube1.22.0.tar.gz
- sealos版本: 3.3.9-rc.10
- 操作系统:  centos7.6
- 运行模式:   虚拟机 ( vmware, 内存 8gb, cpu 2核 ,存储 80gb )
- 集群规模:   1master 2node

**Comment by zhangguanzhang** [comment]
第一张图右侧的日志复制上来
```
jounalctl -xe --no-pager -u kubelet
```

**Comment by KitherRunner** [comment]
> 日志如下：
1月 26 21:50:26 master systemd[1]: kubelet.service holdoff time over, scheduling restart.
1月 26 21:50:26 master systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished shutting down.
1月 26 21:50:26 master systemd[1]: Starting kubelet: The Kubernetes Node Agent...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has begun starting up.
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: * Applying /usr/lib/sysctl.d/00-system.conf ...
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.bridge.bridge-nf-call-ip6tables = 0
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.bridge.bridge-nf-call-iptables = 0
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.bridge.bridge-nf-call-arptables = 0
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: * Applying /usr/lib/sysctl.d/10-default-yama-scope.conf ...
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: kernel.yama.ptrace_scope = 0
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: * Applying /usr/lib/sysctl.d/50-default.conf ...
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: kernel.sysrq = 16
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: kernel.core_uses_pid = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: kernel.kptr_restrict = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.conf.default.rp_filter = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.conf.all.rp_filter = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.conf.default.accept_source_route = 0
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.conf.all.accept_source_route = 0
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.conf.default.promote_secondaries = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.conf.all.promote_secondaries = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: fs.protected_hardlinks = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: fs.protected_symlinks = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: * Applying /etc/sysctl.d/99-sysctl.conf ...
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: * Applying /etc/sysctl.d/k8s.conf ...
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.bridge.bridge-nf-call-ip6tables = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.bridge.bridge-nf-call-iptables = 1
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.conf.all.rp_filter = 0
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: * Applying /etc/sysctl.conf ...
1月 26 21:50:26 master kubelet-pre-start.sh[3303]: net.ipv4.ip_forward = 1
1月 26 21:50:26 master systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished starting up.
--
-- The start-up result is done.
1月 26 21:50:26 master kubelet[3325]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
1月 26 21:50:26 master kubelet[3325]: Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.595109    3325 server.go:199] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should be set in that remote runtime instead"
1月 26 21:50:26 master kubelet[3325]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
1月 26 21:50:26 master kubelet[3325]: Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.610246    3325 server.go:440] "Kubelet version" kubeletVersion="v1.22.0"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.610556    3325 server.go:868] "Client rotation is on, will bootstrap in background"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.613141    3325 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.614454    3325 dynamic_cafile_content.go:155] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.752629    3325 server.go:687] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.752899    3325 container_manager_linux.go:280] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.752996    3325 container_manager_linux.go:285] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver: KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>} {Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerPolicyOptions:map[] ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.753019    3325 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.753029    3325 container_manager_linux.go:320] "Creating device plugin manager" devicePluginEnabled=true
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.753063    3325 state_mem.go:36] "Initialized new in-memory state store"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.753333    3325 kubelet.go:418] "Attempting to sync node with API server"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.753351    3325 kubelet.go:279] "Adding static pod path" path="/etc/kubernetes/manifests"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.753370    3325 kubelet.go:290] "Adding apiserver pod source"
1月 26 21:50:26 master kubelet[3325]: I0126 21:50:26.753385    3325 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
1月 26 21:50:26 master kubelet[3325]: E0126 21:50:26.759616    3325 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://apiserver.cluster.local:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 192.168.15.30:6443: connect: connection refused
1月 26 21:50:26 master kubelet[3325]: E0126 21:50:26.762301    3325 remote_runtime.go:86] "Version from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
1月 26 21:50:26 master kubelet[3325]: E0126 21:50:26.762366    3325 kuberuntime_manager.go:230] "Get runtime version failed" err="get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
1月 26 21:50:26 master kubelet[3325]: E0126 21:50:26.762389    3325 server.go:294] "Failed to run kubelet" err="failed to run Kubelet: failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
1月 26 21:50:26 master systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
1月 26 21:50:26 master systemd[1]: Unit kubelet.service entered failed state.
1月 26 21:50:26 master systemd[1]: kubelet.service failed.

**Comment by cuisongliu** [comment]
CONTAINERD 没启动

**Comment by KitherRunner** [comment]
执行：
rm /etc/containerd/config.toml
systemctl restart containerd
