### ISSUE TITLE
麒麟v10系统 sealos init  没有安装calico

### ISSUE THREAD

**Issue by BingGuo123** [fanux/sealos#843]
sealos init  --master 172.21.93.103 --user root  --passwd  '*******' --pkg-url /root/kube1.22.6.tar.gz --version 1.22.6
**描述你的问题**
操作系统：4.19.90-23.15.v2101.ky10.aarch64（KYLINSOFT）（gcc version 7.3.0）
内核：4.19.90-23.15.v2101.ky10.aarch64
sealos init  没有安装calico

**Comment by cuisongliu** [comment]
这个不应该是没起来吧。你看一下ds有没有正常
