### ISSUE TITLE
集群初始化后有master节点失败，使用clean清理再次join会提示缺少必须的crictl导致join不成功

### ISSUE THREAD

**Issue by xiaochunping** [fanux/sealos#845]
**哪个命令或者组件**
sealos init --master 192.168.x.1 --master 192.168.x.3 --node 192.168.x.3 --version v1.20.0 --pkg-url /root/sealyun/kube1.20.0.tar.gz 
sealos clean --master 192.168.x.1
sealos join --master 192.168.x.1

**描述这个缺陷**
初始化sealos init如果有节点异常，就像这样
![TF0A1LE24A$BXT`VLHPQ909](https://user-images.githubusercontent.com/4407539/152963015-d51b89bb-c3c8-4f58-816a-7810622bab54.jpg)
，排查原因是apiserver没正常启动。然后使用sealos clean --master，再次加入sealos join --master会一直失败，提示没有crictl。

原因：clean的时候会删除crictl，导致再次join的时候需要手动copy crictl才能join成功。

**Comment by cuisongliu** [comment]
https://github.com/fanux/sealos/blob/6f9324af3c061007daa40793a5bc44a3bce3dd67/install/clean.go#L181


这块可以提个pr

**Comment by MTILM** [comment]
> https://github.com/fanux/sealos/blob/6f9324af3c061007daa40793a5bc44a3bce3dd67/install/clean.go#L181
> 
> 这块可以提个pr

i fix it
