### ISSUE TITLE
安装后coredns状态为CrashLoopBackOff

### ISSUE THREAD

**Issue by longting** [fanux/sealos#846]
**那个命令或者组件**
1个master,2个node
kube1.22.0
centos7.7虚拟机（virtual box）
内核：Linux master 5.16.3-1.el7.elrepo.x86_64 #1 SMP PREEMPT Tue Jan 25 15:54:18 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

**描述你的问题**
![image](https://user-images.githubusercontent.com/5129611/153110997-29600c42-6887-4d86-bb4d-381c9fe80d02.png)

![image](https://user-images.githubusercontent.com/5129611/153111697-f135cdb2-df2e-4e09-8ab1-323f70622b80.png)

![image](https://user-images.githubusercontent.com/5129611/153111326-6d39e20f-a324-42d6-a544-9574082c7625.png)

![image](https://user-images.githubusercontent.com/5129611/153111371-6efd026e-5bb2-4c0d-8e49-2628df935a95.png)

**你看到的一些参考资料**
官方文档

**Comment by zhangguanzhang** [comment]
看下runc版本，如果是忽略kmem的话，应该是kubelet的kmem问题。
[kubelet 和 runc 编译关闭 kmem](https://zhangguanzhang.github.io/2021/04/08/kubelet-runc-disable-kmem/)

**Comment by longting** [comment]
> 看下runc版本，如果是忽略kmem的话，应该是kubelet的kmem问题。 [kubelet 和 runc 编译关闭 kmem](https://zhangguanzhang.github.io/2021/04/08/kubelet-runc-disable-kmem/)

runc version 1.0.0-rc92

**Comment by zhangguanzhang** [comment]
你docker run个limit mem的容器看看报错不，还有1.22.x的最新版本试试，可能是kubelet的问题

**Comment by longting** [comment]
解决方案1：重新安装稳定的linux内核版本，比如5.4
