### ISSUE TITLE
POD 启动后 DNS 有问题

### ISSUE THREAD

**Issue by boqian-nbai** [fanux/sealos#848]
集群各组件运行正常，但是pod 启动后域名解析有问题
e.g. 启动一个ubuntu容器测试，google.com ping 不通， 在 /etc/resolv.conf 添加 nameserver 8.8.8.8 后问题解决
请问这个应该如何解决呢？ 

<img width="669" alt="Screen Shot 2022-02-10 at 12 49 51 AM" src="https://user-images.githubusercontent.com/78975968/153345762-361bcd13-55b8-4a15-a816-7e2674cf578b.png">

**Comment by cuisongliu** [comment]
ubuntu  /etc/resolv.conf 这个的问题

**Comment by cuisongliu** [comment]
```
systemctl stop systemd-resolved.service
systemctl disable systemd-resolved.service
rm /etc/resolv.conf
cp /run/systemd/resolve/resolv.conf /etc/resolv.conf
```

**Comment by boqian-nbai** [comment]
> ```
> systemctl stop systemd-resolved.service
> systemctl disable systemd-resolved.service
> rm /etc/resolv.conf
> cp /run/systemd/resolve/resolv.conf /etc/resolv.conf
> ```

我刚刚修改了coredns的ConfigMap，添加了 forward 8.8.8.8，重启coredns 后 pod DNS正常了

<img width="498" alt="Screen Shot 2022-02-10 at 1 30 18 AM" src="https://user-images.githubusercontent.com/78975968/153350534-5aeebc07-8178-4950-abe7-482b1256d94b.png">

**Comment by cuisongliu** [comment]
根本原因/etc/resolv.conf DNS是有问题的

**Comment by zhangguanzhang** [comment]
coredns的resolv.conf是宿主机的内容
