### ISSUE TITLE
debian10  部署1.23.3 sealos init时从第一个节点scp到第二个节点时报错 

### ISSUE THREAD

**Issue by sunhyy** [fanux/sealos#858]
![1645014883](https://user-images.githubusercontent.com/54571533/154265843-8c052b75-43c3-47be-b3b1-4a9cc80a3315.jpg)

sealos init --master 10.83.0.8 \
    --node 10.83.0.58 \
    --user root \
    --pk /root/.ssh/id_rsa \
    --version v1.23.3 \
    --pkg-url /root/kube1.23.3.tar.gz \
    --podcidr 10.244.0.0/16 \
    --svccidr 10.96.0.0/16
版本：3.3.9-rc.10
系统：Debian10
内核：5.10.0-0.bpo.7-cloud-amd64

**Comment by cuisongliu** [comment]
/usr/bin/sealos 在哪？找不到啊

**Comment by sunhyy** [comment]
/usr/bin/sealos 在10.83.0.8 的/usr/bin/sealos  
kube1.23.3.tar.gz在10.83.0.8的/root/kube1.23.3.tar.gz
sealos init 在10.83.0.8执行
master 10.83.0.8 可以正常安装成功

**Comment by cuisongliu** [comment]
没有拷贝到scp到58上

**Comment by sunhyy** [comment]
是的  看报错就是scp时出问题了
但是centos7同样方式正常
版本是不是暂时不兼容Debian10  5.10内核

**Comment by omaidb** [comment]
我rocky Linux8 也遇到过这个问题,每个节点都复制了kube1.23.4.tar.gz

**Comment by cuisongliu** [comment]
> 我rocky Linux8 也遇到过这个问题,每个节点都复制了kube1.23.4.tar.gz
拷贝sealos不是离线包

**Comment by omaidb** [comment]
> > 我rocky Linux8 也遇到过这个问题,每个节点都复制了kube1.23.4.tar.gz
> > 拷贝sealos不是离线包

好的哈
