### ISSUE TITLE
怎么修改api server的nodeport范围？

### ISSUE THREAD

**Issue by diandiankou** [fanux/sealos#872]
我尝试修改api server的nodeport范围？
使用kubectl -n kube-system edit pod kube-apiserver-xxx，vi /etc/kubernetes/manifests/kube-apiserver.yaml两种方式添加--service-node-port-range=20000-50000配置都没效果？

**Comment by diandiankou** [comment]
我尝试修改api server的nodeport范围？
使用kubectl -n kube-system edit pod kube-apiserver-xxx，vi /etc/kubernetes/manifests/kube-apiserver.yaml两种方式添加--service-node-port-range=20000-50000配置都没效果？

**Comment by diandiankou** [comment]
可以了，vi /etc/kubernetes/manifests/kube-apiserver.yaml设置service-node-port-range=20000-50000，删除原有pod即可，无需自己再kubectl apply -f kube-apiserver.yaml

**Comment by zhangguanzhang** [comment]
不要apply staticPod的yml，它会自动watch到的

**Comment by omaidb** [comment]
为什么不适应ingress的hostNetwork
