### ISSUE TITLE
1主，加1从失败

### ISSUE THREAD

**Issue by fighterhit** [fanux/sealos#875]
**哪个命令或者组件**
sealos join

**描述这个缺陷**

初始化时只有1 master，在master上执行添加从节点命令，执行完成后有错误且显示无从节点

`root@master1:~# sealos join --node 10.246.201.181:32200`
![1c5c9d5fb0d200ff98f698b8daa4b74](https://user-images.githubusercontent.com/23624910/157244095-e09e46b6-5aec-4acc-ac9d-561090a7d33a.png)

再添加却显示已存在
```
root@master1:~# sealos join --node 10.246.201.181:32200
21:02:33 [EROR] [join.go:63] [10.246.201.181:32200] has already exist in your cluster. please check.
root@master1:~# cd^C
root@master1:~# kubectl get node
NAME      STATUS   ROLES                  AGE     VERSION
master1   Ready    control-plane,master   4h38m   v1.22.0
```

**运行环境**

- Docker版本:   -
- Kubernetes版本 : kube1.22.0.tar.gz
- sealos版本: v3.1.0-alpha.2
- 操作系统:  debian10
- 运行模式:   虚拟机 (openstack qemu, 内存 4gb, cpu 2核 ,存储 10gb ) 
- 集群规模:   1master

**Comment by cuisongliu** [comment]
清除节点后重新添加试试。apiserver地址不大对啊，应该是apiserver.cluster.local才对

**Comment by fighterhit** [comment]
> 清除节点后重新添加试试。apiserver地址不大对啊，应该是apiserver.cluster.local才对

不行，后来用 kind 了，现在测了一下 sealer 可以
