### ISSUE TITLE
sealos 升级版本出现集群宕机

### ISSUE THREAD

**Issue by wuxiaoshuang123** [fanux/sealos#877]
![image](https://user-images.githubusercontent.com/49451818/157633310-7fda393e-e098-48be-9342-2be38c552f7e.png)

**Comment by wuxiaoshuang123** [comment]
kubectl 重启失败

**Comment by wuxiaoshuang123** [comment]
![image](https://user-images.githubusercontent.com/49451818/157637543-87256cb9-7c25-4ca9-80f4-cecd4366f5f5.png)

**Comment by zhangguanzhang** [comment]
状态码255是没文件，你手动复制下参数执行下看看
systemctl cat kubelet
手动 source下env 
source /etc/config/kubelet.conf
/usr/bin/kubelet --version
