### ISSUE TITLE
arm版本sealos清理完成后，重新组装显示错误

### ISSUE THREAD

**Issue by cryLuantic** [fanux/sealos#880]
![{{F)~4TKMGGUQ8C2B`QMAX6](https://user-images.githubusercontent.com/49525563/158158802-cde89885-4e20-4723-9096-21cb29121a96.png)

![Uploading 91{F1RM[KTODW(3L0O@3M`H.png…]()

**运行环境**

- Docker版本:   eg. 19.03
- Kubernetes版本 : eg.kube1.22.4.tar.gz
- sealos版本: v3.3.9-rc.11
- 操作系统:  eg. openeuler
- 运行模式:  eg. 物理机 
- 集群规模:   eg 1master 2node

**Comment by zhangguanzhang** [comment]
port 6443 in use

**Comment by cuisongliu** [comment]
集群没有清理干净吧，6443被占用
