### ISSUE TITLE
咨询两个问题

### ISSUE THREAD

**Issue by nlzq** [fanux/sealos#891]
咨询两个问题

1. 这个工具是采用 kubeadm 安装还是二进制安装？

2. 安装其他版本，是需要自行下载对应的资源再打包么？这个版本太高了，不是 docker 不太会用。

**Comment by nlzq** [comment]
“高可用通过ipvs实现的localLB”，不用准备 VIP 么？

**Comment by cyl-007** [comment]
> 咨询两个问题
> 
> 1. 这个工具是采用 kubeadm 安装还是二进制安装？
> 2. 安装其他版本，是需要自行下载对应的资源再打包么？这个版本太高了，不是 docker 不太会用。

1.二进制安装
2.目前只提供1.22.0免费版本，其他版本需要官网（https://www.sealyun.com/goodsList）购买，购买完成可以下载离校包，即可安装；1.20+以上版本使用的containerd,想使用docker，请安装1.20以下版本

**Comment by zhangguanzhang** [comment]
> “高可用通过ipvs实现的localLB”，不用准备 VIP 么？

k8s的高可用可以看我这个文章 https://zhangguanzhang.github.io/2019/03/11/k8s-ha/

**Comment by nlzq** [comment]
> > “高可用通过ipvs实现的localLB”，不用准备 VIP 么？
> 
> k8s的高可用可以看我这个文章 https://zhangguanzhang.github.io/2019/03/11/k8s-ha/

谢谢

**Comment by oldthreefeng** [comment]
底层还是 kubeadm安装， 不是 二进制哦～。  @nlzq
