### ISSUE TITLE
集群初始化时容器cri安装以及cri存储路径用户自定义提议

### ISSUE THREAD

**Issue by tqtcloud** [fanux/sealos#900]
**哪个命令或者组件**
sealos init

**详细描述你的需求/任务**
详细描述你的需求和任务要求
1.能否在初始化集群的时候由用户指定容器运行时为docker还是controllerd？
2.能否在初始化的时候指定kubelet以及docker的数据存储路径？
3.能否自定义资源预留？

**是否有解决方案，如果有请详述**
通过xxx方案来解决该任务（设想）
1.初始化的时候指定kubelet以及docker的数据存储路径。现有想法就在所有机器初始化集群之前，做好存储路径到工作路径的软连接，后续数据会跟随写入到存储路径
以下是我再创建集群后修改docker路径的操作
```sh
 systemctl stop kubelet && systemctl stop docker
  cp -ar /var/lib/docker /data/docker
  mv /var/lib/docker /var/lib/docker-bak
  ln -fs /data/docker /var/lib/docker
 systemctl start kubelet && systemctl start docker
```
2.自定义资源预留可自定义kubeadm初始化文件内容实现，但能否实现更为简便的方式在init阶段传入变量实现

**Comment by cuisongliu** [comment]
sealos4.0会改这个设计 ，4.0 将废弃docker全部采用containerd.  #885
