### ISSUE TITLE
support container runtime and cni type add to readme

### ISSUE THREAD

**Issue by willzhang** [fanux/sealos#903]
**那个命令或者组件**
support container runtime and cni type add to readme

**描述你的问题**
not sure what  container runtime and cni support  for sealos

**你看到的一些参考资料**
add to readme ,  eg:

container runtime support : containerd、docker、CRI-O
cni support: calico cilium

**Comment by cuisongliu** [comment]
sealos4.0 重构，重构后只支持containerd

**Comment by willzhang** [comment]
你对CRI-O怎么看，应该也支持用户先手动安装CRI-O吧

**Comment by cuisongliu** [comment]
没必要支持，什么场景下需要这个东西……

**Comment by willzhang** [comment]
我对CRI-O也不熟悉，有人提出想用CRI-O，如果sealos不支持，可能这个工具就被直接pass了

我从这篇文章了解到一些关键点：https://medium.com/cri-o/container-runtimes-clarity-342b62172dc3
1、CRI-O 同时实现了CRI和OCI规范，Containerd 没有实现 CRI 接口，它通过另一个名为 cri-containerd 的守护进程来实现，该守护进程充当 containerd 本身和 kubelet 之间的 shim。
2、CRI-O 在稳定性方面比 cri-containerd 有很大的优势
3、另外说下，CRI-O运行时是k8s官方推荐的2个运行时之一（第一位containerd、第二位CRI-O，第三的docker将被弃用）

这么重要的运行时之一，sealos不考虑支持下吗

**Comment by cuisongliu** [comment]
https://medium.com/cri-o/container-runtimes-clarity-342b62172dc3. 这个链接2018年，首先是有点过时。当年那会并没有一个cri可以完美的兼容docker，containerd和kata等。
1. cri-o 和containerd都已经实现了CRI的接口了，你看的资料可能比较老，现在的containerd早已实现了CRI。所以其实cri-o如果为了CRI接口的话是没有必要的。 https://github.com/containerd/containerd#cri
2. cri-o 是k8s官方做了一个跟CRI的一个中间服务，以前来看的确是CRI-O更好，因为没有一个更好的CRI做支持，所以使用CRI-O，但是目前看的话containerd已经实现了CRI接口，只是docker实现的OCI。稳定性目前我也不好说。
3.  未来我们肯定可以支持，有了集群镜像什么都可以支持，你想搞什么runtime都可以，只是默认官方是containerd的而已。

**Comment by fanux** [comment]
sealos会提供最佳实践，kubernetes生态发展大趋势是 cri，而且已经成熟。

其次，sealos未来兼容集群镜像的标准，意味着有cri-o需求的用户可以自由定制，这个交给社区和生态去补齐。

从产品角度来说，有时给用户提供太多选择不见的是好事，增加了复杂性。虽然现实情况是各种场景各种方案各有优势，但是我们 还是需要努力找到那个最佳方案。
