### ISSUE TITLE
Exec Panic:the install app feature not support

### ISSUE THREAD

**Issue by dp0304** [fanux/sealos#907]
**哪个命令或者组件**
sealos install --pkg-url https://github.com/sealstore/dashboard/releases/download/v2.0.0-bata5/dashboard.tar

**描述这个缺陷**
03:28:01 [EMER] [log.go:405] ###Exec Panic:the install app feature not support

**重现步骤（如果有需要可以附加图片）**
 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/1586562/160972119-3be5b84b-3d24-4c4b-844a-ce1b2e5375e1.png">

**测试结果**

**期望结果**

**运行环境**
 sealos version
Version: 3.3.9-rc.11
Last Commit: 49e79d2
Build Date: 2022-02-17T06:17:34Z

**Comment by cuisongliu** [comment]
这个功能下线了，等4.0 新功能在使用应用
