### ISSUE TITLE
sealos app install设计

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#91]
sealos load  --master xxx --master xxx --node xxx --node  --pkg-url /root/prometheus.tar.gz

1. 同步包到各个节点
2. kubectl apply -f  /root/prometheus/conf

**Comment by fanux** [comment]
我感觉包可以做成 镜像+kustomize文件
kubectl apply -k /root/prometheus/

**Comment by cuisongliu** [comment]
可以可以。但是要求版本1.14+ 之前的版本不支持就可以了。

**Comment by cuisongliu** [comment]
sealos load --master 172.16.3.254 \
    --user root \
    --passwd admin \
    --name dashboard \
    --pkg-url /root/dashboard.tar.gz  (kubectl apply -f ....)
sealos load --master 172.16.3.254 \
    --kust
    --user root \
    --passwd admin \
    --name dashboard \
    --pkg-url /root/dashboard.tar.gz  (kubectl apply -k ....)

**Comment by fanux** [comment]
如果包含 apply动作的话我觉得 sealos install 更合适。 不过现在有种说不上来的别扭之感。

**Comment by fanux** [comment]
但是现在命令行还是太麻烦了，我想的是 sealos install prometheus:1.0 在线  或者sealos install prometheus.tar.gz 离线 ，  默认去找.kube/config

在线的我们把离线都都放 sealyun/apps 的release pages中

**Comment by fanux** [comment]
[文档](https://github.com/fanux/sealos/blob/v3.0.0/docs/v3.0.md)
