### ISSUE TITLE
安装 时候怎么传参变更docker默认存储目录/var/lib/docker ？？

### ISSUE THREAD

**Issue by szbjb** [fanux/sealos#917]
安装 时候怎么传参变更docker默认存储目录/var/lib/docker ？
sealos init 后面加什么参数可以指定默认docker存储路径 和etcd默认存储路径？

**Comment by cuisongliu** [comment]
4.0 可以支持，3.0 就暂时这样了

**Comment by Level1Accelerator** [comment]
怎么变更/run/containerd路径
