### ISSUE TITLE
sealos init命令--repo参数用户密码认证

### ISSUE THREAD

**Issue by cc20110101** [fanux/sealos#928]
**那个命令或者组件**
sealos init命令--repo参数指定仓库

**描述你的问题**
因为集群中服务使用镜像通过imagePullSecrets来认证，因此未在/etc/containerd/config.toml中配置镜像仓库用户密码信息，仅配置了https镜像仓库地址。
但是集群初始化时--repo指定仓库地址，此时未配置用户密码安装中会报错拉取镜像401未认证，请问sealos init中如何指定仓库用户密码。

**Comment by fanux** [comment]
sealos目前并不帮你管理仓库唉，后续4.0会有仓库管理这块，核心组件镜像通过load的方式加载的目前
