### ISSUE TITLE
v1.22.5版本是否kubeadm配置版本为kubeadm.k8s.io/v1beta3

### ISSUE THREAD

**Issue by cc20110101** [fanux/sealos#929]
![image](https://user-images.githubusercontent.com/12064991/163131865-57b1d920-504c-45b4-a035-f1e78f19f3b9.png)

apiVersion: kubeadm.k8s.io/v1beta2是否应该为apiVersion: kubeadm.k8s.io/v1beta3

**Comment by cuisongliu** [comment]
是应该的，具体的4.0的代码会修复。
