### ISSUE TITLE
使用--repo后安装失败

### ISSUE THREAD

**Issue by cc20110101** [fanux/sealos#931]
**哪个命令或者组件**
```
sealos init --pk /root/.ssh/id_rsa --pkg-url /opt/components/provisioner/packages/kubernetes/kube1.22.8.tar.gz \
  --config /opt/components/provisioner/configs/.sealos/config_59e1599531bb478196a4eb9da185d217.yaml \
 --version v1.22.8 \
  --apiserver 59e1599531bb478196a4eb9da185d217.apiserver.local.test \
  --repo iVideo.inspur/k8s \
  --lvscare-image iVideo.inspur/k8s/lvscare \
  --master 192.168.204.76:22 --node 192.168.204.79:22
```
**描述这个缺陷**
简短描述这个缺陷内容.

**重现步骤（如果有需要可以附加图片）**
![image](https://user-images.githubusercontent.com/12064991/163155389-ad3c8a26-f280-4562-81b6-696790481074.png)

下载的1.22.8版本安装后报错，为啥会拉取pasue:3.2版本

**运行环境**

- Kubernetes版本 : eg.kube1.22.8.tar.gz
- sealos版本: 3.3.9-rc.11
- 操作系统:  eg. centos7

**Comment by zhangguanzhang** [comment]
看着是pause 镜像没配置

**Comment by cc20110101** [comment]
![image](https://user-images.githubusercontent.com/12064991/163168451-cde2d9ec-1378-4e3e-a468-58689b530e96.png)

**Comment by cc20110101** [comment]
![image](https://user-images.githubusercontent.com/12064991/163169703-40e0541d-48ed-459d-b485-262a58c78ee7.png)

**Comment by cc20110101** [comment]
![image](https://user-images.githubusercontent.com/12064991/163171892-77680b95-bfc5-4c5d-8eac-811c3c3b86bc.png)
![image](https://user-images.githubusercontent.com/12064991/163172004-ea9b2143-7399-46a0-99db-daa148d7895d.png)
![image](https://user-images.githubusercontent.com/12064991/163172247-f91c43c9-1ec6-4cf7-93b6-7e9d2dcc08b3.png)


1.22.8离线包安装也是不行

**Comment by cc20110101** [comment]
用其他go程序调用sealos会出现此现象

**Comment by cc20110101** [comment]
用其他go程序调用sealos会出现此现象,

golang中exec.Command执行 /bin/sh -c "sealos init ..."出现的问题，直接主机执行没问题，是不能被其他进程调用吗

**Comment by zhangguanzhang** [comment]
重启下kubelet看看会拉取你指定的镜像还是自带的镜像

**Comment by cc20110101** [comment]
问题找到了。containerd配置了pause镜像，kubelet中的pod-infra-container-image不在有效
