### ISSUE TITLE
修改/etc/kubernetes/manifests/kube-apiserver.yaml参数后相关pod不重启且kubectl无法使用

### ISSUE THREAD

**Issue by nestaguo** [fanux/sealos#943]
修改了/etc/kubernetes/manifests/kube-apiserver.yaml文件，添加了- --feature-gates=RemoveSelfLink=false参数后，在3个master节点都修改了该文件，相关pod不自动重启创建，而且kubectl命令无法执行，报错apiserver was refused。也无法删除原来的pod. 请各位大佬帮忙看看如何处理这个问题了。。多谢了！

![image](https://user-images.githubusercontent.com/52433430/164586826-cee433b1-b1c9-4d2d-a872-d5a592f03198.png)

**Comment by zhangguanzhang** [comment]
```
docker ps -a | grep kube-apiserver
journalctl -xe --no-pager -u kubelet | grep kube-apiserver
```

**Comment by nestaguo** [comment]
好的 谢谢馆长 我去查查

**Comment by nestaguo** [comment]
如果镜像被gc掉了。。。咋整啊。。。馆长

**Comment by zhangguanzhang** [comment]
> 如果镜像被gc掉了。。。咋整啊。。。馆长

手动拉取下，或者换国内的镜像
```
k8s.gcr.io ==> registry.aliyuncs.com/k8sxio
k8s.gcr.io/xxx:aaa ==> registry.aliyuncs.com/k8sxio/xxx:aaa
```

**Comment by nestaguo** [comment]
好勒 谢谢馆长！

**Comment by nestaguo** [comment]
嗯 谢谢馆长指导！
