### ISSUE TITLE
Node 节点 NotReady

### ISSUE THREAD

**Issue by Mamahh** [fanux/sealos#958]
发现一个小问题，一键部署完成后，node 的状态一直为 NotReady

我确保 node 节点是已经添加成功的（calico 的 pod 还可以运行在 node 节点上）

然后问题解决方式也很简单，在 node 节点上重启下  containerd 就好了 (systemctl restart containerd.service)

只是有点不太理解问题的产生原因，是否可以在一键部署时修复掉呢？

ps: 
 sealos 版本: 3.3.9-rc.11
 操作系统: ubuntu20.04
 运行时：containerd
 k8版本：v1.23.5

**Comment by cuisongliu** [comment]
sealos exec 解决一下吧先 ，可以批量执行
