### ISSUE TITLE
app安装支持

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#96]
```
prometheus.tar   #app文件
    config             #配置文件
    images.tar       # 镜像文件
    manifests/      # 编排文件
        kustomization.yaml
        deploy.yaml

```
sealos install  --pkg-url /root/prometheus.tar.gz
用户可在任意电脑上执行install命令，执行sealos命令的电脑需要配置.sealos/config文件，该文件可在install的时候回传给执行电脑（用户在执行init的时候，可把master上的/etc/kubernetes/admin.conf 复制到执行sealos的电脑上）。
1. 使用go-client读取集群所有节点
2.复制到每个节点上并进行docker load命令。
3. 在master0上直接执行 kubectl -k prometheus/manifests

统一使用sealos-pass,进行密码管理.可重构之前的clean join 等命令。

**Comment by cuisongliu** [comment]
sealos build --raw https://dl.k8s.io/v1.15.3/kubernetes-server-linux-amd64.tar.gz --kubeadm-url https://github.com/fanux/kube/releases/download/v1.15.2-lvscare/kubeadm

直接单独拆分项目和app小包制作放到一起。[项目地址](https://github.com/cuisongliu/docker-package)
改写项目叫做 sealos-build

1. kube 为离线包制作
2. app  为小包制作

该项目主要就是 1 制作离线包 2 上传oss （根据参数决定是否上传oss）

**Comment by fanux** [comment]
嗯嗯，我觉得可以。   用户ssh 密钥文件也可以考虑放到secret中吧

**Comment by cuisongliu** [comment]
恩恩。可以。这块全部存储到sealos-login里就可以， 可以多写几个字段就可以。

**Comment by fanux** [comment]
可以

**Comment by fanux** [comment]
https://github.com/fanux/sealos/issues/118
