### ISSUE TITLE
离线包构建

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos#97]
sealos build --raw https://dl.k8s.io/v1.15.3/kubernetes-server-linux-amd64.tar.gz --kubeadm-url https://github.com/fanux/kube/releases/download/v1.15.2-lvscare/kubeadm

直接单独拆分项目和app小包制作放到一起。[项目地址](https://github.com/cuisongliu/docker-package)
改写项目叫做 sealos-build

1. kube 为离线包制作
2. app  为小包制作

该项目主要就是 1 制作离线包 2 上传oss （根据参数决定是否上传oss）

**Comment by fanux** [comment]
我觉得单拆一个项目可以，我来新建一个[sealbuild](github.com/fanux/sealbuild)

**Comment by fanux** [comment]
后面k8s自身的包我们称之为cloud kernel. 上层称之APP.    我觉得kernel和 app包的格式可以兼容

**Comment by fanux** [comment]
https://github.com/fanux/sealos/blob/v3.0.0/docs/v3.0.md  增加了config的相关说明

**Comment by cuisongliu** [comment]
好的。我先写小包的。离线的流程回头你在这个项目写个md，我仔细看看。

**Comment by fanux** [comment]
可以
